# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbAntiflickerPlugin <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function cbAntiflickerPlugin(pPanel::Ptr{Cvoid}, paneMask::Integer)
    ptr = KwxFFI.cbAntiflickerPlugin_Create(pPanel, Cint(paneMask))
    ptr == C_NULL && error("Failed to create cbAntiflickerPlugin")
    obj = cbAntiflickerPlugin(ptr)
    return obj
end

function cbAntiflickerPlugin()
    ptr = KwxFFI.cbAntiflickerPlugin_CreateDefault()
    ptr == C_NULL && error("Failed to create cbAntiflickerPlugin")
    obj = cbAntiflickerPlugin(ptr)
    return obj
end

function delete!(obj::cbAntiflickerPlugin)
    KwxFFI.cbAntiflickerPlugin_Delete(obj.ptr)
    nothing
end

