# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbBarInfo <: wxObject
    ptr::Ptr{Cvoid}
end

function cbBarInfo()
    ptr = KwxFFI.cbBarInfo_Create()
    ptr == C_NULL && error("Failed to create cbBarInfo")
    obj = cbBarInfo(ptr)
    return obj
end

function delete!(obj::cbBarInfo)
    KwxFFI.cbBarInfo_Delete(obj.ptr)
    nothing
end

function (obj::cbBarInfo)
    return KwxFFI.cbBarInfo_IsExpanded(obj.ptr) != 0
end

function (obj::cbBarInfo)
    return KwxFFI.cbBarInfo_IsFixed(obj.ptr) != 0
end

