# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbBarSpy <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function cbBarSpy(pPanel::Ptr{Cvoid})
    ptr = KwxFFI.cbBarSpy_Create(pPanel)
    ptr == C_NULL && error("Failed to create cbBarSpy")
    obj = cbBarSpy(ptr)
    return obj
end

function cbBarSpy()
    ptr = KwxFFI.cbBarSpy_CreateDefault()
    ptr == C_NULL && error("Failed to create cbBarSpy")
    obj = cbBarSpy(ptr)
    return obj
end

function delete!(obj::cbBarSpy)
    KwxFFI.cbBarSpy_Delete(obj.ptr)
    nothing
end

function (obj::cbBarSpy, event::Ptr{Cvoid})
    return Int(KwxFFI.cbBarSpy_ProcessEvent(obj.ptr, event))
end

function (obj::cbBarSpy, pWnd::Ptr{Cvoid})
    KwxFFI.cbBarSpy_SetBarWindow(obj.ptr, pWnd)
    nothing
end

