# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbBarHintsPlugin <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function cbBarHintsPlugin(pPanel::Ptr{Cvoid}, paneMask::Integer)
    ptr = KwxFFI.cbBarHintsPlugin_Create(pPanel, Cint(paneMask))
    ptr == C_NULL && error("Failed to create cbBarHintsPlugin")
    obj = cbBarHintsPlugin(ptr)
    return obj
end

function cbBarHintsPlugin()
    ptr = KwxFFI.cbBarHintsPlugin_CreateDefault()
    ptr == C_NULL && error("Failed to create cbBarHintsPlugin")
    obj = cbBarHintsPlugin(ptr)
    return obj
end

function delete!(obj::cbBarHintsPlugin)
    KwxFFI.cbBarHintsPlugin_Delete(obj.ptr)
    nothing
end

function (obj::cbBarHintsPlugin, nGrooves::Integer)
    KwxFFI.cbBarHintsPlugin_SetGrooveCount(obj.ptr, Cint(nGrooves))
    nothing
end

