# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbBarDragPlugin <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function cbBarDragPlugin(pPanel::Ptr{Cvoid}, paneMask::Integer)
    ptr = KwxFFI.cbBarDragPlugin_Create(pPanel, Cint(paneMask))
    ptr == C_NULL && error("Failed to create cbBarDragPlugin")
    obj = cbBarDragPlugin(ptr)
    return obj
end

function cbBarDragPlugin()
    ptr = KwxFFI.cbBarDragPlugin_CreateDefault()
    ptr == C_NULL && error("Failed to create cbBarDragPlugin")
    obj = cbBarDragPlugin(ptr)
    return obj
end

function delete!(obj::cbBarDragPlugin)
    KwxFFI.cbBarDragPlugin_Delete(obj.ptr)
    nothing
end

