# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbCloseBox <: wxObject
    ptr::Ptr{Cvoid}
end

function cbCloseBox()
    ptr = KwxFFI.cbCloseBox_Create()
    ptr == C_NULL && error("Failed to create cbCloseBox")
    obj = cbCloseBox(ptr)
    return obj
end

