# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbCollapseBox <: wxObject
    ptr::Ptr{Cvoid}
end

function cbCollapseBox()
    ptr = KwxFFI.cbCollapseBox_Create()
    ptr == C_NULL && error("Failed to create cbCollapseBox")
    obj = cbCollapseBox(ptr)
    return obj
end

