# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbCustomizeLayoutEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbCustomizeLayoutEvent, arg::Integer)
    KwxFFI.cbCustomizeLayoutEvent_ClickPos(obj.ptr, Cint(arg))
    nothing
end

