# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbCustomizeBarEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbCustomizeBarEvent)
    return KwxFFI.cbCustomizeBarEvent_Bar(obj.ptr)
end

function (obj::cbCustomizeBarEvent, arg::Integer)
    KwxFFI.cbCustomizeBarEvent_ClickPos(obj.ptr, Cint(arg))
    nothing
end

