# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbDimInfo <: wxObject
    ptr::Ptr{Cvoid}
end

function cbDimInfo(x::Integer, y::Integer, isFixed::Bool, gap::Integer, pDimHandler::Ptr{Cvoid})
    ptr = KwxFFI.cbDimInfo_Create(Cint(x), Cint(y), Cint(isFixed), Cint(gap), pDimHandler)
    ptr == C_NULL && error("Failed to create cbDimInfo")
    obj = cbDimInfo(ptr)
    return obj
end

function cbDimInfo()
    ptr = KwxFFI.cbDimInfo_CreateDefault()
    ptr == C_NULL && error("Failed to create cbDimInfo")
    obj = cbDimInfo(ptr)
    return obj
end

function cbDimInfo(dh_x::Integer, dh_y::Integer, dv_x::Integer, dv_y::Integer, f_x::Integer, f_y::Integer, isFixed::Bool, horizGap::Integer, vertGap::Integer, pDimHandler::Ptr{Cvoid})
    ptr = KwxFFI.cbDimInfo_CreateWithInfo(Cint(dh_x), Cint(dh_y), Cint(dv_x), Cint(dv_y), Cint(f_x), Cint(f_y), Cint(isFixed), Cint(horizGap), Cint(vertGap), pDimHandler)
    ptr == C_NULL && error("Failed to create cbDimInfo")
    obj = cbDimInfo(ptr)
    return obj
end

function (obj::cbDimInfo, other::Ptr{Cvoid})
    KwxFFI.cbDimInfo_Assign(obj.ptr, other)
    nothing
end

function (obj::cbDimInfo, isFixed::Bool)
    return KwxFFI.cbDimInfo_CreateWithHandler(obj.ptr, Cint(isFixed))
end

function delete!(obj::cbDimInfo)
    KwxFFI.cbDimInfo_Delete(obj.ptr)
    nothing
end

function (obj::cbDimInfo)
    return KwxFFI.cbDimInfo_GetDimHandler(obj.ptr)
end

