# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbDockBox <: wxObject
    ptr::Ptr{Cvoid}
end

function cbDockBox()
    ptr = KwxFFI.cbDockBox_Create()
    ptr == C_NULL && error("Failed to create cbDockBox")
    obj = cbDockBox(ptr)
    return obj
end

