# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbDrawRowHandlesEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbDrawRowHandlesEvent)
    return KwxFFI.cbDrawRowHandlesEvent_Dc(obj.ptr)
end

function (obj::cbDrawRowHandlesEvent)
    return KwxFFI.cbDrawRowHandlesEvent_Row(obj.ptr)
end

