# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbDrawRowBkGroundEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbDrawRowBkGroundEvent)
    return KwxFFI.cbDrawRowBkGroundEvent_Dc(obj.ptr)
end

function (obj::cbDrawRowBkGroundEvent)
    return KwxFFI.cbDrawRowBkGroundEvent_Row(obj.ptr)
end

