# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbDrawPaneBkGroundEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbDrawPaneBkGroundEvent)
    return KwxFFI.cbDrawPaneBkGroundEvent_Dc(obj.ptr)
end

