# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbDrawRowDecorEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbDrawRowDecorEvent)
    return KwxFFI.cbDrawRowDecorEvent_Dc(obj.ptr)
end

function (obj::cbDrawRowDecorEvent)
    return KwxFFI.cbDrawRowDecorEvent_Row(obj.ptr)
end

