# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbDrawHintRectEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbDrawHintRectEvent)
    return Int(KwxFFI.cbDrawHintRectEvent_EraseRect(obj.ptr))
end

function (obj::cbDrawHintRectEvent)
    return KwxFFI.cbDrawHintRectEvent_IsInClient(obj.ptr) != 0
end

function (obj::cbDrawHintRectEvent)
    return Int(KwxFFI.cbDrawHintRectEvent_LastTime(obj.ptr))
end

function (obj::cbDrawHintRectEvent, arg::Integer)
    KwxFFI.cbDrawHintRectEvent_Rect(obj.ptr, Cint(arg))
    nothing
end

