# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbDrawBarHandlesEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbDrawBarHandlesEvent)
    return KwxFFI.cbDrawBarHandlesEvent_Bar(obj.ptr)
end

function (obj::cbDrawBarHandlesEvent)
    return KwxFFI.cbDrawBarHandlesEvent_Dc(obj.ptr)
end

