# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbDynToolBarDimHandler <: wxObject
    ptr::Ptr{Cvoid}
end

function cbDynToolBarDimHandler()
    ptr = KwxFFI.cbDynToolBarDimHandler_Create()
    ptr == C_NULL && error("Failed to create cbDynToolBarDimHandler")
    obj = cbDynToolBarDimHandler(ptr)
    return obj
end

function delete!(obj::cbDynToolBarDimHandler)
    KwxFFI.cbDynToolBarDimHandler_Delete(obj.ptr)
    nothing
end

