# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbGCUpdatesMgr <: wxObject
    ptr::Ptr{Cvoid}
end

function cbGCUpdatesMgr(pPanel::Ptr{Cvoid})
    ptr = KwxFFI.cbGCUpdatesMgr_Create(pPanel)
    ptr == C_NULL && error("Failed to create cbGCUpdatesMgr")
    obj = cbGCUpdatesMgr(ptr)
    return obj
end

function cbGCUpdatesMgr()
    ptr = KwxFFI.cbGCUpdatesMgr_CreateDefault()
    ptr == C_NULL && error("Failed to create cbGCUpdatesMgr")
    obj = cbGCUpdatesMgr(ptr)
    return obj
end

function delete!(obj::cbGCUpdatesMgr)
    KwxFFI.cbGCUpdatesMgr_Delete(obj.ptr)
    nothing
end

function (obj::cbGCUpdatesMgr)
    KwxFFI.cbGCUpdatesMgr_UpdateNow(obj.ptr)
    nothing
end

