# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbLeftDownEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbLeftDownEvent, arg::Integer)
    KwxFFI.cbLeftDownEvent_Pos(obj.ptr, Cint(arg))
    nothing
end

