# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbLeftDClickEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbLeftDClickEvent, arg::Integer)
    KwxFFI.cbLeftDClickEvent_Pos(obj.ptr, Cint(arg))
    nothing
end

