# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbLeftUpEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbLeftUpEvent, arg::Integer)
    KwxFFI.cbLeftUpEvent_Pos(obj.ptr, Cint(arg))
    nothing
end

