# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbMiniButton <: wxObject
    ptr::Ptr{Cvoid}
end

function cbMiniButton()
    ptr = KwxFFI.cbMiniButton_Create()
    ptr == C_NULL && error("Failed to create cbMiniButton")
    obj = cbMiniButton(ptr)
    return obj
end

function delete!(obj::cbMiniButton)
    KwxFFI.cbMiniButton_Delete(obj.ptr)
    nothing
end

function (obj::cbMiniButton, arg::Integer)
    KwxFFI.cbMiniButton_Dim(obj.ptr, Cint(arg))
    nothing
end

function (obj::cbMiniButton)
    return Int(KwxFFI.cbMiniButton_DragStarted(obj.ptr))
end

function (obj::cbMiniButton, enable::Bool)
    KwxFFI.cbMiniButton_Enable(obj.ptr, Cint(enable))
    nothing
end

function (obj::cbMiniButton)
    return Int(KwxFFI.cbMiniButton_Enabled(obj.ptr))
end

function (obj::cbMiniButton, x::Integer, y::Integer)
    return Int(KwxFFI.cbMiniButton_HitTest(obj.ptr, Cint(x), Cint(y)))
end

function (obj::cbMiniButton)
    return KwxFFI.cbMiniButton_IsPressed(obj.ptr) != 0
end

function (obj::cbMiniButton)
    return KwxFFI.cbMiniButton_Layout(obj.ptr)
end

function (obj::cbMiniButton)
    return KwxFFI.cbMiniButton_Pane(obj.ptr)
end

function (obj::cbMiniButton)
    return KwxFFI.cbMiniButton_Plugin(obj.ptr)
end

function (obj::cbMiniButton, arg::Integer)
    KwxFFI.cbMiniButton_Pos(obj.ptr, Cint(arg))
    nothing
end

function (obj::cbMiniButton)
    return Int(KwxFFI.cbMiniButton_Pressed(obj.ptr))
end

function (obj::cbMiniButton)
    KwxFFI.cbMiniButton_Refresh(obj.ptr)
    nothing
end

function (obj::cbMiniButton)
    KwxFFI.cbMiniButton_Reset(obj.ptr)
    nothing
end

function (obj::cbMiniButton, x::Integer, y::Integer)
    KwxFFI.cbMiniButton_SetPos(obj.ptr, Cint(x), Cint(y))
    nothing
end

function (obj::cbMiniButton)
    return Int(KwxFFI.cbMiniButton_Visible(obj.ptr))
end

function (obj::cbMiniButton)
    return Int(KwxFFI.cbMiniButton_WasClicked(obj.ptr))
end

function (obj::cbMiniButton)
    return KwxFFI.cbMiniButton_Wnd(obj.ptr)
end

