# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbMotionEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbMotionEvent, arg::Integer)
    KwxFFI.cbMotionEvent_Pos(obj.ptr, Cint(arg))
    nothing
end

