# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbPaneDrawPlugin <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function cbPaneDrawPlugin(pPanel::Ptr{Cvoid}, paneMask::Integer)
    ptr = KwxFFI.cbPaneDrawPlugin_Create(pPanel, Cint(paneMask))
    ptr == C_NULL && error("Failed to create cbPaneDrawPlugin")
    obj = cbPaneDrawPlugin(ptr)
    return obj
end

function cbPaneDrawPlugin()
    ptr = KwxFFI.cbPaneDrawPlugin_CreateDefault()
    ptr == C_NULL && error("Failed to create cbPaneDrawPlugin")
    obj = cbPaneDrawPlugin(ptr)
    return obj
end

function delete!(obj::cbPaneDrawPlugin)
    KwxFFI.cbPaneDrawPlugin_Delete(obj.ptr)
    nothing
end

