# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbPluginBase <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function delete!(obj::cbPluginBase)
    KwxFFI.cbPluginBase_Delete(obj.ptr)
    nothing
end

function (obj::cbPluginBase)
    return Int(KwxFFI.cbPluginBase_GetPaneMask(obj.ptr))
end

function (obj::cbPluginBase)
    return KwxFFI.cbPluginBase_IsReady(obj.ptr) != 0
end

function (obj::cbPluginBase, switchVal::Integer)
    return KwxFFI.cbPluginBase_Plugin(obj.ptr, Cint(switchVal))
end

function (obj::cbPluginBase, event::Ptr{Cvoid})
    return Int(KwxFFI.cbPluginBase_ProcessEvent(obj.ptr, event))
end

