# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbResizeBarEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbResizeBarEvent)
    return KwxFFI.cbResizeBarEvent_Bar(obj.ptr)
end

function (obj::cbResizeBarEvent)
    return KwxFFI.cbResizeBarEvent_Row(obj.ptr)
end

