# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbResizeRowEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbResizeRowEvent)
    return Int(KwxFFI.cbResizeRowEvent_ForUpperHandle(obj.ptr))
end

function (obj::cbResizeRowEvent)
    return Int(KwxFFI.cbResizeRowEvent_HandleOfs(obj.ptr))
end

function (obj::cbResizeRowEvent)
    return KwxFFI.cbResizeRowEvent_Row(obj.ptr)
end

