# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbRightDownEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbRightDownEvent, arg::Integer)
    KwxFFI.cbRightDownEvent_Pos(obj.ptr, Cint(arg))
    nothing
end

