# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbRowDragPlugin <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function cbRowDragPlugin(pPanel::Ptr{Cvoid}, paneMask::Integer)
    ptr = KwxFFI.cbRowDragPlugin_Create(pPanel, Cint(paneMask))
    ptr == C_NULL && error("Failed to create cbRowDragPlugin")
    obj = cbRowDragPlugin(ptr)
    return obj
end

function cbRowDragPlugin()
    ptr = KwxFFI.cbRowDragPlugin_CreateDefault()
    ptr == C_NULL && error("Failed to create cbRowDragPlugin")
    obj = cbRowDragPlugin(ptr)
    return obj
end

function delete!(obj::cbRowDragPlugin)
    KwxFFI.cbRowDragPlugin_Delete(obj.ptr)
    nothing
end

