# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbRowLayoutPlugin <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function cbRowLayoutPlugin(pPanel::Ptr{Cvoid}, paneMask::Integer)
    ptr = KwxFFI.cbRowLayoutPlugin_Create(pPanel, Cint(paneMask))
    ptr == C_NULL && error("Failed to create cbRowLayoutPlugin")
    obj = cbRowLayoutPlugin(ptr)
    return obj
end

function cbRowLayoutPlugin()
    ptr = KwxFFI.cbRowLayoutPlugin_CreateDefault()
    ptr == C_NULL && error("Failed to create cbRowLayoutPlugin")
    obj = cbRowLayoutPlugin(ptr)
    return obj
end

function delete!(obj::cbRowLayoutPlugin)
    KwxFFI.cbRowLayoutPlugin_Delete(obj.ptr)
    nothing
end

