# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbSimpleCustomizationPlugin <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function cbSimpleCustomizationPlugin(pPanel::Ptr{Cvoid}, paneMask::Integer)
    ptr = KwxFFI.cbSimpleCustomizationPlugin_Create(pPanel, Cint(paneMask))
    ptr == C_NULL && error("Failed to create cbSimpleCustomizationPlugin")
    obj = cbSimpleCustomizationPlugin(ptr)
    return obj
end

function cbSimpleCustomizationPlugin()
    ptr = KwxFFI.cbSimpleCustomizationPlugin_CreateDefault()
    ptr == C_NULL && error("Failed to create cbSimpleCustomizationPlugin")
    obj = cbSimpleCustomizationPlugin(ptr)
    return obj
end

function delete!(obj::cbSimpleCustomizationPlugin)
    KwxFFI.cbSimpleCustomizationPlugin_Delete(obj.ptr)
    nothing
end

