# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbSizeBarWndEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbSizeBarWndEvent)
    return KwxFFI.cbSizeBarWndEvent_Bar(obj.ptr)
end

function (obj::cbSizeBarWndEvent, arg::Integer)
    KwxFFI.cbSizeBarWndEvent_BoundsInParent(obj.ptr, Cint(arg))
    nothing
end

