# Code generated by kwxgen. DO NOT EDIT.

mutable struct cbStartDrawInAreaEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::cbStartDrawInAreaEvent, arg::Integer)
    KwxFFI.cbStartDrawInAreaEvent_Area(obj.ptr, Cint(arg))
    nothing
end

