# Code generated by kwxgen. DO NOT EDIT.

Null_AcceleratorTable() = ccall((:Null_AcceleratorTable, libkwxFFI), Ptr{Cvoid}, ())
Null_Bitmap() = ccall((:Null_Bitmap, libkwxFFI), Ptr{Cvoid}, ())
Null_Brush() = ccall((:Null_Brush, libkwxFFI), Ptr{Cvoid}, ())
Null_Colour() = ccall((:Null_Colour, libkwxFFI), Ptr{Cvoid}, ())
Null_Cursor() = ccall((:Null_Cursor, libkwxFFI), Ptr{Cvoid}, ())
Null_Font() = ccall((:Null_Font, libkwxFFI), Ptr{Cvoid}, ())
Null_Icon() = ccall((:Null_Icon, libkwxFFI), Ptr{Cvoid}, ())
Null_Palette() = ccall((:Null_Palette, libkwxFFI), Ptr{Cvoid}, ())
Null_Pen() = ccall((:Null_Pen, libkwxFFI), Ptr{Cvoid}, ())
kwxSysErrorCode() = ccall((:kwxSysErrorCode, libkwxFFI), Cint, ())
function kwxSysErrorMsg(nErrCode::Cint)
    ccall((:kwxSysErrorMsg, libkwxFFI), Ptr{Cvoid},
        (Cint,),
        nErrCode)
end
function LogErrorMsg(message::Ptr{Cvoid})
    ccall((:LogErrorMsg, libkwxFFI), Cvoid,
        (Ptr{Cvoid},),
        message)
end
function LogFatalErrorMsg(message::Ptr{Cvoid})
    ccall((:LogFatalErrorMsg, libkwxFFI), Cvoid,
        (Ptr{Cvoid},),
        message)
end
function LogMessageMsg(message::Ptr{Cvoid})
    ccall((:LogMessageMsg, libkwxFFI), Cvoid,
        (Ptr{Cvoid},),
        message)
end
function LogWarningMsg(message::Ptr{Cvoid})
    ccall((:LogWarningMsg, libkwxFFI), Cvoid,
        (Ptr{Cvoid},),
        message)
end
expSetDefaultAssertHandler() = ccall((:expSetDefaultAssertHandler, libkwxFFI), Cvoid, ())
function Quantize(src::Ptr{Cvoid}, dest::Ptr{Cvoid}, desiredNoColours::Cint, eightBitData::Ptr{Cvoid}, flags::Cint)
    ccall((:Quantize, libkwxFFI), Cint,
        (Ptr{Cvoid}, Ptr{Cvoid}, Cint, Ptr{Cvoid}, Cint),
        src, dest, desiredNoColours, eightBitData, flags)
end
function QuantizePalette(src::Ptr{Cvoid}, dest::Ptr{Cvoid}, pPalette::Ptr{Cvoid}, desiredNoColours::Cint, eightBitData::Ptr{Cvoid}, flags::Cint)
    ccall((:QuantizePalette, libkwxFFI), Cint,
        (Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}, Cint, Ptr{Cvoid}, Cint),
        src, dest, pPalette, desiredNoColours, eightBitData, flags)
end
function wxCFree(pointer::Ptr{Cvoid})
    ccall((:wxCFree, libkwxFFI), Cvoid,
        (Ptr{Cvoid},),
        pointer)
end
wxGetkwxLocale() = ccall((:wxGetkwxLocale, libkwxFFI), Ptr{Cvoid}, ())
function wxGetkwxTranslation(text::Ptr{Cvoid})
    ccall((:wxGetkwxTranslation, libkwxFFI), Ptr{Cvoid},
        (Ptr{Cvoid},),
        text)
end
wxMutexGui_Enter() = ccall((:wxMutexGui_Enter, libkwxFFI), Cvoid, ())
wxMutexGui_Leave() = ccall((:wxMutexGui_Leave, libkwxFFI), Cvoid, ())
function kwxUtf8Buffer_Create(str::Ptr{Cvoid})
    ccall((:kwxUtf8Buffer_Create, libkwxFFI), Ptr{Cvoid},
        (Ptr{Cvoid},),
        str)
end
function kwxUtf8Buffer_Data(buf::Ptr{Cvoid})
    ccall((:kwxUtf8Buffer_Data, libkwxFFI), Cstring,
        (Ptr{Cvoid},),
        buf)
end
function kwxUtf8Buffer_Delete(buf::Ptr{Cvoid})
    ccall((:kwxUtf8Buffer_Delete, libkwxFFI), Cvoid,
        (Ptr{Cvoid},),
        buf)
end
