# Code generated by kwxgen. DO NOT EDIT.

mutable struct kwxCommand <: wxObject
    ptr::Ptr{Cvoid}
end

function kwxCommand(canUndo::Integer, name::String, pObject::Ptr{Cvoid}, callback::Ptr{Cvoid})
    name_ws = wxString(name)
    ptr = KwxFFI.kwxCommand_Create(Cint(canUndo), name_ws.ptr, pObject, callback)
    delete!(name_ws)
    ptr == C_NULL && error("Failed to create kwxCommand")
    obj = kwxCommand(ptr)
    return obj
end

function (obj::kwxCommand)
    return KwxFFI.kwxCommand_CanUndo(obj.ptr) != 0
end

function delete!(obj::kwxCommand)
    KwxFFI.kwxCommand_Delete(obj.ptr)
    nothing
end

function (obj::kwxCommand)
    return KwxFFI.kwxCommand_GetName(obj.ptr)
end

