# Code generated by kwxgen. DO NOT EDIT.

mutable struct kwxDragDataObject <: wxObject
    ptr::Ptr{Cvoid}
end

function kwxDragDataObject(pObject::Ptr{Cvoid}, format::String, fnGetDataSize::Ptr{Cvoid}, fnGetDataHere::Ptr{Cvoid}, fnSetData::Ptr{Cvoid})
    format_ws = wxString(format)
    ptr = KwxFFI.kwxDragDataObject_Create(pObject, format_ws.ptr, fnGetDataSize, fnGetDataHere, fnSetData)
    delete!(format_ws)
    ptr == C_NULL && error("Failed to create kwxDragDataObject")
    obj = kwxDragDataObject(ptr)
    return obj
end

function delete!(obj::kwxDragDataObject)
    KwxFFI.kwxDragDataObject_Delete(obj.ptr)
    nothing
end

