# Code generated by kwxgen. DO NOT EDIT.

mutable struct kwxLog <: wxObject
    ptr::Ptr{Cvoid}
end

function kwxLog(pObject::Ptr{Cvoid}, pFunction::Ptr{Cvoid})
    ptr = KwxFFI.kwxLog_Create(pObject, pFunction)
    ptr == C_NULL && error("Failed to create kwxLog")
    obj = kwxLog(ptr)
    return obj
end

function (obj::kwxLog, str::Ptr{Cvoid})
    KwxFFI.kwxLog_AddTraceMask(obj.ptr, str)
    nothing
end

function delete!(obj::kwxLog)
    KwxFFI.kwxLog_Delete(obj.ptr)
    nothing
end

function (obj::kwxLog)
    KwxFFI.kwxLog_DontCreateOnDemand(obj.ptr)
    nothing
end

function (obj::kwxLog, doIt::Bool)
    return Int(KwxFFI.kwxLog_EnableLogging(obj.ptr, Cint(doIt)))
end

function (obj::kwxLog)
    KwxFFI.kwxLog_Flush(obj.ptr)
    nothing
end

function (obj::kwxLog)
    KwxFFI.kwxLog_FlushActive(obj.ptr)
    nothing
end

function (obj::kwxLog)
    return KwxFFI.kwxLog_GetActiveTarget(obj.ptr)
end

function (obj::kwxLog)
    return KwxFFI.kwxLog_GetTimestamp(obj.ptr)
end

function (obj::kwxLog)
    return Int(KwxFFI.kwxLog_GetVerbose(obj.ptr))
end

function (obj::kwxLog)
    return KwxFFI.kwxLog_HasPendingMessages(obj.ptr) != 0
end

function (obj::kwxLog, mask::Ptr{Cvoid})
    return KwxFFI.kwxLog_IsAllowedTraceMask(obj.ptr, mask) != 0
end

function (obj::kwxLog)
    return KwxFFI.kwxLog_IsEnabled(obj.ptr) != 0
end

function (obj::kwxLog, level::Integer, szString::Ptr{Cvoid}, timestamp::Integer)
    KwxFFI.kwxLog_OnLog(obj.ptr, Cint(level), szString, Cint(timestamp))
    nothing
end

function (obj::kwxLog, str::Ptr{Cvoid})
    KwxFFI.kwxLog_RemoveTraceMask(obj.ptr, str)
    nothing
end

function (obj::kwxLog)
    KwxFFI.kwxLog_Resume(obj.ptr)
    nothing
end

function (obj::kwxLog)
    return KwxFFI.kwxLog_SetActiveTarget(obj.ptr)
end

function (obj::kwxLog, timestamp::Ptr{Cvoid})
    KwxFFI.kwxLog_SetTimestamp(obj.ptr, timestamp)
    nothing
end

function (obj::kwxLog, bVerbose::Integer)
    KwxFFI.kwxLog_SetVerbose(obj.ptr, Cint(bVerbose))
    nothing
end

function (obj::kwxLog)
    KwxFFI.kwxLog_Suspend(obj.ptr)
    nothing
end

