# Code generated by kwxgen. DO NOT EDIT.

mutable struct kwxMessageParameters <: wxObject
    ptr::Ptr{Cvoid}
end

function kwxMessageParameters(filePath::Ptr{Cvoid}, type_::Ptr{Cvoid}, pObject::Ptr{Cvoid}, pFunction::Ptr{Cvoid})
    ptr = KwxFFI.wxMessageParameters_Create(filePath, type_, pObject, pFunction)
    ptr == C_NULL && error("Failed to create kwxMessageParameters")
    obj = kwxMessageParameters(ptr)
    return obj
end

function delete!(obj::kwxMessageParameters)
    KwxFFI.wxMessageParameters_Delete(obj.ptr)
    nothing
end

