# Code generated by kwxgen. DO NOT EDIT.

mutable struct kwxPreviewFrame <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function kwxPreviewFrame(pObject::Ptr{Cvoid}, init::Ptr{Cvoid}, createCanvas::Ptr{Cvoid}, createToolbar::Ptr{Cvoid}, preview::Ptr{Cvoid}, parent::Union{wxWindow, Nothing}, title::Ptr{Cvoid}, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.kwxPreviewFrame_Create(pObject, init, createCanvas, createToolbar, preview, parent_ptr, title, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create kwxPreviewFrame")
    obj = kwxPreviewFrame(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::kwxPreviewFrame)
    return KwxFFI.kwxPreviewFrame_GetControlBar(obj.ptr)
end

function (obj::kwxPreviewFrame)
    return KwxFFI.kwxPreviewFrame_GetPreviewCanvas(obj.ptr)
end

function (obj::kwxPreviewFrame)
    return KwxFFI.kwxPreviewFrame_GetPrintPreview(obj.ptr)
end

function (obj::kwxPreviewFrame)
    KwxFFI.kwxPreviewFrame_Initialize(obj.ptr)
    nothing
end

function (obj::kwxPreviewFrame, arg::Ptr{Cvoid})
    KwxFFI.kwxPreviewFrame_SetControlBar(obj.ptr, arg)
    nothing
end

function (obj::kwxPreviewFrame, arg_ptr::Ptr{Cvoid})
    KwxFFI.kwxPreviewFrame_SetPreviewCanvas(obj.ptr, arg_ptr)
    nothing
end

function (obj::kwxPreviewFrame, arg_ptr::Ptr{Cvoid})
    KwxFFI.kwxPreviewFrame_SetPrintPreview(obj.ptr, arg_ptr)
    nothing
end

