# Code generated by kwxgen. DO NOT EDIT.

mutable struct kwxPlotCurve <: wxObject
    ptr::Ptr{Cvoid}
end

function kwxPlotCurve(pObject::Ptr{Cvoid}, fnGetStartX::Ptr{Cvoid}, endVal::Ptr{Cvoid}, y::Ptr{Cvoid}, offsetY::Integer, startY::Float64, endY::Float64)
    ptr = KwxFFI.kwxPlotCurve_Create(pObject, fnGetStartX, endVal, y, Cint(offsetY), Cdouble(startY), Cdouble(endY))
    ptr == C_NULL && error("Failed to create kwxPlotCurve")
    obj = kwxPlotCurve(ptr)
    return obj
end

function delete!(obj::kwxPlotCurve)
    KwxFFI.kwxPlotCurve_Delete(obj.ptr)
    nothing
end

function (obj::kwxPlotCurve)
    return Float64(KwxFFI.kwxPlotCurve_GetEndY(obj.ptr))
end

function (obj::kwxPlotCurve)
    return Int(KwxFFI.kwxPlotCurve_GetOffsetY(obj.ptr))
end

function (obj::kwxPlotCurve)
    return Float64(KwxFFI.kwxPlotCurve_GetStartY(obj.ptr))
end

function (obj::kwxPlotCurve, endY::Float64)
    KwxFFI.kwxPlotCurve_SetEndY(obj.ptr, Cdouble(endY))
    nothing
end

function (obj::kwxPlotCurve, offsetY::Integer)
    KwxFFI.kwxPlotCurve_SetOffsetY(obj.ptr, Cint(offsetY))
    nothing
end

function (obj::kwxPlotCurve, pen::Ptr{Cvoid})
    KwxFFI.kwxPlotCurve_SetPenNormal(obj.ptr, pen)
    nothing
end

function (obj::kwxPlotCurve, pen::Ptr{Cvoid})
    KwxFFI.kwxPlotCurve_SetPenSelected(obj.ptr, pen)
    nothing
end

function (obj::kwxPlotCurve, startY::Float64)
    KwxFFI.kwxPlotCurve_SetStartY(obj.ptr, Cdouble(startY))
    nothing
end

