# Code generated by kwxgen. DO NOT EDIT.

mutable struct kwxTextValidator <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function kwxTextValidator(pObject::Ptr{Cvoid}, pFunction::Ptr{Cvoid}, text::Ptr{Cvoid}, style::Integer)
    ptr = KwxFFI.kwxTextValidator_Create(pObject, pFunction, text, Cint(style))
    ptr == C_NULL && error("Failed to create kwxTextValidator")
    obj = kwxTextValidator(ptr)
    return obj
end

