# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxActivityIndicator <: wxObject
    ptr::Ptr{Cvoid}
end

function wxActivityIndicator(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxActivityIndicator_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxActivityIndicator")
    obj = wxActivityIndicator(ptr)
    return obj
end

function (obj::wxActivityIndicator)
    return KwxFFI.wxActivityIndicator_IsRunning(obj.ptr) != 0
end

function (obj::wxActivityIndicator)
    KwxFFI.wxActivityIndicator_Start(obj.ptr)
    nothing
end

function (obj::wxActivityIndicator)
    KwxFFI.wxActivityIndicator_Stop(obj.ptr)
    nothing
end

