# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxActivateEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxActivateEvent, arg::Ptr{Cvoid})
    KwxFFI.wxActivateEvent_CopyObject(obj.ptr, arg)
    nothing
end

function (obj::wxActivateEvent)
    return KwxFFI.wxActivateEvent_GetActive(obj.ptr) != 0
end

