# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAnimationCtrl <: wxObject
    ptr::Ptr{Cvoid}
end

function wxAnimationCtrl(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxAnimationCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxAnimationCtrl")
    obj = wxAnimationCtrl(ptr)
    return obj
end

function wxAnimationCtrl(parent::Union{wxWindow, Nothing}, id::Integer, anim::Ptr{Cvoid}, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxAnimationCtrl_CreateWithAnimation(parent_ptr, Cint(id), anim, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxAnimationCtrl")
    obj = wxAnimationCtrl(ptr)
    return obj
end

function (obj::wxAnimationCtrl, anim::Ptr{Cvoid})
    KwxFFI.wxAnimationCtrl_GetAnimation(obj.ptr, anim)
    nothing
end

function (obj::wxAnimationCtrl, bmp::Ptr{Cvoid})
    KwxFFI.wxAnimationCtrl_GetInactiveBitmap(obj.ptr, bmp)
    nothing
end

function (obj::wxAnimationCtrl)
    return KwxFFI.wxAnimationCtrl_IsPlaying(obj.ptr) != 0
end

function (obj::wxAnimationCtrl, filename::String, type_::Integer)
    filename_ws = wxString(filename)
    _result = KwxFFI.wxAnimationCtrl_LoadFile(obj.ptr, filename_ws.ptr, Cint(type_)) != 0
    delete!(filename_ws)
    return _result
end

function (obj::wxAnimationCtrl, stream::Ptr{Cvoid}, type_::Integer)
    return KwxFFI.wxAnimationCtrl_Load(obj.ptr, stream, Cint(type_)) != 0
end

function (obj::wxAnimationCtrl)
    return KwxFFI.wxAnimationCtrl_Play(obj.ptr) != 0
end

function (obj::wxAnimationCtrl, anim::Ptr{Cvoid})
    KwxFFI.wxAnimationCtrl_SetAnimation(obj.ptr, anim)
    nothing
end

function (obj::wxAnimationCtrl, bmp::Ptr{Cvoid})
    KwxFFI.wxAnimationCtrl_SetInactiveBitmap(obj.ptr, bmp)
    nothing
end

function (obj::wxAnimationCtrl)
    KwxFFI.wxAnimationCtrl_Stop(obj.ptr)
    nothing
end

