# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxArtProvider <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxArtProvider)
    return KwxFFI.PopProvider(obj.ptr) != 0
end

function (obj::wxArtProvider, provider::Ptr{Cvoid})
    KwxFFI.PushProvider(obj.ptr, provider)
    nothing
end

function (obj::wxArtProvider, provider::Ptr{Cvoid})
    return KwxFFI.RemoveProvider(obj.ptr, provider) != 0
end

