# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiDefaultToolBarArt <: wxObject
    ptr::Ptr{Cvoid}
end

function wxAuiDefaultToolBarArt()
    ptr = KwxFFI.wxAuiDefaultToolBarArt_Create()
    ptr == C_NULL && error("Failed to create wxAuiDefaultToolBarArt")
    obj = wxAuiDefaultToolBarArt(ptr)
    return obj
end

function (obj::wxAuiDefaultToolBarArt)
    return KwxFFI.wxAuiDefaultToolBarArt_Clone(obj.ptr)
end

function (obj::wxAuiDefaultToolBarArt, flags::Integer)
    KwxFFI.wxAuiDefaultToolBarArt_SetFlags(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxAuiDefaultToolBarArt)
    return Int(KwxFFI.wxAuiDefaultToolBarArt_GetFlags(obj.ptr))
end

function (obj::wxAuiDefaultToolBarArt, font::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultToolBarArt_SetFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiDefaultToolBarArt)
    return KwxFFI.wxAuiDefaultToolBarArt_GetFont(obj.ptr)
end

function (obj::wxAuiDefaultToolBarArt, orientation::Integer)
    KwxFFI.wxAuiDefaultToolBarArt_SetTextOrientation(obj.ptr, Cint(orientation))
    nothing
end

function (obj::wxAuiDefaultToolBarArt)
    return Int(KwxFFI.wxAuiDefaultToolBarArt_GetTextOrientation(obj.ptr))
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultToolBarArt_DrawBackground(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultToolBarArt_DrawPlainBackground(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultToolBarArt_DrawLabel(obj.ptr, dc, window, item, rect)
    nothing
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultToolBarArt_DrawButton(obj.ptr, dc, window, item, rect)
    nothing
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultToolBarArt_DrawDropDownButton(obj.ptr, dc, window, item, rect)
    nothing
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultToolBarArt_DrawControlLabel(obj.ptr, dc, window, item, rect)
    nothing
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultToolBarArt_DrawSeparator(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultToolBarArt_DrawGripper(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid}, state::Integer)
    KwxFFI.wxAuiDefaultToolBarArt_DrawOverflowButton(obj.ptr, dc, window, rect, Cint(state))
    nothing
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid})
    return KwxFFI.wxAuiDefaultToolBarArt_GetLabelSize(obj.ptr, dc, window, item)
end

function (obj::wxAuiDefaultToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid})
    return KwxFFI.wxAuiDefaultToolBarArt_GetToolSize(obj.ptr, dc, window, item)
end

function (obj::wxAuiDefaultToolBarArt, element::Integer)
    return Int(KwxFFI.wxAuiDefaultToolBarArt_GetElementSize(obj.ptr, Cint(element)))
end

function (obj::wxAuiDefaultToolBarArt, element_id::Integer, size::Integer)
    KwxFFI.wxAuiDefaultToolBarArt_SetElementSize(obj.ptr, Cint(element_id), Cint(size))
    nothing
end

function (obj::wxAuiDefaultToolBarArt, window::Ptr{Cvoid}, items::Ptr{Cvoid})
    return Int(KwxFFI.wxAuiDefaultToolBarArt_ShowDropDown(obj.ptr, window, items))
end

