# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiToolBarArt <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxAuiToolBarArt)
    return KwxFFI.wxAuiToolBarArt_Clone(obj.ptr)
end

function (obj::wxAuiToolBarArt, flags::Integer)
    KwxFFI.wxAuiToolBarArt_SetFlags(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxAuiToolBarArt)
    return Int(KwxFFI.wxAuiToolBarArt_GetFlags(obj.ptr))
end

function (obj::wxAuiToolBarArt, font::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarArt_SetFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiToolBarArt)
    return KwxFFI.wxAuiToolBarArt_GetFont(obj.ptr)
end

function (obj::wxAuiToolBarArt, orientation::Integer)
    KwxFFI.wxAuiToolBarArt_SetTextOrientation(obj.ptr, Cint(orientation))
    nothing
end

function (obj::wxAuiToolBarArt)
    return Int(KwxFFI.wxAuiToolBarArt_GetTextOrientation(obj.ptr))
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarArt_DrawBackground(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarArt_DrawPlainBackground(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarArt_DrawLabel(obj.ptr, dc, window, item, rect)
    nothing
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarArt_DrawButton(obj.ptr, dc, window, item, rect)
    nothing
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarArt_DrawDropDownButton(obj.ptr, dc, window, item, rect)
    nothing
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarArt_DrawControlLabel(obj.ptr, dc, window, item, rect)
    nothing
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarArt_DrawSeparator(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarArt_DrawGripper(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid}, state::Integer)
    KwxFFI.wxAuiToolBarArt_DrawOverflowButton(obj.ptr, dc, window, rect, Cint(state))
    nothing
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid})
    return KwxFFI.wxAuiToolBarArt_GetLabelSize(obj.ptr, dc, window, item)
end

function (obj::wxAuiToolBarArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, item::Ptr{Cvoid})
    return KwxFFI.wxAuiToolBarArt_GetToolSize(obj.ptr, dc, window, item)
end

function (obj::wxAuiToolBarArt, element_id::Integer)
    return Int(KwxFFI.wxAuiToolBarArt_GetElementSize(obj.ptr, Cint(element_id)))
end

function (obj::wxAuiToolBarArt, element_id::Integer, size::Integer)
    KwxFFI.wxAuiToolBarArt_SetElementSize(obj.ptr, Cint(element_id), Cint(size))
    nothing
end

function (obj::wxAuiToolBarArt, window::Ptr{Cvoid}, items::Ptr{Cvoid})
    return Int(KwxFFI.wxAuiToolBarArt_ShowDropDown(obj.ptr, window, items))
end

