# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiToolBarEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxAuiToolBarEvent)
    return KwxFFI.wxAuiToolBarEvent_IsDropDownClicked(obj.ptr) != 0
end

function (obj::wxAuiToolBarEvent)
    return KwxFFI.wxAuiToolBarEvent_GetClickPoint(obj.ptr)
end

function (obj::wxAuiToolBarEvent)
    return KwxFFI.wxAuiToolBarEvent_GetItemRect(obj.ptr)
end

function (obj::wxAuiToolBarEvent)
    return Int(KwxFFI.wxAuiToolBarEvent_GetToolId(obj.ptr))
end

