# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiManagerEvent <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function wxAuiManagerEvent(type_::Integer)
    ptr = KwxFFI.wxAuiManagerEvent_Create(Cint(type_))
    ptr == C_NULL && error("Failed to create wxAuiManagerEvent")
    obj = wxAuiManagerEvent(ptr)
    return obj
end

function (obj::wxAuiManagerEvent)
    return KwxFFI.wxAuiManagerEvent_CanVeto(obj.ptr) != 0
end

function (obj::wxAuiManagerEvent)
    return Int(KwxFFI.wxAuiManagerEvent_GetButton(obj.ptr))
end

function (obj::wxAuiManagerEvent)
    return KwxFFI.wxAuiManagerEvent_GetDC(obj.ptr)
end

function (obj::wxAuiManagerEvent)
    return KwxFFI.wxAuiManagerEvent_GetVeto(obj.ptr) != 0
end

function (obj::wxAuiManagerEvent)
    return KwxFFI.wxAuiManagerEvent_GetManager(obj.ptr)
end

function (obj::wxAuiManagerEvent)
    return KwxFFI.wxAuiManagerEvent_GetPane(obj.ptr)
end

function (obj::wxAuiManagerEvent, button::Integer)
    KwxFFI.wxAuiManagerEvent_SetButton(obj.ptr, Cint(button))
    nothing
end

function (obj::wxAuiManagerEvent, can_veto::Bool)
    KwxFFI.wxAuiManagerEvent_SetCanVeto(obj.ptr, Cint(can_veto))
    nothing
end

function (obj::wxAuiManagerEvent, paintDC::Ptr{Cvoid})
    KwxFFI.wxAuiManagerEvent_SetDC(obj.ptr, paintDC)
    nothing
end

function (obj::wxAuiManagerEvent, manager::Ptr{Cvoid})
    KwxFFI.wxAuiManagerEvent_SetManager(obj.ptr, manager)
    nothing
end

function (obj::wxAuiManagerEvent, pane::Ptr{Cvoid})
    KwxFFI.wxAuiManagerEvent_SetPane(obj.ptr, pane)
    nothing
end

function (obj::wxAuiManagerEvent, veto::Bool)
    KwxFFI.wxAuiManagerEvent_Veto(obj.ptr, Cint(veto))
    nothing
end

