# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiNotebookPage <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxAuiNotebookPage)
    return KwxFFI.wxAuiNotebookPage_Window(obj.ptr)
end

function (obj::wxAuiNotebookPage)
    return KwxFFI.wxAuiNotebookPage_Caption(obj.ptr)
end

function (obj::wxAuiNotebookPage)
    return KwxFFI.wxAuiNotebookPage_Tooltip(obj.ptr)
end

function (obj::wxAuiNotebookPage)
    return KwxFFI.wxAuiNotebookPage_Bitmap(obj.ptr)
end

function (obj::wxAuiNotebookPage)
    return KwxFFI.wxAuiNotebookPage_Rect(obj.ptr)
end

function (obj::wxAuiNotebookPage)
    return KwxFFI.wxAuiNotebookPage_Active(obj.ptr) != 0
end

