# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiTabContainer <: wxObject
    ptr::Ptr{Cvoid}
end

function wxAuiTabContainer()
    ptr = KwxFFI.wxAuiTabContainer_Create()
    ptr == C_NULL && error("Failed to create wxAuiTabContainer")
    obj = wxAuiTabContainer(ptr)
    return obj
end

function (obj::wxAuiTabContainer, artId::Ptr{Cvoid})
    KwxFFI.wxAuiTabContainer_SetArtProvider(obj.ptr, artId)
    nothing
end

function (obj::wxAuiTabContainer)
    return KwxFFI.wxAuiTabContainer_GetArtProvider(obj.ptr)
end

function (obj::wxAuiTabContainer, flags::Integer)
    KwxFFI.wxAuiTabContainer_SetFlags(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxAuiTabContainer)
    return Int(KwxFFI.wxAuiTabContainer_GetFlags(obj.ptr))
end

function (obj::wxAuiTabContainer, page::Ptr{Cvoid}, info::Ptr{Cvoid})
    return KwxFFI.wxAuiTabContainer_AddPage(obj.ptr, page, info) != 0
end

function (obj::wxAuiTabContainer, page::Ptr{Cvoid}, info::Ptr{Cvoid}, idx::Integer)
    return KwxFFI.wxAuiTabContainer_InsertPage(obj.ptr, page, info, Csize_t(idx)) != 0
end

function (obj::wxAuiTabContainer, page::Ptr{Cvoid}, newIdx::Integer)
    return KwxFFI.wxAuiTabContainer_MovePage(obj.ptr, page, Csize_t(newIdx)) != 0
end

function (obj::wxAuiTabContainer, page::Ptr{Cvoid})
    return KwxFFI.wxAuiTabContainer_RemovePage(obj.ptr, page) != 0
end

function (obj::wxAuiTabContainer, page::Ptr{Cvoid})
    return KwxFFI.wxAuiTabContainer_SetActivePageByWindow(obj.ptr, page) != 0
end

function (obj::wxAuiTabContainer, page::Integer)
    return KwxFFI.wxAuiTabContainer_SetActivePage(obj.ptr, Csize_t(page)) != 0
end

function (obj::wxAuiTabContainer)
    KwxFFI.wxAuiTabContainer_SetNoneActive(obj.ptr)
    nothing
end

function (obj::wxAuiTabContainer)
    return Int(KwxFFI.wxAuiTabContainer_GetActivePage(obj.ptr))
end

function (obj::wxAuiTabContainer, idx::Integer)
    return KwxFFI.wxAuiTabContainer_GetWindowFromIdx(obj.ptr, Csize_t(idx))
end

function (obj::wxAuiTabContainer, page::Ptr{Cvoid})
    return Int(KwxFFI.wxAuiTabContainer_GetIdxFromWindow(obj.ptr, page))
end

function (obj::wxAuiTabContainer)
    return KwxFFI.wxAuiTabContainer_GetPageCount(obj.ptr)
end

function (obj::wxAuiTabContainer, idx::Integer)
    return KwxFFI.wxAuiTabContainer_GetPage(obj.ptr, Csize_t(idx))
end

function (obj::wxAuiTabContainer)
    return KwxFFI.wxAuiTabContainer_GetPages(obj.ptr)
end

function (obj::wxAuiTabContainer, normalFont::Ptr{Cvoid})
    KwxFFI.wxAuiTabContainer_SetNormalFont(obj.ptr, normalFont)
    nothing
end

function (obj::wxAuiTabContainer, selectedFont::Ptr{Cvoid})
    KwxFFI.wxAuiTabContainer_SetSelectedFont(obj.ptr, selectedFont)
    nothing
end

function (obj::wxAuiTabContainer, measuringFont::Ptr{Cvoid})
    KwxFFI.wxAuiTabContainer_SetMeasuringFont(obj.ptr, measuringFont)
    nothing
end

function (obj::wxAuiTabContainer, colour::Ptr{Cvoid})
    KwxFFI.wxAuiTabContainer_SetColour(obj.ptr, colour)
    nothing
end

function (obj::wxAuiTabContainer, colour::Ptr{Cvoid})
    KwxFFI.wxAuiTabContainer_SetActiveColour(obj.ptr, colour)
    nothing
end

function (obj::wxAuiTabContainer)
    KwxFFI.wxAuiTabContainer_DoShowHide(obj.ptr)
    nothing
end

function (obj::wxAuiTabContainer, rect::Ptr{Cvoid})
    KwxFFI.wxAuiTabContainer_SetRect(obj.ptr, rect)
    nothing
end

function (obj::wxAuiTabContainer, id::Integer)
    KwxFFI.wxAuiTabContainer_RemoveButton(obj.ptr, Cint(id))
    nothing
end

function (obj::wxAuiTabContainer, id::Integer, location::Integer, normalBitmap::Ptr{Cvoid}, disabledBitmap::Ptr{Cvoid})
    KwxFFI.wxAuiTabContainer_AddButton(obj.ptr, Cint(id), Cint(location), normalBitmap, disabledBitmap)
    nothing
end

function (obj::wxAuiTabContainer)
    return KwxFFI.wxAuiTabContainer_GetTabOffset(obj.ptr)
end

function (obj::wxAuiTabContainer, offset::Integer)
    KwxFFI.wxAuiTabContainer_SetTabOffset(obj.ptr, Csize_t(offset))
    nothing
end

function (obj::wxAuiTabContainer, tabPage::Integer, tabOffset::Integer, dc::Ptr{Cvoid}, window::Ptr{Cvoid})
    return KwxFFI.wxAuiTabContainer_IsTabVisible(obj.ptr, Cint(tabPage), Cint(tabOffset), dc, window) != 0
end

function (obj::wxAuiTabContainer, tabPage::Integer, win::Ptr{Cvoid})
    KwxFFI.wxAuiTabContainer_MakeTabVisible(obj.ptr, Cint(tabPage), win)
    nothing
end

