# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiNotebook <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxAuiNotebook()
    ptr = KwxFFI.wxAuiNotebook_CreateDefault()
    ptr == C_NULL && error("Failed to create wxAuiNotebook")
    obj = wxAuiNotebook(ptr, Any[], Any[])
    return obj
end

function wxAuiNotebook(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxAuiNotebook_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Clong(style))
    ptr == C_NULL && error("Failed to create wxAuiNotebook")
    obj = wxAuiNotebook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxAuiNotebook, parent::Ptr{Cvoid}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    return KwxFFI.wxAuiNotebook_CreateFromDefault(obj.ptr, parent, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Clong(style)) != 0
end

function (obj::wxAuiNotebook, page::Ptr{Cvoid}, caption::String, select::Bool, bitmap::Ptr{Cvoid})
    caption_ws = wxString(caption)
    _result = KwxFFI.wxAuiNotebook_AddPageWithBitmap(obj.ptr, page, caption_ws.ptr, Cint(select), bitmap) != 0
    delete!(caption_ws)
    return _result
end

function (obj::wxAuiNotebook, page::Ptr{Cvoid}, text::String, select::Bool, imageId::Integer)
    text_ws = wxString(text)
    _result = KwxFFI.wxAuiNotebook_AddPage(obj.ptr, page, text_ws.ptr, Cint(select), Cint(imageId)) != 0
    delete!(text_ws)
    return _result
end

function (obj::wxAuiNotebook, forward::Bool)
    KwxFFI.wxAuiNotebook_AdvanceSelection(obj.ptr, Cint(forward))
    nothing
end

function (obj::wxAuiNotebook, index::Integer)
    return Int(KwxFFI.wxAuiNotebook_ChangeSelection(obj.ptr, Csize_t(index)))
end

function (obj::wxAuiNotebook)
    return KwxFFI.wxAuiNotebook_DeleteAllPages(obj.ptr) != 0
end

function (obj::wxAuiNotebook, page::Integer)
    return KwxFFI.wxAuiNotebook_DeletePage(obj.ptr, Csize_t(page)) != 0
end

function (obj::wxAuiNotebook)
    return KwxFFI.wxAuiNotebook_GetArtProvider(obj.ptr)
end

function (obj::wxAuiNotebook)
    return KwxFFI.wxAuiNotebook_GetCurrentPage(obj.ptr)
end

function (obj::wxAuiNotebook, pageHeight::Integer)
    return Int(KwxFFI.wxAuiNotebook_GetHeightForPageHeight(obj.ptr, Cint(pageHeight)))
end

function (obj::wxAuiNotebook, page_idx::Integer)
    return KwxFFI.wxAuiNotebook_GetPage(obj.ptr, Csize_t(page_idx))
end

function (obj::wxAuiNotebook, page::Integer, bmp::Ptr{Cvoid})
    KwxFFI.wxAuiNotebook_GetPageBitmap(obj.ptr, Csize_t(page), bmp)
    nothing
end

function (obj::wxAuiNotebook)
    return KwxFFI.wxAuiNotebook_GetPageCount(obj.ptr)
end

function (obj::wxAuiNotebook, pageWnd::Ptr{Cvoid})
    return Int(KwxFFI.wxAuiNotebook_GetPageIndex(obj.ptr, pageWnd))
end

function (obj::wxAuiNotebook, page::Integer)
    return KwxFFI.wxAuiNotebook_GetPageText(obj.ptr, Csize_t(page))
end

function (obj::wxAuiNotebook, pageIdx::Integer)
    return KwxFFI.wxAuiNotebook_GetPageToolTip(obj.ptr, Csize_t(pageIdx))
end

function (obj::wxAuiNotebook)
    return Int(KwxFFI.wxAuiNotebook_GetSelection(obj.ptr))
end

function (obj::wxAuiNotebook)
    return Int(KwxFFI.wxAuiNotebook_GetTabCtrlHeight(obj.ptr))
end

function (obj::wxAuiNotebook, page_idx::Integer, page::Ptr{Cvoid}, caption::String, select::Bool, bitmap::Ptr{Cvoid})
    caption_ws = wxString(caption)
    _result = KwxFFI.wxAuiNotebook_InsertPageWithBitmap(obj.ptr, Csize_t(page_idx), page, caption_ws.ptr, Cint(select), bitmap) != 0
    delete!(caption_ws)
    return _result
end

function (obj::wxAuiNotebook, index::Integer, page::Ptr{Cvoid}, text::String, select::Bool, imageId::Integer)
    text_ws = wxString(text)
    _result = KwxFFI.wxAuiNotebook_InsertPage(obj.ptr, Csize_t(index), page, text_ws.ptr, Cint(select), Cint(imageId)) != 0
    delete!(text_ws)
    return _result
end

function (obj::wxAuiNotebook, page::Integer)
    return KwxFFI.wxAuiNotebook_RemovePage(obj.ptr, Csize_t(page)) != 0
end

function (obj::wxAuiNotebook, artId::Ptr{Cvoid})
    KwxFFI.wxAuiNotebook_SetArtProvider(obj.ptr, artId)
    nothing
end

function (obj::wxAuiNotebook, font::Ptr{Cvoid})
    return KwxFFI.wxAuiNotebook_SetFont(obj.ptr, font) != 0
end

function (obj::wxAuiNotebook, font::Ptr{Cvoid})
    KwxFFI.wxAuiNotebook_SetMeasuringFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiNotebook, font::Ptr{Cvoid})
    KwxFFI.wxAuiNotebook_SetNormalFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiNotebook, page::Integer, bitmap::Ptr{Cvoid})
    return KwxFFI.wxAuiNotebook_SetPageBitmap(obj.ptr, Csize_t(page), bitmap) != 0
end

function (obj::wxAuiNotebook, index::Integer, imageId::Integer)
    return KwxFFI.wxAuiNotebook_SetPageImage(obj.ptr, Csize_t(index), Cint(imageId)) != 0
end

function (obj::wxAuiNotebook, page::Integer, text::String)
    text_ws = wxString(text)
    _result = KwxFFI.wxAuiNotebook_SetPageText(obj.ptr, Csize_t(page), text_ws.ptr) != 0
    delete!(text_ws)
    return _result
end

function (obj::wxAuiNotebook, page::Integer, text::String)
    text_ws = wxString(text)
    _result = KwxFFI.wxAuiNotebook_SetPageToolTip(obj.ptr, Csize_t(page), text_ws.ptr) != 0
    delete!(text_ws)
    return _result
end

function (obj::wxAuiNotebook, font::Ptr{Cvoid})
    KwxFFI.wxAuiNotebook_SetSelectedFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiNotebook, new_page::Integer)
    return KwxFFI.wxAuiNotebook_SetSelection(obj.ptr, Csize_t(new_page))
end

function (obj::wxAuiNotebook, height::Integer)
    KwxFFI.wxAuiNotebook_SetTabCtrlHeight(obj.ptr, Cint(height))
    nothing
end

function (obj::wxAuiNotebook)
    return KwxFFI.wxAuiNotebook_ShowWindowMenu(obj.ptr) != 0
end

function (obj::wxAuiNotebook, width::Integer, height::Integer)
    KwxFFI.wxAuiNotebook_SetUniformBitmapSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxAuiNotebook, page::Integer, direction::Integer)
    KwxFFI.wxAuiNotebook_Split(obj.ptr, Csize_t(page), Cint(direction))
    nothing
end

