# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiDockArt <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxAuiDockArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, orientation::Integer, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDockArt_DrawBackground(obj.ptr, dc, window, Cint(orientation), rect)
    nothing
end

function (obj::wxAuiDockArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid}, pane::Ptr{Cvoid})
    KwxFFI.wxAuiDockArt_DrawBorder(obj.ptr, dc, window, rect, pane)
    nothing
end

function (obj::wxAuiDockArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, text::String, rect::Ptr{Cvoid}, pane::Ptr{Cvoid})
    text_ws = wxString(text)
    KwxFFI.wxAuiDockArt_DrawCaption(obj.ptr, dc, window, text_ws.ptr, rect, pane)
    delete!(text_ws)
    nothing
end

function (obj::wxAuiDockArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid}, pane::Ptr{Cvoid})
    KwxFFI.wxAuiDockArt_DrawGripper(obj.ptr, dc, window, rect, pane)
    nothing
end

function (obj::wxAuiDockArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, button::Integer, button_state::Integer, rect::Ptr{Cvoid}, pane::Ptr{Cvoid})
    KwxFFI.wxAuiDockArt_DrawPaneButton(obj.ptr, dc, window, Cint(button), Cint(button_state), rect, pane)
    nothing
end

function (obj::wxAuiDockArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, orientation::Integer, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDockArt_DrawSash(obj.ptr, dc, window, Cint(orientation), rect)
    nothing
end

function (obj::wxAuiDockArt, id::Integer)
    return KwxFFI.wxAuiDockArt_GetColour(obj.ptr, Cint(id))
end

function (obj::wxAuiDockArt, id::Integer)
    return KwxFFI.wxAuiDockArt_GetFont(obj.ptr, Cint(id))
end

function (obj::wxAuiDockArt, id::Integer)
    return Int(KwxFFI.wxAuiDockArt_GetMetric(obj.ptr, Cint(id)))
end

function (obj::wxAuiDockArt, id::Integer, colour::Ptr{Cvoid})
    KwxFFI.wxAuiDockArt_SetColour(obj.ptr, Cint(id), colour)
    nothing
end

function (obj::wxAuiDockArt, id::Integer, font::Ptr{Cvoid})
    KwxFFI.wxAuiDockArt_SetFont(obj.ptr, Cint(id), font)
    nothing
end

function (obj::wxAuiDockArt, id::Integer, new_val::Integer)
    KwxFFI.wxAuiDockArt_SetMetric(obj.ptr, Cint(id), Cint(new_val))
    nothing
end

