# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiManager <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function wxAuiManager(managedWnd::Ptr{Cvoid}, flags::Integer)
    ptr = KwxFFI.wxAuiManager_Create(managedWnd, Cint(flags))
    ptr == C_NULL && error("Failed to create wxAuiManager")
    obj = wxAuiManager(ptr)
    return obj
end

function delete!(obj::wxAuiManager)
    KwxFFI.wxAuiManager_Delete(obj.ptr)
    nothing
end

function (obj::wxAuiManager, window::Ptr{Cvoid})
    return KwxFFI.wxAuiManager_DetachPane(obj.ptr, window) != 0
end

function (obj::wxAuiManager)
    return KwxFFI.wxAuiManager_GetAllPanes(obj.ptr)
end

function (obj::wxAuiManager)
    return KwxFFI.wxAuiManager_GetArtProvider(obj.ptr)
end

function (obj::wxAuiManager, widthPct::Ptr{Cvoid}, heightPct::Ptr{Cvoid})
    KwxFFI.wxAuiManager_GetDockSizeConstraint(obj.ptr, widthPct, heightPct)
    nothing
end

function (obj::wxAuiManager)
    return Int(KwxFFI.wxAuiManager_GetFlags(obj.ptr))
end

function (obj::wxAuiManager)
    return KwxFFI.wxAuiManager_GetManagedWindow(obj.ptr)
end

function (obj::wxAuiManager)
    KwxFFI.wxAuiManager_HideHint(obj.ptr)
    nothing
end

function (obj::wxAuiManager, window::Ptr{Cvoid}, insertLocation::Ptr{Cvoid}, insertLevel::Integer)
    return KwxFFI.wxAuiManager_InsertPane(obj.ptr, window, insertLocation, Cint(insertLevel)) != 0
end

function (obj::wxAuiManager, panePart::String, pane::Ptr{Cvoid})
    panePart_ws = wxString(panePart)
    KwxFFI.wxAuiManager_LoadPaneInfo(obj.ptr, panePart_ws.ptr, pane)
    delete!(panePart_ws)
    nothing
end

function (obj::wxAuiManager, perspective::String, update::Bool)
    perspective_ws = wxString(perspective)
    _result = KwxFFI.wxAuiManager_LoadPerspective(obj.ptr, perspective_ws.ptr, Cint(update)) != 0
    delete!(perspective_ws)
    return _result
end

function (obj::wxAuiManager, pane::Ptr{Cvoid})
    return KwxFFI.wxAuiManager_SavePaneInfo(obj.ptr, pane)
end

function (obj::wxAuiManager)
    return KwxFFI.wxAuiManager_SavePerspective(obj.ptr)
end

function (obj::wxAuiManager, artProvider::Ptr{Cvoid})
    KwxFFI.wxAuiManager_SetArtProvider(obj.ptr, artProvider)
    nothing
end

function (obj::wxAuiManager, widthpct::Float64, heightpct::Float64)
    KwxFFI.wxAuiManager_SetDockSizeConstraint(obj.ptr, Cdouble(widthpct), Cdouble(heightpct))
    nothing
end

function (obj::wxAuiManager, flags::Integer)
    KwxFFI.wxAuiManager_SetFlags(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxAuiManager, managedWnd::Ptr{Cvoid})
    KwxFFI.wxAuiManager_SetManagedWindow(obj.ptr, managedWnd)
    nothing
end

function (obj::wxAuiManager, rect::Ptr{Cvoid})
    KwxFFI.wxAuiManager_ShowHint(obj.ptr, rect)
    nothing
end

function (obj::wxAuiManager)
    KwxFFI.wxAuiManager_UnInit(obj.ptr)
    nothing
end

function (obj::wxAuiManager)
    KwxFFI.wxAuiManager_Update(obj.ptr)
    nothing
end

function (obj::wxAuiManager, window::Ptr{Cvoid}, direction::Integer, caption::String)
    caption_ws = wxString(caption)
    _result = KwxFFI.wxAuiManager_AddPane(obj.ptr, window, Cint(direction), caption_ws.ptr) != 0
    delete!(caption_ws)
    return _result
end

function (obj::wxAuiManager, window::Ptr{Cvoid}, paneInfo::Ptr{Cvoid})
    return KwxFFI.wxAuiManager_AddPaneByPaneInfo(obj.ptr, window, paneInfo) != 0
end

function (obj::wxAuiManager, window::Ptr{Cvoid}, paneInfo::Ptr{Cvoid}, x::Integer, y::Integer)
    return KwxFFI.wxAuiManager_AddPaneByPaneInfoAndDropPosition(obj.ptr, window, paneInfo, Cint(x), Cint(y)) != 0
end

function (obj::wxAuiManager, window::Ptr{Cvoid})
    return KwxFFI.wxAuiManager_GetPaneByWindow(obj.ptr, window)
end

function (obj::wxAuiManager, name::String)
    name_ws = wxString(name)
    _result = KwxFFI.wxAuiManager_GetPaneByName(obj.ptr, name_ws.ptr)
    delete!(name_ws)
    return _result
end

function (obj::wxAuiManager, window::Ptr{Cvoid})
    return KwxFFI.wxAuiManager_GetManager(obj.ptr, window)
end

