# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiToolBarItem <: wxObject
    ptr::Ptr{Cvoid}
end

function wxAuiToolBarItem()
    ptr = KwxFFI.wxAuiToolBarItem_CreateDefault()
    ptr == C_NULL && error("Failed to create wxAuiToolBarItem")
    obj = wxAuiToolBarItem(ptr)
    return obj
end

function wxAuiToolBarItem(source::Ptr{Cvoid})
    ptr = KwxFFI.wxAuiToolBarItem_Create(source)
    ptr == C_NULL && error("Failed to create wxAuiToolBarItem")
    obj = wxAuiToolBarItem(ptr)
    return obj
end

function (obj::wxAuiToolBarItem, source::Ptr{Cvoid})
    return KwxFFI.wxAuiToolBarItem_Copy(obj.ptr, source)
end

function (obj::wxAuiToolBarItem, source::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarItem_Assign(obj.ptr, source)
    nothing
end

function (obj::wxAuiToolBarItem, window::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarItem_SetWindow(obj.ptr, window)
    nothing
end

function (obj::wxAuiToolBarItem)
    return KwxFFI.wxAuiToolBarItem_GetWindow(obj.ptr)
end

function (obj::wxAuiToolBarItem, new_id::Integer)
    KwxFFI.wxAuiToolBarItem_SetId(obj.ptr, Cint(new_id))
    nothing
end

function (obj::wxAuiToolBarItem)
    return Int(KwxFFI.wxAuiToolBarItem_GetId(obj.ptr))
end

function (obj::wxAuiToolBarItem, new_kind::Integer)
    KwxFFI.wxAuiToolBarItem_SetKind(obj.ptr, Cint(new_kind))
    nothing
end

function (obj::wxAuiToolBarItem)
    return Int(KwxFFI.wxAuiToolBarItem_GetKind(obj.ptr))
end

function (obj::wxAuiToolBarItem, new_state::Integer)
    KwxFFI.wxAuiToolBarItem_SetState(obj.ptr, Cint(new_state))
    nothing
end

function (obj::wxAuiToolBarItem)
    return Int(KwxFFI.wxAuiToolBarItem_GetState(obj.ptr))
end

function (obj::wxAuiToolBarItem, sizerItem::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarItem_SetSizerItem(obj.ptr, sizerItem)
    nothing
end

function (obj::wxAuiToolBarItem)
    return KwxFFI.wxAuiToolBarItem_GetSizerItem(obj.ptr)
end

function (obj::wxAuiToolBarItem, label::String)
    label_ws = wxString(label)
    KwxFFI.wxAuiToolBarItem_SetLabel(obj.ptr, label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxAuiToolBarItem)
    return KwxFFI.wxAuiToolBarItem_GetLabel(obj.ptr)
end

function (obj::wxAuiToolBarItem, bitmap::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarItem_SetBitmap(obj.ptr, bitmap)
    nothing
end

function (obj::wxAuiToolBarItem, ref::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarItem_GetBitmap(obj.ptr, ref)
    nothing
end

function (obj::wxAuiToolBarItem, bitmap::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarItem_SetDisabledBitmap(obj.ptr, bitmap)
    nothing
end

function (obj::wxAuiToolBarItem, ref::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarItem_GetDisabledBitmap(obj.ptr, ref)
    nothing
end

function (obj::wxAuiToolBarItem, bitmap::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarItem_SetHoverBitmap(obj.ptr, bitmap)
    nothing
end

function (obj::wxAuiToolBarItem, ref::Ptr{Cvoid})
    KwxFFI.wxAuiToolBarItem_GetHoverBitmap(obj.ptr, ref)
    nothing
end

function (obj::wxAuiToolBarItem, helpString::String)
    helpString_ws = wxString(helpString)
    KwxFFI.wxAuiToolBarItem_SetShortHelp(obj.ptr, helpString_ws.ptr)
    delete!(helpString_ws)
    nothing
end

function (obj::wxAuiToolBarItem)
    return KwxFFI.wxAuiToolBarItem_GetShortHelp(obj.ptr)
end

function (obj::wxAuiToolBarItem, helpString::String)
    helpString_ws = wxString(helpString)
    KwxFFI.wxAuiToolBarItem_SetLongHelp(obj.ptr, helpString_ws.ptr)
    delete!(helpString_ws)
    nothing
end

function (obj::wxAuiToolBarItem)
    return KwxFFI.wxAuiToolBarItem_GetLongHelp(obj.ptr)
end

function (obj::wxAuiToolBarItem, width::Integer, height::Integer)
    KwxFFI.wxAuiToolBarItem_SetMinSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxAuiToolBarItem)
    return KwxFFI.wxAuiToolBarItem_GetMinSize(obj.ptr)
end

function (obj::wxAuiToolBarItem, spacerPixels::Integer)
    KwxFFI.wxAuiToolBarItem_SetSpacerPixels(obj.ptr, Cint(spacerPixels))
    nothing
end

function (obj::wxAuiToolBarItem)
    return Int(KwxFFI.wxAuiToolBarItem_GetSpacerPixels(obj.ptr))
end

function (obj::wxAuiToolBarItem, proportion::Integer)
    KwxFFI.wxAuiToolBarItem_SetProportion(obj.ptr, Cint(proportion))
    nothing
end

function (obj::wxAuiToolBarItem)
    return Int(KwxFFI.wxAuiToolBarItem_GetProportion(obj.ptr))
end

function (obj::wxAuiToolBarItem, enable::Bool)
    KwxFFI.wxAuiToolBarItem_SetActive(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxAuiToolBarItem)
    return KwxFFI.wxAuiToolBarItem_IsActive(obj.ptr) != 0
end

function (obj::wxAuiToolBarItem, enable::Bool)
    KwxFFI.wxAuiToolBarItem_SetHasDropDown(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxAuiToolBarItem)
    return KwxFFI.wxAuiToolBarItem_HasDropDown(obj.ptr) != 0
end

function (obj::wxAuiToolBarItem, enable::Bool)
    KwxFFI.wxAuiToolBarItem_SetSticky(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxAuiToolBarItem)
    return KwxFFI.wxAuiToolBarItem_IsSticky(obj.ptr) != 0
end

function (obj::wxAuiToolBarItem, userData::Integer)
    KwxFFI.wxAuiToolBarItem_SetUserData(obj.ptr, Clong(userData))
    nothing
end

function (obj::wxAuiToolBarItem)
    return Int(KwxFFI.wxAuiToolBarItem_GetUserData(obj.ptr))
end

function (obj::wxAuiToolBarItem, alignment::Integer)
    KwxFFI.wxAuiToolBarItem_SetAlignment(obj.ptr, Cint(alignment))
    nothing
end

function (obj::wxAuiToolBarItem)
    return Int(KwxFFI.wxAuiToolBarItem_GetAlignment(obj.ptr))
end

