# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiTabArt <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxAuiTabArt)
    return KwxFFI.wxAuiTabArt_Clone(obj.ptr)
end

function (obj::wxAuiTabArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiTabArt_DrawBackground(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiTabArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, inRect::Ptr{Cvoid}, bitmap_id::Integer, button_state::Integer, orientation::Integer, outRect::Ptr{Cvoid})
    KwxFFI.wxAuiTabArt_DrawButton(obj.ptr, dc, window, inRect, Cint(bitmap_id), Cint(button_state), Cint(orientation), outRect)
    nothing
end

function (obj::wxAuiTabArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, page::Ptr{Cvoid}, rect::Ptr{Cvoid}, close_button_state::Integer, outTabRect::Ptr{Cvoid}, outButtonRect::Ptr{Cvoid}, x_extent::Ptr{Cvoid})
    KwxFFI.wxAuiTabArt_DrawTab(obj.ptr, dc, window, page, rect, Cint(close_button_state), outTabRect, outButtonRect, x_extent)
    nothing
end

function (obj::wxAuiTabArt, window::Ptr{Cvoid}, pages::Ptr{Cvoid}, width::Integer, height::Integer)
    return Int(KwxFFI.wxAuiTabArt_GetBestTabCtrlSize(obj.ptr, window, pages, Cint(width), Cint(height)))
end

function (obj::wxAuiTabArt)
    return Int(KwxFFI.wxAuiTabArt_GetIndentSize(obj.ptr))
end

function (obj::wxAuiTabArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, caption::String, bitmap::Ptr{Cvoid}, active::Bool, close_button_state::Integer, x_extent::Ptr{Cvoid})
    caption_ws = wxString(caption)
    _result = KwxFFI.wxAuiTabArt_GetTabSize(obj.ptr, dc, window, caption_ws.ptr, bitmap, Cint(active), Cint(close_button_state), x_extent)
    delete!(caption_ws)
    return _result
end

function (obj::wxAuiTabArt, flags::Integer)
    KwxFFI.wxAuiTabArt_SetFlags(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxAuiTabArt, font::Ptr{Cvoid})
    KwxFFI.wxAuiTabArt_SetMeasuringFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiTabArt, font::Ptr{Cvoid})
    KwxFFI.wxAuiTabArt_SetNormalFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiTabArt, font::Ptr{Cvoid})
    KwxFFI.wxAuiTabArt_SetSelectedFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiTabArt, colour::Ptr{Cvoid})
    KwxFFI.wxAuiTabArt_SetColour(obj.ptr, colour)
    nothing
end

function (obj::wxAuiTabArt, colour::Ptr{Cvoid})
    KwxFFI.wxAuiTabArt_SetActiveColour(obj.ptr, colour)
    nothing
end

function (obj::wxAuiTabArt, width::Integer, height::Integer, tab_count::Integer)
    KwxFFI.wxAuiTabArt_SetSizingInfo(obj.ptr, Cint(width), Cint(height), Csize_t(tab_count))
    nothing
end

