# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiMDIChildFrame <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxAuiMDIChildFrame(parent::Union{wxWindow, Nothing}, id::Integer, title::String, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    title_ws = wxString(title)
    ptr = KwxFFI.wxAuiMDIChildFrame_Create(parent_ptr, Cint(id), title_ws.ptr, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    delete!(title_ws)
    ptr == C_NULL && error("Failed to create wxAuiMDIChildFrame")
    obj = wxAuiMDIChildFrame(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxAuiMDIChildFrame)
    KwxFFI.wxAuiMDIChildFrame_Activate(obj.ptr)
    nothing
end

function (obj::wxAuiMDIChildFrame)
    return KwxFFI.wxAuiMDIChildFrame_GetMenuBar(obj.ptr)
end

function (obj::wxAuiMDIChildFrame, menuBar::Ptr{Cvoid})
    KwxFFI.wxAuiMDIChildFrame_SetMenuBar(obj.ptr, menuBar)
    nothing
end

function (obj::wxAuiMDIChildFrame)
    return KwxFFI.wxAuiMDIChildFrame_GetStatusBar(obj.ptr)
end

function (obj::wxAuiMDIChildFrame, number::Integer, style::Integer, id::Integer)
    return KwxFFI.wxAuiMDIChildFrame_CreateStatusBar(obj.ptr, Cint(number), Cint(style), Cint(id))
end

function (obj::wxAuiMDIChildFrame)
    return KwxFFI.wxAuiMDIChildFrame_GetToolBar(obj.ptr)
end

function (obj::wxAuiMDIChildFrame, style::Integer, id::Integer)
    return KwxFFI.wxAuiMDIChildFrame_CreateToolBar(obj.ptr, Cint(style), Cint(id))
end

function (obj::wxAuiMDIChildFrame, title::String)
    title_ws = wxString(title)
    KwxFFI.wxAuiMDIChildFrame_SetTitle(obj.ptr, title_ws.ptr)
    delete!(title_ws)
    nothing
end

function (obj::wxAuiMDIChildFrame)
    return KwxFFI.wxAuiMDIChildFrame_GetTitle(obj.ptr)
end

function (obj::wxAuiMDIChildFrame, icons::Ptr{Cvoid})
    KwxFFI.wxAuiMDIChildFrame_SetIcons(obj.ptr, icons)
    nothing
end

function (obj::wxAuiMDIChildFrame)
    return KwxFFI.wxAuiMDIChildFrame_GetIcons(obj.ptr)
end

function (obj::wxAuiMDIChildFrame, icon::Ptr{Cvoid})
    KwxFFI.wxAuiMDIChildFrame_SetIcon(obj.ptr, icon)
    nothing
end

function (obj::wxAuiMDIChildFrame)
    return KwxFFI.wxAuiMDIChildFrame_GetIcon(obj.ptr)
end

function (obj::wxAuiMDIChildFrame)
    return KwxFFI.wxAuiMDIChildFrame_GetMDIParent(obj.ptr)
end

