# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiPaneInfo <: wxObject
    ptr::Ptr{Cvoid}
end

function wxAuiPaneInfo()
    ptr = KwxFFI.wxAuiPaneInfo_CreateDefault()
    ptr == C_NULL && error("Failed to create wxAuiPaneInfo")
    obj = wxAuiPaneInfo(ptr)
    return obj
end

function wxAuiPaneInfo(source::Ptr{Cvoid})
    ptr = KwxFFI.wxAuiPaneInfo_Create(source)
    ptr == C_NULL && error("Failed to create wxAuiPaneInfo")
    obj = wxAuiPaneInfo(ptr)
    return obj
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Bottom(obj.ptr)
end

function (obj::wxAuiPaneInfo, enable::Bool)
    return KwxFFI.wxAuiPaneInfo_BottomDockable(obj.ptr, Cint(enable))
end

function (obj::wxAuiPaneInfo, caption::String)
    caption_ws = wxString(caption)
    _result = KwxFFI.wxAuiPaneInfo_Caption(obj.ptr, caption_ws.ptr)
    delete!(caption_ws)
    return _result
end

function (obj::wxAuiPaneInfo, visible::Bool)
    return KwxFFI.wxAuiPaneInfo_CaptionVisible(obj.ptr, Cint(visible))
end

function (obj::wxAuiPaneInfo, visible::Bool)
    return KwxFFI.wxAuiPaneInfo_CloseButton(obj.ptr, Cint(visible))
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_DefaultPane(obj.ptr)
end

function (obj::wxAuiPaneInfo, enable::Bool)
    return KwxFFI.wxAuiPaneInfo_DestroyOnClose(obj.ptr, Cint(enable))
end

function (obj::wxAuiPaneInfo, direction::Integer)
    return KwxFFI.wxAuiPaneInfo_Direction(obj.ptr, Cint(direction))
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Dock(obj.ptr)
end

function (obj::wxAuiPaneInfo, enable::Bool)
    return KwxFFI.wxAuiPaneInfo_DockFixed(obj.ptr, Cint(enable))
end

function (obj::wxAuiPaneInfo, enable::Bool)
    return KwxFFI.wxAuiPaneInfo_Dockable(obj.ptr, Cint(enable))
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Fixed(obj.ptr)
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Float(obj.ptr)
end

function (obj::wxAuiPaneInfo, enable::Bool)
    return KwxFFI.wxAuiPaneInfo_Floatable(obj.ptr, Cint(enable))
end

function (obj::wxAuiPaneInfo, visible::Bool)
    return KwxFFI.wxAuiPaneInfo_Gripper(obj.ptr, Cint(visible))
end

function (obj::wxAuiPaneInfo, attop::Bool)
    return KwxFFI.wxAuiPaneInfo_GripperTop(obj.ptr, Cint(attop))
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_HasBorder(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_HasCaption(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_HasCloseButton(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo, flag::Integer)
    return KwxFFI.wxAuiPaneInfo_HasFlag(obj.ptr, Cint(flag)) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_HasGripper(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_HasGripperTop(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_HasMaximizeButton(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_HasMinimizeButton(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_HasPinButton(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Hide(obj.ptr)
end

function (obj::wxAuiPaneInfo, bitmap::Ptr{Cvoid})
    return KwxFFI.wxAuiPaneInfo_Icon(obj.ptr, bitmap)
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsBottomDockable(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsDockable(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsDocked(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsFixed(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsFloatable(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsFloating(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsLeftDockable(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsMovable(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsOk(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsResizable(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsRightDockable(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsShown(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsToolbar(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_IsTopDockable(obj.ptr) != 0
end

function (obj::wxAuiPaneInfo, layer::Integer)
    return KwxFFI.wxAuiPaneInfo_Layer(obj.ptr, Cint(layer))
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Left(obj.ptr)
end

function (obj::wxAuiPaneInfo, enable::Bool)
    return KwxFFI.wxAuiPaneInfo_LeftDockable(obj.ptr, Cint(enable))
end

function (obj::wxAuiPaneInfo, visible::Bool)
    return KwxFFI.wxAuiPaneInfo_MaximizeButton(obj.ptr, Cint(visible))
end

function (obj::wxAuiPaneInfo, visible::Bool)
    return KwxFFI.wxAuiPaneInfo_MinimizeButton(obj.ptr, Cint(visible))
end

function (obj::wxAuiPaneInfo, enable::Bool)
    return KwxFFI.wxAuiPaneInfo_Movable(obj.ptr, Cint(enable))
end

function (obj::wxAuiPaneInfo, name::String)
    name_ws = wxString(name)
    _result = KwxFFI.wxAuiPaneInfo_Name(obj.ptr, name_ws.ptr)
    delete!(name_ws)
    return _result
end

function (obj::wxAuiPaneInfo, visible::Bool)
    return KwxFFI.wxAuiPaneInfo_PaneBorder(obj.ptr, Cint(visible))
end

function (obj::wxAuiPaneInfo, visible::Bool)
    return KwxFFI.wxAuiPaneInfo_PinButton(obj.ptr, Cint(visible))
end

function (obj::wxAuiPaneInfo, pos::Integer)
    return KwxFFI.wxAuiPaneInfo_Position(obj.ptr, Cint(pos))
end

function (obj::wxAuiPaneInfo, resizable::Bool)
    return KwxFFI.wxAuiPaneInfo_Resizable(obj.ptr, Cint(resizable))
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Right(obj.ptr)
end

function (obj::wxAuiPaneInfo, enable::Bool)
    return KwxFFI.wxAuiPaneInfo_RightDockable(obj.ptr, Cint(enable))
end

function (obj::wxAuiPaneInfo, row::Integer)
    return KwxFFI.wxAuiPaneInfo_Row(obj.ptr, Cint(row))
end

function (obj::wxAuiPaneInfo, source::Ptr{Cvoid})
    KwxFFI.wxAuiPaneInfo_SafeSet(obj.ptr, source)
    nothing
end

function (obj::wxAuiPaneInfo, flag::Integer, option_state::Bool)
    return KwxFFI.wxAuiPaneInfo_SetFlag(obj.ptr, Cint(flag), Cint(option_state))
end

function (obj::wxAuiPaneInfo, show::Bool)
    return KwxFFI.wxAuiPaneInfo_Show(obj.ptr, Cint(show))
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_ToolbarPane(obj.ptr)
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Top(obj.ptr)
end

function (obj::wxAuiPaneInfo, enable::Bool)
    return KwxFFI.wxAuiPaneInfo_TopDockable(obj.ptr, Cint(enable))
end

function (obj::wxAuiPaneInfo, window::Ptr{Cvoid})
    return KwxFFI.wxAuiPaneInfo_Window(obj.ptr, window)
end

function (obj::wxAuiPaneInfo, source::Ptr{Cvoid})
    return KwxFFI.wxAuiPaneInfo_Copy(obj.ptr, source)
end

function (obj::wxAuiPaneInfo, width::Integer, height::Integer)
    return KwxFFI.wxAuiPaneInfo_BestSize(obj.ptr, Cint(width), Cint(height))
end

function (obj::wxAuiPaneInfo, x::Integer, y::Integer)
    return KwxFFI.wxAuiPaneInfo_BestSizeXY(obj.ptr, Cint(x), Cint(y))
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Centre(obj.ptr)
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_Center(obj.ptr)
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_CentrePane(obj.ptr)
end

function (obj::wxAuiPaneInfo)
    return KwxFFI.wxAuiPaneInfo_CenterPane(obj.ptr)
end

function (obj::wxAuiPaneInfo, x::Integer, y::Integer)
    return KwxFFI.wxAuiPaneInfo_FloatingPosition(obj.ptr, Cint(x), Cint(y))
end

function (obj::wxAuiPaneInfo, x::Integer, y::Integer)
    return KwxFFI.wxAuiPaneInfo_FloatingPositionXY(obj.ptr, Cint(x), Cint(y))
end

function (obj::wxAuiPaneInfo, width::Integer, height::Integer)
    return KwxFFI.wxAuiPaneInfo_FloatingSize(obj.ptr, Cint(width), Cint(height))
end

function (obj::wxAuiPaneInfo, x::Integer, y::Integer)
    return KwxFFI.wxAuiPaneInfo_FloatingSizeXY(obj.ptr, Cint(x), Cint(y))
end

function (obj::wxAuiPaneInfo, width::Integer, height::Integer)
    return KwxFFI.wxAuiPaneInfo_MaxSize(obj.ptr, Cint(width), Cint(height))
end

function (obj::wxAuiPaneInfo, x::Integer, y::Integer)
    return KwxFFI.wxAuiPaneInfo_MaxSizeXY(obj.ptr, Cint(x), Cint(y))
end

function (obj::wxAuiPaneInfo, width::Integer, height::Integer)
    return KwxFFI.wxAuiPaneInfo_MinSize(obj.ptr, Cint(width), Cint(height))
end

function (obj::wxAuiPaneInfo, x::Integer, y::Integer)
    return KwxFFI.wxAuiPaneInfo_MinSizeXY(obj.ptr, Cint(x), Cint(y))
end

