# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiToolBar <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxAuiToolBar()
    ptr = KwxFFI.wxAuiToolBar_CreateDefault()
    ptr == C_NULL && error("Failed to create wxAuiToolBar")
    obj = wxAuiToolBar(ptr, Any[], Any[])
    return obj
end

function wxAuiToolBar(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxAuiToolBar_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Clong(style))
    ptr == C_NULL && error("Failed to create wxAuiToolBar")
    obj = wxAuiToolBar(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxAuiToolBar, parent::Ptr{Cvoid}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    return KwxFFI.wxAuiToolBar_CreateFromDefault(obj.ptr, parent, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Clong(style)) != 0
end

function delete!(obj::wxAuiToolBar)
    KwxFFI.wxAuiToolBar_Delete(obj.ptr)
    nothing
end

function (obj::wxAuiToolBar, style::Integer)
    KwxFFI.wxAuiToolBar_SetWindowStyleFlag(obj.ptr, Clong(style))
    nothing
end

function (obj::wxAuiToolBar)
    return Int(KwxFFI.wxAuiToolBar_GetWindowStyleFlag(obj.ptr))
end

function (obj::wxAuiToolBar, artId::Ptr{Cvoid})
    KwxFFI.wxAuiToolBar_SetArtProvider(obj.ptr, artId)
    nothing
end

function (obj::wxAuiToolBar)
    return KwxFFI.wxAuiToolBar_GetArtProvider(obj.ptr)
end

function (obj::wxAuiToolBar, font::Ptr{Cvoid})
    return KwxFFI.wxAuiToolBar_SetFont(obj.ptr, font) != 0
end

function (obj::wxAuiToolBar, tool_id::Integer, label::String, bitmap::Ptr{Cvoid}, shortHelpString::String, kind::Integer)
    label_ws = wxString(label)
    shortHelpString_ws = wxString(shortHelpString)
    _result = KwxFFI.wxAuiToolBar_AddToolByLabel(obj.ptr, Cint(tool_id), label_ws.ptr, bitmap, shortHelpString_ws.ptr, Cint(kind))
    delete!(label_ws)
    delete!(shortHelpString_ws)
    return _result
end

function (obj::wxAuiToolBar, tool_id::Integer, label::String, bitmap::Ptr{Cvoid}, disabledBitmap::Ptr{Cvoid}, kind::Integer, shortHelpString::String, longHelpString::String, clientData::Ptr{Cvoid})
    label_ws = wxString(label)
    shortHelpString_ws = wxString(shortHelpString)
    longHelpString_ws = wxString(longHelpString)
    _result = KwxFFI.wxAuiToolBar_AddTool(obj.ptr, Cint(tool_id), label_ws.ptr, bitmap, disabledBitmap, Cint(kind), shortHelpString_ws.ptr, longHelpString_ws.ptr, clientData)
    delete!(label_ws)
    delete!(shortHelpString_ws)
    delete!(longHelpString_ws)
    return _result
end

function (obj::wxAuiToolBar, tool_id::Integer, bitmap::Ptr{Cvoid}, disabledBitmap::Ptr{Cvoid}, toggle::Bool, clientData::Ptr{Cvoid}, shortHelpString::String, longHelpString::String)
    shortHelpString_ws = wxString(shortHelpString)
    longHelpString_ws = wxString(longHelpString)
    _result = KwxFFI.wxAuiToolBar_AddToolByBitmap(obj.ptr, Cint(tool_id), bitmap, disabledBitmap, Cint(toggle), clientData, shortHelpString_ws.ptr, longHelpString_ws.ptr)
    delete!(shortHelpString_ws)
    delete!(longHelpString_ws)
    return _result
end

function (obj::wxAuiToolBar, tool_id::Integer, label::String, width::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxAuiToolBar_AddLabel(obj.ptr, Cint(tool_id), label_ws.ptr, Cint(width))
    delete!(label_ws)
    return _result
end

function (obj::wxAuiToolBar, control::Ptr{Cvoid}, label::String)
    label_ws = wxString(label)
    _result = KwxFFI.wxAuiToolBar_AddControl(obj.ptr, control, label_ws.ptr)
    delete!(label_ws)
    return _result
end

function (obj::wxAuiToolBar)
    return KwxFFI.wxAuiToolBar_AddSeparator(obj.ptr)
end

function (obj::wxAuiToolBar, pixels::Integer)
    return KwxFFI.wxAuiToolBar_AddSpacer(obj.ptr, Cint(pixels))
end

function (obj::wxAuiToolBar, proportion::Integer)
    return KwxFFI.wxAuiToolBar_AddStretchSpacer(obj.ptr, Cint(proportion))
end

function (obj::wxAuiToolBar)
    return KwxFFI.wxAuiToolBar_Realize(obj.ptr) != 0
end

function (obj::wxAuiToolBar, window_id::Integer)
    return KwxFFI.wxAuiToolBar_FindControl(obj.ptr, Cint(window_id))
end

function (obj::wxAuiToolBar, x::Integer, y::Integer)
    return KwxFFI.wxAuiToolBar_FindToolByPosition(obj.ptr, Cint(x), Cint(y))
end

function (obj::wxAuiToolBar, idx::Integer)
    return KwxFFI.wxAuiToolBar_FindToolByIndex(obj.ptr, Cint(idx))
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_FindTool(obj.ptr, Cint(tool_id))
end

function (obj::wxAuiToolBar)
    KwxFFI.wxAuiToolBar_ClearTools(obj.ptr)
    nothing
end

function (obj::wxAuiToolBar)
    KwxFFI.wxAuiToolBar_Clear(obj.ptr)
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_DeleteTool(obj.ptr, Cint(tool_id)) != 0
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_DeleteByIndex(obj.ptr, Cint(tool_id)) != 0
end

function (obj::wxAuiToolBar)
    return KwxFFI.wxAuiToolBar_GetToolCount(obj.ptr)
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return Int(KwxFFI.wxAuiToolBar_GetToolPos(obj.ptr, Cint(tool_id)))
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return Int(KwxFFI.wxAuiToolBar_GetToolIndex(obj.ptr, Cint(tool_id)))
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolFits(obj.ptr, Cint(tool_id)) != 0
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolRect(obj.ptr, Cint(tool_id))
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolFitsByIndex(obj.ptr, Cint(tool_id)) != 0
end

function (obj::wxAuiToolBar)
    return KwxFFI.wxAuiToolBar_GetToolBarFits(obj.ptr) != 0
end

function (obj::wxAuiToolBar, width::Integer, height::Integer)
    KwxFFI.wxAuiToolBar_SetMargins(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxAuiToolBar, x::Integer, y::Integer)
    KwxFFI.wxAuiToolBar_SetMarginsXY(obj.ptr, Cint(x), Cint(y))
    nothing
end

function (obj::wxAuiToolBar, left::Integer, right::Integer, top::Integer, bottom::Integer)
    KwxFFI.wxAuiToolBar_SetMarginsDetailed(obj.ptr, Cint(left), Cint(right), Cint(top), Cint(bottom))
    nothing
end

function (obj::wxAuiToolBar, width::Integer, height::Integer)
    KwxFFI.wxAuiToolBar_SetToolBitmapSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxAuiToolBar)
    return KwxFFI.wxAuiToolBar_GetToolBitmapSize(obj.ptr)
end

function (obj::wxAuiToolBar)
    return KwxFFI.wxAuiToolBar_GetOverflowVisible(obj.ptr) != 0
end

function (obj::wxAuiToolBar, visible::Bool)
    KwxFFI.wxAuiToolBar_SetOverflowVisible(obj.ptr, Cint(visible))
    nothing
end

function (obj::wxAuiToolBar)
    return KwxFFI.wxAuiToolBar_GetGripperVisible(obj.ptr) != 0
end

function (obj::wxAuiToolBar, visible::Bool)
    KwxFFI.wxAuiToolBar_SetGripperVisible(obj.ptr, Cint(visible))
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer, state::Bool)
    KwxFFI.wxAuiToolBar_ToggleTool(obj.ptr, Cint(tool_id), Cint(state))
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolToggled(obj.ptr, Cint(tool_id)) != 0
end

function (obj::wxAuiToolBar, tool_id::Integer, state::Bool)
    KwxFFI.wxAuiToolBar_EnableTool(obj.ptr, Cint(tool_id), Cint(state))
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolEnabled(obj.ptr, Cint(tool_id)) != 0
end

function (obj::wxAuiToolBar, tool_id::Integer, dropdown::Bool)
    KwxFFI.wxAuiToolBar_SetToolDropDown(obj.ptr, Cint(tool_id), Cint(dropdown))
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolDropDown(obj.ptr, Cint(tool_id)) != 0
end

function (obj::wxAuiToolBar, padding::Integer)
    KwxFFI.wxAuiToolBar_SetToolBorderPadding(obj.ptr, Cint(padding))
    nothing
end

function (obj::wxAuiToolBar)
    return Int(KwxFFI.wxAuiToolBar_GetToolBorderPadding(obj.ptr))
end

function (obj::wxAuiToolBar, orientation::Integer)
    KwxFFI.wxAuiToolBar_SetToolTextOrientation(obj.ptr, Cint(orientation))
    nothing
end

function (obj::wxAuiToolBar)
    return Int(KwxFFI.wxAuiToolBar_GetToolTextOrientation(obj.ptr))
end

function (obj::wxAuiToolBar, packing::Integer)
    KwxFFI.wxAuiToolBar_SetToolPacking(obj.ptr, Cint(packing))
    nothing
end

function (obj::wxAuiToolBar)
    return Int(KwxFFI.wxAuiToolBar_GetToolPacking(obj.ptr))
end

function (obj::wxAuiToolBar, tool_id::Integer, proportion::Integer)
    KwxFFI.wxAuiToolBar_SetToolProportion(obj.ptr, Cint(tool_id), Cint(proportion))
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return Int(KwxFFI.wxAuiToolBar_GetToolProportion(obj.ptr, Cint(tool_id)))
end

function (obj::wxAuiToolBar, separation::Integer)
    KwxFFI.wxAuiToolBar_SetToolSeparation(obj.ptr, Cint(separation))
    nothing
end

function (obj::wxAuiToolBar)
    return Int(KwxFFI.wxAuiToolBar_GetToolSeparation(obj.ptr))
end

function (obj::wxAuiToolBar, tool_id::Integer, sticky::Bool)
    KwxFFI.wxAuiToolBar_SetToolSticky(obj.ptr, Cint(tool_id), Cint(sticky))
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolSticky(obj.ptr, Cint(tool_id)) != 0
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolLabel(obj.ptr, Cint(tool_id))
end

function (obj::wxAuiToolBar, tool_id::Integer, label::String)
    label_ws = wxString(label)
    KwxFFI.wxAuiToolBar_SetToolLabel(obj.ptr, Cint(tool_id), label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer, bitmap::Ptr{Cvoid})
    KwxFFI.wxAuiToolBar_GetToolBitmap(obj.ptr, Cint(tool_id), bitmap)
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer, bitmap::Ptr{Cvoid})
    KwxFFI.wxAuiToolBar_SetToolBitmap(obj.ptr, Cint(tool_id), bitmap)
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolShortHelp(obj.ptr, Cint(tool_id))
end

function (obj::wxAuiToolBar, tool_id::Integer, helpString::String)
    helpString_ws = wxString(helpString)
    KwxFFI.wxAuiToolBar_SetToolShortHelp(obj.ptr, Cint(tool_id), helpString_ws.ptr)
    delete!(helpString_ws)
    nothing
end

function (obj::wxAuiToolBar, tool_id::Integer)
    return KwxFFI.wxAuiToolBar_GetToolLongHelp(obj.ptr, Cint(tool_id))
end

function (obj::wxAuiToolBar, tool_id::Integer, helpString::String)
    helpString_ws = wxString(helpString)
    KwxFFI.wxAuiToolBar_SetToolLongHelp(obj.ptr, Cint(tool_id), helpString_ws.ptr)
    delete!(helpString_ws)
    nothing
end

function (obj::wxAuiToolBar, prepend::Ptr{Cvoid}, append::Ptr{Cvoid})
    KwxFFI.wxAuiToolBar_SetCustomOverflowItems(obj.ptr, prepend, append)
    nothing
end

function (obj::wxAuiToolBar, dock_direction::Integer)
    return KwxFFI.wxAuiToolBar_GetHintSize(obj.ptr, Cint(dock_direction))
end

function (obj::wxAuiToolBar, pane::Ptr{Cvoid})
    return KwxFFI.wxAuiToolBar_IsPaneValid(obj.ptr, pane) != 0
end

