# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiNotebookEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function wxAuiNotebookEvent(command_type::Integer, win_id::Integer)
    ptr = KwxFFI.wxAuiNotebookEvent_Create(Cint(command_type), Cint(win_id))
    ptr == C_NULL && error("Failed to create wxAuiNotebookEvent")
    obj = wxAuiNotebookEvent(ptr)
    return obj
end

function (obj::wxAuiNotebookEvent)
    return KwxFFI.wxAuiNotebookEvent_GetDragSource(obj.ptr)
end

