# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAutoBufferedPaintDC <: wxObject
    ptr::Ptr{Cvoid}
end

function wxAutoBufferedPaintDC(window::Ptr{Cvoid})
    ptr = KwxFFI.wxAutoBufferedPaintDC_Create(window)
    ptr == C_NULL && error("Failed to create wxAutoBufferedPaintDC")
    obj = wxAutoBufferedPaintDC(ptr)
    return obj
end

function delete!(obj::wxAutoBufferedPaintDC)
    KwxFFI.wxAutoBufferedPaintDC_Delete(obj.ptr)
    nothing
end

