# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiTabCtrl <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function (obj::wxAuiTabCtrl, artId::Ptr{Cvoid})
    KwxFFI.wxAuiTabCtrl_SetArtProvider(obj.ptr, artId)
    nothing
end

function (obj::wxAuiTabCtrl)
    return KwxFFI.wxAuiTabCtrl_GetArtProvider(obj.ptr)
end

function (obj::wxAuiTabCtrl, flags::Integer)
    KwxFFI.wxAuiTabCtrl_SetFlags(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxAuiTabCtrl)
    return Int(KwxFFI.wxAuiTabCtrl_GetFlags(obj.ptr))
end

function (obj::wxAuiTabCtrl, page::Ptr{Cvoid}, info::Ptr{Cvoid})
    return KwxFFI.wxAuiTabCtrl_AddPage(obj.ptr, page, info) != 0
end

function (obj::wxAuiTabCtrl, page::Ptr{Cvoid}, info::Ptr{Cvoid}, idx::Integer)
    return KwxFFI.wxAuiTabCtrl_InsertPage(obj.ptr, page, info, Csize_t(idx)) != 0
end

function (obj::wxAuiTabCtrl, page::Ptr{Cvoid}, newIdx::Integer)
    return KwxFFI.wxAuiTabCtrl_MovePage(obj.ptr, page, Csize_t(newIdx)) != 0
end

function (obj::wxAuiTabCtrl, page::Ptr{Cvoid})
    return KwxFFI.wxAuiTabCtrl_RemovePage(obj.ptr, page) != 0
end

function (obj::wxAuiTabCtrl, page::Ptr{Cvoid})
    return KwxFFI.wxAuiTabCtrl_SetActivePageByWindow(obj.ptr, page) != 0
end

function (obj::wxAuiTabCtrl, page::Integer)
    return KwxFFI.wxAuiTabCtrl_SetActivePage(obj.ptr, Csize_t(page)) != 0
end

function (obj::wxAuiTabCtrl)
    KwxFFI.wxAuiTabCtrl_SetNoneActive(obj.ptr)
    nothing
end

function (obj::wxAuiTabCtrl)
    return Int(KwxFFI.wxAuiTabCtrl_GetActivePage(obj.ptr))
end

function (obj::wxAuiTabCtrl, idx::Integer)
    return KwxFFI.wxAuiTabCtrl_GetWindowFromIdx(obj.ptr, Csize_t(idx))
end

function (obj::wxAuiTabCtrl, page::Ptr{Cvoid})
    return Int(KwxFFI.wxAuiTabCtrl_GetIdxFromWindow(obj.ptr, page))
end

function (obj::wxAuiTabCtrl)
    return KwxFFI.wxAuiTabCtrl_GetPageCount(obj.ptr)
end

function (obj::wxAuiTabCtrl, idx::Integer)
    return KwxFFI.wxAuiTabCtrl_GetPage(obj.ptr, Csize_t(idx))
end

function (obj::wxAuiTabCtrl)
    return KwxFFI.wxAuiTabCtrl_GetPages(obj.ptr)
end

function (obj::wxAuiTabCtrl, normalFont::Ptr{Cvoid})
    KwxFFI.wxAuiTabCtrl_SetNormalFont(obj.ptr, normalFont)
    nothing
end

function (obj::wxAuiTabCtrl, selectedFont::Ptr{Cvoid})
    KwxFFI.wxAuiTabCtrl_SetSelectedFont(obj.ptr, selectedFont)
    nothing
end

function (obj::wxAuiTabCtrl, measuringFont::Ptr{Cvoid})
    KwxFFI.wxAuiTabCtrl_SetMeasuringFont(obj.ptr, measuringFont)
    nothing
end

function (obj::wxAuiTabCtrl, colour::Ptr{Cvoid})
    KwxFFI.wxAuiTabCtrl_SetColour(obj.ptr, colour)
    nothing
end

function (obj::wxAuiTabCtrl, colour::Ptr{Cvoid})
    KwxFFI.wxAuiTabCtrl_SetActiveColour(obj.ptr, colour)
    nothing
end

function (obj::wxAuiTabCtrl)
    KwxFFI.wxAuiTabCtrl_DoShowHide(obj.ptr)
    nothing
end

function (obj::wxAuiTabCtrl, rect::Ptr{Cvoid})
    KwxFFI.wxAuiTabCtrl_SetRect(obj.ptr, rect)
    nothing
end

function (obj::wxAuiTabCtrl, id::Integer)
    KwxFFI.wxAuiTabCtrl_RemoveButton(obj.ptr, Cint(id))
    nothing
end

function (obj::wxAuiTabCtrl, id::Integer, location::Integer, normalBitmap::Ptr{Cvoid}, disabledBitmap::Ptr{Cvoid})
    KwxFFI.wxAuiTabCtrl_AddButton(obj.ptr, Cint(id), Cint(location), normalBitmap, disabledBitmap)
    nothing
end

function (obj::wxAuiTabCtrl)
    return KwxFFI.wxAuiTabCtrl_GetTabOffset(obj.ptr)
end

function (obj::wxAuiTabCtrl, offset::Integer)
    KwxFFI.wxAuiTabCtrl_SetTabOffset(obj.ptr, Csize_t(offset))
    nothing
end

function (obj::wxAuiTabCtrl, tabPage::Integer, tabOffset::Integer, dc::Ptr{Cvoid}, window::Ptr{Cvoid})
    return KwxFFI.wxAuiTabCtrl_IsTabVisible(obj.ptr, Cint(tabPage), Cint(tabOffset), dc, window) != 0
end

function (obj::wxAuiTabCtrl, tabPage::Integer, win::Ptr{Cvoid})
    KwxFFI.wxAuiTabCtrl_MakeTabVisible(obj.ptr, Cint(tabPage), win)
    nothing
end

