# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiToolBarItemArray <: wxObject
    ptr::Ptr{Cvoid}
end

function wxAuiToolBarItemArray()
    ptr = KwxFFI.wxAuiToolBarItemArray_Create()
    ptr == C_NULL && error("Failed to create wxAuiToolBarItemArray")
    obj = wxAuiToolBarItemArray(ptr)
    return obj
end

function delete!(obj::wxAuiToolBarItemArray)
    KwxFFI.wxAuiToolBarItemArray_Delete(obj.ptr)
    nothing
end

function (obj::wxAuiToolBarItemArray)
    return Int(KwxFFI.wxAuiToolBarItemArray_GetCount(obj.ptr))
end

function (obj::wxAuiToolBarItemArray, index::Integer)
    return KwxFFI.wxAuiToolBarItemArray_Item(obj.ptr, Cint(index))
end

