# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxAuiDefaultTabArt <: wxObject
    ptr::Ptr{Cvoid}
end

function wxAuiDefaultTabArt()
    ptr = KwxFFI.wxAuiDefaultTabArt_Create()
    ptr == C_NULL && error("Failed to create wxAuiDefaultTabArt")
    obj = wxAuiDefaultTabArt(ptr)
    return obj
end

function (obj::wxAuiDefaultTabArt)
    return KwxFFI.wxAuiDefaultTabArt_Clone(obj.ptr)
end

function (obj::wxAuiDefaultTabArt, flags::Integer)
    KwxFFI.wxAuiDefaultTabArt_SetFlags(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxAuiDefaultTabArt, width::Integer, height::Integer, tabCount::Integer)
    KwxFFI.wxAuiDefaultTabArt_SetSizingInfo(obj.ptr, Cint(width), Cint(height), Csize_t(tabCount))
    nothing
end

function (obj::wxAuiDefaultTabArt, font::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultTabArt_SetNormalFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiDefaultTabArt, font::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultTabArt_SetSelectedFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiDefaultTabArt, font::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultTabArt_SetMeasuringFont(obj.ptr, font)
    nothing
end

function (obj::wxAuiDefaultTabArt, colour::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultTabArt_SetColour(obj.ptr, colour)
    nothing
end

function (obj::wxAuiDefaultTabArt, colour::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultTabArt_SetActiveColour(obj.ptr, colour)
    nothing
end

function (obj::wxAuiDefaultTabArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, rect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultTabArt_DrawBackground(obj.ptr, dc, window, rect)
    nothing
end

function (obj::wxAuiDefaultTabArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, pane::Ptr{Cvoid}, inRect::Ptr{Cvoid}, closeButtonState::Integer, outTabRect::Ptr{Cvoid}, outButtonRect::Ptr{Cvoid}, xExtent::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultTabArt_DrawTab(obj.ptr, dc, window, pane, inRect, Cint(closeButtonState), outTabRect, outButtonRect, xExtent)
    nothing
end

function (obj::wxAuiDefaultTabArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, inRect::Ptr{Cvoid}, bitmapId::Integer, buttonState::Integer, orientation::Integer, outRect::Ptr{Cvoid})
    KwxFFI.wxAuiDefaultTabArt_DrawButton(obj.ptr, dc, window, inRect, Cint(bitmapId), Cint(buttonState), Cint(orientation), outRect)
    nothing
end

function (obj::wxAuiDefaultTabArt)
    return Int(KwxFFI.wxAuiDefaultTabArt_GetIndentSize(obj.ptr))
end

function (obj::wxAuiDefaultTabArt, dc::Ptr{Cvoid}, window::Ptr{Cvoid}, caption::String, bitmap::Ptr{Cvoid}, active::Bool, closeButtonState::Integer, xExtent::Ptr{Cvoid})
    caption_ws = wxString(caption)
    _result = KwxFFI.wxAuiDefaultTabArt_GetTabSize(obj.ptr, dc, window, caption_ws.ptr, bitmap, Cint(active), Cint(closeButtonState), xExtent)
    delete!(caption_ws)
    return _result
end

function (obj::wxAuiDefaultTabArt, window::Ptr{Cvoid}, items::Ptr{Cvoid}, activeIdx::Integer)
    return Int(KwxFFI.wxAuiDefaultTabArt_ShowDropDown(obj.ptr, window, items, Cint(activeIdx)))
end

function (obj::wxAuiDefaultTabArt, window::Ptr{Cvoid}, pages::Ptr{Cvoid}, width::Integer, height::Integer)
    return Int(KwxFFI.wxAuiDefaultTabArt_GetBestTabCtrlSize(obj.ptr, window, pages, Cint(width), Cint(height)))
end

