# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxBitmapComboBox <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxBitmapComboBox(parent::Union{wxWindow, Nothing}, id::Integer, value::String, x::Integer, y::Integer, width::Integer, height::Integer, n::Integer, str::Ptr{Cvoid}, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    value_ws = wxString(value)
    ptr = KwxFFI.wxBitmapComboBox_Create(parent_ptr, Cint(id), value_ws.ptr, Cint(x), Cint(y), Cint(width), Cint(height), Cint(n), str, Cint(style))
    delete!(value_ws)
    ptr == C_NULL && error("Failed to create wxBitmapComboBox")
    obj = wxBitmapComboBox(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxBitmapComboBox, item::String, bitmap::Ptr{Cvoid})
    item_ws = wxString(item)
    KwxFFI.wxBitmapComboBox_Append(obj.ptr, item_ws.ptr, bitmap)
    delete!(item_ws)
    nothing
end

function (obj::wxBitmapComboBox, item::String, bitmap::Ptr{Cvoid}, data::Ptr{Cvoid})
    item_ws = wxString(item)
    KwxFFI.wxBitmapComboBox_AppendWithClientData(obj.ptr, item_ws.ptr, bitmap, data)
    delete!(item_ws)
    nothing
end

function (obj::wxBitmapComboBox, item::String, bitmap::Ptr{Cvoid}, pos::Integer)
    item_ws = wxString(item)
    KwxFFI.wxBitmapComboBox_Insert(obj.ptr, item_ws.ptr, bitmap, Cint(pos))
    delete!(item_ws)
    nothing
end

function (obj::wxBitmapComboBox, item::String, bitmap::Ptr{Cvoid}, pos::Integer, data::Ptr{Cvoid})
    item_ws = wxString(item)
    KwxFFI.wxBitmapComboBox_InsertWithClientData(obj.ptr, item_ws.ptr, bitmap, Cint(pos), data)
    delete!(item_ws)
    nothing
end

function (obj::wxBitmapComboBox, index::Integer)
    return KwxFFI.wxBitmapComboBox_GetItemBitmap(obj.ptr, Cint(index))
end

function (obj::wxBitmapComboBox, index::Integer, bitmap::Ptr{Cvoid})
    KwxFFI.wxBitmapComboBox_SetItemBitmap(obj.ptr, Cint(index), bitmap)
    nothing
end

function (obj::wxBitmapComboBox)
    return KwxFFI.wxBitmapComboBox_GetBitmapSize(obj.ptr)
end

