# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxBitmapDataObject <: wxObject
    ptr::Ptr{Cvoid}
end

function wxBitmapDataObject(bitmap::Ptr{Cvoid})
    ptr = KwxFFI.BitmapDataObject_Create(bitmap)
    ptr == C_NULL && error("Failed to create wxBitmapDataObject")
    obj = wxBitmapDataObject(ptr)
    return obj
end

function wxBitmapDataObject()
    ptr = KwxFFI.BitmapDataObject_CreateEmpty()
    ptr == C_NULL && error("Failed to create wxBitmapDataObject")
    obj = wxBitmapDataObject(ptr)
    return obj
end

function delete!(obj::wxBitmapDataObject)
    KwxFFI.BitmapDataObject_Delete(obj.ptr)
    nothing
end

function (obj::wxBitmapDataObject, bitmap::Ptr{Cvoid})
    KwxFFI.BitmapDataObject_GetBitmap(obj.ptr, bitmap)
    nothing
end

function (obj::wxBitmapDataObject, bitmap::Ptr{Cvoid})
    KwxFFI.BitmapDataObject_SetBitmap(obj.ptr, bitmap)
    nothing
end

