# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxBookCtrlBase <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function (obj::wxBookCtrlBase, parent::Ptr{Cvoid}, winid::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer, name::String)
    name_ws = wxString(name)
    _result = KwxFFI.wxBookCtrlBase_CreateFromDefault(obj.ptr, parent, Cint(winid), Cint(x), Cint(y), Cint(width), Cint(height), Clong(style), name_ws.ptr) != 0
    delete!(name_ws)
    return _result
end

function (obj::wxBookCtrlBase, width::Integer, height::Integer)
    KwxFFI.wxBookCtrlBase_SetPageSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxBookCtrlBase, x::Integer, y::Integer, flags::Ptr{Cvoid})
    return Int(KwxFFI.wxBookCtrlBase_HitTest(obj.ptr, Cint(x), Cint(y), flags))
end

function (obj::wxBookCtrlBase, nPage::Integer)
    return Int(KwxFFI.wxBookCtrlBase_GetPageImage(obj.ptr, Csize_t(nPage)))
end

function (obj::wxBookCtrlBase, page::Integer, image::Integer)
    return KwxFFI.wxBookCtrlBase_SetPageImage(obj.ptr, Csize_t(page), Cint(image)) != 0
end

function (obj::wxBookCtrlBase, nPage::Integer)
    return KwxFFI.wxBookCtrlBase_GetPageText(obj.ptr, Csize_t(nPage))
end

function (obj::wxBookCtrlBase, page::Integer, text::String)
    text_ws = wxString(text)
    _result = KwxFFI.wxBookCtrlBase_SetPageText(obj.ptr, Csize_t(page), text_ws.ptr) != 0
    delete!(text_ws)
    return _result
end

function (obj::wxBookCtrlBase)
    return Int(KwxFFI.wxBookCtrlBase_GetSelection(obj.ptr))
end

function (obj::wxBookCtrlBase)
    return KwxFFI.wxBookCtrlBase_GetCurrentPage(obj.ptr)
end

function (obj::wxBookCtrlBase, page::Integer)
    return Int(KwxFFI.wxBookCtrlBase_SetSelection(obj.ptr, Csize_t(page)))
end

function (obj::wxBookCtrlBase, forward::Bool)
    KwxFFI.wxBookCtrlBase_AdvanceSelection(obj.ptr, Cint(forward))
    nothing
end

function (obj::wxBookCtrlBase, page::Integer)
    return Int(KwxFFI.wxBookCtrlBase_ChangeSelection(obj.ptr, Csize_t(page)))
end

function (obj::wxBookCtrlBase, page::Ptr{Cvoid})
    return Int(KwxFFI.wxBookCtrlBase_FindPage(obj.ptr, page))
end

function (obj::wxBookCtrlBase, page::Ptr{Cvoid}, text::String, select::Bool, imageId::Integer)
    text_ws = wxString(text)
    _result = KwxFFI.wxBookCtrlBase_AddPage(obj.ptr, page, text_ws.ptr, Cint(select), Cint(imageId)) != 0
    delete!(text_ws)
    return _result
end

function (obj::wxBookCtrlBase)
    return KwxFFI.wxBookCtrlBase_DeleteAllPages(obj.ptr) != 0
end

function (obj::wxBookCtrlBase, page::Integer)
    return KwxFFI.wxBookCtrlBase_DeletePage(obj.ptr, Csize_t(page)) != 0
end

function (obj::wxBookCtrlBase, index::Integer, page::Ptr{Cvoid}, text::String, select::Bool, imageId::Integer)
    text_ws = wxString(text)
    _result = KwxFFI.wxBookCtrlBase_InsertPage(obj.ptr, Csize_t(index), page, text_ws.ptr, Cint(select), Cint(imageId)) != 0
    delete!(text_ws)
    return _result
end

function (obj::wxBookCtrlBase, page::Integer)
    return KwxFFI.wxBookCtrlBase_RemovePage(obj.ptr, Csize_t(page)) != 0
end

function (obj::wxBookCtrlBase)
    return KwxFFI.wxBookCtrlBase_GetPageCount(obj.ptr)
end

function (obj::wxBookCtrlBase, page::Integer)
    return KwxFFI.wxBookCtrlBase_GetPage(obj.ptr, Csize_t(page))
end

function (obj::wxBookCtrlBase, imageList::Ptr{Cvoid})
    KwxFFI.wxBookCtrlBase_AssignImageList(obj.ptr, imageList)
    nothing
end

function (obj::wxBookCtrlBase, imageList::Ptr{Cvoid})
    KwxFFI.wxBookCtrlBase_SetImageList(obj.ptr, imageList)
    nothing
end

function (obj::wxBookCtrlBase)
    return KwxFFI.wxBookCtrlBase_GetImageList(obj.ptr)
end

