# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxBoxSizer <: wxSizer
    ptr::Ptr{Cvoid}
end

function wxBoxSizer(orient::Integer)
    ptr = KwxFFI.wxBoxSizer_Create(Cint(orient))
    ptr == C_NULL && error("Failed to create wxBoxSizer")
    obj = wxBoxSizer(ptr)
    return obj
end

function (obj::wxBoxSizer)
    return KwxFFI.wxBoxSizer_CalcMin(obj.ptr)
end

function (obj::wxBoxSizer)
    return Int(KwxFFI.wxBoxSizer_GetOrientation(obj.ptr))
end

function (obj::wxBoxSizer)
    KwxFFI.wxBoxSizer_RecalcSizes(obj.ptr)
    nothing
end

