# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCalculateLayoutEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function wxCalculateLayoutEvent(id::Integer)
    ptr = KwxFFI.wxCalculateLayoutEvent_Create(Cint(id))
    ptr == C_NULL && error("Failed to create wxCalculateLayoutEvent")
    obj = wxCalculateLayoutEvent(ptr)
    return obj
end

function (obj::wxCalculateLayoutEvent)
    return Int(KwxFFI.wxCalculateLayoutEvent_GetFlags(obj.ptr))
end

function (obj::wxCalculateLayoutEvent)
    return KwxFFI.wxCalculateLayoutEvent_GetRect(obj.ptr)
end

function (obj::wxCalculateLayoutEvent, flags::Integer)
    KwxFFI.wxCalculateLayoutEvent_SetFlags(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxCalculateLayoutEvent, x::Integer, y::Integer, width::Integer, height::Integer)
    KwxFFI.wxCalculateLayoutEvent_SetRect(obj.ptr, Cint(x), Cint(y), Cint(width), Cint(height))
    nothing
end

