# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCalendarCtrl <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxCalendarCtrl(parent::Union{wxWindow, Nothing}, id::Integer, date::Ptr{Cvoid}, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxCalendarCtrl_Create(parent_ptr, Cint(id), date, Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxCalendarCtrl")
    obj = wxCalendarCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxCalendarCtrl, display::Integer)
    KwxFFI.wxCalendarCtrl_EnableHolidayDisplay(obj.ptr, Cint(display))
    nothing
end

function (obj::wxCalendarCtrl, enable::Bool)
    KwxFFI.wxCalendarCtrl_EnableMonthChange(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxCalendarCtrl, day::Integer)
    return KwxFFI.wxCalendarCtrl_GetAttr(obj.ptr, Cint(day))
end

function (obj::wxCalendarCtrl, date::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_GetDate(obj.ptr, date)
    nothing
end

function (obj::wxCalendarCtrl, ref::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_GetHeaderColourBg(obj.ptr, ref)
    nothing
end

function (obj::wxCalendarCtrl, ref::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_GetHeaderColourFg(obj.ptr, ref)
    nothing
end

function (obj::wxCalendarCtrl, ref::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_GetHighlightColourBg(obj.ptr, ref)
    nothing
end

function (obj::wxCalendarCtrl, ref::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_GetHighlightColourFg(obj.ptr, ref)
    nothing
end

function (obj::wxCalendarCtrl, ref::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_GetHolidayColourBg(obj.ptr, ref)
    nothing
end

function (obj::wxCalendarCtrl, ref::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_GetHolidayColourFg(obj.ptr, ref)
    nothing
end

function (obj::wxCalendarCtrl, x::Integer, y::Integer, date::Ptr{Cvoid}, weekday::Ptr{Cvoid})
    return Int(KwxFFI.wxCalendarCtrl_HitTest(obj.ptr, Cint(x), Cint(y), date, weekday))
end

function (obj::wxCalendarCtrl, day::Integer)
    KwxFFI.wxCalendarCtrl_ResetAttr(obj.ptr, Cint(day))
    nothing
end

function (obj::wxCalendarCtrl, day::Integer, attr::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_SetAttr(obj.ptr, Cint(day), attr)
    nothing
end

function (obj::wxCalendarCtrl, date::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_SetDate(obj.ptr, date)
    nothing
end

function (obj::wxCalendarCtrl, colFg::Ptr{Cvoid}, colBg::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_SetHeaderColours(obj.ptr, colFg, colBg)
    nothing
end

function (obj::wxCalendarCtrl, colFg::Ptr{Cvoid}, colBg::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_SetHighlightColours(obj.ptr, colFg, colBg)
    nothing
end

function (obj::wxCalendarCtrl, day::Integer)
    KwxFFI.wxCalendarCtrl_SetHoliday(obj.ptr, Cint(day))
    nothing
end

function (obj::wxCalendarCtrl, colFg::Ptr{Cvoid}, colBg::Ptr{Cvoid})
    KwxFFI.wxCalendarCtrl_SetHolidayColours(obj.ptr, colFg, colBg)
    nothing
end

