# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCaret <: wxObject
    ptr::Ptr{Cvoid}
end

function wxCaret(window::Ptr{Cvoid}, width::Integer, height::Integer)
    ptr = KwxFFI.wxCaret_Create(window, Cint(width), Cint(height))
    ptr == C_NULL && error("Failed to create wxCaret")
    obj = wxCaret(ptr)
    return obj
end

function (obj::wxCaret)
    return Int(KwxFFI.wxCaret_GetBlinkTime(obj.ptr))
end

function (obj::wxCaret)
    return KwxFFI.wxCaret_GetPosition(obj.ptr)
end

function (obj::wxCaret)
    return KwxFFI.wxCaret_GetSize(obj.ptr)
end

function (obj::wxCaret)
    return KwxFFI.wxCaret_GetWindow(obj.ptr)
end

function (obj::wxCaret)
    KwxFFI.wxCaret_Hide(obj.ptr)
    nothing
end

function (obj::wxCaret)
    return KwxFFI.wxCaret_IsOk(obj.ptr) != 0
end

function (obj::wxCaret)
    return KwxFFI.wxCaret_IsVisible(obj.ptr) != 0
end

function (obj::wxCaret, x::Integer, y::Integer)
    KwxFFI.wxCaret_Move(obj.ptr, Cint(x), Cint(y))
    nothing
end

function (obj::wxCaret, milliseconds::Integer)
    KwxFFI.wxCaret_SetBlinkTime(obj.ptr, Cint(milliseconds))
    nothing
end

function (obj::wxCaret, width::Integer, height::Integer)
    KwxFFI.wxCaret_SetSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxCaret)
    KwxFFI.wxCaret_Show(obj.ptr)
    nothing
end

