# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCheckListBox <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxCheckListBox(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, n::Integer, str::Ptr{Cvoid}, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxCheckListBox_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(n), str, Cint(style))
    ptr == C_NULL && error("Failed to create wxCheckListBox")
    obj = wxCheckListBox(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxCheckListBox, item::Integer, check::Bool)
    KwxFFI.wxCheckListBox_Check(obj.ptr, Cint(item), Cint(check))
    nothing
end

function delete!(obj::wxCheckListBox)
    KwxFFI.wxCheckListBox_Delete(obj.ptr)
    nothing
end

function (obj::wxCheckListBox, checkedItems::Ptr{Cvoid}, allocated::Integer)
    return Int(KwxFFI.wxCheckListBox_GetCheckedItems(obj.ptr, checkedItems, Cint(allocated)))
end

function (obj::wxCheckListBox, item::Integer)
    return KwxFFI.wxCheckListBox_IsChecked(obj.ptr, Cint(item)) != 0
end

