# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxClosure <: wxObject
    ptr::Ptr{Cvoid}
end

function wxClosure(fun::Ptr{Cvoid}, data::Ptr{Cvoid})
    ptr = KwxFFI.wxClosure_Create(fun, data)
    ptr == C_NULL && error("Failed to create wxClosure")
    obj = wxClosure(ptr)
    return obj
end

function (obj::wxClosure)
    return KwxFFI.wxClosure_GetData(obj.ptr)
end

