# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxClassInfo <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxClassInfo)
    return KwxFFI.wxClassInfo_CreateClassByName(obj.ptr)
end

function (obj::wxClassInfo)
    return KwxFFI.wxClassInfo_GetClassName(obj.ptr)
end

function (obj::wxClassInfo, name::String)
    name_ws = wxString(name)
    _result = KwxFFI.wxClassInfo_IsKindOf(obj.ptr, name_ws.ptr) != 0
    delete!(name_ws)
    return _result
end

