# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxClientDC <: wxObject
    ptr::Ptr{Cvoid}
end

function wxClientDC(win::Ptr{Cvoid})
    ptr = KwxFFI.wxClientDC_Create(win)
    ptr == C_NULL && error("Failed to create wxClientDC")
    obj = wxClientDC(ptr)
    return obj
end

function delete!(obj::wxClientDC)
    KwxFFI.wxClientDC_Delete(obj.ptr)
    nothing
end

