# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxClipboard <: wxObject
    ptr::Ptr{Cvoid}
end

function wxClipboard()
    ptr = KwxFFI.wxClipboard_Create()
    ptr == C_NULL && error("Failed to create wxClipboard")
    obj = wxClipboard(ptr)
    return obj
end

function (obj::wxClipboard, data::Ptr{Cvoid})
    return KwxFFI.wxClipboard_AddData(obj.ptr, data) != 0
end

function (obj::wxClipboard)
    KwxFFI.wxClipboard_Clear(obj.ptr)
    nothing
end

function (obj::wxClipboard)
    KwxFFI.wxClipboard_Close(obj.ptr)
    nothing
end

function (obj::wxClipboard)
    return KwxFFI.wxClipboard_Flush(obj.ptr) != 0
end

function (obj::wxClipboard, data::Ptr{Cvoid})
    return KwxFFI.wxClipboard_GetData(obj.ptr, data) != 0
end

function (obj::wxClipboard)
    return KwxFFI.wxClipboard_IsOpened(obj.ptr) != 0
end

function (obj::wxClipboard, format::Ptr{Cvoid})
    return KwxFFI.wxClipboard_IsSupported(obj.ptr, format) != 0
end

function (obj::wxClipboard)
    return KwxFFI.wxClipboard_Open(obj.ptr) != 0
end

function (obj::wxClipboard, data::Ptr{Cvoid})
    return KwxFFI.wxClipboard_SetData(obj.ptr, data) != 0
end

function (obj::wxClipboard, primary::Bool)
    KwxFFI.wxClipboard_UsePrimarySelection(obj.ptr, Cint(primary))
    nothing
end

