# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCloseEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxCloseEvent)
    return KwxFFI.wxCloseEvent_CanVeto(obj.ptr) != 0
end

function (obj::wxCloseEvent, arg_ptr::Ptr{Cvoid})
    KwxFFI.wxCloseEvent_CopyObject(obj.ptr, arg_ptr)
    nothing
end

function (obj::wxCloseEvent)
    return KwxFFI.wxCloseEvent_GetLoggingOff(obj.ptr) != 0
end

function (obj::wxCloseEvent)
    return KwxFFI.wxCloseEvent_GetVeto(obj.ptr) != 0
end

function (obj::wxCloseEvent, canVeto::Bool)
    KwxFFI.wxCloseEvent_SetCanVeto(obj.ptr, Cint(canVeto))
    nothing
end

function (obj::wxCloseEvent, logOff::Bool)
    KwxFFI.wxCloseEvent_SetLoggingOff(obj.ptr, Cint(logOff))
    nothing
end

function (obj::wxCloseEvent, veto::Bool)
    KwxFFI.wxCloseEvent_Veto(obj.ptr, Cint(veto))
    nothing
end

