# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxConfigBase <: wxObject
    ptr::Ptr{Cvoid}
end

function wxConfigBase()
    ptr = KwxFFI.wxConfigBase_Create()
    ptr == C_NULL && error("Failed to create wxConfigBase")
    obj = wxConfigBase(ptr)
    return obj
end

function delete!(obj::wxConfigBase)
    KwxFFI.wxConfigBase_Delete(obj.ptr)
    nothing
end

function (obj::wxConfigBase)
    return KwxFFI.wxConfigBase_DeleteAll(obj.ptr) != 0
end

function (obj::wxConfigBase, key::String, bDeleteGroupIfEmpty::Bool)
    key_ws = wxString(key)
    _result = KwxFFI.wxConfigBase_DeleteEntry(obj.ptr, key_ws.ptr, Cint(bDeleteGroupIfEmpty)) != 0
    delete!(key_ws)
    return _result
end

function (obj::wxConfigBase, key::String)
    key_ws = wxString(key)
    _result = KwxFFI.wxConfigBase_DeleteGroup(obj.ptr, key_ws.ptr) != 0
    delete!(key_ws)
    return _result
end

function (obj::wxConfigBase, strName::String)
    strName_ws = wxString(strName)
    _result = KwxFFI.wxConfigBase_Exists(obj.ptr, strName_ws.ptr) != 0
    delete!(strName_ws)
    return _result
end

function (obj::wxConfigBase, str::String)
    str_ws = wxString(str)
    _result = KwxFFI.wxConfigBase_ExpandEnvVars(obj.ptr, str_ws.ptr)
    delete!(str_ws)
    return _result
end

function (obj::wxConfigBase, bCurrentOnly::Bool)
    return KwxFFI.wxConfigBase_Flush(obj.ptr, Cint(bCurrentOnly)) != 0
end

function (obj::wxConfigBase)
    return KwxFFI.wxConfigBase_GetAppName(obj.ptr)
end

function (obj::wxConfigBase, name::String)
    name_ws = wxString(name)
    _result = Int(KwxFFI.wxConfigBase_GetEntryType(obj.ptr, name_ws.ptr))
    delete!(name_ws)
    return _result
end

function (obj::wxConfigBase, lIndex::Ptr{Cvoid})
    return KwxFFI.wxConfigBase_GetFirstEntry(obj.ptr, lIndex)
end

function (obj::wxConfigBase, lIndex::Ptr{Cvoid})
    return KwxFFI.wxConfigBase_GetFirstGroup(obj.ptr, lIndex)
end

function (obj::wxConfigBase, lIndex::Ptr{Cvoid})
    return KwxFFI.wxConfigBase_GetNextEntry(obj.ptr, lIndex)
end

function (obj::wxConfigBase, lIndex::Ptr{Cvoid})
    return KwxFFI.wxConfigBase_GetNextGroup(obj.ptr, lIndex)
end

function (obj::wxConfigBase, bRecursive::Bool)
    return Int(KwxFFI.wxConfigBase_GetNumberOfEntries(obj.ptr, Cint(bRecursive)))
end

function (obj::wxConfigBase, bRecursive::Bool)
    return Int(KwxFFI.wxConfigBase_GetNumberOfGroups(obj.ptr, Cint(bRecursive)))
end

function (obj::wxConfigBase)
    return KwxFFI.wxConfigBase_GetPath(obj.ptr)
end

function (obj::wxConfigBase)
    return Int(KwxFFI.wxConfigBase_GetStyle(obj.ptr))
end

function (obj::wxConfigBase)
    return KwxFFI.wxConfigBase_GetVendorName(obj.ptr)
end

function (obj::wxConfigBase, strName::String)
    strName_ws = wxString(strName)
    _result = KwxFFI.wxConfigBase_HasEntry(obj.ptr, strName_ws.ptr) != 0
    delete!(strName_ws)
    return _result
end

function (obj::wxConfigBase, strName::String)
    strName_ws = wxString(strName)
    _result = KwxFFI.wxConfigBase_HasGroup(obj.ptr, strName_ws.ptr) != 0
    delete!(strName_ws)
    return _result
end

function (obj::wxConfigBase)
    return KwxFFI.wxConfigBase_IsExpandingEnvVars(obj.ptr) != 0
end

function (obj::wxConfigBase)
    return KwxFFI.wxConfigBase_IsRecordingDefaults(obj.ptr) != 0
end

function (obj::wxConfigBase, key::String, defVal::Bool)
    key_ws = wxString(key)
    _result = KwxFFI.wxConfigBase_ReadBool(obj.ptr, key_ws.ptr, Cint(defVal)) != 0
    delete!(key_ws)
    return _result
end

function (obj::wxConfigBase, key::String, defVal::Float64)
    key_ws = wxString(key)
    _result = Float64(KwxFFI.wxConfigBase_ReadDouble(obj.ptr, key_ws.ptr, Cdouble(defVal)))
    delete!(key_ws)
    return _result
end

function (obj::wxConfigBase, key::String, defVal::Integer)
    key_ws = wxString(key)
    _result = Int(KwxFFI.wxConfigBase_ReadInteger(obj.ptr, key_ws.ptr, Cint(defVal)))
    delete!(key_ws)
    return _result
end

function (obj::wxConfigBase, key::String, defVal::String)
    key_ws = wxString(key)
    defVal_ws = wxString(defVal)
    _result = KwxFFI.wxConfigBase_ReadString(obj.ptr, key_ws.ptr, defVal_ws.ptr)
    delete!(key_ws)
    delete!(defVal_ws)
    return _result
end

function (obj::wxConfigBase, oldName::String, newName::String)
    oldName_ws = wxString(oldName)
    newName_ws = wxString(newName)
    _result = KwxFFI.wxConfigBase_RenameEntry(obj.ptr, oldName_ws.ptr, newName_ws.ptr) != 0
    delete!(oldName_ws)
    delete!(newName_ws)
    return _result
end

function (obj::wxConfigBase, oldName::String, newName::String)
    oldName_ws = wxString(oldName)
    newName_ws = wxString(newName)
    _result = KwxFFI.wxConfigBase_RenameGroup(obj.ptr, oldName_ws.ptr, newName_ws.ptr) != 0
    delete!(oldName_ws)
    delete!(newName_ws)
    return _result
end

function (obj::wxConfigBase, appName::String)
    appName_ws = wxString(appName)
    KwxFFI.wxConfigBase_SetAppName(obj.ptr, appName_ws.ptr)
    delete!(appName_ws)
    nothing
end

function (obj::wxConfigBase, bDoIt::Bool)
    KwxFFI.wxConfigBase_SetExpandEnvVars(obj.ptr, Cint(bDoIt))
    nothing
end

function (obj::wxConfigBase, strPath::String)
    strPath_ws = wxString(strPath)
    KwxFFI.wxConfigBase_SetPath(obj.ptr, strPath_ws.ptr)
    delete!(strPath_ws)
    nothing
end

function (obj::wxConfigBase, bDoIt::Bool)
    KwxFFI.wxConfigBase_SetRecordDefaults(obj.ptr, Cint(bDoIt))
    nothing
end

function (obj::wxConfigBase, style::Integer)
    KwxFFI.wxConfigBase_SetStyle(obj.ptr, Cint(style))
    nothing
end

function (obj::wxConfigBase, vendorName::String)
    vendorName_ws = wxString(vendorName)
    KwxFFI.wxConfigBase_SetVendorName(obj.ptr, vendorName_ws.ptr)
    delete!(vendorName_ws)
    nothing
end

function (obj::wxConfigBase, key::String, value::Bool)
    key_ws = wxString(key)
    _result = KwxFFI.wxConfigBase_WriteBool(obj.ptr, key_ws.ptr, Cint(value)) != 0
    delete!(key_ws)
    return _result
end

function (obj::wxConfigBase, key::String, value::Float64)
    key_ws = wxString(key)
    _result = KwxFFI.wxConfigBase_WriteDouble(obj.ptr, key_ws.ptr, Cdouble(value)) != 0
    delete!(key_ws)
    return _result
end

function (obj::wxConfigBase, key::String, value::Integer)
    key_ws = wxString(key)
    _result = KwxFFI.wxConfigBase_WriteInteger(obj.ptr, key_ws.ptr, Cint(value)) != 0
    delete!(key_ws)
    return _result
end

function (obj::wxConfigBase, key::String, value::Integer)
    key_ws = wxString(key)
    _result = KwxFFI.wxConfigBase_WriteLong(obj.ptr, key_ws.ptr, Clong(value)) != 0
    delete!(key_ws)
    return _result
end

function (obj::wxConfigBase, key::String, value::String)
    key_ws = wxString(key)
    value_ws = wxString(value)
    _result = KwxFFI.wxConfigBase_WriteString(obj.ptr, key_ws.ptr, value_ws.ptr) != 0
    delete!(key_ws)
    delete!(value_ws)
    return _result
end

