# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCommandLinkButton <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxCommandLinkButton(parent::Union{wxWindow, Nothing}, id::Integer, mainLabel::String, note::String, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    mainLabel_ws = wxString(mainLabel)
    note_ws = wxString(note)
    ptr = KwxFFI.wxCommandLinkButton_Create(parent_ptr, Cint(id), mainLabel_ws.ptr, note_ws.ptr, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    delete!(mainLabel_ws)
    delete!(note_ws)
    ptr == C_NULL && error("Failed to create wxCommandLinkButton")
    obj = wxCommandLinkButton(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxCommandLinkButton, mainLabel::String)
    mainLabel_ws = wxString(mainLabel)
    KwxFFI.wxCommandLinkButton_SetMainLabel(obj.ptr, mainLabel_ws.ptr)
    delete!(mainLabel_ws)
    nothing
end

function (obj::wxCommandLinkButton, note::String)
    note_ws = wxString(note)
    KwxFFI.wxCommandLinkButton_SetNote(obj.ptr, note_ws.ptr)
    delete!(note_ws)
    nothing
end

function (obj::wxCommandLinkButton)
    return KwxFFI.wxCommandLinkButton_GetMainLabel(obj.ptr)
end

function (obj::wxCommandLinkButton)
    return KwxFFI.wxCommandLinkButton_GetNote(obj.ptr)
end

function (obj::wxCommandLinkButton, mainLabel::String, note::String)
    mainLabel_ws = wxString(mainLabel)
    note_ws = wxString(note)
    KwxFFI.wxCommandLinkButton_SetMainLabelAndNote(obj.ptr, mainLabel_ws.ptr, note_ws.ptr)
    delete!(mainLabel_ws)
    delete!(note_ws)
    nothing
end

