# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCondition <: wxObject
    ptr::Ptr{Cvoid}
end

function wxCondition(mutex::Ptr{Cvoid})
    ptr = KwxFFI.wxCondition_Create(mutex)
    ptr == C_NULL && error("Failed to create wxCondition")
    obj = wxCondition(ptr)
    return obj
end

function (obj::wxCondition)
    KwxFFI.wxCondition_Broadcast(obj.ptr)
    nothing
end

function delete!(obj::wxCondition)
    KwxFFI.wxCondition_Delete(obj.ptr)
    nothing
end

function (obj::wxCondition)
    KwxFFI.wxCondition_Signal(obj.ptr)
    nothing
end

function (obj::wxCondition)
    KwxFFI.wxCondition_Wait(obj.ptr)
    nothing
end

function (obj::wxCondition, sec::Integer, nsec::Integer)
    return Int(KwxFFI.wxCondition_WaitFor(obj.ptr, Cint(sec), Cint(nsec)))
end

