# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxColourDialog <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxColourDialog(parent::Union{wxWindow, Nothing}, col::Ptr{Cvoid})
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxColourDialog_Create(parent_ptr, col)
    ptr == C_NULL && error("Failed to create wxColourDialog")
    obj = wxColourDialog(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxColourDialog, ref::Ptr{Cvoid})
    KwxFFI.wxColourDialog_GetColourData(obj.ptr, ref)
    nothing
end

