# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxColour <: wxObject
    ptr::Ptr{Cvoid}
end

function wxColour(name::String)
    name_ws = wxString(name)
    ptr = KwxFFI.wxColour_CreateByName(name_ws.ptr)
    delete!(name_ws)
    ptr == C_NULL && error("Failed to create wxColour")
    obj = wxColour(ptr)
    return obj
end

function wxColour()
    ptr = KwxFFI.wxColour_CreateEmpty()
    ptr == C_NULL && error("Failed to create wxColour")
    obj = wxColour(ptr)
    return obj
end

function wxColour(id::Integer)
    ptr = KwxFFI.wxColour_CreateFromStock(Cint(id))
    ptr == C_NULL && error("Failed to create wxColour")
    obj = wxColour(ptr)
    return obj
end

function wxColour(red::Integer, green::Integer, blue::Integer, alpha::Integer)
    ptr = KwxFFI.wxColour_CreateRGB(Cuchar(red), Cuchar(green), Cuchar(blue), Cuchar(alpha))
    ptr == C_NULL && error("Failed to create wxColour")
    obj = wxColour(ptr)
    return obj
end

function (obj::wxColour)
    return KwxFFI.wxColour_Alpha(obj.ptr)
end

function (obj::wxColour, other::Ptr{Cvoid})
    KwxFFI.wxColour_Assign(obj.ptr, other)
    nothing
end

function (obj::wxColour)
    return KwxFFI.wxColour_Blue(obj.ptr)
end

function (obj::wxColour, other::Ptr{Cvoid})
    KwxFFI.wxColour_Copy(obj.ptr, other)
    nothing
end

function delete!(obj::wxColour)
    KwxFFI.wxColour_Delete(obj.ptr)
    nothing
end

function (obj::wxColour)
    return KwxFFI.wxColour_Green(obj.ptr)
end

function (obj::wxColour)
    return KwxFFI.wxColour_IsOk(obj.ptr) != 0
end

function (obj::wxColour)
    return KwxFFI.wxColour_Red(obj.ptr)
end

function (obj::wxColour, red::Integer, green::Integer, blue::Integer, alpha::Integer)
    KwxFFI.wxColour_Set(obj.ptr, Cuchar(red), Cuchar(green), Cuchar(blue), Cuchar(alpha))
    nothing
end

function (obj::wxColour, name::String)
    name_ws = wxString(name)
    KwxFFI.wxColour_SetByName(obj.ptr, name_ws.ptr)
    delete!(name_ws)
    nothing
end

function (obj::wxColour, name::Ptr{Cvoid})
    return KwxFFI.wxColour_ValidName(obj.ptr, name) != 0
end

