# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCollapsiblePane <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxCollapsiblePane(parent::Union{wxWindow, Nothing}, id::Integer, label::String, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    label_ws = wxString(label)
    ptr = KwxFFI.wxCollapsiblePane_Create(parent_ptr, Cint(id), label_ws.ptr, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    delete!(label_ws)
    ptr == C_NULL && error("Failed to create wxCollapsiblePane")
    obj = wxCollapsiblePane(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxCollapsiblePane, collapse::Bool)
    KwxFFI.wxCollapsiblePane_Collapse(obj.ptr, Cint(collapse))
    nothing
end

function (obj::wxCollapsiblePane)
    KwxFFI.wxCollapsiblePane_Expand(obj.ptr)
    nothing
end

function (obj::wxCollapsiblePane)
    return KwxFFI.wxCollapsiblePane_IsCollapsed(obj.ptr) != 0
end

function (obj::wxCollapsiblePane)
    return KwxFFI.wxCollapsiblePane_IsExpanded(obj.ptr) != 0
end

function (obj::wxCollapsiblePane)
    return KwxFFI.wxCollapsiblePane_GetPane(obj.ptr)
end

function (obj::wxCollapsiblePane)
    return KwxFFI.wxCollapsiblePane_GetLabel(obj.ptr)
end

function (obj::wxCollapsiblePane, label::String)
    label_ws = wxString(label)
    KwxFFI.wxCollapsiblePane_SetLabel(obj.ptr, label_ws.ptr)
    delete!(label_ws)
    nothing
end

