# Code generated by kwxgen. DO NOT EDIT.

function (obj::wxControl, event::Ptr{Cvoid})
    KwxFFI.wxControl_Command(obj.ptr, event)
    nothing
end

function (obj::wxControl)
    return KwxFFI.wxControl_GetLabel(obj.ptr)
end

function (obj::wxControl, text::String)
    text_ws = wxString(text)
    KwxFFI.wxControl_SetLabel(obj.ptr, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxControl, text::String)
    text_ws = wxString(text)
    KwxFFI.wxControl_SetLabelText(obj.ptr, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxControl)
    return KwxFFI.wxControl_GetLabelText(obj.ptr)
end

function (obj::wxControl, markup::String)
    markup_ws = wxString(markup)
    _result = KwxFFI.wxControl_SetLabelMarkup(obj.ptr, markup_ws.ptr) != 0
    delete!(markup_ws)
    return _result
end

function (obj::wxControl)
    return Int(KwxFFI.wxControl_GetAlignment(obj.ptr))
end

function (obj::wxControl, text::String, w::Ptr{Cvoid}, h::Ptr{Cvoid})
    text_ws = wxString(text)
    KwxFFI.wxControl_GetSizeFromText(obj.ptr, text_ws.ptr, w, h)
    delete!(text_ws)
    nothing
end

function (obj::wxControl, xlen::Integer, ylen::Integer, w::Ptr{Cvoid}, h::Ptr{Cvoid})
    KwxFFI.wxControl_GetSizeFromTextSize(obj.ptr, Cint(xlen), Cint(ylen), w, h)
    nothing
end

function (obj::wxControl, str::String)
    str_ws = wxString(str)
    _result = KwxFFI.wxControl_RemoveMnemonics(obj.ptr, str_ws.ptr)
    delete!(str_ws)
    return _result
end

function (obj::wxControl, str::String)
    str_ws = wxString(str)
    _result = KwxFFI.wxControl_EscapeMnemonics(obj.ptr, str_ws.ptr)
    delete!(str_ws)
    return _result
end

