# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxContextHelp <: wxObject
    ptr::Ptr{Cvoid}
end

function wxContextHelp(win::Ptr{Cvoid}, beginHelp::Bool)
    ptr = KwxFFI.wxContextHelp_Create(win, Cint(beginHelp))
    ptr == C_NULL && error("Failed to create wxContextHelp")
    obj = wxContextHelp(ptr)
    return obj
end

function (obj::wxContextHelp, win::Ptr{Cvoid})
    return KwxFFI.wxContextHelp_BeginContextHelp(obj.ptr, win) != 0
end

function delete!(obj::wxContextHelp)
    KwxFFI.wxContextHelp_Delete(obj.ptr)
    nothing
end

function (obj::wxContextHelp)
    return KwxFFI.wxContextHelp_EndContextHelp(obj.ptr) != 0
end

