# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCommandProcessor <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxCommandProcessor)
    return KwxFFI.wxCommandProcessor_CanRedo(obj.ptr) != 0
end

function (obj::wxCommandProcessor)
    return KwxFFI.wxCommandProcessor_CanUndo(obj.ptr) != 0
end

function (obj::wxCommandProcessor)
    KwxFFI.wxCommandProcessor_ClearCommands(obj.ptr)
    nothing
end

function delete!(obj::wxCommandProcessor)
    KwxFFI.wxCommandProcessor_Delete(obj.ptr)
    nothing
end

function (obj::wxCommandProcessor, ref::Ptr{Cvoid})
    return Int(KwxFFI.wxCommandProcessor_GetCommands(obj.ptr, ref))
end

function (obj::wxCommandProcessor)
    return KwxFFI.wxCommandProcessor_GetEditMenu(obj.ptr)
end

function (obj::wxCommandProcessor)
    return Int(KwxFFI.wxCommandProcessor_GetMaxCommands(obj.ptr))
end

function (obj::wxCommandProcessor)
    KwxFFI.wxCommandProcessor_Initialize(obj.ptr)
    nothing
end

function (obj::wxCommandProcessor)
    return Int(KwxFFI.wxCommandProcessor_Redo(obj.ptr))
end

function (obj::wxCommandProcessor, menu::Ptr{Cvoid})
    KwxFFI.wxCommandProcessor_SetEditMenu(obj.ptr, menu)
    nothing
end

function (obj::wxCommandProcessor)
    KwxFFI.wxCommandProcessor_SetMenuStrings(obj.ptr)
    nothing
end

function (obj::wxCommandProcessor, command::Ptr{Cvoid}, storeIt::Integer)
    return Int(KwxFFI.wxCommandProcessor_Submit(obj.ptr, command, Cint(storeIt)))
end

function (obj::wxCommandProcessor)
    return Int(KwxFFI.wxCommandProcessor_Undo(obj.ptr))
end

function (obj::wxCommandProcessor, maxCommands::Integer)
    return KwxFFI.wxCommandProcessor_wxCommandProcessor(obj.ptr, Cint(maxCommands))
end

