# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCriticalSection <: wxObject
    ptr::Ptr{Cvoid}
end

function wxCriticalSection()
    ptr = KwxFFI.wxCriticalSection_Create()
    ptr == C_NULL && error("Failed to create wxCriticalSection")
    obj = wxCriticalSection(ptr)
    return obj
end

function delete!(obj::wxCriticalSection)
    KwxFFI.wxCriticalSection_Delete(obj.ptr)
    nothing
end

function (obj::wxCriticalSection)
    KwxFFI.wxCriticalSection_Enter(obj.ptr)
    nothing
end

function (obj::wxCriticalSection)
    KwxFFI.wxCriticalSection_Leave(obj.ptr)
    nothing
end

