# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxCursor <: wxObject
    ptr::Ptr{Cvoid}
end

function wxCursor(id::Integer)
    ptr = KwxFFI.Cursor_CreateFromStock(Cint(id))
    ptr == C_NULL && error("Failed to create wxCursor")
    obj = wxCursor(ptr)
    return obj
end

function wxCursor(image::Ptr{Cvoid})
    ptr = KwxFFI.Cursor_CreateFromImage(image)
    ptr == C_NULL && error("Failed to create wxCursor")
    obj = wxCursor(ptr)
    return obj
end

function wxCursor(name::String, type_::Integer, width::Integer, height::Integer)
    name_ws = wxString(name)
    ptr = KwxFFI.Cursor_CreateLoad(name_ws.ptr, Clong(type_), Cint(width), Cint(height))
    delete!(name_ws)
    ptr == C_NULL && error("Failed to create wxCursor")
    obj = wxCursor(ptr)
    return obj
end

