# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDateTime <: wxObject
    ptr::Ptr{Cvoid}
end

function wxDateTime()
    ptr = KwxFFI.wxDateTime_Create()
    ptr == C_NULL && error("Failed to create wxDateTime")
    obj = wxDateTime(ptr)
    return obj
end

function (obj::wxDateTime, diff::Ptr{Cvoid}, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_AddDate(obj.ptr, diff, ref)
    nothing
end

function (obj::wxDateTime, years::Integer, month::Integer, week::Integer, day::Integer)
    KwxFFI.wxDateTime_AddDateValues(obj.ptr, Cint(years), Cint(month), Cint(week), Cint(day))
    nothing
end

function (obj::wxDateTime, diff::Ptr{Cvoid}, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_AddTime(obj.ptr, diff, ref)
    nothing
end

function (obj::wxDateTime, hours::Integer, minVal::Integer, seconds::Integer, milliseconds::Integer)
    KwxFFI.wxDateTime_AddTimeValues(obj.ptr, Cint(hours), Cint(minVal), Cint(seconds), Cint(milliseconds))
    nothing
end

function (obj::wxDateTime, year::Integer)
    return Int(KwxFFI.wxDateTime_ConvertYearToBC(obj.ptr, Cint(year)))
end

function (obj::wxDateTime, format::Ptr{Cvoid}, timeZone::Integer)
    return KwxFFI.wxDateTime_Format(obj.ptr, format, Cint(timeZone))
end

function (obj::wxDateTime)
    return KwxFFI.wxDateTime_FormatDate(obj.ptr)
end

function (obj::wxDateTime)
    return KwxFFI.wxDateTime_FormatISODate(obj.ptr)
end

function (obj::wxDateTime)
    return KwxFFI.wxDateTime_FormatISOTime(obj.ptr)
end

function (obj::wxDateTime)
    return KwxFFI.wxDateTime_FormatTime(obj.ptr)
end

function (obj::wxDateTime)
    return KwxFFI.wxDateTime_GetAmString(obj.ptr)
end

function (obj::wxDateTime, year::Integer, country::Integer, dateTime::Ptr{Cvoid})
    KwxFFI.wxDateTime_GetBeginDST(obj.ptr, Cint(year), Cint(country), dateTime)
    nothing
end

function (obj::wxDateTime, year::Integer)
    return Int(KwxFFI.wxDateTime_GetCentury(obj.ptr, Cint(year)))
end

function (obj::wxDateTime)
    return Int(KwxFFI.wxDateTime_GetCountry(obj.ptr))
end

function (obj::wxDateTime, cal::Integer)
    return Int(KwxFFI.wxDateTime_GetCurrentMonth(obj.ptr, Cint(cal)))
end

function (obj::wxDateTime, cal::Integer)
    return Int(KwxFFI.wxDateTime_GetCurrentYear(obj.ptr, Cint(cal)))
end

function (obj::wxDateTime, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetDay(obj.ptr, Cint(timeZone)))
end

function (obj::wxDateTime, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetDayOfYear(obj.ptr, Cint(timeZone)))
end

function (obj::wxDateTime, year::Integer, country::Integer, dateTime::Ptr{Cvoid})
    KwxFFI.wxDateTime_GetEndDST(obj.ptr, Cint(year), Cint(country), dateTime)
    nothing
end

function (obj::wxDateTime, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetHour(obj.ptr, Cint(timeZone)))
end

function (obj::wxDateTime, month::Integer, year::Integer, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_GetLastMonthDay(obj.ptr, Cint(month), Cint(year), ref)
    nothing
end

function (obj::wxDateTime, weekday::Integer, month::Integer, year::Integer, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_GetLastWeekDay(obj.ptr, Cint(weekday), Cint(month), Cint(year), ref)
    nothing
end

function (obj::wxDateTime, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetMillisecond(obj.ptr, Cint(timeZone)))
end

function (obj::wxDateTime, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetMinute(obj.ptr, Cint(timeZone)))
end

function (obj::wxDateTime, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetMonth(obj.ptr, Cint(timeZone)))
end

function (obj::wxDateTime, month::Integer, flags::Integer)
    return KwxFFI.wxDateTime_GetMonthName(obj.ptr, Cint(month), Cint(flags))
end

function (obj::wxDateTime, weekday::Integer, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_GetNextWeekDay(obj.ptr, Cint(weekday), ref)
    nothing
end

function (obj::wxDateTime, year::Integer, cal::Integer)
    return Int(KwxFFI.wxDateTime_GetNumberOfDays(obj.ptr, Cint(year), Cint(cal)))
end

function (obj::wxDateTime, month::Integer, year::Integer, cal::Integer)
    return Int(KwxFFI.wxDateTime_GetNumberOfDaysMonth(obj.ptr, Cint(month), Cint(year), Cint(cal)))
end

function (obj::wxDateTime)
    return KwxFFI.wxDateTime_GetPmString(obj.ptr)
end

function (obj::wxDateTime, weekday::Integer, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_GetPrevWeekDay(obj.ptr, Cint(weekday), ref)
    nothing
end

function (obj::wxDateTime, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetSecond(obj.ptr, Cint(timeZone)))
end

function (obj::wxDateTime)
    return Int(KwxFFI.wxDateTime_GetTicks(obj.ptr))
end

function (obj::wxDateTime)
    return Int(KwxFFI.wxDateTime_GetTimeNow(obj.ptr))
end

function (obj::wxDateTime, hi_long::Ptr{Cvoid}, lo_long::Ptr{Cvoid})
    KwxFFI.wxDateTime_GetValue(obj.ptr, hi_long, lo_long)
    nothing
end

function (obj::wxDateTime, weekday::Integer, nthWeek::Integer, month::Integer, year::Integer, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_GetWeekDay(obj.ptr, Cint(weekday), Cint(nthWeek), Cint(month), Cint(year), ref)
    nothing
end

function (obj::wxDateTime, weekday::Integer, flags::Integer, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_GetWeekDayInSameWeek(obj.ptr, Cint(weekday), Cint(flags), ref)
    nothing
end

function (obj::wxDateTime, weekday::Integer, flags::Integer)
    return KwxFFI.wxDateTime_GetWeekDayName(obj.ptr, Cint(weekday), Cint(flags))
end

function (obj::wxDateTime, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetWeekDayTZ(obj.ptr, Cint(timeZone)))
end

function (obj::wxDateTime, flags::Integer, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetWeekOfMonth(obj.ptr, Cint(flags), Cint(timeZone)))
end

function (obj::wxDateTime, flags::Integer, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetWeekOfYear(obj.ptr, Cint(flags), Cint(timeZone)))
end

function (obj::wxDateTime, timeZone::Integer)
    return Int(KwxFFI.wxDateTime_GetYear(obj.ptr, Cint(timeZone)))
end

function (obj::wxDateTime, t1::Ptr{Cvoid}, t2::Ptr{Cvoid})
    return KwxFFI.wxDateTime_IsBetween(obj.ptr, t1, t2) != 0
end

function (obj::wxDateTime, country::Integer)
    return KwxFFI.wxDateTime_IsDST(obj.ptr, Cint(country)) != 0
end

function (obj::wxDateTime, year::Integer, country::Integer)
    return KwxFFI.wxDateTime_IsDSTApplicable(obj.ptr, Cint(year), Cint(country)) != 0
end

function (obj::wxDateTime, datetime::Ptr{Cvoid})
    return KwxFFI.wxDateTime_IsEarlierThan(obj.ptr, datetime) != 0
end

function (obj::wxDateTime, datetime::Ptr{Cvoid})
    return KwxFFI.wxDateTime_IsEqualTo(obj.ptr, datetime) != 0
end

function (obj::wxDateTime, dateTime::Ptr{Cvoid}, timeSpan::Ptr{Cvoid})
    return KwxFFI.wxDateTime_IsEqualUpTo(obj.ptr, dateTime, timeSpan) != 0
end

function (obj::wxDateTime, country::Integer)
    return KwxFFI.wxDateTime_IsGregorianDate(obj.ptr, Cint(country)) != 0
end

function (obj::wxDateTime, datetime::Ptr{Cvoid})
    return KwxFFI.wxDateTime_IsLaterThan(obj.ptr, datetime) != 0
end

function (obj::wxDateTime, year::Integer, cal::Integer)
    return KwxFFI.wxDateTime_IsLeapYear(obj.ptr, Cint(year), Cint(cal)) != 0
end

function (obj::wxDateTime, dateTime::Ptr{Cvoid})
    return KwxFFI.wxDateTime_IsSameDate(obj.ptr, dateTime) != 0
end

function (obj::wxDateTime, dateTime::Ptr{Cvoid})
    return KwxFFI.wxDateTime_IsSameTime(obj.ptr, dateTime) != 0
end

function (obj::wxDateTime, t1::Ptr{Cvoid}, t2::Ptr{Cvoid})
    return KwxFFI.wxDateTime_IsStrictlyBetween(obj.ptr, t1, t2) != 0
end

function (obj::wxDateTime)
    return KwxFFI.wxDateTime_IsValid(obj.ptr) != 0
end

function (obj::wxDateTime, country::Integer)
    return KwxFFI.wxDateTime_IsWestEuropeanCountry(obj.ptr, Cint(country)) != 0
end

function (obj::wxDateTime, country::Integer)
    return KwxFFI.wxDateTime_IsWorkDay(obj.ptr, Cint(country)) != 0
end

function (obj::wxDateTime, noDST::Integer)
    KwxFFI.wxDateTime_MakeGMT(obj.ptr, Cint(noDST))
    nothing
end

function (obj::wxDateTime, timeZone::Integer, noDST::Integer)
    KwxFFI.wxDateTime_MakeTimezone(obj.ptr, Cint(timeZone), Cint(noDST))
    nothing
end

function (obj::wxDateTime)
    KwxFFI.wxDateTime_Now(obj.ptr)
    nothing
end

function (obj::wxDateTime, date::Ptr{Cvoid})
    return KwxFFI.wxDateTime_ParseDate(obj.ptr, date)
end

function (obj::wxDateTime, datetime::Ptr{Cvoid})
    return KwxFFI.wxDateTime_ParseDateTime(obj.ptr, datetime)
end

function (obj::wxDateTime, date::Ptr{Cvoid}, format::Ptr{Cvoid}, dateDef::Ptr{Cvoid})
    return KwxFFI.wxDateTime_ParseFormat(obj.ptr, date, format, dateDef)
end

function (obj::wxDateTime, date::Ptr{Cvoid})
    return KwxFFI.wxDateTime_ParseRfc822Date(obj.ptr, date)
end

function (obj::wxDateTime, time::Ptr{Cvoid})
    return KwxFFI.wxDateTime_ParseTime(obj.ptr, time)
end

function (obj::wxDateTime)
    KwxFFI.wxDateTime_ResetTime(obj.ptr)
    nothing
end

function (obj::wxDateTime, day::Integer, month::Integer, year::Integer, hour::Integer, minute::Integer, second::Integer, millisec::Integer)
    KwxFFI.wxDateTime_Set(obj.ptr, Cint(day), Cint(month), Cint(year), Cint(hour), Cint(minute), Cint(second), Cint(millisec))
    nothing
end

function (obj::wxDateTime, country::Integer)
    KwxFFI.wxDateTime_SetCountry(obj.ptr, Cint(country))
    nothing
end

function (obj::wxDateTime, day::Integer)
    KwxFFI.wxDateTime_SetDay(obj.ptr, Cint(day))
    nothing
end

function (obj::wxDateTime, hour::Integer)
    KwxFFI.wxDateTime_SetHour(obj.ptr, Cint(hour))
    nothing
end

function (obj::wxDateTime, millisecond::Integer)
    KwxFFI.wxDateTime_SetMillisecond(obj.ptr, Cint(millisecond))
    nothing
end

function (obj::wxDateTime, minute::Integer)
    KwxFFI.wxDateTime_SetMinute(obj.ptr, Cint(minute))
    nothing
end

function (obj::wxDateTime, month::Integer)
    KwxFFI.wxDateTime_SetMonth(obj.ptr, Cint(month))
    nothing
end

function (obj::wxDateTime, second::Integer)
    KwxFFI.wxDateTime_SetSecond(obj.ptr, Cint(second))
    nothing
end

function (obj::wxDateTime, hour::Integer, minute::Integer, second::Integer, millisec::Integer)
    KwxFFI.wxDateTime_SetTime(obj.ptr, Cint(hour), Cint(minute), Cint(second), Cint(millisec))
    nothing
end

function (obj::wxDateTime)
    KwxFFI.wxDateTime_SetToCurrent(obj.ptr)
    nothing
end

function (obj::wxDateTime, month::Integer, year::Integer)
    KwxFFI.wxDateTime_SetToLastMonthDay(obj.ptr, Cint(month), Cint(year))
    nothing
end

function (obj::wxDateTime, weekday::Integer, month::Integer, year::Integer)
    return KwxFFI.wxDateTime_SetToLastWeekDay(obj.ptr, Cint(weekday), Cint(month), Cint(year)) != 0
end

function (obj::wxDateTime, weekday::Integer)
    KwxFFI.wxDateTime_SetToNextWeekDay(obj.ptr, Cint(weekday))
    nothing
end

function (obj::wxDateTime, weekday::Integer)
    KwxFFI.wxDateTime_SetToPrevWeekDay(obj.ptr, Cint(weekday))
    nothing
end

function (obj::wxDateTime, weekday::Integer, nthWeek::Integer, month::Integer, year::Integer)
    return KwxFFI.wxDateTime_SetToWeekDay(obj.ptr, Cint(weekday), Cint(nthWeek), Cint(month), Cint(year)) != 0
end

function (obj::wxDateTime, weekday::Integer, flags::Integer)
    KwxFFI.wxDateTime_SetToWeekDayInSameWeek(obj.ptr, Cint(weekday), Cint(flags))
    nothing
end

function (obj::wxDateTime, year::Integer)
    KwxFFI.wxDateTime_SetYear(obj.ptr, Cint(year))
    nothing
end

function (obj::wxDateTime, diff::Ptr{Cvoid}, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_SubtractDate(obj.ptr, diff, ref)
    nothing
end

function (obj::wxDateTime, diff::Ptr{Cvoid}, ref::Ptr{Cvoid})
    KwxFFI.wxDateTime_SubtractTime(obj.ptr, diff, ref)
    nothing
end

function (obj::wxDateTime, noDST::Integer)
    KwxFFI.wxDateTime_ToGMT(obj.ptr, Cint(noDST))
    nothing
end

function (obj::wxDateTime, timeZone::Integer, noDST::Integer)
    KwxFFI.wxDateTime_ToTimezone(obj.ptr, Cint(timeZone), Cint(noDST))
    nothing
end

function (obj::wxDateTime)
    KwxFFI.wxDateTime_Today(obj.ptr)
    nothing
end

function (obj::wxDateTime)
    KwxFFI.wxDateTime_UNow(obj.ptr)
    nothing
end

function (obj::wxDateTime, hi_long::Integer, lo_long::Integer)
    return KwxFFI.wxDateTime_wxDateTime(obj.ptr, Cint(hi_long), Cint(lo_long))
end

