# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDateProperty <: wxObject
    ptr::Ptr{Cvoid}
end

function wxDateProperty(label::String, name::String, value::Ptr{Cvoid})
    label_ws = wxString(label)
    name_ws = wxString(name)
    ptr = KwxFFI.wxDateProperty_Create(label_ws.ptr, name_ws.ptr, value)
    delete!(label_ws)
    delete!(name_ws)
    ptr == C_NULL && error("Failed to create wxDateProperty")
    obj = wxDateProperty(ptr)
    return obj
end

