# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDirDialog <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxDirDialog(parent::Union{wxWindow, Nothing}, message::String, directory::String, left::Integer, top::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    message_ws = wxString(message)
    directory_ws = wxString(directory)
    ptr = KwxFFI.wxDirDialog_Create(parent_ptr, message_ws.ptr, directory_ws.ptr, Cint(left), Cint(top), Cint(style))
    delete!(message_ws)
    delete!(directory_ws)
    ptr == C_NULL && error("Failed to create wxDirDialog")
    obj = wxDirDialog(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxDirDialog)
    return KwxFFI.wxDirDialog_GetMessage(obj.ptr)
end

function (obj::wxDirDialog)
    return KwxFFI.wxDirDialog_GetPath(obj.ptr)
end

function (obj::wxDirDialog)
    return Int(KwxFFI.wxDirDialog_GetStyle(obj.ptr))
end

function (obj::wxDirDialog, paths::Integer)
    return Int(KwxFFI.wxDirDialog_GetPaths(obj.ptr, Cint(paths)))
end

function (obj::wxDirDialog, msg::String)
    msg_ws = wxString(msg)
    KwxFFI.wxDirDialog_SetMessage(obj.ptr, msg_ws.ptr)
    delete!(msg_ws)
    nothing
end

function (obj::wxDirDialog, pth::String)
    pth_ws = wxString(pth)
    KwxFFI.wxDirDialog_SetPath(obj.ptr, pth_ws.ptr)
    delete!(pth_ws)
    nothing
end

function (obj::wxDirDialog, style::Integer)
    KwxFFI.wxDirDialog_SetStyle(obj.ptr, Cint(style))
    nothing
end

