# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDialUpEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxDialUpEvent)
    return KwxFFI.wxDialUpEvent_IsConnectedEvent(obj.ptr) != 0
end

function (obj::wxDialUpEvent)
    return KwxFFI.wxDialUpEvent_IsOwnEvent(obj.ptr) != 0
end

