# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDllLoader <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxDllLoader, name::Ptr{Cvoid}, success::Ptr{Cvoid})
    return Int(KwxFFI.wxDllLoader_LoadLibrary(obj.ptr, name, success))
end

function (obj::wxDllLoader, handle::Integer)
    KwxFFI.wxDllLoader_UnloadLibrary(obj.ptr, Cint(handle))
    nothing
end

