# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDocChildFrame <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxDocChildFrame(doc::Ptr{Cvoid}, view::Ptr{Cvoid}, parent::Union{wxWindow, Nothing}, id::Integer, title::String, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    title_ws = wxString(title)
    ptr = KwxFFI.wxDocChildFrame_Create(doc, view, parent_ptr, Cint(id), title_ws.ptr, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    delete!(title_ws)
    ptr == C_NULL && error("Failed to create wxDocChildFrame")
    obj = wxDocChildFrame(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxDocChildFrame)
    return KwxFFI.wxDocChildFrame_GetDocument(obj.ptr)
end

function (obj::wxDocChildFrame)
    return KwxFFI.wxDocChildFrame_GetView(obj.ptr)
end

function (obj::wxDocChildFrame, doc::Ptr{Cvoid})
    KwxFFI.wxDocChildFrame_SetDocument(obj.ptr, doc)
    nothing
end

function (obj::wxDocChildFrame, view::Ptr{Cvoid})
    KwxFFI.wxDocChildFrame_SetView(obj.ptr, view)
    nothing
end

