# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDropTarget <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxDropTarget)
    KwxFFI.wxDropTarget_GetData(obj.ptr)
    nothing
end

function (obj::wxDropTarget, dataObject::Ptr{Cvoid})
    KwxFFI.wxDropTarget_SetDataObject(obj.ptr, dataObject)
    nothing
end

