# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDropSource <: wxObject
    ptr::Ptr{Cvoid}
end

function wxDropSource(data::Ptr{Cvoid}, win::Ptr{Cvoid}, copy::Ptr{Cvoid}, move::Ptr{Cvoid}, none::Ptr{Cvoid})
    ptr = KwxFFI.DropSource_Create(data, win, copy, move, none)
    ptr == C_NULL && error("Failed to create wxDropSource")
    obj = wxDropSource(ptr)
    return obj
end

function delete!(obj::wxDropSource)
    KwxFFI.DropSource_Delete(obj.ptr)
    nothing
end

function (obj::wxDropSource, move::Integer)
    return Int(KwxFFI.DropSource_DoDragDrop(obj.ptr, Cint(move)))
end

