# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDynToolInfo <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxDynToolInfo)
    return Int(KwxFFI.wxDynToolInfo_Index(obj.ptr))
end

function (obj::wxDynToolInfo, arg::Integer)
    KwxFFI.wxDynToolInfo_RealSize(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxDynToolInfo)
    return KwxFFI.wxDynToolInfo_pToolWnd(obj.ptr)
end

