# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxDynamicToolBar <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxDynamicToolBar(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer, orientation::Integer, RowsOrColumns::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxDynamicToolBar_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style), Cint(orientation), Cint(RowsOrColumns))
    ptr == C_NULL && error("Failed to create wxDynamicToolBar")
    obj = wxDynamicToolBar(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function wxDynamicToolBar()
    ptr = KwxFFI.wxDynamicToolBar_CreateDefault()
    ptr == C_NULL && error("Failed to create wxDynamicToolBar")
    obj = wxDynamicToolBar(ptr, Any[], Any[])
    return obj
end

function (obj::wxDynamicToolBar, pSepartorWnd::Ptr{Cvoid})
    KwxFFI.wxDynamicToolBar_AddSeparator(obj.ptr, pSepartorWnd)
    nothing
end

function (obj::wxDynamicToolBar, toolIndex::Integer, pToolWindow::Ptr{Cvoid}, width::Integer, height::Integer)
    KwxFFI.wxDynamicToolBar_AddTool(obj.ptr, Cint(toolIndex), pToolWindow, Cint(width), Cint(height))
    nothing
end

function (obj::wxDynamicToolBar, toolIndex::Integer, bitmap::Ptr{Cvoid}, pushedBitmap::Ptr{Cvoid}, toggle::Integer, x::Integer, y::Integer, clientData::Ptr{Cvoid}, helpString1::Ptr{Cvoid}, helpString2::Ptr{Cvoid})
    return KwxFFI.wxDynamicToolBar_AddToolBitmap(obj.ptr, Cint(toolIndex), bitmap, pushedBitmap, Cint(toggle), Cint(x), Cint(y), clientData, helpString1, helpString2)
end

function (obj::wxDynamicToolBar, toolIndex::Integer, imageFileName::Ptr{Cvoid}, imageFileType::Integer, labelText::Ptr{Cvoid}, alignTextRight::Integer, isFlat::Bool)
    KwxFFI.wxDynamicToolBar_AddToolImage(obj.ptr, Cint(toolIndex), imageFileName, Cint(imageFileType), labelText, Cint(alignTextRight), Cint(isFlat))
    nothing
end

function (obj::wxDynamicToolBar, toolIndex::Integer, labelBmp::Ptr{Cvoid}, labelText::Ptr{Cvoid}, alignTextRight::Integer, isFlat::Bool)
    KwxFFI.wxDynamicToolBar_AddToolLabel(obj.ptr, Cint(toolIndex), labelBmp, labelText, Cint(alignTextRight), Cint(isFlat))
    nothing
end

function (obj::wxDynamicToolBar)
    return KwxFFI.wxDynamicToolBar_CreateDefaultLayout(obj.ptr)
end

function (obj::wxDynamicToolBar, parent::Ptr{Cvoid}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer, orientation::Integer, RowsOrColumns::Integer)
    return Int(KwxFFI.wxDynamicToolBar_CreateParams(obj.ptr, parent, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style), Cint(orientation), Cint(RowsOrColumns)))
end

function (obj::wxDynamicToolBar, id::Integer, label::Ptr{Cvoid}, bmpNormal::Ptr{Cvoid}, bmpDisabled::Ptr{Cvoid}, kind::Integer, clientData::Ptr{Cvoid}, shortHelp::Ptr{Cvoid}, longHelp::Ptr{Cvoid})
    return KwxFFI.wxDynamicToolBar_CreateTool(obj.ptr, Cint(id), label, bmpNormal, bmpDisabled, Cint(kind), clientData, shortHelp, longHelp)
end

function (obj::wxDynamicToolBar, control::Ptr{Cvoid})
    return KwxFFI.wxDynamicToolBar_CreateToolControl(obj.ptr, control)
end

function delete!(obj::wxDynamicToolBar)
    KwxFFI.wxDynamicToolBar_Delete(obj.ptr)
    nothing
end

function (obj::wxDynamicToolBar, pos::Integer, tool::Ptr{Cvoid})
    return Int(KwxFFI.wxDynamicToolBar_DoDeleteTool(obj.ptr, Cint(pos), tool))
end

function (obj::wxDynamicToolBar, tool::Ptr{Cvoid}, enable::Bool)
    KwxFFI.wxDynamicToolBar_DoEnableTool(obj.ptr, tool, Cint(enable))
    nothing
end

function (obj::wxDynamicToolBar, pos::Integer, tool::Ptr{Cvoid})
    return Int(KwxFFI.wxDynamicToolBar_DoInsertTool(obj.ptr, Cint(pos), tool))
end

function (obj::wxDynamicToolBar, tool::Ptr{Cvoid}, toggle::Integer)
    KwxFFI.wxDynamicToolBar_DoSetToggle(obj.ptr, tool, Cint(toggle))
    nothing
end

function (obj::wxDynamicToolBar, tool::Ptr{Cvoid}, toggle::Integer)
    KwxFFI.wxDynamicToolBar_DoToggleTool(obj.ptr, tool, Cint(toggle))
    nothing
end

function (obj::wxDynamicToolBar, info::Ptr{Cvoid}, dc::Ptr{Cvoid})
    KwxFFI.wxDynamicToolBar_DrawSeparator(obj.ptr, info, dc)
    nothing
end

function (obj::wxDynamicToolBar, toolIndex::Integer, enable::Bool)
    KwxFFI.wxDynamicToolBar_EnableTool(obj.ptr, Cint(toolIndex), Cint(enable))
    nothing
end

function (obj::wxDynamicToolBar, x::Integer, y::Integer)
    return KwxFFI.wxDynamicToolBar_FindToolForPosition(obj.ptr, Cint(x), Cint(y))
end

function (obj::wxDynamicToolBar, givenWidth::Integer, givenHeight::Integer, preferredWidth::Ptr{Cvoid}, preferredHeight::Ptr{Cvoid})
    KwxFFI.wxDynamicToolBar_GetPreferredDim(obj.ptr, Cint(givenWidth), Cint(givenHeight), preferredWidth, preferredHeight)
    nothing
end

function (obj::wxDynamicToolBar, toolIndex::Integer)
    return KwxFFI.wxDynamicToolBar_GetToolInfo(obj.ptr, Cint(toolIndex))
end

function (obj::wxDynamicToolBar)
    return Int(KwxFFI.wxDynamicToolBar_Layout(obj.ptr))
end

function (obj::wxDynamicToolBar, toolIndex::Integer)
    KwxFFI.wxDynamicToolBar_RemoveTool(obj.ptr, Cint(toolIndex))
    nothing
end

function (obj::wxDynamicToolBar, pLayout::Ptr{Cvoid})
    KwxFFI.wxDynamicToolBar_SetLayout(obj.ptr, pLayout)
    nothing
end

