# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxEditableListBox <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxEditableListBox(parent::Union{wxWindow, Nothing}, id::Integer, label::Ptr{Cvoid}, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxEditableListBox_Create(parent_ptr, Cint(id), label, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxEditableListBox")
    obj = wxEditableListBox(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxEditableListBox)
    return KwxFFI.wxEditableListBox_GetDelButton(obj.ptr)
end

function (obj::wxEditableListBox)
    return KwxFFI.wxEditableListBox_GetDownButton(obj.ptr)
end

function (obj::wxEditableListBox)
    return KwxFFI.wxEditableListBox_GetEditButton(obj.ptr)
end

function (obj::wxEditableListBox)
    return KwxFFI.wxEditableListBox_GetListCtrl(obj.ptr)
end

function (obj::wxEditableListBox)
    return KwxFFI.wxEditableListBox_GetNewButton(obj.ptr)
end

function (obj::wxEditableListBox, ref::Integer)
    return Int(KwxFFI.wxEditableListBox_GetStrings(obj.ptr, Cint(ref)))
end

function (obj::wxEditableListBox)
    return KwxFFI.wxEditableListBox_GetUpButton(obj.ptr)
end

function (obj::wxEditableListBox, strings::Ptr{Cvoid}, count::Integer)
    KwxFFI.wxEditableListBox_SetStrings(obj.ptr, strings, Cint(count))
    nothing
end

