# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxEraseEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxEraseEvent, arg::Ptr{Cvoid})
    KwxFFI.wxEraseEvent_CopyObject(obj.ptr, arg)
    nothing
end

function (obj::wxEraseEvent)
    return KwxFFI.wxEraseEvent_GetDC(obj.ptr)
end

