# Code generated by kwxgen. DO NOT EDIT.

function (obj::wxEvtHandler, event::Ptr{Cvoid})
    KwxFFI.wxEvtHandler_AddPendingEvent(obj.ptr, event)
    nothing
end

function (obj::wxEvtHandler, first::Integer, last::Integer, type_::Integer, data::Ptr{Cvoid})
    return Int(KwxFFI.wxEvtHandler_Connect(obj.ptr, Cint(first), Cint(last), Cint(type_), data))
end

function delete!(obj::wxEvtHandler)
    KwxFFI.wxEvtHandler_Delete(obj.ptr)
    nothing
end

function (obj::wxEvtHandler, first::Integer, last::Integer, type_::Integer, id::Integer)
    return Int(KwxFFI.wxEvtHandler_Disconnect(obj.ptr, Cint(first), Cint(last), Cint(type_), Cint(id)))
end

function (obj::wxEvtHandler)
    return KwxFFI.wxEvtHandler_GetEvtHandlerEnabled(obj.ptr) != 0
end

function (obj::wxEvtHandler)
    return KwxFFI.wxEvtHandler_GetNextHandler(obj.ptr)
end

function (obj::wxEvtHandler)
    return KwxFFI.wxEvtHandler_GetPreviousHandler(obj.ptr)
end

function (obj::wxEvtHandler, event::Ptr{Cvoid})
    return KwxFFI.wxEvtHandler_ProcessEvent(obj.ptr, event) != 0
end

function (obj::wxEvtHandler)
    KwxFFI.wxEvtHandler_ProcessPendingEvents(obj.ptr)
    nothing
end

function (obj::wxEvtHandler, enabled::Bool)
    KwxFFI.wxEvtHandler_SetEvtHandlerEnabled(obj.ptr, Cint(enabled))
    nothing
end

function (obj::wxEvtHandler, handler::Ptr{Cvoid})
    KwxFFI.wxEvtHandler_SetNextHandler(obj.ptr, handler)
    nothing
end

function (obj::wxEvtHandler, handler::Ptr{Cvoid})
    KwxFFI.wxEvtHandler_SetPreviousHandler(obj.ptr, handler)
    nothing
end

