# Code generated by kwxgen. DO NOT EDIT.

function (obj::wxEvent, object_dest::Ptr{Cvoid})
    KwxFFI.wxEvent_CopyObject(obj.ptr, object_dest)
    nothing
end

function (obj::wxEvent)
    return KwxFFI.wxEvent_GetEventObject(obj.ptr)
end

function (obj::wxEvent)
    return Int(KwxFFI.wxEvent_GetEventType(obj.ptr))
end

function (obj::wxEvent)
    return Int(KwxFFI.wxEvent_GetId(obj.ptr))
end

function (obj::wxEvent)
    return KwxFFI.wxEvent_GetSkipped(obj.ptr) != 0
end

function (obj::wxEvent)
    return Int(KwxFFI.wxEvent_GetTimestamp(obj.ptr))
end

function (obj::wxEvent)
    return KwxFFI.wxEvent_IsCommandEvent(obj.ptr) != 0
end

function (obj::wxEvent)
    return Int(KwxFFI.wxEvent_NewEventType(obj.ptr))
end

function (obj::wxEvent, arg_ptr::Ptr{Cvoid})
    KwxFFI.wxEvent_SetEventObject(obj.ptr, arg_ptr)
    nothing
end

function (obj::wxEvent, typ::Integer)
    KwxFFI.wxEvent_SetEventType(obj.ptr, Cint(typ))
    nothing
end

function (obj::wxEvent, Id::Integer)
    KwxFFI.wxEvent_SetId(obj.ptr, Cint(Id))
    nothing
end

function (obj::wxEvent, timestamp::Integer)
    KwxFFI.wxEvent_SetTimestamp(obj.ptr, Cint(timestamp))
    nothing
end

function (obj::wxEvent, skip::Bool)
    KwxFFI.wxEvent_Skip(obj.ptr, Cint(skip))
    nothing
end

