# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxFileHistory <: wxObject
    ptr::Ptr{Cvoid}
end

function wxFileHistory(maxFiles::Integer)
    ptr = KwxFFI.wxFileHistory_Create(Cint(maxFiles))
    ptr == C_NULL && error("Failed to create wxFileHistory")
    obj = wxFileHistory(ptr)
    return obj
end

function (obj::wxFileHistory, file::String)
    file_ws = wxString(file)
    KwxFFI.wxFileHistory_AddFileToHistory(obj.ptr, file_ws.ptr)
    delete!(file_ws)
    nothing
end

function (obj::wxFileHistory, menu::Ptr{Cvoid})
    KwxFFI.wxFileHistory_AddFilesToMenu(obj.ptr, menu)
    nothing
end

function delete!(obj::wxFileHistory)
    KwxFFI.wxFileHistory_Delete(obj.ptr)
    nothing
end

function (obj::wxFileHistory)
    return Int(KwxFFI.wxFileHistory_GetCount(obj.ptr))
end

function (obj::wxFileHistory, index::Integer)
    return KwxFFI.wxFileHistory_GetHistoryFile(obj.ptr, Cint(index))
end

function (obj::wxFileHistory)
    return Int(KwxFFI.wxFileHistory_GetMaxFiles(obj.ptr))
end

function (obj::wxFileHistory, ref::Ptr{Cvoid})
    return Int(KwxFFI.wxFileHistory_GetMenus(obj.ptr, ref))
end

function (obj::wxFileHistory, config::Ptr{Cvoid})
    KwxFFI.wxFileHistory_Load(obj.ptr, config)
    nothing
end

function (obj::wxFileHistory, index::Integer)
    KwxFFI.wxFileHistory_RemoveFileFromHistory(obj.ptr, Cint(index))
    nothing
end

function (obj::wxFileHistory, menu::Ptr{Cvoid})
    KwxFFI.wxFileHistory_RemoveMenu(obj.ptr, menu)
    nothing
end

function (obj::wxFileHistory, config::Ptr{Cvoid})
    KwxFFI.wxFileHistory_Save(obj.ptr, config)
    nothing
end

function (obj::wxFileHistory, menu::Ptr{Cvoid})
    KwxFFI.wxFileHistory_UseMenu(obj.ptr, menu)
    nothing
end

