# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxFileDataObject <: wxObject
    ptr::Ptr{Cvoid}
end

function wxFileDataObject(count::Integer, list::Ptr{Cvoid})
    ptr = KwxFFI.FileDataObject_Create(Cint(count), list)
    ptr == C_NULL && error("Failed to create wxFileDataObject")
    obj = wxFileDataObject(ptr)
    return obj
end

function (obj::wxFileDataObject, files::String)
    files_ws = wxString(files)
    KwxFFI.FileDataObject_AddFile(obj.ptr, files_ws.ptr)
    delete!(files_ws)
    nothing
end

function delete!(obj::wxFileDataObject)
    KwxFFI.FileDataObject_Delete(obj.ptr)
    nothing
end

function (obj::wxFileDataObject, list::Integer)
    return Int(KwxFFI.FileDataObject_GetFilenames(obj.ptr, Cint(list)))
end

