# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxFindDialogEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxFindDialogEvent, ref::Ptr{Cvoid})
    return Int(KwxFFI.wxFindDialogEvent_GetFindString(obj.ptr, ref))
end

function (obj::wxFindDialogEvent)
    return Int(KwxFFI.wxFindDialogEvent_GetFlags(obj.ptr))
end

function (obj::wxFindDialogEvent, ref::Ptr{Cvoid})
    return Int(KwxFFI.wxFindDialogEvent_GetReplaceString(obj.ptr, ref))
end

