# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxFileType <: wxObject
    ptr::Ptr{Cvoid}
end

function delete!(obj::wxFileType)
    KwxFFI.wxFileType_Delete(obj.ptr)
    nothing
end

function (obj::wxFileType, command::Ptr{Cvoid}, params::Ptr{Cvoid})
    return KwxFFI.wxFileType_ExpandCommand(obj.ptr, command, params)
end

function (obj::wxFileType)
    return KwxFFI.wxFileType_GetDescription(obj.ptr)
end

function (obj::wxFileType, list::Ptr{Cvoid})
    return Int(KwxFFI.wxFileType_GetExtensions(obj.ptr, list))
end

function (obj::wxFileType, icon::Ptr{Cvoid})
    return Int(KwxFFI.wxFileType_GetIcon(obj.ptr, icon))
end

function (obj::wxFileType)
    return KwxFFI.wxFileType_GetMimeType(obj.ptr)
end

function (obj::wxFileType, list::Ptr{Cvoid})
    return Int(KwxFFI.wxFileType_GetMimeTypes(obj.ptr, list))
end

function (obj::wxFileType, buffer::Ptr{Cvoid}, params::Ptr{Cvoid})
    return Int(KwxFFI.wxFileType_GetOpenCommand(obj.ptr, buffer, params))
end

function (obj::wxFileType, buffer::Ptr{Cvoid}, params::Ptr{Cvoid})
    return Int(KwxFFI.wxFileType_GetPrintCommand(obj.ptr, buffer, params))
end

