# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxFlexGridSizer <: wxSizer
    ptr::Ptr{Cvoid}
end

function wxFlexGridSizer(rows::Integer, cols::Integer, vgap::Integer, hgap::Integer)
    ptr = KwxFFI.wxFlexGridSizer_Create(Cint(rows), Cint(cols), Cint(vgap), Cint(hgap))
    ptr == C_NULL && error("Failed to create wxFlexGridSizer")
    obj = wxFlexGridSizer(ptr)
    return obj
end

function (obj::wxFlexGridSizer, idx::Integer, proportion::Integer)
    KwxFFI.wxFlexGridSizer_AddGrowableCol(obj.ptr, Csize_t(idx), Cint(proportion))
    nothing
end

function (obj::wxFlexGridSizer, idx::Integer, proportion::Integer)
    KwxFFI.wxFlexGridSizer_AddGrowableRow(obj.ptr, Csize_t(idx), Cint(proportion))
    nothing
end

function (obj::wxFlexGridSizer)
    return KwxFFI.wxFlexGridSizer_CalcMin(obj.ptr)
end

function (obj::wxFlexGridSizer)
    KwxFFI.wxFlexGridSizer_RecalcSizes(obj.ptr)
    nothing
end

function (obj::wxFlexGridSizer, idx::Integer)
    KwxFFI.wxFlexGridSizer_RemoveGrowableCol(obj.ptr, Csize_t(idx))
    nothing
end

function (obj::wxFlexGridSizer, idx::Integer)
    KwxFFI.wxFlexGridSizer_RemoveGrowableRow(obj.ptr, Csize_t(idx))
    nothing
end

