# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxFontDialog <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxFontDialog(parent::Union{wxWindow, Nothing}, fnt::Ptr{Cvoid})
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxFontDialog_Create(parent_ptr, fnt)
    ptr == C_NULL && error("Failed to create wxFontDialog")
    obj = wxFontDialog(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxFontDialog, ref::Ptr{Cvoid})
    KwxFFI.wxFontDialog_GetFontData(obj.ptr, ref)
    nothing
end

