# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxFont <: wxObject
    ptr::Ptr{Cvoid}
end

function wxFont(pointSize::Integer, family::Integer, style::Integer, weight::Integer, underlined::Bool, face::String, enc::Integer)
    face_ws = wxString(face)
    ptr = KwxFFI.wxFont_Create(Cint(pointSize), Cint(family), Cint(style), Cint(weight), Cint(underlined), face_ws.ptr, Cint(enc))
    delete!(face_ws)
    ptr == C_NULL && error("Failed to create wxFont")
    obj = wxFont(ptr)
    return obj
end

function wxFont(id::Integer)
    ptr = KwxFFI.wxFont_CreateFromStock(Cint(id))
    ptr == C_NULL && error("Failed to create wxFont")
    obj = wxFont(ptr)
    return obj
end

function wxFont()
    ptr = KwxFFI.wxFont_CreateDefault()
    ptr == C_NULL && error("Failed to create wxFont")
    obj = wxFont(ptr)
    return obj
end

function delete!(obj::wxFont)
    KwxFFI.wxFont_Delete(obj.ptr)
    nothing
end

function (obj::wxFont)
    return Int(KwxFFI.wxFont_GetDefaultEncoding(obj.ptr))
end

function (obj::wxFont)
    return Int(KwxFFI.wxFont_GetEncoding(obj.ptr))
end

function (obj::wxFont)
    return KwxFFI.wxFont_GetFaceName(obj.ptr)
end

function (obj::wxFont)
    return Int(KwxFFI.wxFont_GetFamily(obj.ptr))
end

function (obj::wxFont)
    return KwxFFI.wxFont_GetFamilyString(obj.ptr)
end

function (obj::wxFont)
    return Int(KwxFFI.wxFont_GetPointSize(obj.ptr))
end

function (obj::wxFont)
    return Int(KwxFFI.wxFont_GetStyle(obj.ptr))
end

function (obj::wxFont)
    return KwxFFI.wxFont_GetStyleString(obj.ptr)
end

function (obj::wxFont)
    return Int(KwxFFI.wxFont_GetUnderlined(obj.ptr))
end

function (obj::wxFont)
    return Int(KwxFFI.wxFont_GetWeight(obj.ptr))
end

function (obj::wxFont)
    return KwxFFI.wxFont_GetWeightString(obj.ptr)
end

function (obj::wxFont)
    return KwxFFI.wxFont_IsOk(obj.ptr) != 0
end

function (obj::wxFont, encoding::Integer)
    KwxFFI.wxFont_SetDefaultEncoding(obj.ptr, Cint(encoding))
    nothing
end

function (obj::wxFont, encoding::Integer)
    KwxFFI.wxFont_SetEncoding(obj.ptr, Cint(encoding))
    nothing
end

function (obj::wxFont, faceName::String)
    faceName_ws = wxString(faceName)
    KwxFFI.wxFont_SetFaceName(obj.ptr, faceName_ws.ptr)
    delete!(faceName_ws)
    nothing
end

function (obj::wxFont, family::Integer)
    KwxFFI.wxFont_SetFamily(obj.ptr, Cint(family))
    nothing
end

function (obj::wxFont, pointSize::Integer)
    KwxFFI.wxFont_SetPointSize(obj.ptr, Cint(pointSize))
    nothing
end

function (obj::wxFont, style::Integer)
    KwxFFI.wxFont_SetStyle(obj.ptr, Cint(style))
    nothing
end

function (obj::wxFont, underlined::Integer)
    KwxFFI.wxFont_SetUnderlined(obj.ptr, Cint(underlined))
    nothing
end

function (obj::wxFont, weight::Integer)
    KwxFFI.wxFont_SetWeight(obj.ptr, Cint(weight))
    nothing
end

