# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxFrame <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxFrame(parent::Union{wxWindow, Nothing}, id::Integer, text::String, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    text_ws = wxString(text)
    ptr = KwxFFI.wxFrame_Create(parent_ptr, Cint(id), text_ws.ptr, Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxFrame")
    obj = wxFrame(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxFrame, number::Integer, style::Integer)
    return KwxFFI.wxFrame_CreateStatusBar(obj.ptr, Cint(number), Cint(style))
end

function (obj::wxFrame, style::Integer)
    return KwxFFI.wxFrame_CreateToolBar(obj.ptr, Clong(style))
end

function (obj::wxFrame)
    return Int(KwxFFI.wxFrame_GetClientAreaOrigin_left(obj.ptr))
end

function (obj::wxFrame)
    return Int(KwxFFI.wxFrame_GetClientAreaOrigin_top(obj.ptr))
end

function (obj::wxFrame)
    return KwxFFI.wxFrame_GetMenuBar(obj.ptr)
end

function (obj::wxFrame)
    return KwxFFI.wxFrame_GetStatusBar(obj.ptr)
end

function (obj::wxFrame)
    return KwxFFI.wxFrame_GetToolBar(obj.ptr)
end

function (obj::wxFrame)
    KwxFFI.wxFrame_Restore(obj.ptr)
    nothing
end

function (obj::wxFrame, menubar::Ptr{Cvoid})
    KwxFFI.wxFrame_SetMenuBar(obj.ptr, menubar)
    nothing
end

function (obj::wxFrame, statBar::Ptr{Cvoid})
    KwxFFI.wxFrame_SetStatusBar(obj.ptr, statBar)
    nothing
end

function (obj::wxFrame, text::String, number::Integer)
    text_ws = wxString(text)
    KwxFFI.wxFrame_SetStatusText(obj.ptr, text_ws.ptr, Cint(number))
    delete!(text_ws)
    nothing
end

function (obj::wxFrame, count::Integer, widths::Ptr{Cvoid})
    KwxFFI.wxFrame_SetStatusWidths(obj.ptr, Cint(count), widths)
    nothing
end

function (obj::wxFrame, toolbar::Ptr{Cvoid})
    KwxFFI.wxFrame_SetToolBar(obj.ptr, toolbar)
    nothing
end

function (obj::wxFrame, menuId::Integer)
    return KwxFFI.wxFrame_FindItemInMenuBar(obj.ptr, Cint(menuId))
end

function (obj::wxFrame, id::Integer)
    KwxFFI.wxFrame_ProcessCommand(obj.ptr, Cint(id))
    nothing
end

function (obj::wxFrame, n::Integer)
    KwxFFI.wxFrame_SetStatusBarPane(obj.ptr, Cint(n))
    nothing
end

function (obj::wxFrame)
    return Int(KwxFFI.wxFrame_GetStatusBarPane(obj.ptr))
end

function (obj::wxFrame, text::String, field::Integer)
    text_ws = wxString(text)
    KwxFFI.wxFrame_PushStatusText(obj.ptr, text_ws.ptr, Cint(field))
    delete!(text_ws)
    nothing
end

function (obj::wxFrame, field::Integer)
    KwxFFI.wxFrame_PopStatusText(obj.ptr, Cint(field))
    nothing
end

