# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxFrameLayout <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function wxFrameLayout(pParentFrame::Ptr{Cvoid}, pFrameClient::Ptr{Cvoid}, activateNow::Integer)
    ptr = KwxFFI.wxFrameLayout_Create(pParentFrame, pFrameClient, Cint(activateNow))
    ptr == C_NULL && error("Failed to create wxFrameLayout")
    obj = wxFrameLayout(ptr)
    return obj
end

function (obj::wxFrameLayout)
    KwxFFI.wxFrameLayout_Activate(obj.ptr)
    nothing
end

function (obj::wxFrameLayout, pBarWnd::Ptr{Cvoid}, dimInfo::Ptr{Cvoid}, alignment::Integer, rowNo::Integer, columnPos::Integer, name::Ptr{Cvoid}, spyEvents::Integer, state::Integer)
    KwxFFI.wxFrameLayout_AddBar(obj.ptr, pBarWnd, dimInfo, Cint(alignment), Cint(rowNo), Cint(columnPos), name, Cint(spyEvents), Cint(state))
    nothing
end

function (obj::wxFrameLayout, pPlInfo::Ptr{Cvoid}, paneMask::Integer)
    KwxFFI.wxFrameLayout_AddPlugin(obj.ptr, pPlInfo, Cint(paneMask))
    nothing
end

function (obj::wxFrameLayout, pNextPlInfo::Ptr{Cvoid}, pPlInfo::Ptr{Cvoid}, paneMask::Integer)
    KwxFFI.wxFrameLayout_AddPluginBefore(obj.ptr, pNextPlInfo, pPlInfo, Cint(paneMask))
    nothing
end

function (obj::wxFrameLayout, pBar::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_ApplyBarProperties(obj.ptr, pBar)
    nothing
end

function (obj::wxFrameLayout, toPane::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_CaptureEventsForPane(obj.ptr, toPane)
    nothing
end

function (obj::wxFrameLayout, pPlugin::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_CaptureEventsForPlugin(obj.ptr, pPlugin)
    nothing
end

function (obj::wxFrameLayout)
    KwxFFI.wxFrameLayout_Deactivate(obj.ptr)
    nothing
end

function delete!(obj::wxFrameLayout)
    KwxFFI.wxFrameLayout_Delete(obj.ptr)
    nothing
end

function (obj::wxFrameLayout)
    KwxFFI.wxFrameLayout_DestroyBarWindows(obj.ptr)
    nothing
end

function (obj::wxFrameLayout, enable::Bool)
    KwxFFI.wxFrameLayout_EnableFloating(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxFrameLayout, name::Ptr{Cvoid})
    return KwxFFI.wxFrameLayout_FindBarByName(obj.ptr, name)
end

function (obj::wxFrameLayout, pWnd::Ptr{Cvoid})
    return KwxFFI.wxFrameLayout_FindBarByWindow(obj.ptr, pWnd)
end

function (obj::wxFrameLayout, pPlInfo::Ptr{Cvoid})
    return KwxFFI.wxFrameLayout_FindPlugin(obj.ptr, pPlInfo)
end

function (obj::wxFrameLayout, event::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_FirePluginEvent(obj.ptr, event)
    nothing
end

function (obj::wxFrameLayout, ref::Ptr{Cvoid})
    return Int(KwxFFI.wxFrameLayout_GetBars(obj.ptr, ref))
end

function (obj::wxFrameLayout)
    return Int(KwxFFI.wxFrameLayout_GetClientHeight(obj.ptr))
end

function (obj::wxFrameLayout, arg::Integer)
    KwxFFI.wxFrameLayout_GetClientRect(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxFrameLayout)
    return Int(KwxFFI.wxFrameLayout_GetClientWidth(obj.ptr))
end

function (obj::wxFrameLayout)
    return KwxFFI.wxFrameLayout_GetFrameClient(obj.ptr)
end

function (obj::wxFrameLayout, alignment::Integer)
    return KwxFFI.wxFrameLayout_GetPane(obj.ptr, Cint(alignment))
end

function (obj::wxFrameLayout, props::Ptr{Cvoid}, alignment::Integer)
    KwxFFI.wxFrameLayout_GetPaneProperties(obj.ptr, props, Cint(alignment))
    nothing
end

function (obj::wxFrameLayout)
    return KwxFFI.wxFrameLayout_GetParentFrame(obj.ptr)
end

function (obj::wxFrameLayout)
    return KwxFFI.wxFrameLayout_GetTopPlugin(obj.ptr)
end

function (obj::wxFrameLayout)
    return KwxFFI.wxFrameLayout_GetUpdatesManager(obj.ptr)
end

function (obj::wxFrameLayout)
    return KwxFFI.wxFrameLayout_HasTopPlugin(obj.ptr) != 0
end

function (obj::wxFrameLayout)
    KwxFFI.wxFrameLayout_HideBarWindows(obj.ptr)
    nothing
end

function (obj::wxFrameLayout, pBar::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_InverseVisibility(obj.ptr, pBar)
    nothing
end

function (obj::wxFrameLayout, event::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_OnLButtonDown(obj.ptr, event)
    nothing
end

function (obj::wxFrameLayout, event::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_OnLButtonUp(obj.ptr, event)
    nothing
end

function (obj::wxFrameLayout, event::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_OnLDblClick(obj.ptr, event)
    nothing
end

function (obj::wxFrameLayout, event::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_OnMouseMove(obj.ptr, event)
    nothing
end

function (obj::wxFrameLayout, event::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_OnRButtonDown(obj.ptr, event)
    nothing
end

function (obj::wxFrameLayout, event::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_OnRButtonUp(obj.ptr, event)
    nothing
end

function (obj::wxFrameLayout, event::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_OnSize(obj.ptr, event)
    nothing
end

function (obj::wxFrameLayout)
    KwxFFI.wxFrameLayout_PopAllPlugins(obj.ptr)
    nothing
end

function (obj::wxFrameLayout)
    KwxFFI.wxFrameLayout_PopPlugin(obj.ptr)
    nothing
end

function (obj::wxFrameLayout)
    KwxFFI.wxFrameLayout_PushDefaultPlugins(obj.ptr)
    nothing
end

function (obj::wxFrameLayout, pPugin::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_PushPlugin(obj.ptr, pPugin)
    nothing
end

function (obj::wxFrameLayout, repositionBarsNow::Integer)
    KwxFFI.wxFrameLayout_RecalcLayout(obj.ptr, Cint(repositionBarsNow))
    nothing
end

function (obj::wxFrameLayout, pBar::Ptr{Cvoid}, x::Integer, y::Integer, width::Integer, height::Integer, pToPane::Ptr{Cvoid}, updateNow::Integer)
    return Int(KwxFFI.wxFrameLayout_RedockBar(obj.ptr, pBar, Cint(x), Cint(y), Cint(width), Cint(height), pToPane, Cint(updateNow)))
end

function (obj::wxFrameLayout, recalcLayout::Integer)
    KwxFFI.wxFrameLayout_RefreshNow(obj.ptr, Cint(recalcLayout))
    nothing
end

function (obj::wxFrameLayout, fromPane::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_ReleaseEventsFromPane(obj.ptr, fromPane)
    nothing
end

function (obj::wxFrameLayout, pPlugin::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_ReleaseEventsFromPlugin(obj.ptr, pPlugin)
    nothing
end

function (obj::wxFrameLayout, pBar::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_RemoveBar(obj.ptr, pBar)
    nothing
end

function (obj::wxFrameLayout, pPlInfo::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_RemovePlugin(obj.ptr, pPlInfo)
    nothing
end

function (obj::wxFrameLayout, pBar::Ptr{Cvoid}, newStatem::Integer, updateNow::Integer)
    KwxFFI.wxFrameLayout_SetBarState(obj.ptr, pBar, Cint(newStatem), Cint(updateNow))
    nothing
end

function (obj::wxFrameLayout, pFrameClient::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_SetFrameClient(obj.ptr, pFrameClient)
    nothing
end

function (obj::wxFrameLayout, top::Integer, bottom::Integer, left::Integer, right::Integer, paneMask::Integer)
    KwxFFI.wxFrameLayout_SetMargins(obj.ptr, Cint(top), Cint(bottom), Cint(left), Cint(right), Cint(paneMask))
    nothing
end

function (obj::wxFrameLayout, colour::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_SetPaneBackground(obj.ptr, colour)
    nothing
end

function (obj::wxFrameLayout, props::Ptr{Cvoid}, paneMask::Integer)
    KwxFFI.wxFrameLayout_SetPaneProperties(obj.ptr, props, Cint(paneMask))
    nothing
end

function (obj::wxFrameLayout, pPlugin::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_SetTopPlugin(obj.ptr, pPlugin)
    nothing
end

function (obj::wxFrameLayout, pUMgr::Ptr{Cvoid})
    KwxFFI.wxFrameLayout_SetUpdatesManager(obj.ptr, pUMgr)
    nothing
end

