# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGauge <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxGauge(parent::Union{wxWindow, Nothing}, id::Integer, range::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxGauge_Create(parent_ptr, Cint(id), Cint(range), Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxGauge")
    obj = wxGauge(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxGauge)
    return Int(KwxFFI.wxGauge_GetRange(obj.ptr))
end

function (obj::wxGauge)
    return Int(KwxFFI.wxGauge_GetValue(obj.ptr))
end

function (obj::wxGauge, range::Integer)
    KwxFFI.wxGauge_SetRange(obj.ptr, Cint(range))
    nothing
end

function (obj::wxGauge, pos::Integer)
    KwxFFI.wxGauge_SetValue(obj.ptr, Cint(pos))
    nothing
end

function (obj::wxGauge)
    KwxFFI.wxGauge_Pulse(obj.ptr)
    nothing
end

function (obj::wxGauge)
    return KwxFFI.wxGauge_IsVertical(obj.ptr) != 0
end

