# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGridCellBoolEditor <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxGridCellBoolEditor)
    return KwxFFI.wxGridCellBoolEditor_Ctor(obj.ptr)
end

