# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGridBagSizer <: wxSizer
    ptr::Ptr{Cvoid}
end

function wxGridBagSizer(vgap::Integer, hgap::Integer)
    ptr = KwxFFI.wxGridBagSizer_Create(Cint(vgap), Cint(hgap))
    ptr == C_NULL && error("Failed to create wxGridBagSizer")
    obj = wxGridBagSizer(ptr)
    return obj
end

function (obj::wxGridBagSizer, window::Ptr{Cvoid}, row::Integer, col::Integer, rowspan::Integer, colspan::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    return KwxFFI.wxGridBagSizer_AddWindow(obj.ptr, window, Cint(row), Cint(col), Cint(rowspan), Cint(colspan), Cint(flag), Cint(border), userData)
end

function (obj::wxGridBagSizer, sizer::Ptr{Cvoid}, row::Integer, col::Integer, rowspan::Integer, colspan::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    return KwxFFI.wxGridBagSizer_AddSizer(obj.ptr, sizer, Cint(row), Cint(col), Cint(rowspan), Cint(colspan), Cint(flag), Cint(border), userData)
end

function (obj::wxGridBagSizer, width::Integer, height::Integer, row::Integer, col::Integer, rowspan::Integer, colspan::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    return KwxFFI.wxGridBagSizer_AddSpacer(obj.ptr, Cint(width), Cint(height), Cint(row), Cint(col), Cint(rowspan), Cint(colspan), Cint(flag), Cint(border), userData)
end

function (obj::wxGridBagSizer, window::Ptr{Cvoid}, row::Ptr{Cvoid}, col::Ptr{Cvoid})
    KwxFFI.wxGridBagSizer_GetItemPosition(obj.ptr, window, row, col)
    nothing
end

function (obj::wxGridBagSizer, sizer::Ptr{Cvoid}, row::Ptr{Cvoid}, col::Ptr{Cvoid})
    KwxFFI.wxGridBagSizer_GetItemPositionSizer(obj.ptr, sizer, row, col)
    nothing
end

function (obj::wxGridBagSizer, index::Integer, row::Ptr{Cvoid}, col::Ptr{Cvoid})
    KwxFFI.wxGridBagSizer_GetItemPositionIndex(obj.ptr, Csize_t(index), row, col)
    nothing
end

function (obj::wxGridBagSizer, window::Ptr{Cvoid}, row::Integer, col::Integer)
    return KwxFFI.wxGridBagSizer_SetItemPosition(obj.ptr, window, Cint(row), Cint(col)) != 0
end

function (obj::wxGridBagSizer, sizer::Ptr{Cvoid}, row::Integer, col::Integer)
    return KwxFFI.wxGridBagSizer_SetItemPositionSizer(obj.ptr, sizer, Cint(row), Cint(col)) != 0
end

function (obj::wxGridBagSizer, index::Integer, row::Integer, col::Integer)
    return KwxFFI.wxGridBagSizer_SetItemPositionIndex(obj.ptr, Csize_t(index), Cint(row), Cint(col)) != 0
end

function (obj::wxGridBagSizer, window::Ptr{Cvoid}, rowspan::Ptr{Cvoid}, colspan::Ptr{Cvoid})
    KwxFFI.wxGridBagSizer_GetItemSpan(obj.ptr, window, rowspan, colspan)
    nothing
end

function (obj::wxGridBagSizer, sizer::Ptr{Cvoid}, rowspan::Ptr{Cvoid}, colspan::Ptr{Cvoid})
    KwxFFI.wxGridBagSizer_GetItemSpanSizer(obj.ptr, sizer, rowspan, colspan)
    nothing
end

function (obj::wxGridBagSizer, index::Integer, rowspan::Ptr{Cvoid}, colspan::Ptr{Cvoid})
    KwxFFI.wxGridBagSizer_GetItemSpanIndex(obj.ptr, Csize_t(index), rowspan, colspan)
    nothing
end

function (obj::wxGridBagSizer, window::Ptr{Cvoid}, rowspan::Integer, colspan::Integer)
    return KwxFFI.wxGridBagSizer_SetItemSpan(obj.ptr, window, Cint(rowspan), Cint(colspan)) != 0
end

function (obj::wxGridBagSizer, sizer::Ptr{Cvoid}, rowspan::Integer, colspan::Integer)
    return KwxFFI.wxGridBagSizer_SetItemSpanSizer(obj.ptr, sizer, Cint(rowspan), Cint(colspan)) != 0
end

function (obj::wxGridBagSizer, index::Integer, rowspan::Integer, colspan::Integer)
    return KwxFFI.wxGridBagSizer_SetItemSpanIndex(obj.ptr, Csize_t(index), Cint(rowspan), Cint(colspan)) != 0
end

function (obj::wxGridBagSizer, row::Integer, col::Integer)
    return KwxFFI.wxGridBagSizer_FindItemAtPosition(obj.ptr, Cint(row), Cint(col))
end

function (obj::wxGridBagSizer, item::Ptr{Cvoid}, excludeItem::Ptr{Cvoid})
    return KwxFFI.wxGridBagSizer_CheckForIntersection(obj.ptr, item, excludeItem) != 0
end

function (obj::wxGridBagSizer, row::Integer, col::Integer, rowspan::Integer, colspan::Integer, excludeItem::Ptr{Cvoid})
    return KwxFFI.wxGridBagSizer_CheckForIntersectionPos(obj.ptr, Cint(row), Cint(col), Cint(rowspan), Cint(colspan), excludeItem) != 0
end

function (obj::wxGridBagSizer, width::Ptr{Cvoid}, height::Ptr{Cvoid})
    KwxFFI.wxGridBagSizer_GetEmptyCellSize(obj.ptr, width, height)
    nothing
end

function (obj::wxGridBagSizer, width::Integer, height::Integer)
    KwxFFI.wxGridBagSizer_SetEmptyCellSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

