# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGridEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxGridEvent)
    return KwxFFI.wxGridEvent_AltDown(obj.ptr) != 0
end

function (obj::wxGridEvent)
    return KwxFFI.wxGridEvent_ControlDown(obj.ptr) != 0
end

function (obj::wxGridEvent)
    return Int(KwxFFI.wxGridEvent_GetCol(obj.ptr))
end

function (obj::wxGridEvent)
    return KwxFFI.wxGridEvent_GetPosition(obj.ptr)
end

function (obj::wxGridEvent)
    return Int(KwxFFI.wxGridEvent_GetRow(obj.ptr))
end

function (obj::wxGridEvent)
    return KwxFFI.wxGridEvent_MetaDown(obj.ptr) != 0
end

function (obj::wxGridEvent)
    return KwxFFI.wxGridEvent_Selecting(obj.ptr) != 0
end

function (obj::wxGridEvent)
    return KwxFFI.wxGridEvent_ShiftDown(obj.ptr) != 0
end

