# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGridCellNumberRenderer <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxGridCellNumberRenderer)
    return KwxFFI.wxGridCellNumberRenderer_Ctor(obj.ptr)
end

