# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGridSizer <: wxSizer
    ptr::Ptr{Cvoid}
end

function wxGridSizer(rows::Integer, cols::Integer, vgap::Integer, hgap::Integer)
    ptr = KwxFFI.wxGridSizer_Create(Cint(rows), Cint(cols), Cint(vgap), Cint(hgap))
    ptr == C_NULL && error("Failed to create wxGridSizer")
    obj = wxGridSizer(ptr)
    return obj
end

function (obj::wxGridSizer)
    return KwxFFI.wxGridSizer_CalcMin(obj.ptr)
end

function (obj::wxGridSizer)
    return Int(KwxFFI.wxGridSizer_GetCols(obj.ptr))
end

function (obj::wxGridSizer)
    return Int(KwxFFI.wxGridSizer_GetHGap(obj.ptr))
end

function (obj::wxGridSizer)
    return Int(KwxFFI.wxGridSizer_GetRows(obj.ptr))
end

function (obj::wxGridSizer)
    return Int(KwxFFI.wxGridSizer_GetVGap(obj.ptr))
end

function (obj::wxGridSizer)
    KwxFFI.wxGridSizer_RecalcSizes(obj.ptr)
    nothing
end

function (obj::wxGridSizer, cols::Integer)
    KwxFFI.wxGridSizer_SetCols(obj.ptr, Cint(cols))
    nothing
end

function (obj::wxGridSizer, gap::Integer)
    KwxFFI.wxGridSizer_SetHGap(obj.ptr, Cint(gap))
    nothing
end

function (obj::wxGridSizer, rows::Integer)
    KwxFFI.wxGridSizer_SetRows(obj.ptr, Cint(rows))
    nothing
end

function (obj::wxGridSizer, gap::Integer)
    KwxFFI.wxGridSizer_SetVGap(obj.ptr, Cint(gap))
    nothing
end

