# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGridSizeEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxGridSizeEvent)
    return Int(KwxFFI.wxGridSizeEvent_GetRowOrCol(obj.ptr))
end

function (obj::wxGridSizeEvent)
    return KwxFFI.wxGridSizeEvent_GetPosition(obj.ptr)
end

function (obj::wxGridSizeEvent)
    return KwxFFI.wxGridSizeEvent_ControlDown(obj.ptr) != 0
end

function (obj::wxGridSizeEvent)
    return KwxFFI.wxGridSizeEvent_MetaDown(obj.ptr) != 0
end

function (obj::wxGridSizeEvent)
    return KwxFFI.wxGridSizeEvent_ShiftDown(obj.ptr) != 0
end

function (obj::wxGridSizeEvent)
    return KwxFFI.wxGridSizeEvent_AltDown(obj.ptr) != 0
end

