# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGridEditorCreatedEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxGridEditorCreatedEvent)
    return Int(KwxFFI.wxGridEditorCreatedEvent_GetCol(obj.ptr))
end

function (obj::wxGridEditorCreatedEvent)
    return KwxFFI.wxGridEditorCreatedEvent_GetControl(obj.ptr)
end

function (obj::wxGridEditorCreatedEvent)
    return Int(KwxFFI.wxGridEditorCreatedEvent_GetRow(obj.ptr))
end

function (obj::wxGridEditorCreatedEvent, col::Integer)
    KwxFFI.wxGridEditorCreatedEvent_SetCol(obj.ptr, Cint(col))
    nothing
end

function (obj::wxGridEditorCreatedEvent, ctrl::Ptr{Cvoid})
    KwxFFI.wxGridEditorCreatedEvent_SetControl(obj.ptr, ctrl)
    nothing
end

function (obj::wxGridEditorCreatedEvent, row::Integer)
    KwxFFI.wxGridEditorCreatedEvent_SetRow(obj.ptr, Cint(row))
    nothing
end

