# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGridCellCoordsArray <: wxObject
    ptr::Ptr{Cvoid}
end

function wxGridCellCoordsArray()
    ptr = KwxFFI.wxGridCellCoordsArray_Create()
    ptr == C_NULL && error("Failed to create wxGridCellCoordsArray")
    obj = wxGridCellCoordsArray(ptr)
    return obj
end

function delete!(obj::wxGridCellCoordsArray)
    KwxFFI.wxGridCellCoordsArray_Delete(obj.ptr)
    nothing
end

function (obj::wxGridCellCoordsArray)
    return Int(KwxFFI.wxGridCellCoordsArray_GetCount(obj.ptr))
end

function (obj::wxGridCellCoordsArray, index::Integer, col::Ref{Int32}, row::Ref{Int32})
    KwxFFI.wxGridCellCoordsArray_Item(obj.ptr, Cint(index), col, row)
    nothing
end

