# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGridCellTextEditor <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxGridCellTextEditor)
    return KwxFFI.wxGridCellTextEditor_Ctor(obj.ptr)
end

