# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxGrid <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxGrid(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxGrid_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxGrid")
    obj = wxGrid(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxGrid, numCols::Integer, updateLabels::Bool)
    return KwxFFI.wxGrid_AppendCols(obj.ptr, Cint(numCols), Cint(updateLabels)) != 0
end

function (obj::wxGrid, numRows::Integer, updateLabels::Bool)
    return KwxFFI.wxGrid_AppendRows(obj.ptr, Cint(numRows), Cint(updateLabels)) != 0
end

function (obj::wxGrid)
    KwxFFI.wxGrid_AutoSize(obj.ptr)
    nothing
end

function (obj::wxGrid, col::Integer, setAsMin::Bool)
    KwxFFI.wxGrid_AutoSizeColumn(obj.ptr, Cint(col), Cint(setAsMin))
    nothing
end

function (obj::wxGrid, setAsMin::Bool)
    KwxFFI.wxGrid_AutoSizeColumns(obj.ptr, Cint(setAsMin))
    nothing
end

function (obj::wxGrid, row::Integer, setAsMin::Bool)
    KwxFFI.wxGrid_AutoSizeRow(obj.ptr, Cint(row), Cint(setAsMin))
    nothing
end

function (obj::wxGrid, setAsMin::Bool)
    KwxFFI.wxGrid_AutoSizeRows(obj.ptr, Cint(setAsMin))
    nothing
end

function (obj::wxGrid)
    KwxFFI.wxGrid_BeginBatch(obj.ptr)
    nothing
end

function (obj::wxGrid, top::Integer, left::Integer, bottom::Integer, right::Integer)
    return KwxFFI.wxGrid_BlockToDeviceRect(obj.ptr, Cint(top), Cint(left), Cint(bottom), Cint(right))
end

function (obj::wxGrid, col::Integer)
    return KwxFFI.wxGrid_CanDragColSize(obj.ptr, Cint(col)) != 0
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_CanDragGridSize(obj.ptr) != 0
end

function (obj::wxGrid, row::Integer)
    return KwxFFI.wxGrid_CanDragRowSize(obj.ptr, Cint(row)) != 0
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_CanEnableCellControl(obj.ptr) != 0
end

function (obj::wxGrid, row::Integer, col::Integer)
    return KwxFFI.wxGrid_CellToRect(obj.ptr, Cint(row), Cint(col))
end

function (obj::wxGrid)
    KwxFFI.wxGrid_ClearGrid(obj.ptr)
    nothing
end

function (obj::wxGrid)
    KwxFFI.wxGrid_ClearSelection(obj.ptr)
    nothing
end

function (obj::wxGrid, rows::Integer, cols::Integer, selmode::Integer)
    KwxFFI.wxGrid_CreateGrid(obj.ptr, Cint(rows), Cint(cols), Cint(selmode))
    nothing
end

function (obj::wxGrid, pos::Integer, numCols::Integer, updateLabels::Bool)
    return KwxFFI.wxGrid_DeleteCols(obj.ptr, Cint(pos), Cint(numCols), Cint(updateLabels)) != 0
end

function (obj::wxGrid, pos::Integer, numRows::Integer, updateLabels::Bool)
    return KwxFFI.wxGrid_DeleteRows(obj.ptr, Cint(pos), Cint(numRows), Cint(updateLabels)) != 0
end

function (obj::wxGrid)
    KwxFFI.wxGrid_DisableCellEditControl(obj.ptr)
    nothing
end

function (obj::wxGrid)
    KwxFFI.wxGrid_DisableDragColSize(obj.ptr)
    nothing
end

function (obj::wxGrid)
    KwxFFI.wxGrid_DisableDragGridSize(obj.ptr)
    nothing
end

function (obj::wxGrid)
    KwxFFI.wxGrid_DisableDragRowSize(obj.ptr)
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid}, reg::Ptr{Cvoid})
    KwxFFI.wxGrid_DrawAllGridLines(obj.ptr, dc, reg)
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid}, row::Integer, col::Integer)
    KwxFFI.wxGrid_DrawCell(obj.ptr, dc, Cint(row), Cint(col))
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid}, row::Integer, col::Integer)
    KwxFFI.wxGrid_DrawCellBorder(obj.ptr, dc, Cint(row), Cint(col))
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid}, attr::Ptr{Cvoid})
    KwxFFI.wxGrid_DrawCellHighlight(obj.ptr, dc, attr)
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid}, col::Integer)
    KwxFFI.wxGrid_DrawColLabel(obj.ptr, dc, Cint(col))
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid})
    KwxFFI.wxGrid_DrawColLabels(obj.ptr, dc)
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid})
    KwxFFI.wxGrid_DrawGridSpace(obj.ptr, dc)
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid}, row::Integer)
    KwxFFI.wxGrid_DrawRowLabel(obj.ptr, dc, Cint(row))
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid})
    KwxFFI.wxGrid_DrawRowLabels(obj.ptr, dc)
    nothing
end

function (obj::wxGrid, dc::Ptr{Cvoid}, txt::String, x::Integer, y::Integer, width::Integer, height::Integer, horizontalAlignment::Integer, verticalAlignment::Integer)
    txt_ws = wxString(txt)
    KwxFFI.wxGrid_DrawTextRectangle(obj.ptr, dc, txt_ws.ptr, Cint(x), Cint(y), Cint(width), Cint(height), Cint(horizontalAlignment), Cint(verticalAlignment))
    delete!(txt_ws)
    nothing
end

function (obj::wxGrid, enable::Bool)
    KwxFFI.wxGrid_EnableCellEditControl(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxGrid, enable::Bool)
    KwxFFI.wxGrid_EnableDragColSize(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxGrid, enable::Bool)
    KwxFFI.wxGrid_EnableDragGridSize(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxGrid, enable::Bool)
    KwxFFI.wxGrid_EnableDragRowSize(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxGrid, edit::Bool)
    KwxFFI.wxGrid_EnableEditing(obj.ptr, Cint(edit))
    nothing
end

function (obj::wxGrid, enable::Bool)
    KwxFFI.wxGrid_EnableGridLines(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxGrid)
    KwxFFI.wxGrid_EndBatch(obj.ptr)
    nothing
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetBatchCount(obj.ptr))
end

function (obj::wxGrid, row::Integer, col::Integer, horiz::Ref{Int32}, vert::Ref{Int32})
    KwxFFI.wxGrid_GetCellAlignment(obj.ptr, Cint(row), Cint(col), horiz, vert)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_GetCellBackgroundColour(obj.ptr, Cint(row), Cint(col), colour)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer)
    return KwxFFI.wxGrid_GetCellEditor(obj.ptr, Cint(row), Cint(col))
end

function (obj::wxGrid, row::Integer, col::Integer, font::Ptr{Cvoid})
    KwxFFI.wxGrid_GetCellFont(obj.ptr, Cint(row), Cint(col), font)
    nothing
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetCellHighlightColour(obj.ptr, ref)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer)
    return KwxFFI.wxGrid_GetCellRenderer(obj.ptr, Cint(row), Cint(col))
end

function (obj::wxGrid, row::Integer, col::Integer, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_GetCellTextColour(obj.ptr, Cint(row), Cint(col), colour)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer)
    return KwxFFI.wxGrid_GetCellValue(obj.ptr, Cint(row), Cint(col))
end

function (obj::wxGrid, horiz::Ref{Int32}, vert::Ref{Int32})
    KwxFFI.wxGrid_GetColLabelAlignment(obj.ptr, horiz, vert)
    nothing
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetColLabelSize(obj.ptr))
end

function (obj::wxGrid, col::Integer)
    return KwxFFI.wxGrid_GetColLabelValue(obj.ptr, Cint(col))
end

function (obj::wxGrid, col::Integer)
    return Int(KwxFFI.wxGrid_GetColSize(obj.ptr, Cint(col)))
end

function (obj::wxGrid, horiz::Ref{Int32}, vert::Ref{Int32})
    KwxFFI.wxGrid_GetDefaultCellAlignment(obj.ptr, horiz, vert)
    nothing
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetDefaultCellBackgroundColour(obj.ptr, ref)
    nothing
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetDefaultCellFont(obj.ptr, ref)
    nothing
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetDefaultCellTextColour(obj.ptr, ref)
    nothing
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetDefaultColLabelSize(obj.ptr))
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetDefaultColSize(obj.ptr))
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_GetDefaultEditor(obj.ptr)
end

function (obj::wxGrid, row::Integer, col::Integer)
    return KwxFFI.wxGrid_GetDefaultEditorForCell(obj.ptr, Cint(row), Cint(col))
end

function (obj::wxGrid, typeName::String)
    typeName_ws = wxString(typeName)
    _result = KwxFFI.wxGrid_GetDefaultEditorForType(obj.ptr, typeName_ws.ptr)
    delete!(typeName_ws)
    return _result
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_GetDefaultRenderer(obj.ptr)
end

function (obj::wxGrid, row::Integer, col::Integer)
    return KwxFFI.wxGrid_GetDefaultRendererForCell(obj.ptr, Cint(row), Cint(col))
end

function (obj::wxGrid, typeName::String)
    typeName_ws = wxString(typeName)
    _result = KwxFFI.wxGrid_GetDefaultRendererForType(obj.ptr, typeName_ws.ptr)
    delete!(typeName_ws)
    return _result
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetDefaultRowLabelSize(obj.ptr))
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetDefaultRowSize(obj.ptr))
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetGridCursorCol(obj.ptr))
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetGridCursorRow(obj.ptr))
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetGridLineColour(obj.ptr, ref)
    nothing
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetLabelBackgroundColour(obj.ptr, ref)
    nothing
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetLabelFont(obj.ptr, ref)
    nothing
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetLabelTextColour(obj.ptr, ref)
    nothing
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetNumberCols(obj.ptr))
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetNumberRows(obj.ptr))
end

function (obj::wxGrid, horiz::Ref{Int32}, vert::Ref{Int32})
    KwxFFI.wxGrid_GetRowLabelAlignment(obj.ptr, horiz, vert)
    nothing
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GetRowLabelSize(obj.ptr))
end

function (obj::wxGrid, row::Integer)
    return KwxFFI.wxGrid_GetRowLabelValue(obj.ptr, Cint(row))
end

function (obj::wxGrid, row::Integer)
    return Int(KwxFFI.wxGrid_GetRowSize(obj.ptr, Cint(row)))
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetSelectionBackground(obj.ptr, ref)
    nothing
end

function (obj::wxGrid, ref::Ptr{Cvoid})
    KwxFFI.wxGrid_GetSelectionForeground(obj.ptr, ref)
    nothing
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_GetTable(obj.ptr)
end

function (obj::wxGrid, dc::Ptr{Cvoid}, count::Integer, lines::Ptr{Cvoid}, arg::Integer)
    KwxFFI.wxGrid_GetTextBoxSize(obj.ptr, dc, Cint(count), lines, Cint(arg))
    nothing
end

function (obj::wxGrid)
    return Int(KwxFFI.wxGrid_GridLinesEnabled(obj.ptr))
end

function (obj::wxGrid)
    KwxFFI.wxGrid_HideCellEditControl(obj.ptr)
    nothing
end

function (obj::wxGrid, pos::Integer, numCols::Integer, updateLabels::Bool)
    return KwxFFI.wxGrid_InsertCols(obj.ptr, Cint(pos), Cint(numCols), Cint(updateLabels)) != 0
end

function (obj::wxGrid, pos::Integer, numRows::Integer, updateLabels::Bool)
    return KwxFFI.wxGrid_InsertRows(obj.ptr, Cint(pos), Cint(numRows), Cint(updateLabels)) != 0
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_IsCellEditControlEnabled(obj.ptr) != 0
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_IsCellEditControlShown(obj.ptr) != 0
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_IsCurrentCellReadOnly(obj.ptr) != 0
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_IsEditable(obj.ptr) != 0
end

function (obj::wxGrid, row::Integer, col::Integer)
    return KwxFFI.wxGrid_IsInSelection(obj.ptr, Cint(row), Cint(col)) != 0
end

function (obj::wxGrid, row::Integer, col::Integer)
    return KwxFFI.wxGrid_IsReadOnly(obj.ptr, Cint(row), Cint(col)) != 0
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_IsSelection(obj.ptr) != 0
end

function (obj::wxGrid, row::Integer, col::Integer, wholeCellVisible::Bool)
    return KwxFFI.wxGrid_IsVisible(obj.ptr, Cint(row), Cint(col), Cint(wholeCellVisible)) != 0
end

function (obj::wxGrid, row::Integer, col::Integer)
    KwxFFI.wxGrid_MakeCellVisible(obj.ptr, Cint(row), Cint(col))
    nothing
end

function (obj::wxGrid, expandSelection::Bool)
    return KwxFFI.wxGrid_MoveCursorDown(obj.ptr, Cint(expandSelection)) != 0
end

function (obj::wxGrid, expandSelection::Bool)
    return KwxFFI.wxGrid_MoveCursorDownBlock(obj.ptr, Cint(expandSelection)) != 0
end

function (obj::wxGrid, expandSelection::Bool)
    return KwxFFI.wxGrid_MoveCursorLeft(obj.ptr, Cint(expandSelection)) != 0
end

function (obj::wxGrid, expandSelection::Bool)
    return KwxFFI.wxGrid_MoveCursorLeftBlock(obj.ptr, Cint(expandSelection)) != 0
end

function (obj::wxGrid, expandSelection::Bool)
    return KwxFFI.wxGrid_MoveCursorRight(obj.ptr, Cint(expandSelection)) != 0
end

function (obj::wxGrid, expandSelection::Bool)
    return KwxFFI.wxGrid_MoveCursorRightBlock(obj.ptr, Cint(expandSelection)) != 0
end

function (obj::wxGrid, expandSelection::Bool)
    return KwxFFI.wxGrid_MoveCursorUp(obj.ptr, Cint(expandSelection)) != 0
end

function (obj::wxGrid, expandSelection::Bool)
    return KwxFFI.wxGrid_MoveCursorUpBlock(obj.ptr, Cint(expandSelection)) != 0
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_MovePageDown(obj.ptr) != 0
end

function (obj::wxGrid)
    return KwxFFI.wxGrid_MovePageUp(obj.ptr) != 0
end

function (obj::wxGrid, evt::Ptr{Cvoid})
    return KwxFFI.wxGrid_ProcessTableMessage(obj.ptr, evt) != 0
end

function (obj::wxGrid, typeName::String, renderer::Ptr{Cvoid}, editor::Ptr{Cvoid})
    typeName_ws = wxString(typeName)
    KwxFFI.wxGrid_RegisterDataType(obj.ptr, typeName_ws.ptr, renderer, editor)
    delete!(typeName_ws)
    nothing
end

function (obj::wxGrid)
    KwxFFI.wxGrid_SaveEditControlValue(obj.ptr)
    nothing
end

function (obj::wxGrid)
    KwxFFI.wxGrid_SelectAll(obj.ptr)
    nothing
end

function (obj::wxGrid, topRow::Integer, leftCol::Integer, bottomRow::Integer, rightCol::Integer, addToSelected::Bool)
    KwxFFI.wxGrid_SelectBlock(obj.ptr, Cint(topRow), Cint(leftCol), Cint(bottomRow), Cint(rightCol), Cint(addToSelected))
    nothing
end

function (obj::wxGrid, col::Integer, addToSelected::Bool)
    KwxFFI.wxGrid_SelectCol(obj.ptr, Cint(col), Cint(addToSelected))
    nothing
end

function (obj::wxGrid, row::Integer, addToSelected::Bool)
    KwxFFI.wxGrid_SelectRow(obj.ptr, Cint(row), Cint(addToSelected))
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, horiz::Integer, vert::Integer)
    KwxFFI.wxGrid_SetCellAlignment(obj.ptr, Cint(row), Cint(col), Cint(horiz), Cint(vert))
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_SetCellBackgroundColour(obj.ptr, Cint(row), Cint(col), colour)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, editor::Ptr{Cvoid})
    KwxFFI.wxGrid_SetCellEditor(obj.ptr, Cint(row), Cint(col), editor)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, font::Ptr{Cvoid})
    KwxFFI.wxGrid_SetCellFont(obj.ptr, Cint(row), Cint(col), font)
    nothing
end

function (obj::wxGrid, col::Ptr{Cvoid})
    KwxFFI.wxGrid_SetCellHighlightColour(obj.ptr, col)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, renderer::Ptr{Cvoid})
    KwxFFI.wxGrid_SetCellRenderer(obj.ptr, Cint(row), Cint(col), renderer)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_SetCellTextColour(obj.ptr, Cint(row), Cint(col), colour)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, str::String)
    str_ws = wxString(str)
    KwxFFI.wxGrid_SetCellValue(obj.ptr, Cint(row), Cint(col), str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxGrid, col::Integer, attr::Ptr{Cvoid})
    KwxFFI.wxGrid_SetColAttr(obj.ptr, Cint(col), attr)
    nothing
end

function (obj::wxGrid, col::Integer)
    KwxFFI.wxGrid_SetColFormatBool(obj.ptr, Cint(col))
    nothing
end

function (obj::wxGrid, col::Integer, typeName::String)
    typeName_ws = wxString(typeName)
    KwxFFI.wxGrid_SetColFormatCustom(obj.ptr, Cint(col), typeName_ws.ptr)
    delete!(typeName_ws)
    nothing
end

function (obj::wxGrid, col::Integer, width::Integer, precision::Integer)
    KwxFFI.wxGrid_SetColFormatFloat(obj.ptr, Cint(col), Cint(width), Cint(precision))
    nothing
end

function (obj::wxGrid, col::Integer)
    KwxFFI.wxGrid_SetColFormatNumber(obj.ptr, Cint(col))
    nothing
end

function (obj::wxGrid, horiz::Integer, vert::Integer)
    KwxFFI.wxGrid_SetColLabelAlignment(obj.ptr, Cint(horiz), Cint(vert))
    nothing
end

function (obj::wxGrid, height::Integer)
    KwxFFI.wxGrid_SetColLabelSize(obj.ptr, Cint(height))
    nothing
end

function (obj::wxGrid, col::Integer, label::String)
    label_ws = wxString(label)
    KwxFFI.wxGrid_SetColLabelValue(obj.ptr, Cint(col), label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxGrid, col::Integer, width::Integer)
    KwxFFI.wxGrid_SetColMinimalWidth(obj.ptr, Cint(col), Cint(width))
    nothing
end

function (obj::wxGrid, col::Integer, width::Integer)
    KwxFFI.wxGrid_SetColSize(obj.ptr, Cint(col), Cint(width))
    nothing
end

function (obj::wxGrid, horiz::Integer, vert::Integer)
    KwxFFI.wxGrid_SetDefaultCellAlignment(obj.ptr, Cint(horiz), Cint(vert))
    nothing
end

function (obj::wxGrid, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_SetDefaultCellBackgroundColour(obj.ptr, colour)
    nothing
end

function (obj::wxGrid, font::Ptr{Cvoid})
    KwxFFI.wxGrid_SetDefaultCellFont(obj.ptr, font)
    nothing
end

function (obj::wxGrid, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_SetDefaultCellTextColour(obj.ptr, colour)
    nothing
end

function (obj::wxGrid, width::Integer, resizeExistingCols::Bool)
    KwxFFI.wxGrid_SetDefaultColSize(obj.ptr, Cint(width), Cint(resizeExistingCols))
    nothing
end

function (obj::wxGrid, editor::Ptr{Cvoid})
    KwxFFI.wxGrid_SetDefaultEditor(obj.ptr, editor)
    nothing
end

function (obj::wxGrid, renderer::Ptr{Cvoid})
    KwxFFI.wxGrid_SetDefaultRenderer(obj.ptr, renderer)
    nothing
end

function (obj::wxGrid, height::Integer, resizeExistingRows::Bool)
    KwxFFI.wxGrid_SetDefaultRowSize(obj.ptr, Cint(height), Cint(resizeExistingRows))
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer)
    KwxFFI.wxGrid_SetGridCursor(obj.ptr, Cint(row), Cint(col))
    nothing
end

function (obj::wxGrid, col::Ptr{Cvoid})
    KwxFFI.wxGrid_SetGridLineColour(obj.ptr, col)
    nothing
end

function (obj::wxGrid, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_SetLabelBackgroundColour(obj.ptr, colour)
    nothing
end

function (obj::wxGrid, font::Ptr{Cvoid})
    KwxFFI.wxGrid_SetLabelFont(obj.ptr, font)
    nothing
end

function (obj::wxGrid, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_SetLabelTextColour(obj.ptr, colour)
    nothing
end

function (obj::wxGrid, extraWidth::Integer, extraHeight::Integer)
    KwxFFI.wxGrid_SetMargins(obj.ptr, Cint(extraWidth), Cint(extraHeight))
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, isReadOnly::Bool)
    KwxFFI.wxGrid_SetReadOnly(obj.ptr, Cint(row), Cint(col), Cint(isReadOnly))
    nothing
end

function (obj::wxGrid, row::Integer, attr::Ptr{Cvoid})
    KwxFFI.wxGrid_SetRowAttr(obj.ptr, Cint(row), attr)
    nothing
end

function (obj::wxGrid, horiz::Integer, vert::Integer)
    KwxFFI.wxGrid_SetRowLabelAlignment(obj.ptr, Cint(horiz), Cint(vert))
    nothing
end

function (obj::wxGrid, width::Integer)
    KwxFFI.wxGrid_SetRowLabelSize(obj.ptr, Cint(width))
    nothing
end

function (obj::wxGrid, row::Integer, label::String)
    label_ws = wxString(label)
    KwxFFI.wxGrid_SetRowLabelValue(obj.ptr, Cint(row), label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxGrid, row::Integer, width::Integer)
    KwxFFI.wxGrid_SetRowMinimalHeight(obj.ptr, Cint(row), Cint(width))
    nothing
end

function (obj::wxGrid, row::Integer, height::Integer)
    KwxFFI.wxGrid_SetRowSize(obj.ptr, Cint(row), Cint(height))
    nothing
end

function (obj::wxGrid, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_SetSelectionBackground(obj.ptr, colour)
    nothing
end

function (obj::wxGrid, colour::Ptr{Cvoid})
    KwxFFI.wxGrid_SetSelectionForeground(obj.ptr, colour)
    nothing
end

function (obj::wxGrid, selmode::Integer)
    KwxFFI.wxGrid_SetSelectionMode(obj.ptr, Cint(selmode))
    nothing
end

function (obj::wxGrid, table::Ptr{Cvoid}, takeOwnership::Bool, selmode::Integer)
    return KwxFFI.wxGrid_SetTable(obj.ptr, table, Cint(takeOwnership), Cint(selmode)) != 0
end

function (obj::wxGrid)
    KwxFFI.wxGrid_ShowCellEditControl(obj.ptr)
    nothing
end

function (obj::wxGrid, value::String, lines::Ptr{Cvoid})
    value_ws = wxString(value)
    _result = Int(KwxFFI.wxGrid_StringToLines(obj.ptr, value_ws.ptr, lines))
    delete!(value_ws)
    return _result
end

function (obj::wxGrid, x::Integer, clipToMinMax::Bool)
    return Int(KwxFFI.wxGrid_XToCol(obj.ptr, Cint(x), Cint(clipToMinMax)))
end

function (obj::wxGrid, x::Integer)
    return Int(KwxFFI.wxGrid_XToEdgeOfCol(obj.ptr, Cint(x)))
end

function (obj::wxGrid, x::Integer, y::Integer, row::Ref{Int32}, col::Ref{Int32})
    KwxFFI.wxGrid_XYToCell(obj.ptr, Cint(x), Cint(y), row, col)
    nothing
end

function (obj::wxGrid, y::Integer)
    return Int(KwxFFI.wxGrid_YToEdgeOfRow(obj.ptr, Cint(y)))
end

function (obj::wxGrid, y::Integer, clipToMinMax::Bool)
    return Int(KwxFFI.wxGrid_YToRow(obj.ptr, Cint(y), Cint(clipToMinMax)))
end

function (obj::wxGrid, array::Ptr{Cvoid})
    KwxFFI.wxGrid_GetSelectedCells(obj.ptr, array)
    nothing
end

function (obj::wxGrid, array::Ptr{Cvoid})
    KwxFFI.wxGrid_GetSelectionBlockTopLeft(obj.ptr, array)
    nothing
end

function (obj::wxGrid, array::Ptr{Cvoid})
    KwxFFI.wxGrid_GetSelectionBlockBottomRight(obj.ptr, array)
    nothing
end

function (obj::wxGrid, array::Integer)
    return Int(KwxFFI.wxGrid_GetSelectedRows(obj.ptr, Cint(array)))
end

function (obj::wxGrid, array::Integer)
    return Int(KwxFFI.wxGrid_GetSelectedCols(obj.ptr, Cint(array)))
end

function (obj::wxGrid, row::Integer, col::Integer, srow::Ref{Int32}, scol::Ref{Int32})
    KwxFFI.wxGrid_GetCellSize(obj.ptr, Cint(row), Cint(col), srow, scol)
    nothing
end

function (obj::wxGrid, row::Integer, col::Integer, srow::Integer, scol::Integer)
    KwxFFI.wxGrid_SetCellSize(obj.ptr, Cint(row), Cint(col), Cint(srow), Cint(scol))
    nothing
end

