# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxHelpControllerHelpProvider <: wxObject
    ptr::Ptr{Cvoid}
end

function wxHelpControllerHelpProvider(ctr::Ptr{Cvoid})
    ptr = KwxFFI.wxHelpControllerHelpProvider_Create(ctr)
    ptr == C_NULL && error("Failed to create wxHelpControllerHelpProvider")
    obj = wxHelpControllerHelpProvider(ptr)
    return obj
end

function (obj::wxHelpControllerHelpProvider)
    return KwxFFI.wxHelpControllerHelpProvider_GetHelpController(obj.ptr)
end

function (obj::wxHelpControllerHelpProvider, helpController::Ptr{Cvoid})
    KwxFFI.wxHelpControllerHelpProvider_SetHelpController(obj.ptr, helpController)
    nothing
end

