# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxHelpProvider <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxHelpProvider, window::Ptr{Cvoid}, text::String)
    text_ws = wxString(text)
    KwxFFI.wxHelpProvider_AddHelp(obj.ptr, window, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxHelpProvider, id::Integer, text::String)
    text_ws = wxString(text)
    KwxFFI.wxHelpProvider_AddHelpById(obj.ptr, Cint(id), text_ws.ptr)
    delete!(text_ws)
    nothing
end

function delete!(obj::wxHelpProvider)
    KwxFFI.wxHelpProvider_Delete(obj.ptr)
    nothing
end

function (obj::wxHelpProvider)
    return KwxFFI.wxHelpProvider_Get(obj.ptr)
end

function (obj::wxHelpProvider, window::Ptr{Cvoid})
    return KwxFFI.wxHelpProvider_GetHelp(obj.ptr, window)
end

function (obj::wxHelpProvider, window::Ptr{Cvoid})
    KwxFFI.wxHelpProvider_RemoveHelp(obj.ptr, window)
    nothing
end

function (obj::wxHelpProvider)
    return KwxFFI.wxHelpProvider_Set(obj.ptr)
end

function (obj::wxHelpProvider, window::Ptr{Cvoid})
    return KwxFFI.wxHelpProvider_ShowHelp(obj.ptr, window) != 0
end

