# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxHelpEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxHelpEvent)
    return KwxFFI.wxHelpEvent_GetLink(obj.ptr)
end

function (obj::wxHelpEvent)
    return KwxFFI.wxHelpEvent_GetPosition(obj.ptr)
end

function (obj::wxHelpEvent)
    return KwxFFI.wxHelpEvent_GetTarget(obj.ptr)
end

function (obj::wxHelpEvent, link::String)
    link_ws = wxString(link)
    KwxFFI.wxHelpEvent_SetLink(obj.ptr, link_ws.ptr)
    delete!(link_ws)
    nothing
end

function (obj::wxHelpEvent, x::Integer, y::Integer)
    KwxFFI.wxHelpEvent_SetPosition(obj.ptr, Cint(x), Cint(y))
    nothing
end

function (obj::wxHelpEvent, target::String)
    target_ws = wxString(target)
    KwxFFI.wxHelpEvent_SetTarget(obj.ptr, target_ws.ptr)
    delete!(target_ws)
    nothing
end

