# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxIconBundle <: wxObject
    ptr::Ptr{Cvoid}
end

function wxIconBundle()
    ptr = KwxFFI.wxIconBundle_CreateDefault()
    ptr == C_NULL && error("Failed to create wxIconBundle")
    obj = wxIconBundle(ptr)
    return obj
end

function wxIconBundle(file::String, type_::Integer)
    file_ws = wxString(file)
    ptr = KwxFFI.wxIconBundle_CreateFromFile(file_ws.ptr, Cint(type_))
    delete!(file_ws)
    ptr == C_NULL && error("Failed to create wxIconBundle")
    obj = wxIconBundle(ptr)
    return obj
end

function wxIconBundle(icon::Ptr{Cvoid})
    ptr = KwxFFI.wxIconBundle_CreateFromIcon(icon)
    ptr == C_NULL && error("Failed to create wxIconBundle")
    obj = wxIconBundle(ptr)
    return obj
end

function (obj::wxIconBundle, icon::Ptr{Cvoid})
    KwxFFI.wxIconBundle_AddIcon(obj.ptr, icon)
    nothing
end

function (obj::wxIconBundle, file::String, type_::Integer)
    file_ws = wxString(file)
    KwxFFI.wxIconBundle_AddIconFromFile(obj.ptr, file_ws.ptr, Cint(type_))
    delete!(file_ws)
    nothing
end

function (obj::wxIconBundle, ref::Ptr{Cvoid})
    KwxFFI.wxIconBundle_Assign(obj.ptr, ref)
    nothing
end

function delete!(obj::wxIconBundle)
    KwxFFI.wxIconBundle_Delete(obj.ptr)
    nothing
end

function (obj::wxIconBundle, width::Integer, height::Integer, flags::Integer, ref::Ptr{Cvoid})
    KwxFFI.wxIconBundle_GetIcon(obj.ptr, Cint(width), Cint(height), Cint(flags), ref)
    nothing
end

