# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxIcon <: wxObject
    ptr::Ptr{Cvoid}
end

function wxIcon()
    ptr = KwxFFI.wxIcon_CreateDefault()
    ptr == C_NULL && error("Failed to create wxIcon")
    obj = wxIcon(ptr)
    return obj
end

function wxIcon(name::String, type_::Integer, width::Integer, height::Integer)
    name_ws = wxString(name)
    ptr = KwxFFI.wxIcon_CreateLoad(name_ws.ptr, Clong(type_), Cint(width), Cint(height))
    delete!(name_ws)
    ptr == C_NULL && error("Failed to create wxIcon")
    obj = wxIcon(ptr)
    return obj
end

function (obj::wxIcon, other::Ptr{Cvoid})
    KwxFFI.wxIcon_Assign(obj.ptr, other)
    nothing
end

function (obj::wxIcon, bmp::Ptr{Cvoid})
    KwxFFI.wxIcon_CopyFromBitmap(obj.ptr, bmp)
    nothing
end

function delete!(obj::wxIcon)
    KwxFFI.wxIcon_Delete(obj.ptr)
    nothing
end

function (obj::wxIcon, width::Integer, height::Integer)
    return KwxFFI.wxIcon_FromRaw(obj.ptr, Cint(width), Cint(height))
end

function (obj::wxIcon)
    return KwxFFI.wxIcon_FromXPM(obj.ptr)
end

function (obj::wxIcon)
    return Int(KwxFFI.wxIcon_GetDepth(obj.ptr))
end

function (obj::wxIcon)
    return Int(KwxFFI.wxIcon_GetHeight(obj.ptr))
end

function (obj::wxIcon)
    return Int(KwxFFI.wxIcon_GetWidth(obj.ptr))
end

function (obj::wxIcon)
    return KwxFFI.wxIcon_IsEqual(obj.ptr) != 0
end

function (obj::wxIcon, name::String, type_::Integer, width::Integer, height::Integer)
    name_ws = wxString(name)
    _result = Int(KwxFFI.wxIcon_Load(obj.ptr, name_ws.ptr, Clong(type_), Cint(width), Cint(height)))
    delete!(name_ws)
    return _result
end

function (obj::wxIcon)
    return KwxFFI.wxIcon_IsOk(obj.ptr) != 0
end

function (obj::wxIcon, depth::Integer)
    KwxFFI.wxIcon_SetDepth(obj.ptr, Cint(depth))
    nothing
end

function (obj::wxIcon, height::Integer)
    KwxFFI.wxIcon_SetHeight(obj.ptr, Cint(height))
    nothing
end

function (obj::wxIcon, width::Integer)
    KwxFFI.wxIcon_SetWidth(obj.ptr, Cint(width))
    nothing
end

