# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxImageList <: wxObject
    ptr::Ptr{Cvoid}
end

function wxImageList(width::Integer, height::Integer, mask::Bool, initialCount::Integer)
    ptr = KwxFFI.wxImageList_Create(Cint(width), Cint(height), Cint(mask), Cint(initialCount))
    ptr == C_NULL && error("Failed to create wxImageList")
    obj = wxImageList(ptr)
    return obj
end

function (obj::wxImageList, bitmap::Ptr{Cvoid}, mask::Ptr{Cvoid})
    return Int(KwxFFI.wxImageList_AddBitmap(obj.ptr, bitmap, mask))
end

function (obj::wxImageList, icon::Ptr{Cvoid})
    return Int(KwxFFI.wxImageList_AddIcon(obj.ptr, icon))
end

function (obj::wxImageList, bitmap::Ptr{Cvoid}, maskColour::Ptr{Cvoid})
    return Int(KwxFFI.wxImageList_AddMasked(obj.ptr, bitmap, maskColour))
end

function delete!(obj::wxImageList)
    KwxFFI.wxImageList_Delete(obj.ptr)
    nothing
end

function (obj::wxImageList, index::Integer, dc::Ptr{Cvoid}, x::Integer, y::Integer, flags::Integer, solidBackground::Bool)
    return KwxFFI.wxImageList_Draw(obj.ptr, Cint(index), dc, Cint(x), Cint(y), Cint(flags), Cint(solidBackground)) != 0
end

function (obj::wxImageList)
    return Int(KwxFFI.wxImageList_GetImageCount(obj.ptr))
end

function (obj::wxImageList, index::Integer, width::Ref{Int32}, height::Ref{Int32})
    KwxFFI.wxImageList_GetSize(obj.ptr, Cint(index), width, height)
    nothing
end

function (obj::wxImageList, index::Integer)
    return KwxFFI.wxImageList_Remove(obj.ptr, Cint(index)) != 0
end

function (obj::wxImageList)
    return KwxFFI.wxImageList_RemoveAll(obj.ptr) != 0
end

function (obj::wxImageList, index::Integer, bitmap::Ptr{Cvoid}, mask::Ptr{Cvoid})
    return KwxFFI.wxImageList_Replace(obj.ptr, Cint(index), bitmap, mask) != 0
end

function (obj::wxImageList, index::Integer, icon::Ptr{Cvoid})
    return KwxFFI.wxImageList_ReplaceIcon(obj.ptr, Cint(index), icon) != 0
end

