# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxIntProperty <: wxObject
    ptr::Ptr{Cvoid}
end

function wxIntProperty(label::String, name::String, value::Integer)
    label_ws = wxString(label)
    name_ws = wxString(name)
    ptr = KwxFFI.wxIntProperty_Create(label_ws.ptr, name_ws.ptr, Cint(value))
    delete!(label_ws)
    delete!(name_ws)
    ptr == C_NULL && error("Failed to create wxIntProperty")
    obj = wxIntProperty(ptr)
    return obj
end

