# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxInfoBar <: wxObject
    ptr::Ptr{Cvoid}
end

function wxInfoBar(parent::Union{wxWindow, Nothing}, id::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxInfoBar_Create(parent_ptr, Cint(id))
    ptr == C_NULL && error("Failed to create wxInfoBar")
    obj = wxInfoBar(ptr)
    return obj
end

function (obj::wxInfoBar, btnid::Integer, label::String)
    label_ws = wxString(label)
    KwxFFI.wxInfoBar_AddButton(obj.ptr, Cint(btnid), label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxInfoBar)
    KwxFFI.wxInfoBar_Dismiss(obj.ptr)
    nothing
end

function (obj::wxInfoBar)
    return KwxFFI.wxInfoBar_GetButtonCount(obj.ptr)
end

function (obj::wxInfoBar, idx::Integer)
    return Int(KwxFFI.wxInfoBar_GetButtonId(obj.ptr, Cint(idx)))
end

function (obj::wxInfoBar)
    return Int(KwxFFI.wxInfoBar_GetEffectDuration(obj.ptr))
end

function (obj::wxInfoBar)
    return Int(KwxFFI.wxInfoBar_GetShowEffect(obj.ptr))
end

function (obj::wxInfoBar)
    return Int(KwxFFI.wxInfoBar_GetHideEffect(obj.ptr))
end

function (obj::wxInfoBar, flag::Integer)
    return KwxFFI.wxInfoBar_HasFlag(obj.ptr, Cint(flag)) != 0
end

function (obj::wxInfoBar, btnid::Integer)
    KwxFFI.wxInfoBar_RemoveButton(obj.ptr, Cint(btnid))
    nothing
end

function (obj::wxInfoBar, duration::Integer)
    KwxFFI.wxInfoBar_SetEffectDuration(obj.ptr, Cint(duration))
    nothing
end

function (obj::wxInfoBar, showEffect::Integer, hideEffect::Integer)
    KwxFFI.wxInfoBar_SetShowHideEffects(obj.ptr, Cint(showEffect), Cint(hideEffect))
    nothing
end

function (obj::wxInfoBar, msg::String, flags::Integer)
    msg_ws = wxString(msg)
    KwxFFI.wxInfoBar_ShowMessage(obj.ptr, msg_ws.ptr, Cint(flags))
    delete!(msg_ws)
    nothing
end

