# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxItemContainer <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxItemContainer, self::Ptr{Cvoid})
    return KwxFFI.wxItemContainer_GetCount(obj.ptr, self)
end

function (obj::wxItemContainer, self::Ptr{Cvoid})
    return KwxFFI.wxItemContainer_IsEmpty(obj.ptr, self) != 0
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, n::Integer)
    return KwxFFI.wxItemContainer_GetString(obj.ptr, self, Cuint(n))
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, n::Integer, s::String)
    s_ws = wxString(s)
    KwxFFI.wxItemContainer_SetString(obj.ptr, self, Cuint(n), s_ws.ptr)
    delete!(s_ws)
    nothing
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, s::String, caseSensitive::Bool)
    s_ws = wxString(s)
    _result = Int(KwxFFI.wxItemContainer_FindString(obj.ptr, self, s_ws.ptr, Cint(caseSensitive)))
    delete!(s_ws)
    return _result
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, n::Integer)
    KwxFFI.wxItemContainer_SetSelection(obj.ptr, self, Cint(n))
    nothing
end

function (obj::wxItemContainer, self::Ptr{Cvoid})
    return Int(KwxFFI.wxItemContainer_GetSelection(obj.ptr, self))
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, s::String)
    s_ws = wxString(s)
    _result = KwxFFI.wxItemContainer_SetStringSelection(obj.ptr, self, s_ws.ptr) != 0
    delete!(s_ws)
    return _result
end

function (obj::wxItemContainer, self::Ptr{Cvoid})
    return KwxFFI.wxItemContainer_GetStringSelection(obj.ptr, self)
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, n::Integer)
    KwxFFI.wxItemContainer_Select(obj.ptr, self, Cint(n))
    nothing
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, item::String)
    item_ws = wxString(item)
    _result = Int(KwxFFI.wxItemContainer_Append(obj.ptr, self, item_ws.ptr))
    delete!(item_ws)
    return _result
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, count::Integer, items::Ptr{Cvoid})
    return Int(KwxFFI.wxItemContainer_AppendItems(obj.ptr, self, Cint(count), items))
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, item::String, pos::Integer)
    item_ws = wxString(item)
    _result = Int(KwxFFI.wxItemContainer_Insert(obj.ptr, self, item_ws.ptr, Cuint(pos)))
    delete!(item_ws)
    return _result
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, count::Integer, items::Ptr{Cvoid}, pos::Integer)
    return Int(KwxFFI.wxItemContainer_InsertItems(obj.ptr, self, Cint(count), items, Cuint(pos)))
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, count::Integer, items::Ptr{Cvoid})
    KwxFFI.wxItemContainer_Set(obj.ptr, self, Cint(count), items)
    nothing
end

function (obj::wxItemContainer, self::Ptr{Cvoid})
    KwxFFI.wxItemContainer_Clear(obj.ptr, self)
    nothing
end

function delete!(obj::wxItemContainer, self::Ptr{Cvoid}, pos::Integer)
    KwxFFI.wxItemContainer_Delete(obj.ptr, self, Cuint(pos))
    nothing
end

function (obj::wxItemContainer, self::Ptr{Cvoid})
    return KwxFFI.wxItemContainer_IsSorted(obj.ptr, self) != 0
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, n::Integer, clientData::Ptr{Cvoid})
    KwxFFI.wxItemContainer_SetClientData(obj.ptr, self, Cuint(n), clientData)
    nothing
end

function (obj::wxItemContainer, self::Ptr{Cvoid}, n::Integer)
    return KwxFFI.wxItemContainer_GetClientData(obj.ptr, self, Cuint(n))
end

function (obj::wxItemContainer, self::Ptr{Cvoid})
    return KwxFFI.wxItemContainer_HasClientData(obj.ptr, self) != 0
end

