# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxJoystick <: wxObject
    ptr::Ptr{Cvoid}
end

function wxJoystick(joystick::Integer)
    ptr = KwxFFI.wxJoystick_Create(Cint(joystick))
    ptr == C_NULL && error("Failed to create wxJoystick")
    obj = wxJoystick(ptr)
    return obj
end

function delete!(obj::wxJoystick)
    KwxFFI.wxJoystick_Delete(obj.ptr)
    nothing
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetButtonState(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetManufacturerId(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetMaxAxes(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetMaxButtons(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetMovementThreshold(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetNumberAxes(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetNumberButtons(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetNumberJoysticks(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetPOVCTSPosition(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetPOVPosition(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetPollingMax(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetPollingMin(obj.ptr))
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_GetPosition(obj.ptr)
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetProductId(obj.ptr))
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_GetProductName(obj.ptr)
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetRudderMax(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetRudderMin(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetRudderPosition(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetUMax(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetUMin(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetUPosition(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetVMax(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetVMin(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetVPosition(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetXMax(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetXMin(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetYMax(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetYMin(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetZMax(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetZMin(obj.ptr))
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_GetZPosition(obj.ptr))
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_HasPOV(obj.ptr) != 0
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_HasPOV4Dir(obj.ptr) != 0
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_HasPOVCTS(obj.ptr) != 0
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_HasRudder(obj.ptr) != 0
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_HasU(obj.ptr) != 0
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_HasV(obj.ptr) != 0
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_HasZ(obj.ptr) != 0
end

function (obj::wxJoystick)
    return KwxFFI.wxJoystick_IsOk(obj.ptr) != 0
end

function (obj::wxJoystick)
    return Int(KwxFFI.wxJoystick_ReleaseCapture(obj.ptr))
end

function (obj::wxJoystick, win::Ptr{Cvoid}, pollingFreq::Integer)
    return Int(KwxFFI.wxJoystick_SetCapture(obj.ptr, win, Cint(pollingFreq)))
end

function (obj::wxJoystick, threshold::Integer)
    KwxFFI.wxJoystick_SetMovementThreshold(obj.ptr, Cint(threshold))
    nothing
end

