# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxLayoutAlgorithm <: wxObject
    ptr::Ptr{Cvoid}
end

function wxLayoutAlgorithm()
    ptr = KwxFFI.wxLayoutAlgorithm_Create()
    ptr == C_NULL && error("Failed to create wxLayoutAlgorithm")
    obj = wxLayoutAlgorithm(ptr)
    return obj
end

function delete!(obj::wxLayoutAlgorithm)
    KwxFFI.wxLayoutAlgorithm_Delete(obj.ptr)
    nothing
end

function (obj::wxLayoutAlgorithm, frame::Ptr{Cvoid}, mainWindow::Ptr{Cvoid})
    return KwxFFI.wxLayoutAlgorithm_LayoutFrame(obj.ptr, frame, mainWindow) != 0
end

function (obj::wxLayoutAlgorithm, frame::Ptr{Cvoid}, x::Integer, y::Integer, width::Integer, height::Integer, use::Integer)
    return KwxFFI.wxLayoutAlgorithm_LayoutMDIFrame(obj.ptr, frame, Cint(x), Cint(y), Cint(width), Cint(height), Cint(use)) != 0
end

function (obj::wxLayoutAlgorithm, frame::Ptr{Cvoid}, mainWindow::Ptr{Cvoid})
    return KwxFFI.wxLayoutAlgorithm_LayoutWindow(obj.ptr, frame, mainWindow) != 0
end

