# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxLEDNumberCtrl <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxLEDNumberCtrl(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxLEDNumberCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxLEDNumberCtrl")
    obj = wxLEDNumberCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxLEDNumberCtrl)
    return Int(KwxFFI.wxLEDNumberCtrl_GetAlignment(obj.ptr))
end

function (obj::wxLEDNumberCtrl)
    return Int(KwxFFI.wxLEDNumberCtrl_GetDrawFaded(obj.ptr))
end

function (obj::wxLEDNumberCtrl, ref::Ptr{Cvoid})
    return Int(KwxFFI.wxLEDNumberCtrl_GetValue(obj.ptr, ref))
end

function (obj::wxLEDNumberCtrl, Alignment::Integer, Redraw::Integer)
    KwxFFI.wxLEDNumberCtrl_SetAlignment(obj.ptr, Cint(Alignment), Cint(Redraw))
    nothing
end

function (obj::wxLEDNumberCtrl, DrawFaded::Integer, Redraw::Integer)
    KwxFFI.wxLEDNumberCtrl_SetDrawFaded(obj.ptr, Cint(DrawFaded), Cint(Redraw))
    nothing
end

function (obj::wxLEDNumberCtrl, Value::Ptr{Cvoid}, Redraw::Integer)
    KwxFFI.wxLEDNumberCtrl_SetValue(obj.ptr, Value, Cint(Redraw))
    nothing
end

