# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxListBox <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxListBox(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, n::Integer, str::Ptr{Cvoid}, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxListBox_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(n), str, Cint(style))
    ptr == C_NULL && error("Failed to create wxListBox")
    obj = wxListBox(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxListBox, item::String)
    item_ws = wxString(item)
    KwxFFI.wxListBox_Append(obj.ptr, item_ws.ptr)
    delete!(item_ws)
    nothing
end

function (obj::wxListBox, item::String, data::Ptr{Cvoid})
    item_ws = wxString(item)
    KwxFFI.wxListBox_AppendData(obj.ptr, item_ws.ptr, data)
    delete!(item_ws)
    nothing
end

function (obj::wxListBox)
    KwxFFI.wxListBox_Clear(obj.ptr)
    nothing
end

function delete!(obj::wxListBox, index::Integer)
    KwxFFI.wxListBox_Delete(obj.ptr, Cint(index))
    nothing
end

function (obj::wxListBox, str::String)
    str_ws = wxString(str)
    _result = Int(KwxFFI.wxListBox_FindString(obj.ptr, str_ws.ptr))
    delete!(str_ws)
    return _result
end

function (obj::wxListBox, index::Integer)
    return KwxFFI.wxListBox_GetClientData(obj.ptr, Cint(index))
end

function (obj::wxListBox)
    return Int(KwxFFI.wxListBox_GetCount(obj.ptr))
end

function (obj::wxListBox)
    return Int(KwxFFI.wxListBox_GetSelection(obj.ptr))
end

function (obj::wxListBox, aSelections::Ptr{Cvoid}, allocated::Integer)
    return Int(KwxFFI.wxListBox_GetSelections(obj.ptr, aSelections, Cint(allocated)))
end

function (obj::wxListBox, index::Integer)
    return KwxFFI.wxListBox_GetString(obj.ptr, Cint(index))
end

function (obj::wxListBox, items::Ptr{Cvoid}, pos::Integer, count::Integer)
    KwxFFI.wxListBox_InsertItems(obj.ptr, items, Cint(pos), Cint(count))
    nothing
end

function (obj::wxListBox, index::Integer)
    return KwxFFI.wxListBox_IsSelected(obj.ptr, Cint(index)) != 0
end

function (obj::wxListBox, index::Integer, clientData::Ptr{Cvoid})
    KwxFFI.wxListBox_SetClientData(obj.ptr, Cint(index), clientData)
    nothing
end

function (obj::wxListBox, index::Integer)
    KwxFFI.wxListBox_SetFirstItem(obj.ptr, Cint(index))
    nothing
end

function (obj::wxListBox, index::Integer, select::Bool)
    KwxFFI.wxListBox_SetSelection(obj.ptr, Cint(index), Cint(select))
    nothing
end

function (obj::wxListBox, index::Integer, str::String)
    str_ws = wxString(str)
    KwxFFI.wxListBox_SetString(obj.ptr, Cint(index), str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxListBox, str::String, sel::Bool)
    str_ws = wxString(str)
    KwxFFI.wxListBox_SetStringSelection(obj.ptr, str_ws.ptr, Cint(sel))
    delete!(str_ws)
    nothing
end

function (obj::wxListBox, index::Integer)
    KwxFFI.wxListBox_EnsureVisible(obj.ptr, Cint(index))
    nothing
end

function (obj::wxListBox, x::Integer, y::Integer)
    return Int(KwxFFI.wxListBox_HitTest(obj.ptr, Cint(x), Cint(y)))
end

function (obj::wxListBox)
    return Int(KwxFFI.wxListBox_GetTopItem(obj.ptr))
end

function (obj::wxListBox)
    return Int(KwxFFI.wxListBox_GetCountPerPage(obj.ptr))
end

