# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxListEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxListEvent)
    return KwxFFI.wxListEvent_Cancelled(obj.ptr) != 0
end

function (obj::wxListEvent)
    return Int(KwxFFI.wxListEvent_GetCode(obj.ptr))
end

function (obj::wxListEvent)
    return Int(KwxFFI.wxListEvent_GetColumn(obj.ptr))
end

function (obj::wxListEvent)
    return Int(KwxFFI.wxListEvent_GetData(obj.ptr))
end

function (obj::wxListEvent)
    return Int(KwxFFI.wxListEvent_GetImage(obj.ptr))
end

function (obj::wxListEvent)
    return Int(KwxFFI.wxListEvent_GetIndex(obj.ptr))
end

function (obj::wxListEvent, ref::Ptr{Cvoid})
    KwxFFI.wxListEvent_GetItem(obj.ptr, ref)
    nothing
end

function (obj::wxListEvent)
    return KwxFFI.wxListEvent_GetLabel(obj.ptr)
end

function (obj::wxListEvent)
    return Int(KwxFFI.wxListEvent_GetMask(obj.ptr))
end

function (obj::wxListEvent)
    return Int(KwxFFI.wxListEvent_GetOldItem(obj.ptr))
end

function (obj::wxListEvent)
    return KwxFFI.wxListEvent_GetText(obj.ptr)
end

