# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxListView <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxListView(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxListView_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxListView")
    obj = wxListView(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxListView, col::Integer)
    KwxFFI.wxListView_ClearColumnImage(obj.ptr, Cint(col))
    nothing
end

function (obj::wxListView, index::Integer)
    KwxFFI.wxListView_Focus(obj.ptr, Clong(index))
    nothing
end

function (obj::wxListView)
    return Int(KwxFFI.wxListView_GetFirstSelected(obj.ptr))
end

function (obj::wxListView)
    return Int(KwxFFI.wxListView_GetFocusedItem(obj.ptr))
end

function (obj::wxListView, item::Integer)
    return Int(KwxFFI.wxListView_GetNextSelected(obj.ptr, Clong(item)))
end

function (obj::wxListView, index::Integer)
    return KwxFFI.wxListView_IsSelected(obj.ptr, Clong(index)) != 0
end

function (obj::wxListView, index::Integer, select::Bool)
    KwxFFI.wxListView_Select(obj.ptr, Clong(index), Cint(select))
    nothing
end

function (obj::wxListView, col::Integer, image::Integer)
    KwxFFI.wxListView_SetColumnImage(obj.ptr, Cint(col), Cint(image))
    nothing
end

