# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxListCtrl <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxListCtrl(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxListCtrl_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxListCtrl")
    obj = wxListCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxListCtrl, flag::Integer)
    return KwxFFI.wxListCtrl_Arrange(obj.ptr, Cint(flag)) != 0
end

function (obj::wxListCtrl)
    KwxFFI.wxListCtrl_ClearAll(obj.ptr)
    nothing
end

function (obj::wxListCtrl)
    return KwxFFI.wxListCtrl_DeleteAllColumns(obj.ptr) != 0
end

function (obj::wxListCtrl)
    return KwxFFI.wxListCtrl_DeleteAllItems(obj.ptr) != 0
end

function (obj::wxListCtrl, col::Integer)
    return KwxFFI.wxListCtrl_DeleteColumn(obj.ptr, Cint(col)) != 0
end

function (obj::wxListCtrl, item::Integer)
    return KwxFFI.wxListCtrl_DeleteItem(obj.ptr, Cint(item)) != 0
end

function (obj::wxListCtrl, item::Integer)
    KwxFFI.wxListCtrl_EditLabel(obj.ptr, Cint(item))
    nothing
end

function (obj::wxListCtrl, cancel::Integer)
    return KwxFFI.wxListCtrl_EndEditLabel(obj.ptr, Cint(cancel)) != 0
end

function (obj::wxListCtrl, item::Integer)
    return KwxFFI.wxListCtrl_EnsureVisible(obj.ptr, Cint(item)) != 0
end

function (obj::wxListCtrl, start::Integer, str::String, partial::Bool)
    str_ws = wxString(str)
    _result = Int(KwxFFI.wxListCtrl_FindItem(obj.ptr, Cint(start), str_ws.ptr, Cint(partial)))
    delete!(str_ws)
    return _result
end

function (obj::wxListCtrl, start::Integer, data::Integer)
    return Int(KwxFFI.wxListCtrl_FindItemByData(obj.ptr, Cint(start), Cint(data)))
end

function (obj::wxListCtrl, start::Integer, x::Integer, y::Integer, direction::Integer)
    return Int(KwxFFI.wxListCtrl_FindItemByPosition(obj.ptr, Cint(start), Cint(x), Cint(y), Cint(direction)))
end

function (obj::wxListCtrl, col::Integer, item::Ptr{Cvoid})
    return KwxFFI.wxListCtrl_GetColumn(obj.ptr, Cint(col), item) != 0
end

function (obj::wxListCtrl)
    return Int(KwxFFI.wxListCtrl_GetColumnCount(obj.ptr))
end

function (obj::wxListCtrl, col::Integer)
    return Int(KwxFFI.wxListCtrl_GetColumnWidth(obj.ptr, Cint(col)))
end

function (obj::wxListCtrl)
    return Int(KwxFFI.wxListCtrl_GetCountPerPage(obj.ptr))
end

function (obj::wxListCtrl)
    return KwxFFI.wxListCtrl_GetEditControl(obj.ptr)
end

function (obj::wxListCtrl, which::Integer)
    return KwxFFI.wxListCtrl_GetImageList(obj.ptr, Cint(which))
end

function (obj::wxListCtrl, info::Ptr{Cvoid})
    return KwxFFI.wxListCtrl_GetItem(obj.ptr, info) != 0
end

function (obj::wxListCtrl)
    return Int(KwxFFI.wxListCtrl_GetItemCount(obj.ptr))
end

function (obj::wxListCtrl, item::Integer)
    return Int(KwxFFI.wxListCtrl_GetItemData(obj.ptr, Cint(item)))
end

function (obj::wxListCtrl, item::Integer)
    return KwxFFI.wxListCtrl_GetItemFont(obj.ptr, Clong(item))
end

function (obj::wxListCtrl, item::Integer)
    return KwxFFI.wxListCtrl_GetItemPosition(obj.ptr, Cint(item))
end

function (obj::wxListCtrl, item::Integer, code::Integer)
    return KwxFFI.wxListCtrl_GetItemRect(obj.ptr, Cint(item), Cint(code))
end

function (obj::wxListCtrl, isSmall::Bool)
    return KwxFFI.wxListCtrl_GetItemSpacing(obj.ptr, Cint(isSmall))
end

function (obj::wxListCtrl, item::Integer, stateMask::Integer)
    return Int(KwxFFI.wxListCtrl_GetItemState(obj.ptr, Cint(item), Cint(stateMask)))
end

function (obj::wxListCtrl, item::Integer, col::Integer)
    return KwxFFI.wxListCtrl_GetItemText(obj.ptr, Cint(item), Cint(col))
end

function (obj::wxListCtrl, item::Integer, geometry::Integer, state::Integer)
    return Int(KwxFFI.wxListCtrl_GetNextItem(obj.ptr, Cint(item), Cint(geometry), Cint(state)))
end

function (obj::wxListCtrl)
    return Int(KwxFFI.wxListCtrl_GetSelectedItemCount(obj.ptr))
end

function (obj::wxListCtrl, ref::Ptr{Cvoid})
    KwxFFI.wxListCtrl_GetTextColour(obj.ptr, ref)
    nothing
end

function (obj::wxListCtrl)
    return Int(KwxFFI.wxListCtrl_GetTopItem(obj.ptr))
end

function (obj::wxListCtrl, x::Integer, y::Integer, flags::Ptr{Cvoid}, pSubItem::Ptr{Cvoid})
    return Int(KwxFFI.wxListCtrl_HitTest(obj.ptr, Cint(x), Cint(y), flags, pSubItem))
end

function (obj::wxListCtrl, col::Integer, heading::String, format::Integer, width::Integer)
    heading_ws = wxString(heading)
    _result = Int(KwxFFI.wxListCtrl_InsertColumn(obj.ptr, Cint(col), heading_ws.ptr, Cint(format), Cint(width)))
    delete!(heading_ws)
    return _result
end

function (obj::wxListCtrl, col::Integer, info::Ptr{Cvoid})
    return Int(KwxFFI.wxListCtrl_InsertColumnFromInfo(obj.ptr, Cint(col), info))
end

function (obj::wxListCtrl, info::Ptr{Cvoid})
    return Int(KwxFFI.wxListCtrl_InsertItem(obj.ptr, info))
end

function (obj::wxListCtrl, index::Integer, label::String)
    label_ws = wxString(label)
    _result = Int(KwxFFI.wxListCtrl_InsertItemWithData(obj.ptr, Cint(index), label_ws.ptr))
    delete!(label_ws)
    return _result
end

function (obj::wxListCtrl, index::Integer, imageIndex::Integer)
    return Int(KwxFFI.wxListCtrl_InsertItemWithImage(obj.ptr, Cint(index), Cint(imageIndex)))
end

function (obj::wxListCtrl, index::Integer, label::String, imageIndex::Integer)
    label_ws = wxString(label)
    _result = Int(KwxFFI.wxListCtrl_InsertItemWithLabel(obj.ptr, Cint(index), label_ws.ptr, Cint(imageIndex)))
    delete!(label_ws)
    return _result
end

function (obj::wxListCtrl)
    return KwxFFI.wxListCtrl_IsVirtual(obj.ptr) != 0
end

function (obj::wxListCtrl, item::Integer)
    KwxFFI.wxListCtrl_RefreshItem(obj.ptr, Clong(item))
    nothing
end

function (obj::wxListCtrl, dx::Integer, dy::Integer)
    return KwxFFI.wxListCtrl_ScrollList(obj.ptr, Cint(dx), Cint(dy)) != 0
end

function (obj::wxListCtrl, col::Ptr{Cvoid})
    KwxFFI.wxListCtrl_SetBackgroundColour(obj.ptr, col)
    nothing
end

function (obj::wxListCtrl, col::Integer, item::Ptr{Cvoid})
    return KwxFFI.wxListCtrl_SetColumn(obj.ptr, Cint(col), item) != 0
end

function (obj::wxListCtrl, col::Integer, width::Integer)
    return KwxFFI.wxListCtrl_SetColumnWidth(obj.ptr, Cint(col), Cint(width)) != 0
end

function (obj::wxListCtrl, col::Ptr{Cvoid})
    return Int(KwxFFI.wxListCtrl_SetForegroundColour(obj.ptr, col))
end

function (obj::wxListCtrl, imageList::Ptr{Cvoid}, which::Integer)
    KwxFFI.wxListCtrl_SetImageList(obj.ptr, imageList, Cint(which))
    nothing
end

function (obj::wxListCtrl, index::Integer, col::Integer, label::String, imageId::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxListCtrl_SetItem(obj.ptr, Cint(index), Cint(col), label_ws.ptr, Cint(imageId)) != 0
    delete!(label_ws)
    return _result
end

function (obj::wxListCtrl, item::Integer, data::Integer)
    return KwxFFI.wxListCtrl_SetItemData(obj.ptr, Cint(item), Cint(data)) != 0
end

function (obj::wxListCtrl, info::Ptr{Cvoid})
    return KwxFFI.wxListCtrl_SetItemFromInfo(obj.ptr, info) != 0
end

function (obj::wxListCtrl, item::Integer, image::Integer, selImage::Integer)
    return KwxFFI.wxListCtrl_SetItemImage(obj.ptr, Cint(item), Cint(image), Cint(selImage)) != 0
end

function (obj::wxListCtrl, item::Integer, x::Integer, y::Integer)
    return KwxFFI.wxListCtrl_SetItemPosition(obj.ptr, Cint(item), Cint(x), Cint(y)) != 0
end

function (obj::wxListCtrl, item::Integer, state::Integer, stateMask::Integer)
    return KwxFFI.wxListCtrl_SetItemState(obj.ptr, Cint(item), Cint(state), Cint(stateMask)) != 0
end

function (obj::wxListCtrl, item::Integer, str::String)
    str_ws = wxString(str)
    KwxFFI.wxListCtrl_SetItemText(obj.ptr, Cint(item), str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxListCtrl, style::Integer, add::Bool)
    KwxFFI.wxListCtrl_SetSingleStyle(obj.ptr, Cint(style), Cint(add))
    nothing
end

function (obj::wxListCtrl, col::Ptr{Cvoid})
    KwxFFI.wxListCtrl_SetTextColour(obj.ptr, col)
    nothing
end

function (obj::wxListCtrl, style::Integer)
    KwxFFI.wxListCtrl_SetWindowStyleFlag(obj.ptr, Cint(style))
    nothing
end

function (obj::wxListCtrl, compareFunc::Ptr{Cvoid}, arg::Ptr{Cvoid})
    return KwxFFI.wxListCtrl_SortItems(obj.ptr, compareFunc, arg) != 0
end

function (obj::wxListCtrl)
    KwxFFI.wxListCtrl_UpdateStyle(obj.ptr)
    nothing
end

function (obj::wxListCtrl, item::Integer, subItem::Integer, x::Ptr{Cvoid}, y::Ptr{Cvoid}, width::Ptr{Cvoid}, height::Ptr{Cvoid}, code::Integer)
    return KwxFFI.wxListCtrl_GetSubItemRect(obj.ptr, Clong(item), Clong(subItem), x, y, width, height, Cint(code)) != 0
end

function (obj::wxListCtrl, x::Ptr{Cvoid}, y::Ptr{Cvoid}, width::Ptr{Cvoid}, height::Ptr{Cvoid})
    KwxFFI.wxListCtrl_GetViewRect(obj.ptr, x, y, width, height)
    nothing
end

function (obj::wxListCtrl)
    return KwxFFI.wxListCtrl_HasCheckBoxes(obj.ptr) != 0
end

function (obj::wxListCtrl, enable::Bool)
    return KwxFFI.wxListCtrl_EnableCheckBoxes(obj.ptr, Cint(enable)) != 0
end

function (obj::wxListCtrl, item::Integer)
    return KwxFFI.wxListCtrl_IsItemChecked(obj.ptr, Clong(item)) != 0
end

function (obj::wxListCtrl, item::Integer, check::Bool)
    KwxFFI.wxListCtrl_CheckItem(obj.ptr, Clong(item), Cint(check))
    nothing
end

function (obj::wxListCtrl, col::Integer, ascending::Bool)
    KwxFFI.wxListCtrl_ShowSortIndicator(obj.ptr, Cint(col), Cint(ascending))
    nothing
end

function (obj::wxListCtrl)
    return Int(KwxFFI.wxListCtrl_GetSortIndicator(obj.ptr))
end

function (obj::wxListCtrl)
    return KwxFFI.wxListCtrl_IsAscendingSortIndicator(obj.ptr) != 0
end

function (obj::wxListCtrl, item::Integer)
    return KwxFFI.wxListCtrl_IsVisible(obj.ptr, Clong(item)) != 0
end

function (obj::wxListCtrl, count::Integer)
    KwxFFI.wxListCtrl_SetItemCount(obj.ptr, Clong(count))
    nothing
end

function (obj::wxListCtrl, attr::Ptr{Cvoid})
    return KwxFFI.wxListCtrl_SetHeaderAttr(obj.ptr, attr) != 0
end

