# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxListbook <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxListbook(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxListbook_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxListbook")
    obj = wxListbook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxListbook, pPage::Ptr{Cvoid}, strText::String, bSelect::Bool, imageId::Integer)
    strText_ws = wxString(strText)
    _result = KwxFFI.wxListbook_AddPage(obj.ptr, pPage, strText_ws.ptr, Cint(bSelect), Cint(imageId)) != 0
    delete!(strText_ws)
    return _result
end

function (obj::wxListbook, bForward::Bool)
    KwxFFI.wxListbook_AdvanceSelection(obj.ptr, Cint(bForward))
    nothing
end

function (obj::wxListbook)
    return KwxFFI.wxListbook_DeleteAllPages(obj.ptr) != 0
end

function (obj::wxListbook, nPage::Integer)
    return KwxFFI.wxListbook_DeletePage(obj.ptr, Cint(nPage)) != 0
end

function (obj::wxListbook)
    return KwxFFI.wxListbook_GetImageList(obj.ptr)
end

function (obj::wxListbook)
    return KwxFFI.wxListbook_GetListView(obj.ptr)
end

function (obj::wxListbook, nPage::Integer)
    return KwxFFI.wxListbook_GetPage(obj.ptr, Cint(nPage))
end

function (obj::wxListbook)
    return Int(KwxFFI.wxListbook_GetPageCount(obj.ptr))
end

function (obj::wxListbook, nPage::Integer)
    return Int(KwxFFI.wxListbook_GetPageImage(obj.ptr, Cint(nPage)))
end

function (obj::wxListbook, nPage::Integer)
    return KwxFFI.wxListbook_GetPageText(obj.ptr, Cint(nPage))
end

function (obj::wxListbook)
    return Int(KwxFFI.wxListbook_GetSelection(obj.ptr))
end

function (obj::wxListbook, x::Integer, y::Integer, flags::Ptr{Cvoid})
    return Int(KwxFFI.wxListbook_HitTest(obj.ptr, Cint(x), Cint(y), flags))
end

function (obj::wxListbook, nPage::Integer, pPage::Ptr{Cvoid}, strText::String, bSelect::Bool, imageId::Integer)
    strText_ws = wxString(strText)
    _result = KwxFFI.wxListbook_InsertPage(obj.ptr, Cint(nPage), pPage, strText_ws.ptr, Cint(bSelect), Cint(imageId)) != 0
    delete!(strText_ws)
    return _result
end

function (obj::wxListbook, nPage::Integer)
    return KwxFFI.wxListbook_RemovePage(obj.ptr, Cint(nPage)) != 0
end

function (obj::wxListbook, imageList::Ptr{Cvoid})
    KwxFFI.wxListbook_SetImageList(obj.ptr, imageList)
    nothing
end

function (obj::wxListbook, nPage::Integer, nImage::Integer)
    return KwxFFI.wxListbook_SetPageImage(obj.ptr, Cint(nPage), Cint(nImage)) != 0
end

function (obj::wxListbook, nPage::Integer, strText::String)
    strText_ws = wxString(strText)
    _result = KwxFFI.wxListbook_SetPageText(obj.ptr, Cint(nPage), strText_ws.ptr) != 0
    delete!(strText_ws)
    return _result
end

function (obj::wxListbook, nPage::Integer)
    return Int(KwxFFI.wxListbook_SetSelection(obj.ptr, Cint(nPage)))
end

function (obj::wxListbook)
    return Int(KwxFFI.expLB_DEFAULT(obj.ptr))
end

function (obj::wxListbook)
    return Int(KwxFFI.expLB_TOP(obj.ptr))
end

function (obj::wxListbook)
    return Int(KwxFFI.expLB_BOTTOM(obj.ptr))
end

function (obj::wxListbook)
    return Int(KwxFFI.expLB_LEFT(obj.ptr))
end

function (obj::wxListbook)
    return Int(KwxFFI.expLB_RIGHT(obj.ptr))
end

