# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxLogChain <: wxObject
    ptr::Ptr{Cvoid}
end

function wxLogChain(logger::Ptr{Cvoid})
    ptr = KwxFFI.wxLogChain_Create(logger)
    ptr == C_NULL && error("Failed to create wxLogChain")
    obj = wxLogChain(ptr)
    return obj
end

function delete!(obj::wxLogChain)
    KwxFFI.wxLogChain_Delete(obj.ptr)
    nothing
end

function (obj::wxLogChain)
    return KwxFFI.wxLogChain_GetOldLog(obj.ptr)
end

function (obj::wxLogChain)
    return KwxFFI.wxLogChain_IsPassingMessages(obj.ptr) != 0
end

function (obj::wxLogChain, bDoPass::Bool)
    KwxFFI.wxLogChain_PassMessages(obj.ptr, Cint(bDoPass))
    nothing
end

function (obj::wxLogChain, logger::Ptr{Cvoid})
    KwxFFI.wxLogChain_SetLog(obj.ptr, logger)
    nothing
end

