# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxLocale <: wxObject
    ptr::Ptr{Cvoid}
end

function wxLocale(name::Integer, flags::Integer)
    ptr = KwxFFI.wxLocale_Create(Cint(name), Cint(flags))
    ptr == C_NULL && error("Failed to create wxLocale")
    obj = wxLocale(ptr)
    return obj
end

function (obj::wxLocale, szDomain::Ptr{Cvoid}, msgIdLanguage::Integer)
    return Int(KwxFFI.wxLocale_AddCatalog(obj.ptr, szDomain, Cint(msgIdLanguage)))
end

function (obj::wxLocale, prefix::Ptr{Cvoid})
    KwxFFI.wxLocale_AddCatalogLookupPathPrefix(obj.ptr, prefix)
    nothing
end

function delete!(obj::wxLocale)
    KwxFFI.wxLocale_Delete(obj.ptr)
    nothing
end

function (obj::wxLocale)
    return KwxFFI.wxLocale_GetLocale(obj.ptr)
end

function (obj::wxLocale)
    return KwxFFI.wxLocale_GetName(obj.ptr)
end

function (obj::wxLocale, szOrigString::Ptr{Cvoid}, szDomain::Ptr{Cvoid})
    return _wx_get_string(KwxFFI.wxLocale_GetString(obj.ptr, szOrigString, szDomain))
end

function (obj::wxLocale, szDomain::Ptr{Cvoid})
    return KwxFFI.wxLocale_IsLoaded(obj.ptr, szDomain) != 0
end

function (obj::wxLocale)
    return KwxFFI.wxLocale_IsOk(obj.ptr) != 0
end

