# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMDIChildFrame <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxMDIChildFrame(parent::Union{wxWindow, Nothing}, id::Integer, text::String, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    text_ws = wxString(text)
    ptr = KwxFFI.wxMDIChildFrame_Create(parent_ptr, Cint(id), text_ws.ptr, Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxMDIChildFrame")
    obj = wxMDIChildFrame(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxMDIChildFrame)
    KwxFFI.wxMDIChildFrame_Activate(obj.ptr)
    nothing
end

function (obj::wxMDIChildFrame)
    return KwxFFI.wxMDIChildFrame_GetMDIParent(obj.ptr)
end

