# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMetafileDC <: wxObject
    ptr::Ptr{Cvoid}
end

function wxMetafileDC(filePath::String)
    filePath_ws = wxString(filePath)
    ptr = KwxFFI.wxMetafileDC_Create(filePath_ws.ptr)
    delete!(filePath_ws)
    ptr == C_NULL && error("Failed to create wxMetafileDC")
    obj = wxMetafileDC(ptr)
    return obj
end

function (obj::wxMetafileDC)
    return KwxFFI.wxMetafileDC_Close(obj.ptr)
end

function delete!(obj::wxMetafileDC)
    KwxFFI.wxMetafileDC_Delete(obj.ptr)
    nothing
end

