# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMenuBar <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function wxMenuBar(style::Integer)
    ptr = KwxFFI.wxMenuBar_Create(Cint(style))
    ptr == C_NULL && error("Failed to create wxMenuBar")
    obj = wxMenuBar(ptr)
    return obj
end

function (obj::wxMenuBar, menu::Ptr{Cvoid}, title::String)
    title_ws = wxString(title)
    _result = Int(KwxFFI.wxMenuBar_Append(obj.ptr, menu, title_ws.ptr))
    delete!(title_ws)
    return _result
end

function (obj::wxMenuBar, id::Integer, check::Bool)
    KwxFFI.wxMenuBar_Check(obj.ptr, Cint(id), Cint(check))
    nothing
end

function (obj::wxMenuBar)
    KwxFFI.wxMenuBar_DeletePointer(obj.ptr)
    nothing
end

function (obj::wxMenuBar, enable::Bool)
    return Int(KwxFFI.wxMenuBar_Enable(obj.ptr, Cint(enable)))
end

function (obj::wxMenuBar, id::Integer, enable::Bool)
    KwxFFI.wxMenuBar_EnableItem(obj.ptr, Cint(id), Cint(enable))
    nothing
end

function (obj::wxMenuBar, pos::Integer, enable::Bool)
    KwxFFI.wxMenuBar_EnableTop(obj.ptr, Cint(pos), Cint(enable))
    nothing
end

function (obj::wxMenuBar, id::Integer)
    return KwxFFI.wxMenuBar_FindItem(obj.ptr, Cint(id))
end

function (obj::wxMenuBar, title::String)
    title_ws = wxString(title)
    _result = Int(KwxFFI.wxMenuBar_FindMenu(obj.ptr, title_ws.ptr))
    delete!(title_ws)
    return _result
end

function (obj::wxMenuBar, menuString::String, itemString::String)
    menuString_ws = wxString(menuString)
    itemString_ws = wxString(itemString)
    _result = Int(KwxFFI.wxMenuBar_FindMenuItem(obj.ptr, menuString_ws.ptr, itemString_ws.ptr))
    delete!(menuString_ws)
    delete!(itemString_ws)
    return _result
end

function (obj::wxMenuBar, id::Integer)
    return KwxFFI.wxMenuBar_GetHelpString(obj.ptr, Cint(id))
end

function (obj::wxMenuBar, id::Integer)
    return KwxFFI.wxMenuBar_GetLabel(obj.ptr, Cint(id))
end

function (obj::wxMenuBar, pos::Integer)
    return KwxFFI.wxMenuBar_GetMenuLabel(obj.ptr, Cint(pos))
end

function (obj::wxMenuBar, pos::Integer)
    return KwxFFI.wxMenuBar_GetMenu(obj.ptr, Cint(pos))
end

function (obj::wxMenuBar)
    return Int(KwxFFI.wxMenuBar_GetMenuCount(obj.ptr))
end

function (obj::wxMenuBar, pos::Integer, menu::Ptr{Cvoid}, title::String)
    title_ws = wxString(title)
    _result = Int(KwxFFI.wxMenuBar_Insert(obj.ptr, Cint(pos), menu, title_ws.ptr))
    delete!(title_ws)
    return _result
end

function (obj::wxMenuBar, id::Integer)
    return KwxFFI.wxMenuBar_IsChecked(obj.ptr, Cint(id)) != 0
end

function (obj::wxMenuBar, id::Integer)
    return KwxFFI.wxMenuBar_IsEnabled(obj.ptr, Cint(id)) != 0
end

function (obj::wxMenuBar, pos::Integer)
    return KwxFFI.wxMenuBar_Remove(obj.ptr, Cint(pos))
end

function (obj::wxMenuBar, pos::Integer, menu::Ptr{Cvoid}, title::String)
    title_ws = wxString(title)
    _result = KwxFFI.wxMenuBar_Replace(obj.ptr, Cint(pos), menu, title_ws.ptr)
    delete!(title_ws)
    return _result
end

function (obj::wxMenuBar, id::Integer, helpString::String)
    helpString_ws = wxString(helpString)
    KwxFFI.wxMenuBar_SetHelpString(obj.ptr, Cint(id), helpString_ws.ptr)
    delete!(helpString_ws)
    nothing
end

function (obj::wxMenuBar, id::Integer, label::String)
    label_ws = wxString(label)
    KwxFFI.wxMenuBar_SetItemLabel(obj.ptr, Cint(id), label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxMenuBar, str::String)
    str_ws = wxString(str)
    KwxFFI.wxMenuBar_SetLabel(obj.ptr, str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxMenuBar, pos::Integer, label::String)
    label_ws = wxString(label)
    KwxFFI.wxMenuBar_SetMenuLabel(obj.ptr, Cint(pos), label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxMenuBar, pos::Integer)
    return KwxFFI.wxMenuBar_IsEnabledTop(obj.ptr, Cint(pos)) != 0
end

function (obj::wxMenuBar, pos::Integer)
    return KwxFFI.wxMenuBar_GetMenuLabelText(obj.ptr, Cint(pos))
end

function (obj::wxMenuBar)
    KwxFFI.wxMenuBar_UpdateMenus(obj.ptr)
    nothing
end

