# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMenuItem <: wxObject
    ptr::Ptr{Cvoid}
end

function wxMenuItem()
    ptr = KwxFFI.wxMenuItem_Create()
    ptr == C_NULL && error("Failed to create wxMenuItem")
    obj = wxMenuItem(ptr)
    return obj
end

function (obj::wxMenuItem, check::Bool)
    KwxFFI.wxMenuItem_Check(obj.ptr, Cint(check))
    nothing
end

function delete!(obj::wxMenuItem)
    KwxFFI.wxMenuItem_Delete(obj.ptr)
    nothing
end

function (obj::wxMenuItem, enable::Bool)
    KwxFFI.wxMenuItem_Enable(obj.ptr, Cint(enable))
    nothing
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_GetHelp(obj.ptr)
end

function (obj::wxMenuItem)
    return Int(KwxFFI.wxMenuItem_GetId(obj.ptr))
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_GetItemLabelText(obj.ptr)
end

function (obj::wxMenuItem, text::Ptr{Cvoid})
    return KwxFFI.wxMenuItem_GetLabelText(obj.ptr, text)
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_GetMenu(obj.ptr)
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_GetSubMenu(obj.ptr)
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_GetItemLabel(obj.ptr)
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_IsCheckable(obj.ptr) != 0
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_IsChecked(obj.ptr) != 0
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_IsEnabled(obj.ptr) != 0
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_IsSeparator(obj.ptr) != 0
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_IsSubMenu(obj.ptr) != 0
end

function (obj::wxMenuItem, checkable::Bool)
    KwxFFI.wxMenuItem_SetCheckable(obj.ptr, Cint(checkable))
    nothing
end

function (obj::wxMenuItem, str::String)
    str_ws = wxString(str)
    KwxFFI.wxMenuItem_SetHelp(obj.ptr, str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxMenuItem, id::Integer)
    KwxFFI.wxMenuItem_SetId(obj.ptr, Cint(id))
    nothing
end

function (obj::wxMenuItem, menu::Ptr{Cvoid})
    KwxFFI.wxMenuItem_SetSubMenu(obj.ptr, menu)
    nothing
end

function (obj::wxMenuItem, str::String)
    str_ws = wxString(str)
    KwxFFI.wxMenuItem_SetItemLabel(obj.ptr, str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxMenuItem)
    return Int(KwxFFI.wxMenuItem_GetKind(obj.ptr))
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_IsCheck(obj.ptr) != 0
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_IsRadio(obj.ptr) != 0
end

function (obj::wxMenuItem)
    KwxFFI.wxMenuItem_Toggle(obj.ptr)
    nothing
end

function (obj::wxMenuItem, bmp::Ptr{Cvoid})
    KwxFFI.wxMenuItem_SetBitmap(obj.ptr, bmp)
    nothing
end

function (obj::wxMenuItem)
    return KwxFFI.wxMenuItem_GetBitmap(obj.ptr)
end

