# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMemoryDC <: wxObject
    ptr::Ptr{Cvoid}
end

function wxMemoryDC()
    ptr = KwxFFI.wxMemoryDC_Create()
    ptr == C_NULL && error("Failed to create wxMemoryDC")
    obj = wxMemoryDC(ptr)
    return obj
end

function wxMemoryDC(dc::Ptr{Cvoid})
    ptr = KwxFFI.wxMemoryDC_CreateCompatible(dc)
    ptr == C_NULL && error("Failed to create wxMemoryDC")
    obj = wxMemoryDC(ptr)
    return obj
end

function wxMemoryDC(bitmap::Ptr{Cvoid})
    ptr = KwxFFI.wxMemoryDC_CreateWithBitmap(bitmap)
    ptr == C_NULL && error("Failed to create wxMemoryDC")
    obj = wxMemoryDC(ptr)
    return obj
end

function delete!(obj::wxMemoryDC)
    KwxFFI.wxMemoryDC_Delete(obj.ptr)
    nothing
end

function (obj::wxMemoryDC, bitmap::Ptr{Cvoid})
    KwxFFI.wxMemoryDC_SelectObject(obj.ptr, bitmap)
    nothing
end

