# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMenuEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxMenuEvent, arg::Ptr{Cvoid})
    KwxFFI.wxMenuEvent_CopyObject(obj.ptr, arg)
    nothing
end

function (obj::wxMenuEvent)
    return Int(KwxFFI.wxMenuEvent_GetMenuId(obj.ptr))
end

