# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMiniFrame <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxMiniFrame(parent::Union{wxWindow, Nothing}, id::Integer, text::String, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    text_ws = wxString(text)
    ptr = KwxFFI.wxMiniFrame_Create(parent_ptr, Cint(id), text_ws.ptr, Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxMiniFrame")
    obj = wxMiniFrame(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

