# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMimeTypesManager <: wxObject
    ptr::Ptr{Cvoid}
end

function wxMimeTypesManager()
    ptr = KwxFFI.wxMimeTypesManager_Create()
    ptr == C_NULL && error("Failed to create wxMimeTypesManager")
    obj = wxMimeTypesManager(ptr)
    return obj
end

function (obj::wxMimeTypesManager, types::Ptr{Cvoid})
    KwxFFI.wxMimeTypesManager_AddFallbacks(obj.ptr, types)
    nothing
end

function (obj::wxMimeTypesManager, list::Ptr{Cvoid})
    return Int(KwxFFI.wxMimeTypesManager_EnumAllFileTypes(obj.ptr, list))
end

function (obj::wxMimeTypesManager, extension::String)
    extension_ws = wxString(extension)
    _result = KwxFFI.wxMimeTypesManager_GetFileTypeFromExtension(obj.ptr, extension_ws.ptr)
    delete!(extension_ws)
    return _result
end

function (obj::wxMimeTypesManager, name::String)
    name_ws = wxString(name)
    _result = KwxFFI.wxMimeTypesManager_GetFileTypeFromMimeType(obj.ptr, name_ws.ptr)
    delete!(name_ws)
    return _result
end

function (obj::wxMimeTypesManager, type_::String, wildcard::String)
    type__ws = wxString(type_)
    wildcard_ws = wxString(wildcard)
    _result = KwxFFI.wxMimeTypesManager_IsOfType(obj.ptr, type__ws.ptr, wildcard_ws.ptr) != 0
    delete!(type__ws)
    delete!(wildcard_ws)
    return _result
end

