# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMouseEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_AltDown(obj.ptr) != 0
end

function (obj::wxMouseEvent, but::Integer)
    return KwxFFI.wxMouseEvent_Button(obj.ptr, Cint(but)) != 0
end

function (obj::wxMouseEvent, but::Integer)
    return KwxFFI.wxMouseEvent_ButtonDClick(obj.ptr, Cint(but)) != 0
end

function (obj::wxMouseEvent, but::Integer)
    return KwxFFI.wxMouseEvent_ButtonDown(obj.ptr, Cint(but)) != 0
end

function (obj::wxMouseEvent, but::Integer)
    return KwxFFI.wxMouseEvent_ButtonIsDown(obj.ptr, Cint(but)) != 0
end

function (obj::wxMouseEvent, but::Integer)
    return KwxFFI.wxMouseEvent_ButtonUp(obj.ptr, Cint(but)) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_ControlDown(obj.ptr) != 0
end

function (obj::wxMouseEvent, object_dest::Ptr{Cvoid})
    KwxFFI.wxMouseEvent_CopyObject(obj.ptr, object_dest)
    nothing
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_Dragging(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_Entering(obj.ptr) != 0
end

function (obj::wxMouseEvent, dc::Ptr{Cvoid})
    return KwxFFI.wxMouseEvent_GetLogicalPosition(obj.ptr, dc)
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_GetPosition(obj.ptr)
end

function (obj::wxMouseEvent)
    return Int(KwxFFI.wxMouseEvent_GetX(obj.ptr))
end

function (obj::wxMouseEvent)
    return Int(KwxFFI.wxMouseEvent_GetY(obj.ptr))
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_IsButton(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_Leaving(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_LeftDClick(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_LeftDown(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_LeftIsDown(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_LeftUp(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_MetaDown(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_MiddleDClick(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_MiddleDown(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_MiddleIsDown(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_MiddleUp(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_Moving(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_RightDClick(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_RightDown(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_RightIsDown(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_RightUp(obj.ptr) != 0
end

function (obj::wxMouseEvent)
    return KwxFFI.wxMouseEvent_ShiftDown(obj.ptr) != 0
end

