# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMultiCellSizer <: wxSizer
    ptr::Ptr{Cvoid}
end

function wxMultiCellSizer(rows::Integer, cols::Integer)
    ptr = KwxFFI.wxMultiCellSizer_Create(Cint(rows), Cint(cols))
    ptr == C_NULL && error("Failed to create wxMultiCellSizer")
    obj = wxMultiCellSizer(ptr)
    return obj
end

function (obj::wxMultiCellSizer, arg::Integer)
    KwxFFI.wxMultiCellSizer_CalcMin(obj.ptr, Cint(arg))
    nothing
end

function delete!(obj::wxMultiCellSizer)
    KwxFFI.wxMultiCellSizer_Delete(obj.ptr)
    nothing
end

function (obj::wxMultiCellSizer, win::Ptr{Cvoid})
    return Int(KwxFFI.wxMultiCellSizer_EnableGridLines(obj.ptr, win))
end

function (obj::wxMultiCellSizer)
    KwxFFI.wxMultiCellSizer_RecalcSizes(obj.ptr)
    nothing
end

function (obj::wxMultiCellSizer, column::Integer, colSize::Integer, expandable::Integer)
    return Int(KwxFFI.wxMultiCellSizer_SetColumnWidth(obj.ptr, Cint(column), Cint(colSize), Cint(expandable)))
end

function (obj::wxMultiCellSizer, width::Integer, height::Integer)
    return Int(KwxFFI.wxMultiCellSizer_SetDefaultCellSize(obj.ptr, Cint(width), Cint(height)))
end

function (obj::wxMultiCellSizer, pen::Ptr{Cvoid})
    return Int(KwxFFI.wxMultiCellSizer_SetGridPen(obj.ptr, pen))
end

function (obj::wxMultiCellSizer, row::Integer, rowSize::Integer, expandable::Integer)
    return Int(KwxFFI.wxMultiCellSizer_SetRowHeight(obj.ptr, Cint(row), Cint(rowSize), Cint(expandable)))
end

