# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMultiCellItemHandle <: wxObject
    ptr::Ptr{Cvoid}
end

function wxMultiCellItemHandle(row::Integer, column::Integer, height::Integer, width::Integer, sizeX::Integer, sizeY::Integer, style::Integer, weightX::Integer, weightY::Integer, align::Integer)
    ptr = KwxFFI.wxMultiCellItemHandle_Create(Cint(row), Cint(column), Cint(height), Cint(width), Cint(sizeX), Cint(sizeY), Cint(style), Cint(weightX), Cint(weightY), Cint(align))
    ptr == C_NULL && error("Failed to create wxMultiCellItemHandle")
    obj = wxMultiCellItemHandle(ptr)
    return obj
end

function (obj::wxMultiCellItemHandle, row::Integer, column::Integer, sizeX::Integer, sizeY::Integer, style::Integer, weightX::Integer, weightY::Integer, align::Integer)
    return KwxFFI.wxMultiCellItemHandle_CreateWithSize(obj.ptr, Cint(row), Cint(column), Cint(sizeX), Cint(sizeY), Cint(style), Cint(weightX), Cint(weightY), Cint(align))
end

function (obj::wxMultiCellItemHandle, row::Integer, column::Integer, style::Integer, weightX::Integer, weightY::Integer, align::Integer)
    return KwxFFI.wxMultiCellItemHandle_CreateWithStyle(obj.ptr, Cint(row), Cint(column), Cint(style), Cint(weightX), Cint(weightY), Cint(align))
end

function (obj::wxMultiCellItemHandle)
    return Int(KwxFFI.wxMultiCellItemHandle_GetAlignment(obj.ptr))
end

function (obj::wxMultiCellItemHandle)
    return Int(KwxFFI.wxMultiCellItemHandle_GetColumn(obj.ptr))
end

function (obj::wxMultiCellItemHandle)
    return Int(KwxFFI.wxMultiCellItemHandle_GetHeight(obj.ptr))
end

function (obj::wxMultiCellItemHandle, arg::Integer)
    KwxFFI.wxMultiCellItemHandle_GetLocalSize(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxMultiCellItemHandle)
    return Int(KwxFFI.wxMultiCellItemHandle_GetRow(obj.ptr))
end

function (obj::wxMultiCellItemHandle)
    return Int(KwxFFI.wxMultiCellItemHandle_GetStyle(obj.ptr))
end

function (obj::wxMultiCellItemHandle, arg::Integer)
    KwxFFI.wxMultiCellItemHandle_GetWeight(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxMultiCellItemHandle)
    return Int(KwxFFI.wxMultiCellItemHandle_GetWidth(obj.ptr))
end

