# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxMultiCellCanvas <: wxSizer
    ptr::Ptr{Cvoid}
end

function wxMultiCellCanvas(parent::Union{wxWindow, Nothing}, numRows::Integer, numCols::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxMultiCellCanvas_Create(parent_ptr, Cint(numRows), Cint(numCols))
    ptr == C_NULL && error("Failed to create wxMultiCellCanvas")
    obj = wxMultiCellCanvas(ptr)
    return obj
end

function (obj::wxMultiCellCanvas, win::Ptr{Cvoid}, row::Integer, col::Integer)
    KwxFFI.wxMultiCellCanvas_Add(obj.ptr, win, Cint(row), Cint(col))
    nothing
end

function (obj::wxMultiCellCanvas)
    KwxFFI.wxMultiCellCanvas_CalculateConstraints(obj.ptr)
    nothing
end

function (obj::wxMultiCellCanvas)
    return Int(KwxFFI.wxMultiCellCanvas_MaxCols(obj.ptr))
end

function (obj::wxMultiCellCanvas)
    return Int(KwxFFI.wxMultiCellCanvas_MaxRows(obj.ptr))
end

function (obj::wxMultiCellCanvas, width::Integer, height::Integer)
    KwxFFI.wxMultiCellCanvas_SetMinCellSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

