# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxNavigationKeyEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxNavigationKeyEvent)
    return KwxFFI.wxNavigationKeyEvent_GetCurrentFocus(obj.ptr)
end

function (obj::wxNavigationKeyEvent)
    return KwxFFI.wxNavigationKeyEvent_GetDirection(obj.ptr) != 0
end

function (obj::wxNavigationKeyEvent)
    return KwxFFI.wxNavigationKeyEvent_IsWindowChange(obj.ptr) != 0
end

function (obj::wxNavigationKeyEvent, win::Ptr{Cvoid})
    KwxFFI.wxNavigationKeyEvent_SetCurrentFocus(obj.ptr, win)
    nothing
end

function (obj::wxNavigationKeyEvent, bForward::Bool)
    KwxFFI.wxNavigationKeyEvent_SetDirection(obj.ptr, Cint(bForward))
    nothing
end

function (obj::wxNavigationKeyEvent)
    return Int(KwxFFI.wxNavigationKeyEvent_ShouldPropagate(obj.ptr))
end

