# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPaletteChangedEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxPaletteChangedEvent, arg::Ptr{Cvoid})
    KwxFFI.wxPaletteChangedEvent_CopyObject(obj.ptr, arg)
    nothing
end

function (obj::wxPaletteChangedEvent)
    return KwxFFI.wxPaletteChangedEvent_GetChangedWindow(obj.ptr)
end

function (obj::wxPaletteChangedEvent, win::Ptr{Cvoid})
    KwxFFI.wxPaletteChangedEvent_SetChangedWindow(obj.ptr, win)
    nothing
end

