# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPaintDC <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPaintDC(win::Ptr{Cvoid})
    ptr = KwxFFI.wxPaintDC_Create(win)
    ptr == C_NULL && error("Failed to create wxPaintDC")
    obj = wxPaintDC(ptr)
    return obj
end

function delete!(obj::wxPaintDC)
    KwxFFI.wxPaintDC_Delete(obj.ptr)
    nothing
end

