# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPalette <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPalette()
    ptr = KwxFFI.wxPalette_CreateDefault()
    ptr == C_NULL && error("Failed to create wxPalette")
    obj = wxPalette(ptr)
    return obj
end

function wxPalette(count::Integer, red::Ptr{Cvoid}, green::Ptr{Cvoid}, blue::Ptr{Cvoid})
    ptr = KwxFFI.wxPalette_CreateRGB(Cint(count), red, green, blue)
    ptr == C_NULL && error("Failed to create wxPalette")
    obj = wxPalette(ptr)
    return obj
end

function (obj::wxPalette, palette::Ptr{Cvoid})
    KwxFFI.wxPalette_Assign(obj.ptr, palette)
    nothing
end

function delete!(obj::wxPalette)
    KwxFFI.wxPalette_Delete(obj.ptr)
    nothing
end

function (obj::wxPalette, red::Integer, green::Integer, blue::Integer)
    return Int(KwxFFI.wxPalette_GetPixel(obj.ptr, Cuchar(red), Cuchar(green), Cuchar(blue)))
end

function (obj::wxPalette, pixel::Integer, red::Ptr{Cvoid}, green::Ptr{Cvoid}, blue::Ptr{Cvoid})
    return KwxFFI.wxPalette_GetRGB(obj.ptr, Cint(pixel), red, green, blue) != 0
end

function (obj::wxPalette, palette::Ptr{Cvoid})
    return KwxFFI.wxPalette_IsEqual(obj.ptr, palette) != 0
end

function (obj::wxPalette)
    return KwxFFI.wxPalette_IsOk(obj.ptr) != 0
end

