# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPen <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPen()
    ptr = KwxFFI.wxPen_CreateDefault()
    ptr == C_NULL && error("Failed to create wxPen")
    obj = wxPen(ptr)
    return obj
end

function wxPen(stipple::Ptr{Cvoid}, width::Integer)
    ptr = KwxFFI.wxPen_CreateFromBitmap(stipple, Cint(width))
    ptr == C_NULL && error("Failed to create wxPen")
    obj = wxPen(ptr)
    return obj
end

function wxPen(col::Ptr{Cvoid}, width::Integer, style::Integer)
    ptr = KwxFFI.wxPen_CreateFromColour(col, Cint(width), Cint(style))
    ptr == C_NULL && error("Failed to create wxPen")
    obj = wxPen(ptr)
    return obj
end

function wxPen(id::Integer)
    ptr = KwxFFI.wxPen_CreateFromStock(Cint(id))
    ptr == C_NULL && error("Failed to create wxPen")
    obj = wxPen(ptr)
    return obj
end

function (obj::wxPen, pen::Ptr{Cvoid})
    KwxFFI.wxPen_Assign(obj.ptr, pen)
    nothing
end

function delete!(obj::wxPen)
    KwxFFI.wxPen_Delete(obj.ptr)
    nothing
end

function (obj::wxPen)
    return Int(KwxFFI.wxPen_GetCap(obj.ptr))
end

function (obj::wxPen, ref::Ptr{Cvoid})
    KwxFFI.wxPen_GetColour(obj.ptr, ref)
    nothing
end

function (obj::wxPen, ptr::Ptr{Cvoid})
    return Int(KwxFFI.wxPen_GetDashes(obj.ptr, ptr))
end

function (obj::wxPen)
    return Int(KwxFFI.wxPen_GetJoin(obj.ptr))
end

function (obj::wxPen, ref::Ptr{Cvoid})
    KwxFFI.wxPen_GetStipple(obj.ptr, ref)
    nothing
end

function (obj::wxPen)
    return Int(KwxFFI.wxPen_GetStyle(obj.ptr))
end

function (obj::wxPen)
    return Int(KwxFFI.wxPen_GetWidth(obj.ptr))
end

function (obj::wxPen, pen::Ptr{Cvoid})
    return KwxFFI.wxPen_IsEqual(obj.ptr, pen) != 0
end

function (obj::wxPen)
    return KwxFFI.wxPen_IsOk(obj.ptr) != 0
end

function (obj::wxPen, cap::Integer)
    KwxFFI.wxPen_SetCap(obj.ptr, Cint(cap))
    nothing
end

function (obj::wxPen, col::Ptr{Cvoid})
    KwxFFI.wxPen_SetColour(obj.ptr, col)
    nothing
end

function (obj::wxPen, red::Integer, green::Integer, blue::Integer)
    KwxFFI.wxPen_SetColourSingle(obj.ptr, Cchar(red), Cchar(green), Cchar(blue))
    nothing
end

function (obj::wxPen, nb_dashes::Integer, dash::Ptr{Cvoid})
    KwxFFI.wxPen_SetDashes(obj.ptr, Cint(nb_dashes), dash)
    nothing
end

function (obj::wxPen, join::Integer)
    KwxFFI.wxPen_SetJoin(obj.ptr, Cint(join))
    nothing
end

function (obj::wxPen, stipple::Ptr{Cvoid})
    KwxFFI.wxPen_SetStipple(obj.ptr, stipple)
    nothing
end

function (obj::wxPen, style::Integer)
    KwxFFI.wxPen_SetStyle(obj.ptr, Cint(style))
    nothing
end

function (obj::wxPen, width::Integer)
    KwxFFI.wxPen_SetWidth(obj.ptr, Cint(width))
    nothing
end

