# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPlotOnOffCurve <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPlotOnOffCurve(offsetY::Integer)
    ptr = KwxFFI.wxPlotOnOffCurve_Create(Cint(offsetY))
    ptr == C_NULL && error("Failed to create wxPlotOnOffCurve")
    obj = wxPlotOnOffCurve(ptr)
    return obj
end

function (obj::wxPlotOnOffCurve, onPos::Integer, offPos::Integer, clientData::Ptr{Cvoid})
    KwxFFI.wxPlotOnOffCurve_Add(obj.ptr, Cint(onPos), Cint(offPos), clientData)
    nothing
end

function delete!(obj::wxPlotOnOffCurve)
    KwxFFI.wxPlotOnOffCurve_Delete(obj.ptr)
    nothing
end

function (obj::wxPlotOnOffCurve, dc::Ptr{Cvoid}, y::Integer, start::Integer, end_::Integer)
    KwxFFI.wxPlotOnOffCurve_DrawOffLine(obj.ptr, dc, Cint(y), Cint(start), Cint(end_))
    nothing
end

function (obj::wxPlotOnOffCurve, dc::Ptr{Cvoid}, y::Integer, start::Integer, end_::Integer, clientData::Ptr{Cvoid})
    KwxFFI.wxPlotOnOffCurve_DrawOnLine(obj.ptr, dc, Cint(y), Cint(start), Cint(end_), clientData)
    nothing
end

function (obj::wxPlotOnOffCurve, index::Integer)
    return KwxFFI.wxPlotOnOffCurve_GetAt(obj.ptr, Cint(index))
end

function (obj::wxPlotOnOffCurve, index::Integer)
    return KwxFFI.wxPlotOnOffCurve_GetClientData(obj.ptr, Cint(index))
end

function (obj::wxPlotOnOffCurve)
    return Int(KwxFFI.wxPlotOnOffCurve_GetCount(obj.ptr))
end

function (obj::wxPlotOnOffCurve)
    return Int(KwxFFI.wxPlotOnOffCurve_GetEndX(obj.ptr))
end

function (obj::wxPlotOnOffCurve, index::Integer)
    return Int(KwxFFI.wxPlotOnOffCurve_GetOff(obj.ptr, Cint(index)))
end

function (obj::wxPlotOnOffCurve)
    return Int(KwxFFI.wxPlotOnOffCurve_GetOffsetY(obj.ptr))
end

function (obj::wxPlotOnOffCurve, index::Integer)
    return Int(KwxFFI.wxPlotOnOffCurve_GetOn(obj.ptr, Cint(index)))
end

function (obj::wxPlotOnOffCurve)
    return Int(KwxFFI.wxPlotOnOffCurve_GetStartX(obj.ptr))
end

function (obj::wxPlotOnOffCurve, offsetY::Integer)
    KwxFFI.wxPlotOnOffCurve_SetOffsetY(obj.ptr, Cint(offsetY))
    nothing
end

