# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPostScriptDC <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPostScriptDC(data::Ptr{Cvoid})
    ptr = KwxFFI.wxPostScriptDC_Create(data)
    ptr == C_NULL && error("Failed to create wxPostScriptDC")
    obj = wxPostScriptDC(ptr)
    return obj
end

function delete!(obj::wxPostScriptDC)
    KwxFFI.wxPostScriptDC_Delete(obj.ptr)
    nothing
end

function (obj::wxPostScriptDC, ppi::Integer)
    KwxFFI.wxPostScriptDC_SetResolution(obj.ptr, Cint(ppi))
    nothing
end

function (obj::wxPostScriptDC)
    return Int(KwxFFI.wxPostScriptDC_GetResolution(obj.ptr))
end

