# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPoint <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPoint(xx::Integer, yy::Integer)
    ptr = KwxFFI.wxPoint_Create(Cint(xx), Cint(yy))
    ptr == C_NULL && error("Failed to create wxPoint")
    obj = wxPoint(ptr)
    return obj
end

function (obj::wxPoint)
    KwxFFI.wxPoint_Destroy(obj.ptr)
    nothing
end

function (obj::wxPoint)
    return Int(KwxFFI.wxPoint_GetX(obj.ptr))
end

function (obj::wxPoint)
    return Int(KwxFFI.wxPoint_GetY(obj.ptr))
end

function (obj::wxPoint, width::Integer)
    KwxFFI.wxPoint_SetX(obj.ptr, Cint(width))
    nothing
end

function (obj::wxPoint, height::Integer)
    KwxFFI.wxPoint_SetY(obj.ptr, Cint(height))
    nothing
end

