# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPropertyGridManager <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxPropertyGridManager(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxPropertyGridManager_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxPropertyGridManager")
    obj = wxPropertyGridManager(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxPropertyGridManager, label::String, bmp::Ptr{Cvoid})
    label_ws = wxString(label)
    _result = KwxFFI.wxPropertyGridManager_AddPage(obj.ptr, label_ws.ptr, bmp)
    delete!(label_ws)
    return _result
end

function (obj::wxPropertyGridManager, index::Integer, label::String, bmp::Ptr{Cvoid})
    label_ws = wxString(label)
    _result = KwxFFI.wxPropertyGridManager_InsertPage(obj.ptr, Cint(index), label_ws.ptr, bmp)
    delete!(label_ws)
    return _result
end

function (obj::wxPropertyGridManager, page::Integer)
    return KwxFFI.wxPropertyGridManager_RemovePage(obj.ptr, Cint(page)) != 0
end

function (obj::wxPropertyGridManager, page::Integer)
    KwxFFI.wxPropertyGridManager_ClearPage(obj.ptr, Cint(page))
    nothing
end

function (obj::wxPropertyGridManager)
    return Int(KwxFFI.wxPropertyGridManager_GetPageCount(obj.ptr))
end

function (obj::wxPropertyGridManager, index::Integer)
    return KwxFFI.wxPropertyGridManager_GetPage(obj.ptr, Cuint(index))
end

function (obj::wxPropertyGridManager, name::String)
    name_ws = wxString(name)
    _result = Int(KwxFFI.wxPropertyGridManager_GetPageByName(obj.ptr, name_ws.ptr))
    delete!(name_ws)
    return _result
end

function (obj::wxPropertyGridManager, index::Integer)
    return KwxFFI.wxPropertyGridManager_GetPageName(obj.ptr, Cint(index))
end

function (obj::wxPropertyGridManager)
    return Int(KwxFFI.wxPropertyGridManager_GetSelectedPage(obj.ptr))
end

function (obj::wxPropertyGridManager, index::Integer)
    KwxFFI.wxPropertyGridManager_SelectPage(obj.ptr, Cint(index))
    nothing
end

function (obj::wxPropertyGridManager, label::String)
    label_ws = wxString(label)
    KwxFFI.wxPropertyGridManager_SelectPageByLabel(obj.ptr, label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxPropertyGridManager)
    return KwxFFI.wxPropertyGridManager_GetGrid(obj.ptr)
end

function (obj::wxPropertyGridManager)
    return KwxFFI.wxPropertyGridManager_GetCurrentPage(obj.ptr)
end

function (obj::wxPropertyGridManager)
    return KwxFFI.wxPropertyGridManager_GetToolBar(obj.ptr)
end

function (obj::wxPropertyGridManager, descBoxHeight::Integer, refresh::Bool)
    KwxFFI.wxPropertyGridManager_SetDescBoxHeight(obj.ptr, Cint(descBoxHeight), Cint(refresh))
    nothing
end

function (obj::wxPropertyGridManager)
    return Int(KwxFFI.wxPropertyGridManager_GetDescBoxHeight(obj.ptr))
end

function (obj::wxPropertyGridManager, show::Bool)
    KwxFFI.wxPropertyGridManager_ShowHeader(obj.ptr, Cint(show))
    nothing
end

function (obj::wxPropertyGridManager)
    return KwxFFI.wxPropertyGridManager_IsAnyModified(obj.ptr) != 0
end

function (obj::wxPropertyGridManager, index::Integer)
    return KwxFFI.wxPropertyGridManager_IsPageModified(obj.ptr, Csize_t(index)) != 0
end

function (obj::wxPropertyGridManager)
    KwxFFI.wxPropertyGridManager_Clear(obj.ptr)
    nothing
end

