# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPrinterDC <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPrinterDC(data::Ptr{Cvoid})
    ptr = KwxFFI.wxPrinterDC_Create(data)
    ptr == C_NULL && error("Failed to create wxPrinterDC")
    obj = wxPrinterDC(ptr)
    return obj
end

function delete!(obj::wxPrinterDC)
    KwxFFI.wxPrinterDC_Delete(obj.ptr)
    nothing
end

function (obj::wxPrinterDC)
    return KwxFFI.wxPrinterDC_GetPaperRect(obj.ptr)
end

