# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPropertySheetDialog <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxPropertySheetDialog(parent::Union{wxWindow, Nothing}, id::Integer, title::String, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    title_ws = wxString(title)
    ptr = KwxFFI.wxPropertySheetDialog_Create(parent_ptr, Cint(id), title_ws.ptr, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    delete!(title_ws)
    ptr == C_NULL && error("Failed to create wxPropertySheetDialog")
    obj = wxPropertySheetDialog(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxPropertySheetDialog, flags::Integer)
    KwxFFI.wxPropertySheetDialog_CreateButtons(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxPropertySheetDialog)
    return KwxFFI.wxPropertySheetDialog_GetBookCtrl(obj.ptr)
end

function (obj::wxPropertySheetDialog)
    return KwxFFI.wxPropertySheetDialog_GetInnerSizer(obj.ptr)
end

function (obj::wxPropertySheetDialog, sizer::Ptr{Cvoid})
    KwxFFI.wxPropertySheetDialog_SetInnerSizer(obj.ptr, sizer)
    nothing
end

function (obj::wxPropertySheetDialog, centreFlags::Integer)
    KwxFFI.wxPropertySheetDialog_LayoutDialog(obj.ptr, Cint(centreFlags))
    nothing
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.wxPropertySheetDialog_GetSheetStyle(obj.ptr))
end

function (obj::wxPropertySheetDialog, style::Integer)
    KwxFFI.wxPropertySheetDialog_SetSheetStyle(obj.ptr, Cint(style))
    nothing
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.wxPropertySheetDialog_GetSheetOuterBorder(obj.ptr))
end

function (obj::wxPropertySheetDialog, border::Integer)
    KwxFFI.wxPropertySheetDialog_SetSheetOuterBorder(obj.ptr, Cint(border))
    nothing
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.wxPropertySheetDialog_GetSheetInnerBorder(obj.ptr))
end

function (obj::wxPropertySheetDialog, border::Integer)
    KwxFFI.wxPropertySheetDialog_SetSheetInnerBorder(obj.ptr, Cint(border))
    nothing
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.expPROPSHEET_NOTEBOOK(obj.ptr))
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.expPROPSHEET_TOOLBOOK(obj.ptr))
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.expPROPSHEET_CHOICEBOOK(obj.ptr))
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.expPROPSHEET_LISTBOOK(obj.ptr))
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.expPROPSHEET_BUTTONTOOLBOOK(obj.ptr))
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.expPROPSHEET_TREEBOOK(obj.ptr))
end

function (obj::wxPropertySheetDialog)
    return Int(KwxFFI.expPROPSHEET_SHRINKTOFIT(obj.ptr))
end

