# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPrinter <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPrinter(data::Ptr{Cvoid})
    ptr = KwxFFI.wxPrinter_Create(data)
    ptr == C_NULL && error("Failed to create wxPrinter")
    obj = wxPrinter(ptr)
    return obj
end

function (obj::wxPrinter, parent::Ptr{Cvoid}, printout::Ptr{Cvoid})
    return KwxFFI.wxPrinter_CreateAbortWindow(obj.ptr, parent, printout)
end

function delete!(obj::wxPrinter)
    KwxFFI.wxPrinter_Delete(obj.ptr)
    nothing
end

function (obj::wxPrinter)
    return KwxFFI.wxPrinter_GetAbort(obj.ptr) != 0
end

function (obj::wxPrinter)
    return Int(KwxFFI.wxPrinter_GetLastError(obj.ptr))
end

function (obj::wxPrinter, ref::Ptr{Cvoid})
    KwxFFI.wxPrinter_GetPrintDialogData(obj.ptr, ref)
    nothing
end

function (obj::wxPrinter, parent::Ptr{Cvoid}, printout::Ptr{Cvoid}, prompt::Bool)
    return KwxFFI.wxPrinter_Print(obj.ptr, parent, printout, Cint(prompt)) != 0
end

function (obj::wxPrinter, parent::Ptr{Cvoid})
    return KwxFFI.wxPrinter_PrintDialog(obj.ptr, parent)
end

function (obj::wxPrinter, parent::Ptr{Cvoid}, printout::Ptr{Cvoid}, message::String)
    message_ws = wxString(message)
    KwxFFI.wxPrinter_ReportError(obj.ptr, parent, printout, message_ws.ptr)
    delete!(message_ws)
    nothing
end

function (obj::wxPrinter, parent::Ptr{Cvoid})
    return KwxFFI.wxPrinter_Setup(obj.ptr, parent) != 0
end

