# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPrintDialogData <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPrintDialogData()
    ptr = KwxFFI.wxPrintDialogData_CreateDefault()
    ptr == C_NULL && error("Failed to create wxPrintDialogData")
    obj = wxPrintDialogData(ptr)
    return obj
end

function wxPrintDialogData(printData::Ptr{Cvoid})
    ptr = KwxFFI.wxPrintDialogData_CreateFromData(printData)
    ptr == C_NULL && error("Failed to create wxPrintDialogData")
    obj = wxPrintDialogData(ptr)
    return obj
end

function (obj::wxPrintDialogData, data::Ptr{Cvoid})
    KwxFFI.wxPrintDialogData_Assign(obj.ptr, data)
    nothing
end

function (obj::wxPrintDialogData, data::Ptr{Cvoid})
    KwxFFI.wxPrintDialogData_AssignData(obj.ptr, data)
    nothing
end

function delete!(obj::wxPrintDialogData)
    KwxFFI.wxPrintDialogData_Delete(obj.ptr)
    nothing
end

function (obj::wxPrintDialogData, flag::Bool)
    KwxFFI.wxPrintDialogData_EnableHelp(obj.ptr, Cint(flag))
    nothing
end

function (obj::wxPrintDialogData, flag::Bool)
    KwxFFI.wxPrintDialogData_EnablePageNumbers(obj.ptr, Cint(flag))
    nothing
end

function (obj::wxPrintDialogData, flag::Bool)
    KwxFFI.wxPrintDialogData_EnablePrintToFile(obj.ptr, Cint(flag))
    nothing
end

function (obj::wxPrintDialogData, flag::Bool)
    KwxFFI.wxPrintDialogData_EnableSelection(obj.ptr, Cint(flag))
    nothing
end

function (obj::wxPrintDialogData)
    return Int(KwxFFI.wxPrintDialogData_GetAllPages(obj.ptr))
end

function (obj::wxPrintDialogData)
    return KwxFFI.wxPrintDialogData_GetCollate(obj.ptr) != 0
end

function (obj::wxPrintDialogData)
    return KwxFFI.wxPrintDialogData_GetEnableHelp(obj.ptr) != 0
end

function (obj::wxPrintDialogData)
    return KwxFFI.wxPrintDialogData_GetEnablePageNumbers(obj.ptr) != 0
end

function (obj::wxPrintDialogData)
    return KwxFFI.wxPrintDialogData_GetEnablePrintToFile(obj.ptr) != 0
end

function (obj::wxPrintDialogData)
    return KwxFFI.wxPrintDialogData_GetEnableSelection(obj.ptr) != 0
end

function (obj::wxPrintDialogData)
    return Int(KwxFFI.wxPrintDialogData_GetFromPage(obj.ptr))
end

function (obj::wxPrintDialogData)
    return Int(KwxFFI.wxPrintDialogData_GetMaxPage(obj.ptr))
end

function (obj::wxPrintDialogData)
    return Int(KwxFFI.wxPrintDialogData_GetMinPage(obj.ptr))
end

function (obj::wxPrintDialogData)
    return Int(KwxFFI.wxPrintDialogData_GetNoCopies(obj.ptr))
end

function (obj::wxPrintDialogData, ref::Ptr{Cvoid})
    KwxFFI.wxPrintDialogData_GetPrintData(obj.ptr, ref)
    nothing
end

function (obj::wxPrintDialogData)
    return KwxFFI.wxPrintDialogData_GetPrintToFile(obj.ptr) != 0
end

function (obj::wxPrintDialogData)
    return KwxFFI.wxPrintDialogData_GetSelection(obj.ptr) != 0
end

function (obj::wxPrintDialogData)
    return Int(KwxFFI.wxPrintDialogData_GetToPage(obj.ptr))
end

function (obj::wxPrintDialogData, flag::Bool)
    KwxFFI.wxPrintDialogData_SetAllPages(obj.ptr, Cint(flag))
    nothing
end

function (obj::wxPrintDialogData, flag::Bool)
    KwxFFI.wxPrintDialogData_SetCollate(obj.ptr, Cint(flag))
    nothing
end

function (obj::wxPrintDialogData, value::Integer)
    KwxFFI.wxPrintDialogData_SetFromPage(obj.ptr, Cint(value))
    nothing
end

function (obj::wxPrintDialogData, value::Integer)
    KwxFFI.wxPrintDialogData_SetMaxPage(obj.ptr, Cint(value))
    nothing
end

function (obj::wxPrintDialogData, value::Integer)
    KwxFFI.wxPrintDialogData_SetMinPage(obj.ptr, Cint(value))
    nothing
end

function (obj::wxPrintDialogData, value::Integer)
    KwxFFI.wxPrintDialogData_SetNoCopies(obj.ptr, Cint(value))
    nothing
end

function (obj::wxPrintDialogData, printData::Ptr{Cvoid})
    KwxFFI.wxPrintDialogData_SetPrintData(obj.ptr, printData)
    nothing
end

function (obj::wxPrintDialogData, flag::Bool)
    KwxFFI.wxPrintDialogData_SetPrintToFile(obj.ptr, Cint(flag))
    nothing
end

function (obj::wxPrintDialogData, flag::Bool)
    KwxFFI.wxPrintDialogData_SetSelection(obj.ptr, Cint(flag))
    nothing
end

function (obj::wxPrintDialogData, value::Integer)
    KwxFFI.wxPrintDialogData_SetToPage(obj.ptr, Cint(value))
    nothing
end

