# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPrintDialog <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxPrintDialog(parent::Union{wxWindow, Nothing}, data::Ptr{Cvoid})
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxPrintDialog_Create(parent_ptr, data)
    ptr == C_NULL && error("Failed to create wxPrintDialog")
    obj = wxPrintDialog(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxPrintDialog)
    return KwxFFI.wxPrintDialog_GetPrintDC(obj.ptr)
end

function (obj::wxPrintDialog, ref::Ptr{Cvoid})
    KwxFFI.wxPrintDialog_GetPrintData(obj.ptr, ref)
    nothing
end

function (obj::wxPrintDialog)
    return KwxFFI.wxPrintDialog_GetPrintDialogData(obj.ptr)
end

