# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPropertyGridEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxPropertyGridEvent)
    return KwxFFI.wxPropertyGridEvent_HasProperty(obj.ptr) != 0
end

function (obj::wxPropertyGridEvent)
    return KwxFFI.wxPropertyGridEvent_GetProperty(obj.ptr)
end

