# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPropertyCategory <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPropertyCategory(label::String)
    label_ws = wxString(label)
    ptr = KwxFFI.wxPropertyCategory_Create(label_ws.ptr)
    delete!(label_ws)
    ptr == C_NULL && error("Failed to create wxPropertyCategory")
    obj = wxPropertyCategory(ptr)
    return obj
end

