# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPrintPreview <: wxObject
    ptr::Ptr{Cvoid}
end

function wxPrintPreview(printout::Ptr{Cvoid}, printoutForPrinting::Ptr{Cvoid}, data::Ptr{Cvoid})
    ptr = KwxFFI.wxPrintPreview_CreateFromData(printout, printoutForPrinting, data)
    ptr == C_NULL && error("Failed to create wxPrintPreview")
    obj = wxPrintPreview(ptr)
    return obj
end

function wxPrintPreview(printout::Ptr{Cvoid}, printoutForPrinting::Ptr{Cvoid}, data::Ptr{Cvoid})
    ptr = KwxFFI.wxPrintPreview_CreateFromDialogData(printout, printoutForPrinting, data)
    ptr == C_NULL && error("Failed to create wxPrintPreview")
    obj = wxPrintPreview(ptr)
    return obj
end

function delete!(obj::wxPrintPreview)
    KwxFFI.wxPrintPreview_Delete(obj.ptr)
    nothing
end

function (obj::wxPrintPreview)
    KwxFFI.wxPrintPreview_DetermineScaling(obj.ptr)
    nothing
end

function (obj::wxPrintPreview, canvas::Ptr{Cvoid}, dc::Ptr{Cvoid})
    return KwxFFI.wxPrintPreview_DrawBlankPage(obj.ptr, canvas, dc) != 0
end

function (obj::wxPrintPreview)
    return KwxFFI.wxPrintPreview_GetCanvas(obj.ptr)
end

function (obj::wxPrintPreview)
    return Int(KwxFFI.wxPrintPreview_GetCurrentPage(obj.ptr))
end

function (obj::wxPrintPreview)
    return KwxFFI.wxPrintPreview_GetFrame(obj.ptr)
end

function (obj::wxPrintPreview)
    return Int(KwxFFI.wxPrintPreview_GetMaxPage(obj.ptr))
end

function (obj::wxPrintPreview)
    return Int(KwxFFI.wxPrintPreview_GetMinPage(obj.ptr))
end

function (obj::wxPrintPreview, ref::Ptr{Cvoid})
    KwxFFI.wxPrintPreview_GetPrintDialogData(obj.ptr, ref)
    nothing
end

function (obj::wxPrintPreview)
    return KwxFFI.wxPrintPreview_GetPrintout(obj.ptr)
end

function (obj::wxPrintPreview)
    return KwxFFI.wxPrintPreview_GetPrintoutForPrinting(obj.ptr)
end

function (obj::wxPrintPreview)
    return Int(KwxFFI.wxPrintPreview_GetZoom(obj.ptr))
end

function (obj::wxPrintPreview)
    return KwxFFI.wxPrintPreview_IsOk(obj.ptr) != 0
end

function (obj::wxPrintPreview, canvas::Ptr{Cvoid}, dc::Ptr{Cvoid})
    return KwxFFI.wxPrintPreview_PaintPage(obj.ptr, canvas, dc) != 0
end

function (obj::wxPrintPreview, interactive::Bool)
    return KwxFFI.wxPrintPreview_Print(obj.ptr, Cint(interactive)) != 0
end

function (obj::wxPrintPreview, pageNum::Integer)
    return KwxFFI.wxPrintPreview_RenderPage(obj.ptr, Cint(pageNum)) != 0
end

function (obj::wxPrintPreview, canvas::Ptr{Cvoid})
    KwxFFI.wxPrintPreview_SetCanvas(obj.ptr, canvas)
    nothing
end

function (obj::wxPrintPreview, pageNum::Integer)
    return KwxFFI.wxPrintPreview_SetCurrentPage(obj.ptr, Cint(pageNum)) != 0
end

function (obj::wxPrintPreview, frame::Ptr{Cvoid})
    KwxFFI.wxPrintPreview_SetFrame(obj.ptr, frame)
    nothing
end

function (obj::wxPrintPreview, isOk::Bool)
    KwxFFI.wxPrintPreview_SetOk(obj.ptr, Cint(isOk))
    nothing
end

function (obj::wxPrintPreview, printout::Ptr{Cvoid})
    KwxFFI.wxPrintPreview_SetPrintout(obj.ptr, printout)
    nothing
end

function (obj::wxPrintPreview, percent::Integer)
    KwxFFI.wxPrintPreview_SetZoom(obj.ptr, Cint(percent))
    nothing
end

