# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxPropertyGrid <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxPropertyGrid(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxPropertyGrid_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxPropertyGrid")
    obj = wxPropertyGrid(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxPropertyGrid, prop::Ptr{Cvoid})
    return KwxFFI.wxPropertyGrid_Append(obj.ptr, prop)
end

function (obj::wxPropertyGrid, propName::String)
    propName_ws = wxString(propName)
    _result = KwxFFI.wxPropertyGrid_DisableProperty(obj.ptr, propName_ws.ptr) != 0
    delete!(propName_ws)
    return _result
end

