# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxQueryNewPaletteEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxQueryNewPaletteEvent, arg_ptr::Ptr{Cvoid})
    KwxFFI.wxQueryNewPaletteEvent_CopyObject(obj.ptr, arg_ptr)
    nothing
end

function (obj::wxQueryNewPaletteEvent)
    return KwxFFI.wxQueryNewPaletteEvent_GetPaletteRealized(obj.ptr) != 0
end

function (obj::wxQueryNewPaletteEvent, realized::Bool)
    KwxFFI.wxQueryNewPaletteEvent_SetPaletteRealized(obj.ptr, Cint(realized))
    nothing
end

