# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxRadioBox <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxRadioBox(parent::Union{wxWindow, Nothing}, id::Integer, text::String, left::Integer, top::Integer, width::Integer, height::Integer, n::Integer, strings::Ptr{Cvoid}, dimension::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    text_ws = wxString(text)
    ptr = KwxFFI.wxRadioBox_Create(parent_ptr, Cint(id), text_ws.ptr, Cint(left), Cint(top), Cint(width), Cint(height), Cint(n), strings, Cint(dimension), Cint(style))
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxRadioBox")
    obj = wxRadioBox(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxRadioBox, item::Integer, enable::Bool)
    KwxFFI.wxRadioBox_EnableItem(obj.ptr, Cint(item), Cint(enable))
    nothing
end

function (obj::wxRadioBox, str::String)
    str_ws = wxString(str)
    _result = Int(KwxFFI.wxRadioBox_FindString(obj.ptr, str_ws.ptr))
    delete!(str_ws)
    return _result
end

function (obj::wxRadioBox, item::Integer)
    return KwxFFI.wxRadioBox_GetItemLabel(obj.ptr, Cint(item))
end

function (obj::wxRadioBox)
    return Int(KwxFFI.wxRadioBox_GetNumberOfRowsOrCols(obj.ptr))
end

function (obj::wxRadioBox)
    return Int(KwxFFI.wxRadioBox_GetSelection(obj.ptr))
end

function (obj::wxRadioBox)
    return KwxFFI.wxRadioBox_GetStringSelection(obj.ptr)
end

function (obj::wxRadioBox)
    return Int(KwxFFI.wxRadioBox_Number(obj.ptr))
end

function (obj::wxRadioBox, item::Integer, bitmap::Ptr{Cvoid})
    KwxFFI.wxRadioBox_SetItemBitmap(obj.ptr, Cint(item), bitmap)
    nothing
end

function (obj::wxRadioBox, item::Integer, label::String)
    label_ws = wxString(label)
    KwxFFI.wxRadioBox_SetItemLabel(obj.ptr, Cint(item), label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxRadioBox, count::Integer)
    KwxFFI.wxRadioBox_SetNumberOfRowsOrCols(obj.ptr, Cint(count))
    nothing
end

function (obj::wxRadioBox, selection::Integer)
    KwxFFI.wxRadioBox_SetSelection(obj.ptr, Cint(selection))
    nothing
end

function (obj::wxRadioBox, str::String)
    str_ws = wxString(str)
    KwxFFI.wxRadioBox_SetStringSelection(obj.ptr, str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxRadioBox, item::Integer, show::Bool)
    KwxFFI.wxRadioBox_ShowItem(obj.ptr, Cint(item), Cint(show))
    nothing
end

function (obj::wxRadioBox)
    return Int(KwxFFI.wxRadioBox_GetColumnCount(obj.ptr))
end

function (obj::wxRadioBox)
    return Int(KwxFFI.wxRadioBox_GetRowCount(obj.ptr))
end

function (obj::wxRadioBox, item::Integer)
    return KwxFFI.wxRadioBox_IsItemEnabled(obj.ptr, Cint(item)) != 0
end

function (obj::wxRadioBox, item::Integer)
    return KwxFFI.wxRadioBox_IsItemShown(obj.ptr, Cint(item)) != 0
end

function (obj::wxRadioBox)
    return Int(KwxFFI.wxRadioBox_GetCount(obj.ptr))
end

