# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxRearrangeCtrl <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxRearrangeCtrl(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, order::Ptr{Cvoid}, items::Ptr{Cvoid}, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxRearrangeCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), order, items, Cint(style))
    ptr == C_NULL && error("Failed to create wxRearrangeCtrl")
    obj = wxRearrangeCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxRearrangeCtrl)
    return KwxFFI.wxRearrangeCtrl_GetCurrentOrder(obj.ptr)
end

function (obj::wxRearrangeCtrl)
    return KwxFFI.wxRearrangeCtrl_GetList(obj.ptr)
end

function (obj::wxRearrangeCtrl)
    return KwxFFI.wxRearrangeCtrl_CanMoveCurrentUp(obj.ptr) != 0
end

function (obj::wxRearrangeCtrl)
    return KwxFFI.wxRearrangeCtrl_CanMoveCurrentDown(obj.ptr) != 0
end

function (obj::wxRearrangeCtrl)
    return KwxFFI.wxRearrangeCtrl_MoveCurrentUp(obj.ptr) != 0
end

function (obj::wxRearrangeCtrl)
    return KwxFFI.wxRearrangeCtrl_MoveCurrentDown(obj.ptr) != 0
end

