# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxRemotelyScrolledTreeCtrl <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxRemotelyScrolledTreeCtrl(pObject::Ptr{Cvoid}, compareFunc::Ptr{Cvoid}, parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxRemotelyScrolledTreeCtrl_Create(pObject, compareFunc, parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxRemotelyScrolledTreeCtrl")
    obj = wxRemotelyScrolledTreeCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxRemotelyScrolledTreeCtrl)
    KwxFFI.wxRemotelyScrolledTreeCtrl_AdjustRemoteScrollbars(obj.ptr)
    nothing
end

function (obj::wxRemotelyScrolledTreeCtrl, arg::Integer)
    KwxFFI.wxRemotelyScrolledTreeCtrl_CalcTreeSize(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxRemotelyScrolledTreeCtrl, id::Ptr{Cvoid}, arg::Integer)
    KwxFFI.wxRemotelyScrolledTreeCtrl_CalcTreeSizeItem(obj.ptr, id, Cint(arg))
    nothing
end

function delete!(obj::wxRemotelyScrolledTreeCtrl)
    KwxFFI.wxRemotelyScrolledTreeCtrl_Delete(obj.ptr)
    nothing
end

function (obj::wxRemotelyScrolledTreeCtrl)
    return KwxFFI.wxRemotelyScrolledTreeCtrl_GetCompanionWindow(obj.ptr)
end

function (obj::wxRemotelyScrolledTreeCtrl, orient::Integer)
    return Int(KwxFFI.wxRemotelyScrolledTreeCtrl_GetScrollPos(obj.ptr, Cint(orient)))
end

function (obj::wxRemotelyScrolledTreeCtrl)
    return KwxFFI.wxRemotelyScrolledTreeCtrl_GetScrolledWindow(obj.ptr)
end

function (obj::wxRemotelyScrolledTreeCtrl, arg::Integer)
    KwxFFI.wxRemotelyScrolledTreeCtrl_GetViewStart(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxRemotelyScrolledTreeCtrl)
    KwxFFI.wxRemotelyScrolledTreeCtrl_HideVScrollbar(obj.ptr)
    nothing
end

function (obj::wxRemotelyScrolledTreeCtrl, dc::Ptr{Cvoid})
    KwxFFI.wxRemotelyScrolledTreeCtrl_PrepareDC(obj.ptr, dc)
    nothing
end

function (obj::wxRemotelyScrolledTreeCtrl, posHoriz::Integer, posVert::Integer)
    KwxFFI.wxRemotelyScrolledTreeCtrl_ScrollToLine(obj.ptr, Cint(posHoriz), Cint(posVert))
    nothing
end

function (obj::wxRemotelyScrolledTreeCtrl, companion::Ptr{Cvoid})
    KwxFFI.wxRemotelyScrolledTreeCtrl_SetCompanionWindow(obj.ptr, companion)
    nothing
end

function (obj::wxRemotelyScrolledTreeCtrl, pixelsPerUnitX::Integer, pixelsPerUnitY::Integer, noUnitsX::Integer, noUnitsY::Integer, xPos::Integer, yPos::Integer, noRefresh::Integer)
    KwxFFI.wxRemotelyScrolledTreeCtrl_SetScrollbars(obj.ptr, Cint(pixelsPerUnitX), Cint(pixelsPerUnitY), Cint(noUnitsX), Cint(noUnitsY), Cint(xPos), Cint(yPos), Cint(noRefresh))
    nothing
end

