# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxRegion <: wxObject
    ptr::Ptr{Cvoid}
end

function wxRegion()
    ptr = KwxFFI.wxRegion_CreateDefault()
    ptr == C_NULL && error("Failed to create wxRegion")
    obj = wxRegion(ptr)
    return obj
end

function wxRegion(x::Integer, y::Integer, width::Integer, height::Integer)
    ptr = KwxFFI.wxRegion_CreateFromRect(Cint(x), Cint(y), Cint(width), Cint(height))
    ptr == C_NULL && error("Failed to create wxRegion")
    obj = wxRegion(ptr)
    return obj
end

function (obj::wxRegion, region::Ptr{Cvoid})
    KwxFFI.wxRegion_Assign(obj.ptr, region)
    nothing
end

function (obj::wxRegion)
    KwxFFI.wxRegion_Clear(obj.ptr)
    nothing
end

function (obj::wxRegion, x::Integer, y::Integer)
    return KwxFFI.wxRegion_ContainsPoint(obj.ptr, Cint(x), Cint(y)) != 0
end

function (obj::wxRegion, x::Integer, y::Integer, width::Integer, height::Integer)
    return KwxFFI.wxRegion_ContainsRect(obj.ptr, Cint(x), Cint(y), Cint(width), Cint(height)) != 0
end

function delete!(obj::wxRegion)
    KwxFFI.wxRegion_Delete(obj.ptr)
    nothing
end

function (obj::wxRegion)
    return KwxFFI.wxRegion_IsEmpty(obj.ptr) != 0
end

function (obj::wxRegion, arg::Integer)
    KwxFFI.wxRegion_GetBox(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxRegion, x::Integer, y::Integer, width::Integer, height::Integer)
    return KwxFFI.wxRegion_IntersectRect(obj.ptr, Cint(x), Cint(y), Cint(width), Cint(height)) != 0
end

function (obj::wxRegion, region::Ptr{Cvoid})
    return KwxFFI.wxRegion_IntersectRegion(obj.ptr, region) != 0
end

function (obj::wxRegion, x::Integer, y::Integer, width::Integer, height::Integer)
    return KwxFFI.wxRegion_SubtractRect(obj.ptr, Cint(x), Cint(y), Cint(width), Cint(height)) != 0
end

function (obj::wxRegion, region::Ptr{Cvoid})
    return KwxFFI.wxRegion_SubtractRegion(obj.ptr, region) != 0
end

function (obj::wxRegion, x::Integer, y::Integer, width::Integer, height::Integer)
    return KwxFFI.wxRegion_UnionRect(obj.ptr, Cint(x), Cint(y), Cint(width), Cint(height)) != 0
end

function (obj::wxRegion, region::Ptr{Cvoid})
    return KwxFFI.wxRegion_UnionRegion(obj.ptr, region) != 0
end

function (obj::wxRegion, x::Integer, y::Integer, width::Integer, height::Integer)
    return KwxFFI.wxRegion_XorRect(obj.ptr, Cint(x), Cint(y), Cint(width), Cint(height)) != 0
end

function (obj::wxRegion, region::Ptr{Cvoid})
    return KwxFFI.wxRegion_XorRegion(obj.ptr, region) != 0
end

