# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxRibbonButtonBar <: wxObject
    ptr::Ptr{Cvoid}
end

function wxRibbonButtonBar(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxRibbonButtonBar_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxRibbonButtonBar")
    obj = wxRibbonButtonBar(ptr)
    return obj
end

function (obj::wxRibbonButtonBar, button_id::Integer, label::String, bitmap::Ptr{Cvoid}, help_string::String, kind::Integer, bitmap_small::Ptr{Cvoid}, bitmap_disabled::Ptr{Cvoid}, bitmap_small_disabled::Ptr{Cvoid})
    label_ws = wxString(label)
    help_string_ws = wxString(help_string)
    _result = KwxFFI.wxRibbonButtonBar_AddButton(obj.ptr, Cint(button_id), label_ws.ptr, bitmap, help_string_ws.ptr, Cint(kind), bitmap_small, bitmap_disabled, bitmap_small_disabled)
    delete!(label_ws)
    delete!(help_string_ws)
    return _result
end

function (obj::wxRibbonButtonBar, button_id::Integer, label::String, bitmap::Ptr{Cvoid}, help_string::String)
    label_ws = wxString(label)
    help_string_ws = wxString(help_string)
    _result = KwxFFI.wxRibbonButtonBar_AddDropdownButton(obj.ptr, Cint(button_id), label_ws.ptr, bitmap, help_string_ws.ptr)
    delete!(label_ws)
    delete!(help_string_ws)
    return _result
end

function (obj::wxRibbonButtonBar, button_id::Integer, label::String, bitmap::Ptr{Cvoid}, help_string::String)
    label_ws = wxString(label)
    help_string_ws = wxString(help_string)
    _result = KwxFFI.wxRibbonButtonBar_AddHybridButton(obj.ptr, Cint(button_id), label_ws.ptr, bitmap, help_string_ws.ptr)
    delete!(label_ws)
    delete!(help_string_ws)
    return _result
end

function (obj::wxRibbonButtonBar, button_id::Integer, label::String, bitmap::Ptr{Cvoid}, help_string::String)
    label_ws = wxString(label)
    help_string_ws = wxString(help_string)
    _result = KwxFFI.wxRibbonButtonBar_AddToggleButton(obj.ptr, Cint(button_id), label_ws.ptr, bitmap, help_string_ws.ptr)
    delete!(label_ws)
    delete!(help_string_ws)
    return _result
end

function (obj::wxRibbonButtonBar, pos::Integer, button_id::Integer, label::String, bitmap::Ptr{Cvoid}, help_string::String, kind::Integer, bitmap_small::Ptr{Cvoid}, bitmap_disabled::Ptr{Cvoid}, bitmap_small_disabled::Ptr{Cvoid})
    label_ws = wxString(label)
    help_string_ws = wxString(help_string)
    _result = KwxFFI.wxRibbonButtonBar_InsertButton(obj.ptr, Csize_t(pos), Cint(button_id), label_ws.ptr, bitmap, help_string_ws.ptr, Cint(kind), bitmap_small, bitmap_disabled, bitmap_small_disabled)
    delete!(label_ws)
    delete!(help_string_ws)
    return _result
end

function (obj::wxRibbonButtonBar, pos::Integer, button_id::Integer, label::String, bitmap::Ptr{Cvoid}, help_string::String)
    label_ws = wxString(label)
    help_string_ws = wxString(help_string)
    _result = KwxFFI.wxRibbonButtonBar_InsertDropdownButton(obj.ptr, Csize_t(pos), Cint(button_id), label_ws.ptr, bitmap, help_string_ws.ptr)
    delete!(label_ws)
    delete!(help_string_ws)
    return _result
end

function (obj::wxRibbonButtonBar, pos::Integer, button_id::Integer, label::String, bitmap::Ptr{Cvoid}, help_string::String)
    label_ws = wxString(label)
    help_string_ws = wxString(help_string)
    _result = KwxFFI.wxRibbonButtonBar_InsertHybridButton(obj.ptr, Csize_t(pos), Cint(button_id), label_ws.ptr, bitmap, help_string_ws.ptr)
    delete!(label_ws)
    delete!(help_string_ws)
    return _result
end

function (obj::wxRibbonButtonBar, pos::Integer, button_id::Integer, label::String, bitmap::Ptr{Cvoid}, help_string::String)
    label_ws = wxString(label)
    help_string_ws = wxString(help_string)
    _result = KwxFFI.wxRibbonButtonBar_InsertToggleButton(obj.ptr, Csize_t(pos), Cint(button_id), label_ws.ptr, bitmap, help_string_ws.ptr)
    delete!(label_ws)
    delete!(help_string_ws)
    return _result
end

function (obj::wxRibbonButtonBar)
    KwxFFI.wxRibbonButtonBar_ClearButtons(obj.ptr)
    nothing
end

function (obj::wxRibbonButtonBar, button_id::Integer)
    return KwxFFI.wxRibbonButtonBar_DeleteButton(obj.ptr, Cint(button_id)) != 0
end

function (obj::wxRibbonButtonBar, button_id::Integer, enable::Bool)
    KwxFFI.wxRibbonButtonBar_EnableButton(obj.ptr, Cint(button_id), Cint(enable))
    nothing
end

function (obj::wxRibbonButtonBar, button_id::Integer, bitmap::Ptr{Cvoid}, bitmap_small::Ptr{Cvoid}, bitmap_disabled::Ptr{Cvoid}, bitmap_small_disabled::Ptr{Cvoid})
    KwxFFI.wxRibbonButtonBar_SetButtonIcon(obj.ptr, Cint(button_id), bitmap, bitmap_small, bitmap_disabled, bitmap_small_disabled)
    nothing
end

function (obj::wxRibbonButtonBar, button_id::Integer, label::String)
    label_ws = wxString(label)
    KwxFFI.wxRibbonButtonBar_SetButtonText(obj.ptr, Cint(button_id), label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxRibbonButtonBar, button_id::Integer, min_width_medium::Integer, min_width_large::Integer)
    KwxFFI.wxRibbonButtonBar_SetButtonTextMinWidth_Int(obj.ptr, Cint(button_id), Cint(min_width_medium), Cint(min_width_large))
    nothing
end

function (obj::wxRibbonButtonBar, button_id::Integer, label::String)
    label_ws = wxString(label)
    KwxFFI.wxRibbonButtonBar_SetButtonTextMinWidth_String(obj.ptr, Cint(button_id), label_ws.ptr)
    delete!(label_ws)
    nothing
end

function (obj::wxRibbonButtonBar, button_id::Integer, min_class::Integer)
    KwxFFI.wxRibbonButtonBar_SetButtonMinSizeClass(obj.ptr, Cint(button_id), Cint(min_class))
    nothing
end

function (obj::wxRibbonButtonBar, button_id::Integer, max_class::Integer)
    KwxFFI.wxRibbonButtonBar_SetButtonMaxSizeClass(obj.ptr, Cint(button_id), Cint(max_class))
    nothing
end

function (obj::wxRibbonButtonBar)
    return KwxFFI.wxRibbonButtonBar_GetButtonCount(obj.ptr)
end

function (obj::wxRibbonButtonBar, index::Integer)
    return KwxFFI.wxRibbonButtonBar_GetItem(obj.ptr, Csize_t(index))
end

function (obj::wxRibbonButtonBar, button_id::Integer)
    return KwxFFI.wxRibbonButtonBar_GetItemById(obj.ptr, Cint(button_id))
end

function (obj::wxRibbonButtonBar, button::Ptr{Cvoid})
    return Int(KwxFFI.wxRibbonButtonBar_GetItemId(obj.ptr, button))
end

function (obj::wxRibbonButtonBar, button_id::Integer, x::Ptr{Cvoid}, y::Ptr{Cvoid}, width::Ptr{Cvoid}, height::Ptr{Cvoid})
    KwxFFI.wxRibbonButtonBar_GetItemRect(obj.ptr, Cint(button_id), x, y, width, height)
    nothing
end

function (obj::wxRibbonButtonBar)
    return KwxFFI.wxRibbonButtonBar_GetActiveItem(obj.ptr)
end

function (obj::wxRibbonButtonBar)
    return KwxFFI.wxRibbonButtonBar_GetHoveredItem(obj.ptr)
end

function (obj::wxRibbonButtonBar, item::Ptr{Cvoid}, data::Ptr{Cvoid})
    KwxFFI.wxRibbonButtonBar_SetItemClientData(obj.ptr, item, data)
    nothing
end

function (obj::wxRibbonButtonBar, item::Ptr{Cvoid})
    return KwxFFI.wxRibbonButtonBar_GetItemClientData(obj.ptr, item)
end

function (obj::wxRibbonButtonBar, show::Bool)
    KwxFFI.wxRibbonButtonBar_SetShowToolTipsForDisabled(obj.ptr, Cint(show))
    nothing
end

function (obj::wxRibbonButtonBar)
    return KwxFFI.wxRibbonButtonBar_GetShowToolTipsForDisabled(obj.ptr) != 0
end

function (obj::wxRibbonButtonBar)
    KwxFFI.wxRibbonButtonBar_Realize(obj.ptr)
    nothing
end

function (obj::wxRibbonButtonBar, art::Ptr{Cvoid})
    KwxFFI.wxRibbonButtonBar_SetArtProvider(obj.ptr, art)
    nothing
end

function (obj::wxRibbonButtonBar)
    return KwxFFI.wxRibbonButtonBar_GetArtProvider(obj.ptr)
end

