# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxRibbonBar <: wxObject
    ptr::Ptr{Cvoid}
end

function wxRibbonBar(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxRibbonBar_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxRibbonBar")
    obj = wxRibbonBar(ptr)
    return obj
end

function (obj::wxRibbonBar)
    KwxFFI.wxRibbonBar_DismissExpandedPanel(obj.ptr)
    nothing
end

function (obj::wxRibbonBar, index::Integer)
    return KwxFFI.wxRibbonBar_GetPage(obj.ptr, Cint(index))
end

function (obj::wxRibbonBar)
    return KwxFFI.wxRibbonBar_GetPageCount(obj.ptr)
end

function (obj::wxRibbonBar, index::Integer)
    return KwxFFI.wxRibbonBar_DeletePage(obj.ptr, Csize_t(index)) != 0
end

function (obj::wxRibbonBar)
    KwxFFI.wxRibbonBar_ClearPages(obj.ptr)
    nothing
end

function (obj::wxRibbonBar)
    return Int(KwxFFI.wxRibbonBar_GetActivePage(obj.ptr))
end

function (obj::wxRibbonBar, page::Integer)
    KwxFFI.wxRibbonBar_SetActivePage_ByIndex(obj.ptr, Csize_t(page))
    nothing
end

function (obj::wxRibbonBar, page::Ptr{Cvoid})
    KwxFFI.wxRibbonBar_SetActivePage_ByPtr(obj.ptr, page)
    nothing
end

function (obj::wxRibbonBar)
    KwxFFI.wxRibbonBar_Realize(obj.ptr)
    nothing
end

function (obj::wxRibbonBar, art::Ptr{Cvoid})
    KwxFFI.wxRibbonBar_SetArtProvider(obj.ptr, art)
    nothing
end

function (obj::wxRibbonBar)
    return KwxFFI.wxRibbonBar_GetArtProvider(obj.ptr)
end

