# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxRibbonPage <: wxObject
    ptr::Ptr{Cvoid}
end

function wxRibbonPage(parent::Union{wxWindow, Nothing}, id::Integer, label::String, icon::Ptr{Cvoid}, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    label_ws = wxString(label)
    ptr = KwxFFI.wxRibbonPage_Create(parent_ptr, Cint(id), label_ws.ptr, icon, Cint(style))
    delete!(label_ws)
    ptr == C_NULL && error("Failed to create wxRibbonPage")
    obj = wxRibbonPage(ptr)
    return obj
end

function (obj::wxRibbonPage)
    KwxFFI.wxRibbonPage_DismissExpandedPanel(obj.ptr)
    nothing
end

function (obj::wxRibbonPage, lines::Integer)
    return KwxFFI.wxRibbonPage_ScrollLines(obj.ptr, Cint(lines)) != 0
end

function (obj::wxRibbonPage, pixels::Integer)
    return KwxFFI.wxRibbonPage_ScrollPixels(obj.ptr, Cint(pixels)) != 0
end

function (obj::wxRibbonPage)
    return KwxFFI.wxRibbonPage_GetLabel(obj.ptr)
end

function (obj::wxRibbonPage)
    KwxFFI.wxRibbonPage_Realize(obj.ptr)
    nothing
end

function (obj::wxRibbonPage)
    return KwxFFI.wxRibbonPage_GetMinSize(obj.ptr)
end

function (obj::wxRibbonPage, art::Ptr{Cvoid})
    KwxFFI.wxRibbonPage_SetArtProvider(obj.ptr, art)
    nothing
end

function (obj::wxRibbonPage)
    return KwxFFI.wxRibbonPage_GetArtProvider(obj.ptr)
end

