# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxRichTextCtrl <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxRichTextCtrl(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxRichTextCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxRichTextCtrl")
    obj = wxRichTextCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_GetValue(obj.ptr)
end

function (obj::wxRichTextCtrl, value::String)
    value_ws = wxString(value)
    KwxFFI.wxRichTextCtrl_SetValue(obj.ptr, value_ws.ptr)
    delete!(value_ws)
    nothing
end

function (obj::wxRichTextCtrl, from::Integer, toPos::Integer)
    return KwxFFI.wxRichTextCtrl_GetRange(obj.ptr, Clong(from), Clong(toPos))
end

function (obj::wxRichTextCtrl, lineNo::Integer)
    return Int(KwxFFI.wxRichTextCtrl_GetLineLength(obj.ptr, Clong(lineNo)))
end

function (obj::wxRichTextCtrl, lineNo::Integer)
    return KwxFFI.wxRichTextCtrl_GetLineText(obj.ptr, Clong(lineNo))
end

function (obj::wxRichTextCtrl)
    return Int(KwxFFI.wxRichTextCtrl_GetNumberOfLines(obj.ptr))
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_IsModified(obj.ptr) != 0
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_MarkDirty(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_DiscardEdits(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_IsEditable(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, editable::Bool)
    KwxFFI.wxRichTextCtrl_SetEditable(obj.ptr, Cint(editable))
    nothing
end

function (obj::wxRichTextCtrl, from::Ptr{Cvoid}, to::Ptr{Cvoid})
    KwxFFI.wxRichTextCtrl_GetSelection(obj.ptr, from, to)
    nothing
end

function (obj::wxRichTextCtrl, from::Integer, toPos::Integer)
    KwxFFI.wxRichTextCtrl_SetSelection(obj.ptr, Clong(from), Clong(toPos))
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_SelectAll(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_SelectNone(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_GetStringSelection(obj.ptr)
end

function (obj::wxRichTextCtrl)
    return Int(KwxFFI.wxRichTextCtrl_GetInsertionPoint(obj.ptr))
end

function (obj::wxRichTextCtrl)
    return Int(KwxFFI.wxRichTextCtrl_GetLastPosition(obj.ptr))
end

function (obj::wxRichTextCtrl, pos::Integer)
    KwxFFI.wxRichTextCtrl_SetInsertionPoint(obj.ptr, Clong(pos))
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_SetInsertionPointEnd(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl, text::String)
    text_ws = wxString(text)
    KwxFFI.wxRichTextCtrl_WriteText(obj.ptr, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxRichTextCtrl, text::String)
    text_ws = wxString(text)
    KwxFFI.wxRichTextCtrl_AppendText(obj.ptr, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_Clear(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl, from::Integer, toPos::Integer, value::String)
    value_ws = wxString(value)
    KwxFFI.wxRichTextCtrl_Replace(obj.ptr, Clong(from), Clong(toPos), value_ws.ptr)
    delete!(value_ws)
    nothing
end

function (obj::wxRichTextCtrl, from::Integer, toPos::Integer)
    KwxFFI.wxRichTextCtrl_Remove(obj.ptr, Clong(from), Clong(toPos))
    nothing
end

function (obj::wxRichTextCtrl, file::String, type_::Integer)
    file_ws = wxString(file)
    _result = KwxFFI.wxRichTextCtrl_LoadFile(obj.ptr, file_ws.ptr, Cint(type_)) != 0
    delete!(file_ws)
    return _result
end

function (obj::wxRichTextCtrl, file::String, type_::Integer)
    file_ws = wxString(file)
    _result = KwxFFI.wxRichTextCtrl_SaveFile(obj.ptr, file_ws.ptr, Cint(type_)) != 0
    delete!(file_ws)
    return _result
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_GetFilename(obj.ptr)
end

function (obj::wxRichTextCtrl, filename::String)
    filename_ws = wxString(filename)
    KwxFFI.wxRichTextCtrl_SetFilename(obj.ptr, filename_ws.ptr)
    delete!(filename_ws)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_Undo(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_Redo(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_CanUndo(obj.ptr) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_CanRedo(obj.ptr) != 0
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_Copy(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_Cut(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_Paste(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_DeleteSelection(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_CanCopy(obj.ptr) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_CanCut(obj.ptr) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_CanPaste(obj.ptr) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_CanDeleteSelection(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, start::Integer, end_::Integer, style::Ptr{Cvoid})
    return KwxFFI.wxRichTextCtrl_SetStyle(obj.ptr, Clong(start), Clong(end_), style) != 0
end

function (obj::wxRichTextCtrl, position::Integer, style::Ptr{Cvoid})
    return KwxFFI.wxRichTextCtrl_GetStyle(obj.ptr, Clong(position), style) != 0
end

function (obj::wxRichTextCtrl, style::Ptr{Cvoid})
    return KwxFFI.wxRichTextCtrl_SetDefaultStyle(obj.ptr, style) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_GetDefaultStyle(obj.ptr)
end

function (obj::wxRichTextCtrl, font::Ptr{Cvoid})
    return KwxFFI.wxRichTextCtrl_SetFont(obj.ptr, font) != 0
end

function (obj::wxRichTextCtrl, start::Integer, end_::Integer, font::Ptr{Cvoid})
    return KwxFFI.wxRichTextCtrl_SetFontStyle(obj.ptr, Clong(start), Clong(end_), font) != 0
end

function (obj::wxRichTextCtrl, x::Integer, y::Integer)
    return Int(KwxFFI.wxRichTextCtrl_XYToPosition(obj.ptr, Clong(x), Clong(y)))
end

function (obj::wxRichTextCtrl, pos::Integer, x::Ptr{Cvoid}, y::Ptr{Cvoid})
    return KwxFFI.wxRichTextCtrl_PositionToXY(obj.ptr, Clong(pos), x, y) != 0
end

function (obj::wxRichTextCtrl, position::Integer)
    KwxFFI.wxRichTextCtrl_ShowPosition(obj.ptr, Clong(position))
    nothing
end

function (obj::wxRichTextCtrl, readOnly::Bool)
    KwxFFI.wxRichTextCtrl_SetReadOnly(obj.ptr, Cint(readOnly))
    nothing
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_IsReadOnly(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, onlyVisibleRect::Bool)
    return KwxFFI.wxRichTextCtrl_LayoutContent(obj.ptr, Cint(onlyVisibleRect)) != 0
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_ForceDelayedLayout(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl, position::Integer, keyCode::Integer)
    KwxFFI.wxRichTextCtrl_ScrollIntoView(obj.ptr, Clong(position), Cint(keyCode))
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_BeginBold(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_EndBold(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_BeginItalic(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_EndItalic(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_BeginUnderline(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl)
    KwxFFI.wxRichTextCtrl_EndUnderline(obj.ptr)
    nothing
end

function (obj::wxRichTextCtrl, pointSize::Integer)
    return KwxFFI.wxRichTextCtrl_BeginFontSize(obj.ptr, Cint(pointSize)) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndFontSize(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, font::Ptr{Cvoid})
    return KwxFFI.wxRichTextCtrl_BeginFont(obj.ptr, font) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndFont(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, colour::Ptr{Cvoid})
    return KwxFFI.wxRichTextCtrl_BeginTextColour(obj.ptr, colour) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndTextColour(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, alignment::Integer)
    return KwxFFI.wxRichTextCtrl_BeginAlignment(obj.ptr, Cint(alignment)) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndAlignment(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, leftIndent::Integer, leftSubIndent::Integer)
    return KwxFFI.wxRichTextCtrl_BeginLeftIndent(obj.ptr, Cint(leftIndent), Cint(leftSubIndent)) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndLeftIndent(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, rightIndent::Integer)
    return KwxFFI.wxRichTextCtrl_BeginRightIndent(obj.ptr, Cint(rightIndent)) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndRightIndent(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, before::Integer, after::Integer)
    return KwxFFI.wxRichTextCtrl_BeginParagraphSpacing(obj.ptr, Cint(before), Cint(after)) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndParagraphSpacing(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, lineSpacing::Integer)
    return KwxFFI.wxRichTextCtrl_BeginLineSpacing(obj.ptr, Cint(lineSpacing)) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndLineSpacing(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, bulletNumber::Integer, leftIndent::Integer, leftSubIndent::Integer, bulletStyle::Integer)
    return KwxFFI.wxRichTextCtrl_BeginNumberedBullet(obj.ptr, Cint(bulletNumber), Cint(leftIndent), Cint(leftSubIndent), Cint(bulletStyle)) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndNumberedBullet(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, symbol::String, leftIndent::Integer, leftSubIndent::Integer, bulletStyle::Integer)
    symbol_ws = wxString(symbol)
    _result = KwxFFI.wxRichTextCtrl_BeginSymbolBullet(obj.ptr, symbol_ws.ptr, Cint(leftIndent), Cint(leftSubIndent), Cint(bulletStyle)) != 0
    delete!(symbol_ws)
    return _result
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndSymbolBullet(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, bulletName::String, leftIndent::Integer, leftSubIndent::Integer, bulletStyle::Integer)
    bulletName_ws = wxString(bulletName)
    _result = KwxFFI.wxRichTextCtrl_BeginStandardBullet(obj.ptr, bulletName_ws.ptr, Cint(leftIndent), Cint(leftSubIndent), Cint(bulletStyle)) != 0
    delete!(bulletName_ws)
    return _result
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndStandardBullet(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, url::String, characterStyle::String)
    url_ws = wxString(url)
    characterStyle_ws = wxString(characterStyle)
    _result = KwxFFI.wxRichTextCtrl_BeginURL(obj.ptr, url_ws.ptr, characterStyle_ws.ptr) != 0
    delete!(url_ws)
    delete!(characterStyle_ws)
    return _result
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_EndURL(obj.ptr) != 0
end

function (obj::wxRichTextCtrl, image::Ptr{Cvoid}, bitmapType::Integer, textAttr::Ptr{Cvoid})
    return KwxFFI.wxRichTextCtrl_WriteImage(obj.ptr, image, Cint(bitmapType), textAttr) != 0
end

function (obj::wxRichTextCtrl, filename::String, bitmapType::Integer, textAttr::Ptr{Cvoid})
    filename_ws = wxString(filename)
    _result = KwxFFI.wxRichTextCtrl_WriteImageFile(obj.ptr, filename_ws.ptr, Cint(bitmapType), textAttr) != 0
    delete!(filename_ws)
    return _result
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_Newline(obj.ptr) != 0
end

function (obj::wxRichTextCtrl)
    return KwxFFI.wxRichTextCtrl_LineBreak(obj.ptr) != 0
end

