# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSashEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function wxSashEvent(id::Integer, edge::Integer)
    ptr = KwxFFI.wxSashEvent_Create(Cint(id), Cint(edge))
    ptr == C_NULL && error("Failed to create wxSashEvent")
    obj = wxSashEvent(ptr)
    return obj
end

function (obj::wxSashEvent)
    return KwxFFI.wxSashEvent_GetDragRect(obj.ptr)
end

function (obj::wxSashEvent)
    return Int(KwxFFI.wxSashEvent_GetDragStatus(obj.ptr))
end

function (obj::wxSashEvent)
    return Int(KwxFFI.wxSashEvent_GetEdge(obj.ptr))
end

function (obj::wxSashEvent, x::Integer, y::Integer, width::Integer, height::Integer)
    KwxFFI.wxSashEvent_SetDragRect(obj.ptr, Cint(x), Cint(y), Cint(width), Cint(height))
    nothing
end

function (obj::wxSashEvent, status::Integer)
    KwxFFI.wxSashEvent_SetDragStatus(obj.ptr, Cint(status))
    nothing
end

function (obj::wxSashEvent, edge::Integer)
    KwxFFI.wxSashEvent_SetEdge(obj.ptr, Cint(edge))
    nothing
end

