# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSashLayoutWindow <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxSashLayoutWindow(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxSashLayoutWindow_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxSashLayoutWindow")
    obj = wxSashLayoutWindow(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxSashLayoutWindow)
    return Int(KwxFFI.wxSashLayoutWindow_GetAlignment(obj.ptr))
end

function (obj::wxSashLayoutWindow)
    return Int(KwxFFI.wxSashLayoutWindow_GetOrientation(obj.ptr))
end

function (obj::wxSashLayoutWindow, align::Integer)
    KwxFFI.wxSashLayoutWindow_SetAlignment(obj.ptr, Cint(align))
    nothing
end

function (obj::wxSashLayoutWindow, width::Integer, height::Integer)
    KwxFFI.wxSashLayoutWindow_SetDefaultSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxSashLayoutWindow, orient::Integer)
    KwxFFI.wxSashLayoutWindow_SetOrientation(obj.ptr, Cint(orient))
    nothing
end

