# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSashWindow <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxSashWindow(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxSashWindow_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxSashWindow")
    obj = wxSashWindow(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxSashWindow)
    return Int(KwxFFI.wxSashWindow_GetDefaultBorderSize(obj.ptr))
end

function (obj::wxSashWindow, edge::Integer)
    return Int(KwxFFI.wxSashWindow_GetEdgeMargin(obj.ptr, Cint(edge)))
end

function (obj::wxSashWindow)
    return Int(KwxFFI.wxSashWindow_GetExtraBorderSize(obj.ptr))
end

function (obj::wxSashWindow)
    return Int(KwxFFI.wxSashWindow_GetMaximumSizeX(obj.ptr))
end

function (obj::wxSashWindow)
    return Int(KwxFFI.wxSashWindow_GetMaximumSizeY(obj.ptr))
end

function (obj::wxSashWindow)
    return Int(KwxFFI.wxSashWindow_GetMinimumSizeX(obj.ptr))
end

function (obj::wxSashWindow)
    return Int(KwxFFI.wxSashWindow_GetMinimumSizeY(obj.ptr))
end

function (obj::wxSashWindow, edge::Integer)
    return KwxFFI.wxSashWindow_GetSashVisible(obj.ptr, Cint(edge)) != 0
end

function (obj::wxSashWindow, edge::Integer)
    return KwxFFI.wxSashWindow_HasBorder(obj.ptr, Cint(edge)) != 0
end

function (obj::wxSashWindow, width::Integer)
    KwxFFI.wxSashWindow_SetDefaultBorderSize(obj.ptr, Cint(width))
    nothing
end

function (obj::wxSashWindow, width::Integer)
    KwxFFI.wxSashWindow_SetExtraBorderSize(obj.ptr, Cint(width))
    nothing
end

function (obj::wxSashWindow, max::Integer)
    KwxFFI.wxSashWindow_SetMaximumSizeX(obj.ptr, Cint(max))
    nothing
end

function (obj::wxSashWindow, max::Integer)
    KwxFFI.wxSashWindow_SetMaximumSizeY(obj.ptr, Cint(max))
    nothing
end

function (obj::wxSashWindow, min::Integer)
    KwxFFI.wxSashWindow_SetMinimumSizeX(obj.ptr, Cint(min))
    nothing
end

function (obj::wxSashWindow, min::Integer)
    KwxFFI.wxSashWindow_SetMinimumSizeY(obj.ptr, Cint(min))
    nothing
end

function (obj::wxSashWindow, edge::Integer, border::Bool)
    KwxFFI.wxSashWindow_SetSashBorder(obj.ptr, Cint(edge), Cint(border))
    nothing
end

function (obj::wxSashWindow, edge::Integer, sash::Bool)
    KwxFFI.wxSashWindow_SetSashVisible(obj.ptr, Cint(edge), Cint(sash))
    nothing
end

