# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxScrollBar <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxScrollBar(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxScrollBar_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxScrollBar")
    obj = wxScrollBar(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxScrollBar)
    return Int(KwxFFI.wxScrollBar_GetPageSize(obj.ptr))
end

function (obj::wxScrollBar)
    return Int(KwxFFI.wxScrollBar_GetRange(obj.ptr))
end

function (obj::wxScrollBar)
    return Int(KwxFFI.wxScrollBar_GetThumbPosition(obj.ptr))
end

function (obj::wxScrollBar)
    return Int(KwxFFI.wxScrollBar_GetThumbSize(obj.ptr))
end

function (obj::wxScrollBar, position::Integer, thumbSize::Integer, range::Integer, pageSize::Integer, refresh::Bool)
    KwxFFI.wxScrollBar_SetScrollbar(obj.ptr, Cint(position), Cint(thumbSize), Cint(range), Cint(pageSize), Cint(refresh))
    nothing
end

function (obj::wxScrollBar, viewStart::Integer)
    KwxFFI.wxScrollBar_SetThumbPosition(obj.ptr, Cint(viewStart))
    nothing
end

