# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxScrollEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxScrollEvent)
    return Int(KwxFFI.wxScrollEvent_GetOrientation(obj.ptr))
end

function (obj::wxScrollEvent)
    return Int(KwxFFI.wxScrollEvent_GetPosition(obj.ptr))
end

