# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxScrolledWindow <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxScrolledWindow(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxScrolledWindow_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxScrolledWindow")
    obj = wxScrolledWindow(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxScrolledWindow)
    KwxFFI.wxScrolledWindow_AdjustScrollbars(obj.ptr)
    nothing
end

function (obj::wxScrolledWindow, x::Integer, y::Integer, arg::Integer)
    KwxFFI.wxScrolledWindow_CalcScrolledPosition(obj.ptr, Cint(x), Cint(y), Cint(arg))
    nothing
end

function (obj::wxScrolledWindow, x::Integer, y::Integer, arg::Integer)
    KwxFFI.wxScrolledWindow_CalcUnscrolledPosition(obj.ptr, Cint(x), Cint(y), Cint(arg))
    nothing
end

function (obj::wxScrolledWindow, x_scrolling::Bool, y_scrolling::Bool)
    KwxFFI.wxScrolledWindow_EnableScrolling(obj.ptr, Cint(x_scrolling), Cint(y_scrolling))
    nothing
end

function (obj::wxScrolledWindow)
    return Float64(KwxFFI.wxScrolledWindow_GetScaleX(obj.ptr))
end

function (obj::wxScrolledWindow)
    return Float64(KwxFFI.wxScrolledWindow_GetScaleY(obj.ptr))
end

function (obj::wxScrolledWindow, orient::Integer)
    return Int(KwxFFI.wxScrolledWindow_GetScrollPageSize(obj.ptr, Cint(orient)))
end

function (obj::wxScrolledWindow, arg::Integer)
    KwxFFI.wxScrolledWindow_GetScrollPixelsPerUnit(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxScrolledWindow)
    return KwxFFI.wxScrolledWindow_GetTargetWindow(obj.ptr)
end

function (obj::wxScrolledWindow, arg::Integer)
    KwxFFI.wxScrolledWindow_GetViewStart(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxScrolledWindow, arg::Integer)
    KwxFFI.wxScrolledWindow_GetVirtualSize(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxScrolledWindow, dc::Ptr{Cvoid})
    KwxFFI.wxScrolledWindow_OnDraw(obj.ptr, dc)
    nothing
end

function (obj::wxScrolledWindow, dc::Ptr{Cvoid})
    KwxFFI.wxScrolledWindow_PrepareDC(obj.ptr, dc)
    nothing
end

function (obj::wxScrolledWindow, x_pos::Integer, y_pos::Integer)
    KwxFFI.wxScrolledWindow_Scroll(obj.ptr, Cint(x_pos), Cint(y_pos))
    nothing
end

function (obj::wxScrolledWindow, xScale::Float64, yScale::Float64)
    KwxFFI.wxScrolledWindow_SetScale(obj.ptr, Cdouble(xScale), Cdouble(yScale))
    nothing
end

function (obj::wxScrolledWindow, orient::Integer, pageSize::Integer)
    KwxFFI.wxScrolledWindow_SetScrollPageSize(obj.ptr, Cint(orient), Cint(pageSize))
    nothing
end

function (obj::wxScrolledWindow, pixelsPerUnitX::Integer, pixelsPerUnitY::Integer, noUnitsX::Integer, noUnitsY::Integer, xPos::Integer, yPos::Integer, noRefresh::Bool)
    KwxFFI.wxScrolledWindow_SetScrollbars(obj.ptr, Cint(pixelsPerUnitX), Cint(pixelsPerUnitY), Cint(noUnitsX), Cint(noUnitsY), Cint(xPos), Cint(yPos), Cint(noRefresh))
    nothing
end

function (obj::wxScrolledWindow, showh::Integer, showv::Integer)
    KwxFFI.wxScrolledWindow_ShowScrollbars(obj.ptr, Cint(showh), Cint(showv))
    nothing
end

function (obj::wxScrolledWindow, target::Ptr{Cvoid})
    KwxFFI.wxScrolledWindow_SetTargetWindow(obj.ptr, target)
    nothing
end

function (obj::wxScrolledWindow, arg::Integer)
    KwxFFI.wxScrolledWindow_ViewStart(obj.ptr, Cint(arg))
    nothing
end

function (obj::wxScrolledWindow, orient::Integer)
    return Int(KwxFFI.wxScrolledWindow_GetScrollLines(obj.ptr, Cint(orient)))
end

function (obj::wxScrolledWindow, orient::Integer)
    return KwxFFI.wxScrolledWindow_IsScrollbarShown(obj.ptr, Cint(orient)) != 0
end

function (obj::wxScrolledWindow)
    KwxFFI.wxScrolledWindow_DisableKeyboardScrolling(obj.ptr)
    nothing
end

function (obj::wxScrolledWindow, x::Ptr{Cvoid}, y::Ptr{Cvoid})
    KwxFFI.wxScrolledWindow_GetViewStartPixels(obj.ptr, x, y)
    nothing
end

