# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSetCursorEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxSetCursorEvent)
    return KwxFFI.wxSetCursorEvent_GetCursor(obj.ptr)
end

function (obj::wxSetCursorEvent)
    return Int(KwxFFI.wxSetCursorEvent_GetX(obj.ptr))
end

function (obj::wxSetCursorEvent)
    return Int(KwxFFI.wxSetCursorEvent_GetY(obj.ptr))
end

function (obj::wxSetCursorEvent)
    return KwxFFI.wxSetCursorEvent_HasCursor(obj.ptr) != 0
end

function (obj::wxSetCursorEvent, cursor::Ptr{Cvoid})
    KwxFFI.wxSetCursorEvent_SetCursor(obj.ptr, cursor)
    nothing
end

