# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSearchCtrl <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxSearchCtrl(parent::Union{wxWindow, Nothing}, id::Integer, value::String, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    value_ws = wxString(value)
    ptr = KwxFFI.wxSearchCtrl_Create(parent_ptr, Cint(id), value_ws.ptr, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    delete!(value_ws)
    ptr == C_NULL && error("Failed to create wxSearchCtrl")
    obj = wxSearchCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxSearchCtrl, menu::Ptr{Cvoid})
    KwxFFI.wxSearchCtrl_SetMenu(obj.ptr, menu)
    nothing
end

function (obj::wxSearchCtrl)
    return KwxFFI.wxSearchCtrl_GetMenu(obj.ptr)
end

function (obj::wxSearchCtrl, show::Bool)
    KwxFFI.wxSearchCtrl_ShowSearchButton(obj.ptr, Cint(show))
    nothing
end

function (obj::wxSearchCtrl)
    return KwxFFI.wxSearchCtrl_IsSearchButtonVisible(obj.ptr) != 0
end

function (obj::wxSearchCtrl, show::Bool)
    KwxFFI.wxSearchCtrl_ShowCancelButton(obj.ptr, Cint(show))
    nothing
end

function (obj::wxSearchCtrl)
    return KwxFFI.wxSearchCtrl_IsCancelButtonVisible(obj.ptr) != 0
end

function (obj::wxSearchCtrl, text::String)
    text_ws = wxString(text)
    KwxFFI.wxSearchCtrl_SetDescriptiveText(obj.ptr, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxSearchCtrl)
    return KwxFFI.wxSearchCtrl_GetDescriptiveText(obj.ptr)
end

