# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxShowEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxShowEvent, arg_ptr::Ptr{Cvoid})
    KwxFFI.wxShowEvent_CopyObject(obj.ptr, arg_ptr)
    nothing
end

function (obj::wxShowEvent)
    return KwxFFI.wxShowEvent_IsShown(obj.ptr) != 0
end

function (obj::wxShowEvent, show::Bool)
    KwxFFI.wxShowEvent_SetShow(obj.ptr, Cint(show))
    nothing
end

