# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSingleInstanceChecker <: wxObject
    ptr::Ptr{Cvoid}
end

function wxSingleInstanceChecker(pObject::Ptr{Cvoid}, name::String, path::String)
    name_ws = wxString(name)
    path_ws = wxString(path)
    ptr = KwxFFI.wxSingleInstanceChecker_Create(pObject, name_ws.ptr, path_ws.ptr)
    delete!(name_ws)
    delete!(path_ws)
    ptr == C_NULL && error("Failed to create wxSingleInstanceChecker")
    obj = wxSingleInstanceChecker(ptr)
    return obj
end

function wxSingleInstanceChecker()
    ptr = KwxFFI.wxSingleInstanceChecker_CreateDefault()
    ptr == C_NULL && error("Failed to create wxSingleInstanceChecker")
    obj = wxSingleInstanceChecker(ptr)
    return obj
end

function delete!(obj::wxSingleInstanceChecker)
    KwxFFI.wxSingleInstanceChecker_Delete(obj.ptr)
    nothing
end

function (obj::wxSingleInstanceChecker)
    return KwxFFI.wxSingleInstanceChecker_IsAnotherRunning(obj.ptr) != 0
end

