# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSimpleHtmlListBox <: wxObject
    ptr::Ptr{Cvoid}
end

function wxSimpleHtmlListBox(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxSimpleHtmlListBox_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxSimpleHtmlListBox")
    obj = wxSimpleHtmlListBox(ptr)
    return obj
end

function (obj::wxSimpleHtmlListBox)
    KwxFFI.wxSimpleHtmlListBox_Clear(obj.ptr)
    nothing
end

function delete!(obj::wxSimpleHtmlListBox, index::Integer)
    KwxFFI.wxSimpleHtmlListBox_Delete(obj.ptr, Cint(index))
    nothing
end

function (obj::wxSimpleHtmlListBox)
    return Int(KwxFFI.wxSimpleHtmlListBox_GetCount(obj.ptr))
end

function (obj::wxSimpleHtmlListBox, index::Integer)
    return KwxFFI.wxSimpleHtmlListBox_GetString(obj.ptr, Cint(index))
end

function (obj::wxSimpleHtmlListBox, index::Integer, str::String)
    str_ws = wxString(str)
    KwxFFI.wxSimpleHtmlListBox_SetString(obj.ptr, Cint(index), str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxSimpleHtmlListBox)
    return Int(KwxFFI.wxSimpleHtmlListBox_GetSelection(obj.ptr))
end

function (obj::wxSimpleHtmlListBox, index::Integer)
    KwxFFI.wxSimpleHtmlListBox_SetSelection(obj.ptr, Cint(index))
    nothing
end

function (obj::wxSimpleHtmlListBox, item::String)
    item_ws = wxString(item)
    _result = Int(KwxFFI.wxSimpleHtmlListBox_Append(obj.ptr, item_ws.ptr))
    delete!(item_ws)
    return _result
end

function (obj::wxSimpleHtmlListBox, item::String, data::Ptr{Cvoid})
    item_ws = wxString(item)
    _result = Int(KwxFFI.wxSimpleHtmlListBox_AppendData(obj.ptr, item_ws.ptr, data))
    delete!(item_ws)
    return _result
end

function (obj::wxSimpleHtmlListBox, item::String, pos::Integer)
    item_ws = wxString(item)
    _result = Int(KwxFFI.wxSimpleHtmlListBox_Insert(obj.ptr, item_ws.ptr, Cint(pos)))
    delete!(item_ws)
    return _result
end

function (obj::wxSimpleHtmlListBox, item::String, pos::Integer, data::Ptr{Cvoid})
    item_ws = wxString(item)
    _result = Int(KwxFFI.wxSimpleHtmlListBox_InsertData(obj.ptr, item_ws.ptr, Cint(pos), data))
    delete!(item_ws)
    return _result
end

function (obj::wxSimpleHtmlListBox, str::String, caseSensitive::Bool)
    str_ws = wxString(str)
    _result = Int(KwxFFI.wxSimpleHtmlListBox_FindString(obj.ptr, str_ws.ptr, Cint(caseSensitive)))
    delete!(str_ws)
    return _result
end

function (obj::wxSimpleHtmlListBox, index::Integer)
    return KwxFFI.wxSimpleHtmlListBox_GetClientData(obj.ptr, Cint(index))
end

function (obj::wxSimpleHtmlListBox, index::Integer, data::Ptr{Cvoid})
    KwxFFI.wxSimpleHtmlListBox_SetClientData(obj.ptr, Cint(index), data)
    nothing
end

function (obj::wxSimpleHtmlListBox)
    return KwxFFI.wxSimpleHtmlListBox_IsEmpty(obj.ptr) != 0
end

function (obj::wxSimpleHtmlListBox)
    return Int(KwxFFI.wxSimpleHtmlListBox_GetItemCount(obj.ptr))
end

