# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSize <: wxObject
    ptr::Ptr{Cvoid}
end

function wxSize(width::Integer, height::Integer)
    ptr = KwxFFI.wxSize_Create(Cint(width), Cint(height))
    ptr == C_NULL && error("Failed to create wxSize")
    obj = wxSize(ptr)
    return obj
end

function delete!(obj::wxSize)
    KwxFFI.wxSize_Delete(obj.ptr)
    nothing
end

function (obj::wxSize)
    return Int(KwxFFI.wxSize_GetHeight(obj.ptr))
end

function (obj::wxSize)
    return Int(KwxFFI.wxSize_GetWidth(obj.ptr))
end

function (obj::wxSize, height::Integer)
    KwxFFI.wxSize_SetHeight(obj.ptr, Cint(height))
    nothing
end

function (obj::wxSize, width::Integer)
    KwxFFI.wxSize_SetWidth(obj.ptr, Cint(width))
    nothing
end

