# Code generated by kwxgen. DO NOT EDIT.

function (obj::wxSizer, width::Integer, height::Integer, option::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    KwxFFI.wxSizer_Add(obj.ptr, Cint(width), Cint(height), Cint(option), Cint(flag), Cint(border), userData)
    nothing
end

function (obj::wxSizer, sizer::Ptr{Cvoid}, option::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    KwxFFI.wxSizer_AddSizer(obj.ptr, sizer, Cint(option), Cint(flag), Cint(border), userData)
    nothing
end

function (obj::wxSizer, window::Ptr{Cvoid}, option::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    KwxFFI.wxSizer_AddWindow(obj.ptr, window, Cint(option), Cint(flag), Cint(border), userData)
    nothing
end

function (obj::wxSizer)
    return KwxFFI.wxSizer_CalcMin(obj.ptr)
end

function (obj::wxSizer, window::Ptr{Cvoid})
    KwxFFI.wxSizer_Fit(obj.ptr, window)
    nothing
end

function (obj::wxSizer, result::Ptr{Cvoid}, count::Integer)
    return Int(KwxFFI.wxSizer_GetChildren(obj.ptr, result, Cint(count)))
end

function (obj::wxSizer)
    return KwxFFI.wxSizer_GetMinSize(obj.ptr)
end

function (obj::wxSizer)
    return KwxFFI.wxSizer_GetPosition(obj.ptr)
end

function (obj::wxSizer)
    return KwxFFI.wxSizer_GetSize(obj.ptr)
end

function (obj::wxSizer, before::Integer, width::Integer, height::Integer, option::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    KwxFFI.wxSizer_Insert(obj.ptr, Cint(before), Cint(width), Cint(height), Cint(option), Cint(flag), Cint(border), userData)
    nothing
end

function (obj::wxSizer, before::Integer, sizer::Ptr{Cvoid}, option::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    KwxFFI.wxSizer_InsertSizer(obj.ptr, Cint(before), sizer, Cint(option), Cint(flag), Cint(border), userData)
    nothing
end

function (obj::wxSizer, before::Integer, window::Ptr{Cvoid}, option::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    KwxFFI.wxSizer_InsertWindow(obj.ptr, Cint(before), window, Cint(option), Cint(flag), Cint(border), userData)
    nothing
end

function (obj::wxSizer)
    KwxFFI.wxSizer_Layout(obj.ptr)
    nothing
end

function (obj::wxSizer, width::Integer, height::Integer, option::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    KwxFFI.wxSizer_Prepend(obj.ptr, Cint(width), Cint(height), Cint(option), Cint(flag), Cint(border), userData)
    nothing
end

function (obj::wxSizer, sizer::Ptr{Cvoid}, option::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    KwxFFI.wxSizer_PrependSizer(obj.ptr, sizer, Cint(option), Cint(flag), Cint(border), userData)
    nothing
end

function (obj::wxSizer, window::Ptr{Cvoid}, option::Integer, flag::Integer, border::Integer, userData::Ptr{Cvoid})
    KwxFFI.wxSizer_PrependWindow(obj.ptr, window, Cint(option), Cint(flag), Cint(border), userData)
    nothing
end

function (obj::wxSizer)
    KwxFFI.wxSizer_RecalcSizes(obj.ptr)
    nothing
end

function (obj::wxSizer, x::Integer, y::Integer, width::Integer, height::Integer)
    KwxFFI.wxSizer_SetDimension(obj.ptr, Cint(x), Cint(y), Cint(width), Cint(height))
    nothing
end

function (obj::wxSizer, pos::Integer, width::Integer, height::Integer)
    KwxFFI.wxSizer_SetItemMinSize(obj.ptr, Cint(pos), Cint(width), Cint(height))
    nothing
end

function (obj::wxSizer, sizer::Ptr{Cvoid}, width::Integer, height::Integer)
    KwxFFI.wxSizer_SetItemMinSizeSizer(obj.ptr, sizer, Cint(width), Cint(height))
    nothing
end

function (obj::wxSizer, window::Ptr{Cvoid}, width::Integer, height::Integer)
    KwxFFI.wxSizer_SetItemMinSizeWindow(obj.ptr, window, Cint(width), Cint(height))
    nothing
end

function (obj::wxSizer, width::Integer, height::Integer)
    KwxFFI.wxSizer_SetMinSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxSizer, window::Ptr{Cvoid})
    KwxFFI.wxSizer_SetSizeHints(obj.ptr, window)
    nothing
end

function (obj::wxSizer, size::Integer)
    KwxFFI.wxSizer_AddSpacer(obj.ptr, Cint(size))
    nothing
end

function (obj::wxSizer, size::Integer)
    KwxFFI.wxSizer_AddStretchSpacer(obj.ptr, Cint(size))
    nothing
end

function (obj::wxSizer, delete_windows::Bool)
    KwxFFI.wxSizer_Clear(obj.ptr, Cint(delete_windows))
    nothing
end

function (obj::wxSizer, window::Ptr{Cvoid})
    return KwxFFI.wxSizer_DetachWindow(obj.ptr, window) != 0
end

function (obj::wxSizer, sizer::Ptr{Cvoid})
    return KwxFFI.wxSizer_DetachSizer(obj.ptr, sizer) != 0
end

function (obj::wxSizer, index::Integer)
    return KwxFFI.wxSizer_Detach(obj.ptr, Cint(index)) != 0
end

function (obj::wxSizer, window::Ptr{Cvoid})
    KwxFFI.wxSizer_FitInside(obj.ptr, window)
    nothing
end

function (obj::wxSizer)
    return KwxFFI.wxSizer_GetContainingWindow(obj.ptr)
end

function (obj::wxSizer, window::Ptr{Cvoid}, recursive::Bool)
    return KwxFFI.wxSizer_GetItemWindow(obj.ptr, window, Cint(recursive))
end

function (obj::wxSizer, window::Ptr{Cvoid}, recursive::Bool)
    return KwxFFI.wxSizer_GetItemSizer(obj.ptr, window, Cint(recursive))
end

function (obj::wxSizer, index::Integer)
    return KwxFFI.wxSizer_GetItem(obj.ptr, Cint(index))
end

function (obj::wxSizer, window::Ptr{Cvoid})
    return KwxFFI.wxSizer_HideWindow(obj.ptr, window) != 0
end

function (obj::wxSizer, sizer::Ptr{Cvoid})
    return KwxFFI.wxSizer_HideSizer(obj.ptr, sizer) != 0
end

function (obj::wxSizer, index::Integer)
    return KwxFFI.wxSizer_Hide(obj.ptr, Cint(index)) != 0
end

function (obj::wxSizer, index::Integer, size::Integer)
    return KwxFFI.wxSizer_InsertSpacer(obj.ptr, Cint(index), Cint(size))
end

function (obj::wxSizer, index::Integer, prop::Integer)
    return KwxFFI.wxSizer_InsertStretchSpacer(obj.ptr, Cint(index), Cint(prop))
end

function (obj::wxSizer, window::Ptr{Cvoid})
    return KwxFFI.wxSizer_IsShownWindow(obj.ptr, window) != 0
end

function (obj::wxSizer, sizer::Ptr{Cvoid})
    return KwxFFI.wxSizer_IsShownSizer(obj.ptr, sizer) != 0
end

function (obj::wxSizer, index::Integer)
    return KwxFFI.wxSizer_IsShown(obj.ptr, Cint(index)) != 0
end

function (obj::wxSizer, size::Integer)
    return KwxFFI.wxSizer_PrependSpacer(obj.ptr, Cint(size))
end

function (obj::wxSizer, prop::Integer)
    return KwxFFI.wxSizer_PrependStretchSpacer(obj.ptr, Cint(prop))
end

function (obj::wxSizer, oldwin::Ptr{Cvoid}, newwin::Ptr{Cvoid}, recursive::Bool)
    return KwxFFI.wxSizer_ReplaceWindow(obj.ptr, oldwin, newwin, Cint(recursive)) != 0
end

function (obj::wxSizer, oldsz::Ptr{Cvoid}, newsz::Ptr{Cvoid}, recursive::Bool)
    return KwxFFI.wxSizer_ReplaceSizer(obj.ptr, oldsz, newsz, Cint(recursive)) != 0
end

function (obj::wxSizer, oldindex::Integer, newitem::Ptr{Cvoid})
    return KwxFFI.wxSizer_Replace(obj.ptr, Cint(oldindex), newitem) != 0
end

function (obj::wxSizer, window::Ptr{Cvoid}, show::Bool, recursive::Bool)
    return KwxFFI.wxSizer_ShowWindow(obj.ptr, window, Cint(show), Cint(recursive)) != 0
end

function (obj::wxSizer, sizer::Ptr{Cvoid}, show::Bool, recursive::Bool)
    return KwxFFI.wxSizer_ShowSizer(obj.ptr, sizer, Cint(show), Cint(recursive)) != 0
end

function (obj::wxSizer, sizer::Ptr{Cvoid}, index::Integer, show::Bool)
    return KwxFFI.wxSizer_Show(obj.ptr, sizer, Cint(index), Cint(show)) != 0
end

