# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSlider <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxSlider(parent::Union{wxWindow, Nothing}, id::Integer, init::Integer, minVal::Integer, maxVal::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxSlider_Create(parent_ptr, Cint(id), Cint(init), Cint(minVal), Cint(maxVal), Cint(left), Cint(top), Cint(width), Cint(height), Clong(style))
    ptr == C_NULL && error("Failed to create wxSlider")
    obj = wxSlider(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxSlider)
    KwxFFI.wxSlider_ClearSel(obj.ptr)
    nothing
end

function (obj::wxSlider)
    KwxFFI.wxSlider_ClearTicks(obj.ptr)
    nothing
end

function (obj::wxSlider)
    return Int(KwxFFI.wxSlider_GetLineSize(obj.ptr))
end

function (obj::wxSlider)
    return Int(KwxFFI.wxSlider_GetMax(obj.ptr))
end

function (obj::wxSlider)
    return Int(KwxFFI.wxSlider_GetMin(obj.ptr))
end

function (obj::wxSlider)
    return Int(KwxFFI.wxSlider_GetPageSize(obj.ptr))
end

function (obj::wxSlider)
    return Int(KwxFFI.wxSlider_GetSelEnd(obj.ptr))
end

function (obj::wxSlider)
    return Int(KwxFFI.wxSlider_GetSelStart(obj.ptr))
end

function (obj::wxSlider)
    return Int(KwxFFI.wxSlider_GetThumbLength(obj.ptr))
end

function (obj::wxSlider)
    return Int(KwxFFI.wxSlider_GetTickFreq(obj.ptr))
end

function (obj::wxSlider)
    return Int(KwxFFI.wxSlider_GetValue(obj.ptr))
end

function (obj::wxSlider, lineSize::Integer)
    KwxFFI.wxSlider_SetLineSize(obj.ptr, Cint(lineSize))
    nothing
end

function (obj::wxSlider, pageSize::Integer)
    KwxFFI.wxSlider_SetPageSize(obj.ptr, Cint(pageSize))
    nothing
end

function (obj::wxSlider, minValue::Integer, maxValue::Integer)
    KwxFFI.wxSlider_SetRange(obj.ptr, Cint(minValue), Cint(maxValue))
    nothing
end

function (obj::wxSlider, minPos::Integer, maxPos::Integer)
    KwxFFI.wxSlider_SetSelection(obj.ptr, Cint(minPos), Cint(maxPos))
    nothing
end

function (obj::wxSlider, len::Integer)
    KwxFFI.wxSlider_SetThumbLength(obj.ptr, Cint(len))
    nothing
end

function (obj::wxSlider, tickPos::Integer)
    KwxFFI.wxSlider_SetTick(obj.ptr, Cint(tickPos))
    nothing
end

function (obj::wxSlider, value::Integer)
    KwxFFI.wxSlider_SetValue(obj.ptr, Cint(value))
    nothing
end

