# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSpinCtrlDouble <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxSpinCtrlDouble(parent::Union{wxWindow, Nothing}, id::Integer, value::String, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer, min::Float64, max::Float64, initial::Float64, inc::Float64)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    value_ws = wxString(value)
    ptr = KwxFFI.wxSpinCtrlDouble_Create(parent_ptr, Cint(id), value_ws.ptr, Cint(x), Cint(y), Cint(width), Cint(height), Cint(style), Cdouble(min), Cdouble(max), Cdouble(initial), Cdouble(inc))
    delete!(value_ws)
    ptr == C_NULL && error("Failed to create wxSpinCtrlDouble")
    obj = wxSpinCtrlDouble(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxSpinCtrlDouble)
    return Float64(KwxFFI.wxSpinCtrlDouble_GetValue(obj.ptr))
end

function (obj::wxSpinCtrlDouble, value::Float64)
    KwxFFI.wxSpinCtrlDouble_SetValue(obj.ptr, Cdouble(value))
    nothing
end

function (obj::wxSpinCtrlDouble, value::String)
    value_ws = wxString(value)
    KwxFFI.wxSpinCtrlDouble_SetValueString(obj.ptr, value_ws.ptr)
    delete!(value_ws)
    nothing
end

function (obj::wxSpinCtrlDouble, minVal::Float64, maxVal::Float64)
    KwxFFI.wxSpinCtrlDouble_SetRange(obj.ptr, Cdouble(minVal), Cdouble(maxVal))
    nothing
end

function (obj::wxSpinCtrlDouble)
    return Float64(KwxFFI.wxSpinCtrlDouble_GetMin(obj.ptr))
end

function (obj::wxSpinCtrlDouble)
    return Float64(KwxFFI.wxSpinCtrlDouble_GetMax(obj.ptr))
end

function (obj::wxSpinCtrlDouble, inc::Float64)
    KwxFFI.wxSpinCtrlDouble_SetIncrement(obj.ptr, Cdouble(inc))
    nothing
end

function (obj::wxSpinCtrlDouble)
    return Float64(KwxFFI.wxSpinCtrlDouble_GetIncrement(obj.ptr))
end

function (obj::wxSpinCtrlDouble, digits::Integer)
    KwxFFI.wxSpinCtrlDouble_SetDigits(obj.ptr, Cuint(digits))
    nothing
end

function (obj::wxSpinCtrlDouble)
    return KwxFFI.wxSpinCtrlDouble_GetDigits(obj.ptr)
end

