# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSpinCtrl <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxSpinCtrl(parent::Union{wxWindow, Nothing}, id::Integer, text::String, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer, minVal::Integer, maxVal::Integer, init::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    text_ws = wxString(text)
    ptr = KwxFFI.wxSpinCtrl_Create(parent_ptr, Cint(id), text_ws.ptr, Cint(left), Cint(top), Cint(width), Cint(height), Clong(style), Cint(minVal), Cint(maxVal), Cint(init))
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxSpinCtrl")
    obj = wxSpinCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxSpinCtrl)
    return Int(KwxFFI.wxSpinCtrl_GetBase(obj.ptr))
end

function (obj::wxSpinCtrl, base::Integer)
    return KwxFFI.wxSpinCtrl_SetBase(obj.ptr, Cint(base)) != 0
end

function (obj::wxSpinCtrl)
    return Int(KwxFFI.wxSpinCtrl_GetMax(obj.ptr))
end

function (obj::wxSpinCtrl)
    return Int(KwxFFI.wxSpinCtrl_GetMin(obj.ptr))
end

function (obj::wxSpinCtrl)
    return Int(KwxFFI.wxSpinCtrl_GetValue(obj.ptr))
end

function (obj::wxSpinCtrl, min_val::Integer, max_val::Integer)
    KwxFFI.wxSpinCtrl_SetRange(obj.ptr, Cint(min_val), Cint(max_val))
    nothing
end

function (obj::wxSpinCtrl, val::Integer)
    KwxFFI.wxSpinCtrl_SetValue(obj.ptr, Cint(val))
    nothing
end

