# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSpinButton <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxSpinButton(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxSpinButton_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Clong(style))
    ptr == C_NULL && error("Failed to create wxSpinButton")
    obj = wxSpinButton(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxSpinButton)
    return Int(KwxFFI.wxSpinButton_GetMax(obj.ptr))
end

function (obj::wxSpinButton)
    return Int(KwxFFI.wxSpinButton_GetMin(obj.ptr))
end

function (obj::wxSpinButton)
    return Int(KwxFFI.wxSpinButton_GetValue(obj.ptr))
end

function (obj::wxSpinButton, minVal::Integer, maxVal::Integer)
    KwxFFI.wxSpinButton_SetRange(obj.ptr, Cint(minVal), Cint(maxVal))
    nothing
end

function (obj::wxSpinButton, val::Integer)
    KwxFFI.wxSpinButton_SetValue(obj.ptr, Cint(val))
    nothing
end

