# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxSpinEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxSpinEvent)
    return Int(KwxFFI.wxSpinEvent_GetPosition(obj.ptr))
end

function (obj::wxSpinEvent, pos::Integer)
    KwxFFI.wxSpinEvent_SetPosition(obj.ptr, Cint(pos))
    nothing
end

