# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxStatusBar <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxStatusBar(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxStatusBar_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxStatusBar")
    obj = wxStatusBar(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxStatusBar)
    return Int(KwxFFI.wxStatusBar_GetBorderX(obj.ptr))
end

function (obj::wxStatusBar)
    return Int(KwxFFI.wxStatusBar_GetBorderY(obj.ptr))
end

function (obj::wxStatusBar)
    return Int(KwxFFI.wxStatusBar_GetFieldsCount(obj.ptr))
end

function (obj::wxStatusBar, number::Integer)
    return KwxFFI.wxStatusBar_GetStatusText(obj.ptr, Cint(number))
end

function (obj::wxStatusBar, number::Integer, widths::Ptr{Cvoid})
    KwxFFI.wxStatusBar_SetFieldsCount(obj.ptr, Cint(number), widths)
    nothing
end

function (obj::wxStatusBar, height::Integer)
    KwxFFI.wxStatusBar_SetMinHeight(obj.ptr, Cint(height))
    nothing
end

function (obj::wxStatusBar, text::String, number::Integer)
    text_ws = wxString(text)
    KwxFFI.wxStatusBar_SetStatusText(obj.ptr, text_ws.ptr, Cint(number))
    delete!(text_ws)
    nothing
end

function (obj::wxStatusBar, count::Integer, widths::Ptr{Cvoid})
    KwxFFI.wxStatusBar_SetStatusWidths(obj.ptr, Cint(count), widths)
    nothing
end

function (obj::wxStatusBar, i::Integer, x::Ptr{Cvoid}, y::Ptr{Cvoid}, w::Ptr{Cvoid}, h::Ptr{Cvoid})
    return KwxFFI.wxStatusBar_GetFieldRect(obj.ptr, Cint(i), x, y, w, h) != 0
end

function (obj::wxStatusBar, n::Integer, styles::Ptr{Cvoid})
    KwxFFI.wxStatusBar_SetStatusStyles(obj.ptr, Cint(n), styles)
    nothing
end

function (obj::wxStatusBar, text::String, field::Integer)
    text_ws = wxString(text)
    KwxFFI.wxStatusBar_PushStatusText(obj.ptr, text_ws.ptr, Cint(field))
    delete!(text_ws)
    nothing
end

function (obj::wxStatusBar, field::Integer)
    KwxFFI.wxStatusBar_PopStatusText(obj.ptr, Cint(field))
    nothing
end

function (obj::wxStatusBar, n::Integer)
    return Int(KwxFFI.wxStatusBar_GetStatusWidth(obj.ptr, Cint(n)))
end

function (obj::wxStatusBar, n::Integer)
    return Int(KwxFFI.wxStatusBar_GetStatusStyle(obj.ptr, Cint(n)))
end

