# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxStaticLine <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxStaticLine(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxStaticLine_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxStaticLine")
    obj = wxStaticLine(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxStaticLine)
    return Int(KwxFFI.wxStaticLine_GetDefaultSize(obj.ptr))
end

function (obj::wxStaticLine)
    return KwxFFI.wxStaticLine_IsVertical(obj.ptr) != 0
end

