# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxStdDialogButtonSizer <: wxSizer
    ptr::Ptr{Cvoid}
end

function wxStdDialogButtonSizer()
    ptr = KwxFFI.wxStdDialogButtonSizer_Create()
    ptr == C_NULL && error("Failed to create wxStdDialogButtonSizer")
    obj = wxStdDialogButtonSizer(ptr)
    return obj
end

function (obj::wxStdDialogButtonSizer, button::Ptr{Cvoid})
    KwxFFI.wxStdDialogButtonSizer_AddButton(obj.ptr, button)
    nothing
end

function (obj::wxStdDialogButtonSizer, button::Ptr{Cvoid})
    KwxFFI.wxStdDialogButtonSizer_SetAffirmativeButton(obj.ptr, button)
    nothing
end

function (obj::wxStdDialogButtonSizer, button::Ptr{Cvoid})
    KwxFFI.wxStdDialogButtonSizer_SetNegativeButton(obj.ptr, button)
    nothing
end

function (obj::wxStdDialogButtonSizer, button::Ptr{Cvoid})
    KwxFFI.wxStdDialogButtonSizer_SetCancelButton(obj.ptr, button)
    nothing
end

function (obj::wxStdDialogButtonSizer)
    KwxFFI.wxStdDialogButtonSizer_Realize(obj.ptr)
    nothing
end

function (obj::wxStdDialogButtonSizer)
    return KwxFFI.wxStdDialogButtonSizer_GetAffirmativeButton(obj.ptr)
end

function (obj::wxStdDialogButtonSizer)
    return KwxFFI.wxStdDialogButtonSizer_GetApplyButton(obj.ptr)
end

function (obj::wxStdDialogButtonSizer)
    return KwxFFI.wxStdDialogButtonSizer_GetNegativeButton(obj.ptr)
end

function (obj::wxStdDialogButtonSizer)
    return KwxFFI.wxStdDialogButtonSizer_GetCancelButton(obj.ptr)
end

function (obj::wxStdDialogButtonSizer)
    return KwxFFI.wxStdDialogButtonSizer_GetHelpButton(obj.ptr)
end

