# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxStaticBoxSizer <: wxSizer
    ptr::Ptr{Cvoid}
end

function wxStaticBoxSizer(box::Ptr{Cvoid}, orient::Integer)
    ptr = KwxFFI.wxStaticBoxSizer_Create(box, Cint(orient))
    ptr == C_NULL && error("Failed to create wxStaticBoxSizer")
    obj = wxStaticBoxSizer(ptr)
    return obj
end

function (obj::wxStaticBoxSizer)
    return KwxFFI.wxStaticBoxSizer_CalcMin(obj.ptr)
end

function (obj::wxStaticBoxSizer)
    return KwxFFI.wxStaticBoxSizer_GetStaticBox(obj.ptr)
end

function (obj::wxStaticBoxSizer)
    KwxFFI.wxStaticBoxSizer_RecalcSizes(obj.ptr)
    nothing
end

