# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxStaticText <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxStaticText(parent::Union{wxWindow, Nothing}, id::Integer, text::String, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    text_ws = wxString(text)
    ptr = KwxFFI.wxStaticText_Create(parent_ptr, Cint(id), text_ws.ptr, Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxStaticText")
    obj = wxStaticText(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxStaticText, width::Integer)
    KwxFFI.wxStaticText_Wrap(obj.ptr, Cint(width))
    nothing
end

function (obj::wxStaticText)
    return KwxFFI.wxStaticText_IsEllipsized(obj.ptr) != 0
end

