# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTaskBarIcon <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function wxTaskBarIcon()
    ptr = KwxFFI.wxTaskBarIcon_Create()
    ptr == C_NULL && error("Failed to create wxTaskBarIcon")
    obj = wxTaskBarIcon(ptr)
    return obj
end

function delete!(obj::wxTaskBarIcon)
    KwxFFI.wxTaskBarIcon_Delete(obj.ptr)
    nothing
end

function (obj::wxTaskBarIcon)
    return KwxFFI.wxTaskBarIcon_IsOk(obj.ptr) != 0
end

function (obj::wxTaskBarIcon, menu::Ptr{Cvoid})
    return KwxFFI.wxTaskBarIcon_PopupMenu(obj.ptr, menu) != 0
end

function (obj::wxTaskBarIcon)
    return KwxFFI.wxTaskBarIcon_RemoveIcon(obj.ptr) != 0
end

function (obj::wxTaskBarIcon, icon::Ptr{Cvoid}, text::String)
    text_ws = wxString(text)
    _result = KwxFFI.wxTaskBarIcon_SetIcon(obj.ptr, icon, text_ws.ptr) != 0
    delete!(text_ws)
    return _result
end

