# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTextCtrl <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxTextCtrl(parent::Union{wxWindow, Nothing}, id::Integer, text::String, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    text_ws = wxString(text)
    ptr = KwxFFI.wxTextCtrl_Create(parent_ptr, Cint(id), text_ws.ptr, Cint(left), Cint(top), Cint(width), Cint(height), Clong(style))
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxTextCtrl")
    obj = wxTextCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxTextCtrl, text::String)
    text_ws = wxString(text)
    KwxFFI.wxTextCtrl_AppendText(obj.ptr, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_CanCopy(obj.ptr) != 0
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_CanCut(obj.ptr) != 0
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_CanPaste(obj.ptr) != 0
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_CanRedo(obj.ptr) != 0
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_CanUndo(obj.ptr) != 0
end

function (obj::wxTextCtrl, text::String)
    text_ws = wxString(text)
    KwxFFI.wxTextCtrl_ChangeValue(obj.ptr, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_Clear(obj.ptr)
    nothing
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_Copy(obj.ptr)
    nothing
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_Cut(obj.ptr)
    nothing
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_DiscardEdits(obj.ptr)
    nothing
end

function (obj::wxTextCtrl)
    return Int(KwxFFI.wxTextCtrl_GetInsertionPoint(obj.ptr))
end

function (obj::wxTextCtrl)
    return Int(KwxFFI.wxTextCtrl_GetLastPosition(obj.ptr))
end

function (obj::wxTextCtrl, lineNo::Integer)
    return Int(KwxFFI.wxTextCtrl_GetLineLength(obj.ptr, Clong(lineNo)))
end

function (obj::wxTextCtrl, lineNo::Integer)
    return KwxFFI.wxTextCtrl_GetLineText(obj.ptr, Clong(lineNo))
end

function (obj::wxTextCtrl)
    return Int(KwxFFI.wxTextCtrl_GetNumberOfLines(obj.ptr))
end

function (obj::wxTextCtrl, from::Ptr{Cvoid}, toPos::Ptr{Cvoid})
    KwxFFI.wxTextCtrl_GetSelection(obj.ptr, from, toPos)
    nothing
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_GetValue(obj.ptr)
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_IsEditable(obj.ptr) != 0
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_IsModified(obj.ptr) != 0
end

function (obj::wxTextCtrl, file::String, fileType::Integer)
    file_ws = wxString(file)
    _result = KwxFFI.wxTextCtrl_LoadFile(obj.ptr, file_ws.ptr, Cint(fileType)) != 0
    delete!(file_ws)
    return _result
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_Paste(obj.ptr)
    nothing
end

function (obj::wxTextCtrl, pos::Integer, x::Ptr{Cvoid}, y::Ptr{Cvoid})
    return Int(KwxFFI.wxTextCtrl_PositionToXY(obj.ptr, Clong(pos), x, y))
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_Redo(obj.ptr)
    nothing
end

function (obj::wxTextCtrl, from::Integer, toPos::Integer)
    KwxFFI.wxTextCtrl_Remove(obj.ptr, Clong(from), Clong(toPos))
    nothing
end

function (obj::wxTextCtrl, from::Integer, toPos::Integer, value::String)
    value_ws = wxString(value)
    KwxFFI.wxTextCtrl_Replace(obj.ptr, Clong(from), Clong(toPos), value_ws.ptr)
    delete!(value_ws)
    nothing
end

function (obj::wxTextCtrl, file::String, fileType::Integer)
    file_ws = wxString(file)
    _result = KwxFFI.wxTextCtrl_SaveFile(obj.ptr, file_ws.ptr, Cint(fileType)) != 0
    delete!(file_ws)
    return _result
end

function (obj::wxTextCtrl, editable::Bool)
    KwxFFI.wxTextCtrl_SetEditable(obj.ptr, Cint(editable))
    nothing
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_MarkDirty(obj.ptr)
    nothing
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_IsSingleLine(obj.ptr) != 0
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_IsMultiLine(obj.ptr) != 0
end

function (obj::wxTextCtrl, modified::Bool)
    KwxFFI.wxTextCtrl_SetModified(obj.ptr, Cint(modified))
    nothing
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_EmptyUndoBuffer(obj.ptr)
    nothing
end

function (obj::wxTextCtrl)
    return KwxFFI.wxTextCtrl_GetDefaultStyle(obj.ptr)
end

function (obj::wxTextCtrl, position::Integer, style::Ptr{Cvoid})
    return KwxFFI.wxTextCtrl_GetStyle(obj.ptr, Clong(position), style) != 0
end

function (obj::wxTextCtrl, style::Ptr{Cvoid})
    return KwxFFI.wxTextCtrl_SetDefaultStyle(obj.ptr, style) != 0
end

function (obj::wxTextCtrl, len::Integer)
    KwxFFI.wxTextCtrl_SetMaxLength(obj.ptr, Clong(len))
    nothing
end

function (obj::wxTextCtrl, start::Integer, end_::Integer, style::Ptr{Cvoid})
    return KwxFFI.wxTextCtrl_SetStyle(obj.ptr, Clong(start), Clong(end_), style) != 0
end

function (obj::wxTextCtrl, pos::Integer)
    KwxFFI.wxTextCtrl_SetInsertionPoint(obj.ptr, Clong(pos))
    nothing
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_SetInsertionPointEnd(obj.ptr)
    nothing
end

function (obj::wxTextCtrl, from::Integer, toPos::Integer)
    KwxFFI.wxTextCtrl_SetSelection(obj.ptr, Clong(from), Clong(toPos))
    nothing
end

function (obj::wxTextCtrl, value::String)
    value_ws = wxString(value)
    KwxFFI.wxTextCtrl_SetValue(obj.ptr, value_ws.ptr)
    delete!(value_ws)
    nothing
end

function (obj::wxTextCtrl, pos::Integer)
    KwxFFI.wxTextCtrl_ShowPosition(obj.ptr, Clong(pos))
    nothing
end

function (obj::wxTextCtrl)
    KwxFFI.wxTextCtrl_Undo(obj.ptr)
    nothing
end

function (obj::wxTextCtrl, text::String)
    text_ws = wxString(text)
    KwxFFI.wxTextCtrl_WriteText(obj.ptr, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxTextCtrl, x::Integer, y::Integer)
    return Int(KwxFFI.wxTextCtrl_XYToPosition(obj.ptr, Clong(x), Clong(y)))
end

