# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTextEntry <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, value::String)
    value_ws = wxString(value)
    KwxFFI.wxTextEntry_SetValue(obj.ptr, self, value_ws.ptr)
    delete!(value_ws)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, value::String)
    value_ws = wxString(value)
    KwxFFI.wxTextEntry_ChangeValue(obj.ptr, self, value_ws.ptr)
    delete!(value_ws)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_GetValue(obj.ptr, self)
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, from::Integer, to::Integer)
    return KwxFFI.wxTextEntry_GetRange(obj.ptr, self, Clong(from), Clong(to))
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_IsEmpty(obj.ptr, self) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, text::String)
    text_ws = wxString(text)
    KwxFFI.wxTextEntry_WriteText(obj.ptr, self, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, text::String)
    text_ws = wxString(text)
    KwxFFI.wxTextEntry_AppendText(obj.ptr, self, text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, from::Integer, to::Integer, value::String)
    value_ws = wxString(value)
    KwxFFI.wxTextEntry_Replace(obj.ptr, self, Clong(from), Clong(to), value_ws.ptr)
    delete!(value_ws)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, from::Integer, to::Integer)
    KwxFFI.wxTextEntry_Remove(obj.ptr, self, Clong(from), Clong(to))
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_Clear(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_RemoveSelection(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_Copy(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_Cut(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_Paste(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_CanCopy(obj.ptr, self) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_CanCut(obj.ptr, self) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_CanPaste(obj.ptr, self) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_Undo(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_Redo(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_CanUndo(obj.ptr, self) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_CanRedo(obj.ptr, self) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, pos::Integer)
    KwxFFI.wxTextEntry_SetInsertionPoint(obj.ptr, self, Clong(pos))
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_SetInsertionPointEnd(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return Int(KwxFFI.wxTextEntry_GetInsertionPoint(obj.ptr, self))
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return Int(KwxFFI.wxTextEntry_GetLastPosition(obj.ptr, self))
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, from::Integer, to::Integer)
    KwxFFI.wxTextEntry_SetSelection(obj.ptr, self, Clong(from), Clong(to))
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_SelectAll(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_SelectNone(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, from::Ptr{Cvoid}, to::Ptr{Cvoid})
    KwxFFI.wxTextEntry_GetSelection(obj.ptr, self, from, to)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_HasSelection(obj.ptr, self) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_GetStringSelection(obj.ptr, self)
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_IsEditable(obj.ptr, self) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, editable::Bool)
    KwxFFI.wxTextEntry_SetEditable(obj.ptr, self, Cint(editable))
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, len::Integer)
    KwxFFI.wxTextEntry_SetMaxLength(obj.ptr, self, Culong(len))
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    KwxFFI.wxTextEntry_ForceUpper(obj.ptr, self)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, hint::String)
    hint_ws = wxString(hint)
    _result = KwxFFI.wxTextEntry_SetHint(obj.ptr, self, hint_ws.ptr) != 0
    delete!(hint_ws)
    return _result
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_GetHint(obj.ptr, self)
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, left::Integer, top::Integer)
    return KwxFFI.wxTextEntry_SetMargins(obj.ptr, self, Cint(left), Cint(top)) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, left::Ptr{Cvoid}, top::Ptr{Cvoid})
    KwxFFI.wxTextEntry_GetMargins(obj.ptr, self, left, top)
    nothing
end

function (obj::wxTextEntry, self::Ptr{Cvoid}, count::Integer, items::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_AutoComplete(obj.ptr, self, Cint(count), items) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_AutoCompleteFileNames(obj.ptr, self) != 0
end

function (obj::wxTextEntry, self::Ptr{Cvoid})
    return KwxFFI.wxTextEntry_AutoCompleteDirectories(obj.ptr, self) != 0
end

