# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTextDataObject <: wxObject
    ptr::Ptr{Cvoid}
end

function wxTextDataObject(text::String)
    text_ws = wxString(text)
    ptr = KwxFFI.TextDataObject_Create(text_ws.ptr)
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxTextDataObject")
    obj = wxTextDataObject(ptr)
    return obj
end

function delete!(obj::wxTextDataObject)
    KwxFFI.TextDataObject_Delete(obj.ptr)
    nothing
end

function (obj::wxTextDataObject)
    return KwxFFI.TextDataObject_GetText(obj.ptr)
end

function (obj::wxTextDataObject, text::String)
    text_ws = wxString(text)
    KwxFFI.TextDataObject_SetText(obj.ptr, text_ws.ptr)
    delete!(text_ws)
    nothing
end

