# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTipWindow <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxTipWindow(parent::Union{wxWindow, Nothing}, text::String, maxLength::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    text_ws = wxString(text)
    ptr = KwxFFI.wxTipWindow_Create(parent_ptr, text_ws.ptr, Cint(maxLength))
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxTipWindow")
    obj = wxTipWindow(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxTipWindow)
    KwxFFI.wxTipWindow_Close(obj.ptr)
    nothing
end

function (obj::wxTipWindow, x::Integer, y::Integer, width::Integer, height::Integer)
    KwxFFI.wxTipWindow_SetBoundingRect(obj.ptr, Cint(x), Cint(y), Cint(width), Cint(height))
    nothing
end

function (obj::wxTipWindow, windowPtr::Ptr{Cvoid})
    KwxFFI.wxTipWindow_SetTipWindowPtr(obj.ptr, windowPtr)
    nothing
end

