# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTimer <: wxObject
    ptr::Ptr{Cvoid}
end

function wxTimer(parent::Union{wxWindow, Nothing}, id::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxTimer_Create(parent_ptr, Cint(id))
    ptr == C_NULL && error("Failed to create wxTimer")
    obj = wxTimer(ptr)
    return obj
end

function delete!(obj::wxTimer)
    KwxFFI.wxTimer_Delete(obj.ptr)
    nothing
end

function (obj::wxTimer)
    return Int(KwxFFI.wxTimer_GetInterval(obj.ptr))
end

function (obj::wxTimer)
    return KwxFFI.wxTimer_IsOneShot(obj.ptr) != 0
end

function (obj::wxTimer)
    return KwxFFI.wxTimer_IsRuning(obj.ptr) != 0
end

function (obj::wxTimer, interval::Integer, oneShot::Bool)
    return KwxFFI.wxTimer_Start(obj.ptr, Cint(interval), Cint(oneShot)) != 0
end

function (obj::wxTimer)
    KwxFFI.wxTimer_Stop(obj.ptr)
    nothing
end

