# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxToolLayoutItem <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxToolLayoutItem)
    return KwxFFI.wxToolLayoutItem_IsSeparator(obj.ptr) != 0
end

function (obj::wxToolLayoutItem, arg::Integer)
    KwxFFI.wxToolLayoutItem_Rect(obj.ptr, Cint(arg))
    nothing
end

