# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxToolWindow <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxToolWindow(pObject::Ptr{Cvoid}, button::Ptr{Cvoid}, title::Ptr{Cvoid})
    ptr = KwxFFI.wxToolWindow_Create(pObject, button, title)
    ptr == C_NULL && error("Failed to create wxToolWindow")
    obj = wxToolWindow(ptr, Any[], Any[])
    return obj
end

function (obj::wxToolWindow, button::Ptr{Cvoid})
    KwxFFI.wxToolWindow_AddMiniButton(obj.ptr, button)
    nothing
end

function (obj::wxToolWindow)
    return KwxFFI.wxToolWindow_GetClient(obj.ptr)
end

function (obj::wxToolWindow, window::Ptr{Cvoid})
    KwxFFI.wxToolWindow_SetClient(obj.ptr, window)
    nothing
end

function (obj::wxToolWindow, font::Ptr{Cvoid})
    KwxFFI.wxToolWindow_SetTitleFont(obj.ptr, font)
    nothing
end

