# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxToolBar <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxToolBar(parent::Union{wxWindow, Nothing}, id::Integer, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxToolBar_Create(parent_ptr, Cint(id), Cint(left), Cint(top), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxToolBar")
    obj = wxToolBar(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxToolBar, ctrl::Ptr{Cvoid})
    return KwxFFI.wxToolBar_AddControl(obj.ptr, ctrl) != 0
end

function (obj::wxToolBar)
    KwxFFI.wxToolBar_AddSeparator(obj.ptr)
    nothing
end

function (obj::wxToolBar, toolid::Integer, label::String, bitmap::Ptr{Cvoid}, bmpDisabled::Ptr{Cvoid}, kind::Integer, shortHelp::String, longHelp::String, data::Ptr{Cvoid})
    label_ws = wxString(label)
    shortHelp_ws = wxString(shortHelp)
    longHelp_ws = wxString(longHelp)
    KwxFFI.wxToolBar_AddTool(obj.ptr, Cint(toolid), label_ws.ptr, bitmap, bmpDisabled, Cint(kind), shortHelp_ws.ptr, longHelp_ws.ptr, data)
    delete!(label_ws)
    delete!(shortHelp_ws)
    delete!(longHelp_ws)
    nothing
end

function delete!(obj::wxToolBar)
    KwxFFI.wxToolBar_Delete(obj.ptr)
    nothing
end

function (obj::wxToolBar, id::Integer)
    return KwxFFI.wxToolBar_DeleteTool(obj.ptr, Cint(id)) != 0
end

function (obj::wxToolBar, pos::Integer)
    return KwxFFI.wxToolBar_DeleteToolByPos(obj.ptr, Cint(pos)) != 0
end

function (obj::wxToolBar, id::Integer, enable::Bool)
    KwxFFI.wxToolBar_EnableTool(obj.ptr, Cint(id), Cint(enable))
    nothing
end

function (obj::wxToolBar)
    return KwxFFI.wxToolBar_GetMargins(obj.ptr)
end

function (obj::wxToolBar)
    return KwxFFI.wxToolBar_GetToolBitmapSize(obj.ptr)
end

function (obj::wxToolBar, id::Integer)
    return KwxFFI.wxToolBar_GetToolClientData(obj.ptr, Cint(id))
end

function (obj::wxToolBar, id::Integer)
    return KwxFFI.wxToolBar_GetToolEnabled(obj.ptr, Cint(id)) != 0
end

function (obj::wxToolBar, id::Integer)
    return KwxFFI.wxToolBar_GetToolLongHelp(obj.ptr, Cint(id))
end

function (obj::wxToolBar)
    return Int(KwxFFI.wxToolBar_GetToolPacking(obj.ptr))
end

function (obj::wxToolBar, id::Integer)
    return KwxFFI.wxToolBar_GetToolShortHelp(obj.ptr, Cint(id))
end

function (obj::wxToolBar)
    return KwxFFI.wxToolBar_GetToolSize(obj.ptr)
end

function (obj::wxToolBar, id::Integer)
    return KwxFFI.wxToolBar_GetToolState(obj.ptr, Cint(id)) != 0
end

function (obj::wxToolBar, pos::Integer, ctrl::Ptr{Cvoid})
    KwxFFI.wxToolBar_InsertControl(obj.ptr, Cint(pos), ctrl)
    nothing
end

function (obj::wxToolBar, pos::Integer)
    KwxFFI.wxToolBar_InsertSeparator(obj.ptr, Cint(pos))
    nothing
end

function (obj::wxToolBar)
    return KwxFFI.wxToolBar_Realize(obj.ptr) != 0
end

function (obj::wxToolBar, id::Integer)
    KwxFFI.wxToolBar_RemoveTool(obj.ptr, Cint(id))
    nothing
end

function (obj::wxToolBar, x::Integer, y::Integer)
    KwxFFI.wxToolBar_SetMargins(obj.ptr, Cint(x), Cint(y))
    nothing
end

function (obj::wxToolBar, x::Integer, y::Integer)
    KwxFFI.wxToolBar_SetToolBitmapSize(obj.ptr, Cint(x), Cint(y))
    nothing
end

function (obj::wxToolBar, id::Integer, data::Ptr{Cvoid})
    KwxFFI.wxToolBar_SetToolClientData(obj.ptr, Cint(id), data)
    nothing
end

function (obj::wxToolBar, id::Integer, str::String)
    str_ws = wxString(str)
    KwxFFI.wxToolBar_SetToolLongHelp(obj.ptr, Cint(id), str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxToolBar, packing::Integer)
    KwxFFI.wxToolBar_SetToolPacking(obj.ptr, Cint(packing))
    nothing
end

function (obj::wxToolBar, separation::Integer)
    KwxFFI.wxToolBar_SetToolSeparation(obj.ptr, Cint(separation))
    nothing
end

function (obj::wxToolBar, id::Integer, str::String)
    str_ws = wxString(str)
    KwxFFI.wxToolBar_SetToolShortHelp(obj.ptr, Cint(id), str_ws.ptr)
    delete!(str_ws)
    nothing
end

function (obj::wxToolBar, id::Integer, toggle::Bool)
    KwxFFI.wxToolBar_ToggleTool(obj.ptr, Cint(id), Cint(toggle))
    nothing
end

function (obj::wxToolBar, toolid::Integer, label::String, bitmap::Ptr{Cvoid}, bmpDisabled::Ptr{Cvoid}, shortHelp::String, longHelp::String)
    label_ws = wxString(label)
    shortHelp_ws = wxString(shortHelp)
    longHelp_ws = wxString(longHelp)
    KwxFFI.wxToolBar_AddCheckTool(obj.ptr, Cint(toolid), label_ws.ptr, bitmap, bmpDisabled, shortHelp_ws.ptr, longHelp_ws.ptr)
    delete!(label_ws)
    delete!(shortHelp_ws)
    delete!(longHelp_ws)
    nothing
end

function (obj::wxToolBar, toolid::Integer, label::String, bitmap::Ptr{Cvoid}, bmpDisabled::Ptr{Cvoid}, shortHelp::String, longHelp::String)
    label_ws = wxString(label)
    shortHelp_ws = wxString(shortHelp)
    longHelp_ws = wxString(longHelp)
    KwxFFI.wxToolBar_AddRadioTool(obj.ptr, Cint(toolid), label_ws.ptr, bitmap, bmpDisabled, shortHelp_ws.ptr, longHelp_ws.ptr)
    delete!(label_ws)
    delete!(shortHelp_ws)
    delete!(longHelp_ws)
    nothing
end

function (obj::wxToolBar)
    return KwxFFI.wxToolBar_AddStretchableSpace(obj.ptr)
end

function (obj::wxToolBar, pos::Integer)
    return KwxFFI.wxToolBar_InsertStretchableSpace(obj.ptr, Csize_t(pos))
end

function (obj::wxToolBar, pos::Integer, toolid::Integer, label::String, bitmap::Ptr{Cvoid}, bmpDisabled::Ptr{Cvoid}, kind::Integer, shortHelp::String, longHelp::String)
    label_ws = wxString(label)
    shortHelp_ws = wxString(shortHelp)
    longHelp_ws = wxString(longHelp)
    KwxFFI.wxToolBar_InsertTool(obj.ptr, Csize_t(pos), Cint(toolid), label_ws.ptr, bitmap, bmpDisabled, Cint(kind), shortHelp_ws.ptr, longHelp_ws.ptr)
    delete!(label_ws)
    delete!(shortHelp_ws)
    delete!(longHelp_ws)
    nothing
end

function (obj::wxToolBar)
    KwxFFI.wxToolBar_ClearTools(obj.ptr)
    nothing
end

function (obj::wxToolBar, id::Integer)
    return KwxFFI.wxToolBar_FindControl(obj.ptr, Cint(id))
end

function (obj::wxToolBar, x::Integer, y::Integer)
    return KwxFFI.wxToolBar_FindToolForPosition(obj.ptr, Cint(x), Cint(y))
end

function (obj::wxToolBar, id::Integer)
    return KwxFFI.wxToolBar_FindById(obj.ptr, Cint(id))
end

function (obj::wxToolBar, id::Integer)
    return Int(KwxFFI.wxToolBar_GetToolPos(obj.ptr, Cint(id)))
end

function (obj::wxToolBar)
    return Int(KwxFFI.wxToolBar_GetToolSeparation(obj.ptr))
end

function (obj::wxToolBar)
    return Int(KwxFFI.wxToolBar_GetToolsCount(obj.ptr))
end

function (obj::wxToolBar)
    return KwxFFI.wxToolBar_IsVertical(obj.ptr) != 0
end

function (obj::wxToolBar, id::Integer, bitmap::Ptr{Cvoid})
    KwxFFI.wxToolBar_SetToolNormalBitmap(obj.ptr, Cint(id), bitmap)
    nothing
end

function (obj::wxToolBar, id::Integer, bitmap::Ptr{Cvoid})
    KwxFFI.wxToolBar_SetToolDisabledBitmap(obj.ptr, Cint(id), bitmap)
    nothing
end

function (obj::wxToolBar, id::Integer, menu::Ptr{Cvoid})
    KwxFFI.wxToolBar_SetDropdownMenu(obj.ptr, Cint(id), menu)
    nothing
end

function (obj::wxToolBar, id::Integer, toggle::Bool)
    KwxFFI.wxToolBar_SetToggle(obj.ptr, Cint(id), Cint(toggle))
    nothing
end

