# Code generated by kwxgen. DO NOT EDIT.

function (obj::wxTopLevelWindow, enable::Bool)
    return KwxFFI.wxTopLevelWindow_EnableCloseButton(obj.ptr, Cint(enable)) != 0
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_GetDefaultButton(obj.ptr)
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_GetDefaultItem(obj.ptr)
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_GetIcon(obj.ptr)
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_GetTitle(obj.ptr)
end

function (obj::wxTopLevelWindow, iconize::Bool)
    return KwxFFI.wxTopLevelWindow_Iconize(obj.ptr, Cint(iconize)) != 0
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_IsActive(obj.ptr) != 0
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_IsIconized(obj.ptr) != 0
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_IsMaximized(obj.ptr) != 0
end

function (obj::wxTopLevelWindow, maximize::Bool)
    KwxFFI.wxTopLevelWindow_Maximize(obj.ptr, Cint(maximize))
    nothing
end

function (obj::wxTopLevelWindow, flags::Integer)
    KwxFFI.wxTopLevelWindow_RequestUserAttention(obj.ptr, Cint(flags))
    nothing
end

function (obj::wxTopLevelWindow, pBut::Ptr{Cvoid})
    KwxFFI.wxTopLevelWindow_SetDefaultButton(obj.ptr, pBut)
    nothing
end

function (obj::wxTopLevelWindow, pBut::Ptr{Cvoid})
    KwxFFI.wxTopLevelWindow_SetDefaultItem(obj.ptr, pBut)
    nothing
end

function (obj::wxTopLevelWindow, pIcon::Ptr{Cvoid})
    KwxFFI.wxTopLevelWindow_SetIcon(obj.ptr, pIcon)
    nothing
end

function (obj::wxTopLevelWindow, icons::Ptr{Cvoid})
    KwxFFI.wxTopLevelWindow_SetIcons(obj.ptr, icons)
    nothing
end

function (obj::wxTopLevelWindow, width::Integer, height::Integer)
    KwxFFI.wxTopLevelWindow_SetMaxSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxTopLevelWindow, width::Integer, height::Integer)
    KwxFFI.wxTopLevelWindow_SetMinSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxTopLevelWindow, direction::Integer)
    KwxFFI.wxTopLevelWindow_CenterOnScreen(obj.ptr, Cint(direction))
    nothing
end

function (obj::wxTopLevelWindow, pString::String)
    pString_ws = wxString(pString)
    KwxFFI.wxTopLevelWindow_SetTitle(obj.ptr, pString_ws.ptr)
    delete!(pString_ws)
    nothing
end

function (obj::wxTopLevelWindow)
    KwxFFI.wxTopLevelWindow_Restore(obj.ptr)
    nothing
end

function (obj::wxTopLevelWindow, show::Bool, style::Integer)
    return KwxFFI.wxTopLevelWindow_ShowFullScreen(obj.ptr, Cint(show), Clong(style)) != 0
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_IsFullScreen(obj.ptr) != 0
end

function (obj::wxTopLevelWindow, enable::Bool)
    return KwxFFI.wxTopLevelWindow_EnableMaximizeButton(obj.ptr, Cint(enable)) != 0
end

function (obj::wxTopLevelWindow, enable::Bool)
    return KwxFFI.wxTopLevelWindow_EnableMinimizeButton(obj.ptr, Cint(enable)) != 0
end

function (obj::wxTopLevelWindow)
    KwxFFI.wxTopLevelWindow_ShowWithoutActivating(obj.ptr)
    nothing
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_ShouldPreventAppExit(obj.ptr) != 0
end

function (obj::wxTopLevelWindow, contentProtection::Integer)
    return KwxFFI.wxTopLevelWindow_SetContentProtection(obj.ptr, Cint(contentProtection)) != 0
end

function (obj::wxTopLevelWindow, modified::Bool)
    KwxFFI.wxTopLevelWindow_OSXSetModified(obj.ptr, Cint(modified))
    nothing
end

function (obj::wxTopLevelWindow)
    return KwxFFI.wxTopLevelWindow_OSXIsModified(obj.ptr) != 0
end

function (obj::wxTopLevelWindow, filename::String)
    filename_ws = wxString(filename)
    KwxFFI.wxTopLevelWindow_SetRepresentedFilename(obj.ptr, filename_ws.ptr)
    delete!(filename_ws)
    nothing
end

