# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTreeListEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxTreeListEvent, result::Ptr{Cvoid})
    KwxFFI.wxTreeListEvent_GetItem(obj.ptr, result)
    nothing
end

function (obj::wxTreeListEvent)
    return Int(KwxFFI.wxTreeListEvent_GetOldCheckedState(obj.ptr))
end

function (obj::wxTreeListEvent)
    return KwxFFI.wxTreeListEvent_GetColumn(obj.ptr)
end

function (obj::wxTreeListEvent)
    KwxFFI.wxTreeListEvent_Veto(obj.ptr)
    nothing
end

function (obj::wxTreeListEvent)
    KwxFFI.wxTreeListEvent_Allow(obj.ptr)
    nothing
end

function (obj::wxTreeListEvent)
    return KwxFFI.wxTreeListEvent_IsAllowed(obj.ptr) != 0
end

function (obj::wxTreeListEvent)
    return Int(KwxFFI.expTL_MULTIPLE(obj.ptr))
end

function (obj::wxTreeListEvent)
    return Int(KwxFFI.expTL_CHECKBOX(obj.ptr))
end

function (obj::wxTreeListEvent)
    return Int(KwxFFI.expTL_3STATE(obj.ptr))
end

function (obj::wxTreeListEvent)
    return Int(KwxFFI.expTL_USER_3STATE(obj.ptr))
end

function (obj::wxTreeListEvent)
    return Int(KwxFFI.expTL_NO_HEADER(obj.ptr))
end

function (obj::wxTreeListEvent)
    return Int(KwxFFI.expTL_DEFAULT_STYLE(obj.ptr))
end

