# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTreeListCtrl <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxTreeListCtrl(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxTreeListCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxTreeListCtrl")
    obj = wxTreeListCtrl(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxTreeListCtrl)
    return KwxFFI.wxTreeListCtrl_GetColumnCount(obj.ptr)
end

function (obj::wxTreeListCtrl, col::Integer)
    return KwxFFI.wxTreeListCtrl_DeleteColumn(obj.ptr, Cuint(col)) != 0
end

function (obj::wxTreeListCtrl)
    KwxFFI.wxTreeListCtrl_ClearColumns(obj.ptr)
    nothing
end

function (obj::wxTreeListCtrl, col::Integer, width::Integer)
    KwxFFI.wxTreeListCtrl_SetColumnWidth(obj.ptr, Cuint(col), Cint(width))
    nothing
end

function (obj::wxTreeListCtrl, col::Integer)
    return Int(KwxFFI.wxTreeListCtrl_GetColumnWidth(obj.ptr, Cuint(col)))
end

function (obj::wxTreeListCtrl, text::String)
    text_ws = wxString(text)
    _result = Int(KwxFFI.wxTreeListCtrl_WidthFor(obj.ptr, text_ws.ptr))
    delete!(text_ws)
    return _result
end

function (obj::wxTreeListCtrl, parent::Ptr{Cvoid}, previous::Ptr{Cvoid}, text::String, imageClosed::Integer, imageOpened::Integer, result::Ptr{Cvoid})
    text_ws = wxString(text)
    KwxFFI.wxTreeListCtrl_InsertItem(obj.ptr, parent, previous, text_ws.ptr, Cint(imageClosed), Cint(imageOpened), result)
    delete!(text_ws)
    nothing
end

function (obj::wxTreeListCtrl, parent::Ptr{Cvoid}, text::String, imageClosed::Integer, imageOpened::Integer, result::Ptr{Cvoid})
    text_ws = wxString(text)
    KwxFFI.wxTreeListCtrl_PrependItem(obj.ptr, parent, text_ws.ptr, Cint(imageClosed), Cint(imageOpened), result)
    delete!(text_ws)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_DeleteItem(obj.ptr, item)
    nothing
end

function (obj::wxTreeListCtrl)
    KwxFFI.wxTreeListCtrl_DeleteAllItems(obj.ptr)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid}, result::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_GetItemParent(obj.ptr, item, result)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid}, result::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_GetFirstChild(obj.ptr, item, result)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid}, result::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_GetNextSibling(obj.ptr, item, result)
    nothing
end

function (obj::wxTreeListCtrl, result::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_GetFirstItem(obj.ptr, result)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid}, result::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_GetNextItem(obj.ptr, item, result)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid}, col::Integer, text::String)
    text_ws = wxString(text)
    KwxFFI.wxTreeListCtrl_SetItemText(obj.ptr, item, Cuint(col), text_ws.ptr)
    delete!(text_ws)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid}, closed::Integer, opened::Integer)
    KwxFFI.wxTreeListCtrl_SetItemImage(obj.ptr, item, Cint(closed), Cint(opened))
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_Collapse(obj.ptr, item)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    return KwxFFI.wxTreeListCtrl_IsExpanded(obj.ptr, item) != 0
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_Select(obj.ptr, item)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_Unselect(obj.ptr, item)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    return KwxFFI.wxTreeListCtrl_IsSelected(obj.ptr, item) != 0
end

function (obj::wxTreeListCtrl)
    KwxFFI.wxTreeListCtrl_SelectAll(obj.ptr)
    nothing
end

function (obj::wxTreeListCtrl)
    KwxFFI.wxTreeListCtrl_UnselectAll(obj.ptr)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_EnsureVisible(obj.ptr, item)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_UncheckItem(obj.ptr, item)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid}, state::Integer)
    KwxFFI.wxTreeListCtrl_CheckItemRecursively(obj.ptr, item, Cint(state))
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    KwxFFI.wxTreeListCtrl_UpdateItemParentStateRecursively(obj.ptr, item)
    nothing
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid})
    return Int(KwxFFI.wxTreeListCtrl_GetCheckedState(obj.ptr, item))
end

function (obj::wxTreeListCtrl, item::Ptr{Cvoid}, state::Integer)
    return KwxFFI.wxTreeListCtrl_AreAllChildrenInState(obj.ptr, item, Cint(state)) != 0
end

function (obj::wxTreeListCtrl, col::Ptr{Cvoid}, ascendingOrder::Ref{Bool})
    return KwxFFI.wxTreeListCtrl_GetSortColumn(obj.ptr, col, ascendingOrder) != 0
end

function (obj::wxTreeListCtrl)
    return KwxFFI.wxTreeListCtrl_GetDataView(obj.ptr)
end

