# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTreebook <: wxControl
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxTreebook(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxTreebook_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function wxTreebook(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxDataViewCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function wxTreebook(id::Ptr{Cvoid})
    ptr = KwxFFI.wxDataViewItem_Create(id)
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    return obj
end

function wxTreebook()
    ptr = KwxFFI.wxDataViewItemArray_Create()
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    return obj
end

function wxTreebook(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxDataViewListCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function wxTreebook()
    ptr = KwxFFI.wxVariantVector_Create()
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    return obj
end

function wxTreebook(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxDatePickerCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Clong(style))
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function wxTreebook(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, path::String, message::String, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    path_ws = wxString(path)
    message_ws = wxString(message)
    ptr = KwxFFI.wxDirPickerCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), path_ws.ptr, message_ws.ptr, Clong(style))
    delete!(path_ws)
    delete!(message_ws)
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function wxTreebook(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, path::String, message::String, wildcard::String, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    path_ws = wxString(path)
    message_ws = wxString(message)
    wildcard_ws = wxString(wildcard)
    ptr = KwxFFI.wxFilePickerCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), path_ws.ptr, message_ws.ptr, wildcard_ws.ptr, Clong(style))
    delete!(path_ws)
    delete!(message_ws)
    delete!(wildcard_ws)
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function wxTreebook(parent::Union{wxWindow, Nothing}, id::Integer, initial::Ptr{Cvoid}, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxFontPickerCtrl_Create(parent_ptr, Cint(id), initial, Cint(x), Cint(y), Cint(width), Cint(height), Clong(style))
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function wxTreebook(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxTimePickerCtrl_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Clong(style))
    ptr == C_NULL && error("Failed to create wxTreebook")
    obj = wxTreebook(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxTreebook, pPage::Ptr{Cvoid}, strText::String, bSelect::Bool, imageId::Integer)
    strText_ws = wxString(strText)
    _result = KwxFFI.wxTreebook_AddPage(obj.ptr, pPage, strText_ws.ptr, Cint(bSelect), Cint(imageId)) != 0
    delete!(strText_ws)
    return _result
end

function (obj::wxTreebook, pPage::Ptr{Cvoid}, strText::String, bSelect::Bool, imageId::Integer)
    strText_ws = wxString(strText)
    _result = KwxFFI.wxTreebook_AddSubPage(obj.ptr, pPage, strText_ws.ptr, Cint(bSelect), Cint(imageId)) != 0
    delete!(strText_ws)
    return _result
end

function (obj::wxTreebook, bForward::Bool)
    KwxFFI.wxTreebook_AdvanceSelection(obj.ptr, Cint(bForward))
    nothing
end

function (obj::wxTreebook)
    return KwxFFI.wxTreebook_DeleteAllPages(obj.ptr) != 0
end

function (obj::wxTreebook, nPage::Integer)
    return KwxFFI.wxTreebook_DeletePage(obj.ptr, Cint(nPage)) != 0
end

function (obj::wxTreebook, nPage::Integer, expand::Bool)
    KwxFFI.wxTreebook_ExpandNode(obj.ptr, Cint(nPage), Cint(expand))
    nothing
end

function (obj::wxTreebook)
    return KwxFFI.wxTreebook_GetImageList(obj.ptr)
end

function (obj::wxTreebook, nPage::Integer)
    return KwxFFI.wxTreebook_GetPage(obj.ptr, Cint(nPage))
end

function (obj::wxTreebook)
    return Int(KwxFFI.wxTreebook_GetPageCount(obj.ptr))
end

function (obj::wxTreebook, nPage::Integer)
    return Int(KwxFFI.wxTreebook_GetPageImage(obj.ptr, Cint(nPage)))
end

function (obj::wxTreebook, nPage::Integer)
    return Int(KwxFFI.wxTreebook_GetPageParent(obj.ptr, Cint(nPage)))
end

function (obj::wxTreebook, nPage::Integer)
    return KwxFFI.wxTreebook_GetPageText(obj.ptr, Cint(nPage))
end

function (obj::wxTreebook)
    return Int(KwxFFI.wxTreebook_GetSelection(obj.ptr))
end

function (obj::wxTreebook)
    return KwxFFI.wxTreebook_GetTreeCtrl(obj.ptr)
end

function (obj::wxTreebook, x::Integer, y::Integer, flags::Ptr{Cvoid})
    return Int(KwxFFI.wxTreebook_HitTest(obj.ptr, Cint(x), Cint(y), flags))
end

function (obj::wxTreebook, nPage::Integer, pPage::Ptr{Cvoid}, strText::String, bSelect::Bool, imageId::Integer)
    strText_ws = wxString(strText)
    _result = KwxFFI.wxTreebook_InsertPage(obj.ptr, Cint(nPage), pPage, strText_ws.ptr, Cint(bSelect), Cint(imageId)) != 0
    delete!(strText_ws)
    return _result
end

function (obj::wxTreebook, nPage::Integer, pPage::Ptr{Cvoid}, strText::String, bSelect::Bool, imageId::Integer)
    strText_ws = wxString(strText)
    _result = KwxFFI.wxTreebook_InsertSubPage(obj.ptr, Cint(nPage), pPage, strText_ws.ptr, Cint(bSelect), Cint(imageId)) != 0
    delete!(strText_ws)
    return _result
end

function (obj::wxTreebook, nPage::Integer)
    return KwxFFI.wxTreebook_IsNodeExpanded(obj.ptr, Cint(nPage)) != 0
end

function (obj::wxTreebook, nPage::Integer)
    return KwxFFI.wxTreebook_CollapseNode(obj.ptr, Cint(nPage)) != 0
end

function (obj::wxTreebook, nPage::Integer)
    return KwxFFI.wxTreebook_RemovePage(obj.ptr, Cint(nPage)) != 0
end

function (obj::wxTreebook, imageList::Ptr{Cvoid})
    KwxFFI.wxTreebook_SetImageList(obj.ptr, imageList)
    nothing
end

function (obj::wxTreebook, nPage::Integer, nImage::Integer)
    return KwxFFI.wxTreebook_SetPageImage(obj.ptr, Cint(nPage), Cint(nImage)) != 0
end

function (obj::wxTreebook, nPage::Integer, strText::String)
    strText_ws = wxString(strText)
    _result = KwxFFI.wxTreebook_SetPageText(obj.ptr, Cint(nPage), strText_ws.ptr) != 0
    delete!(strText_ws)
    return _result
end

function (obj::wxTreebook, nPage::Integer)
    return Int(KwxFFI.wxTreebook_SetSelection(obj.ptr, Cint(nPage)))
end

function (obj::wxTreebook, model::Ptr{Cvoid})
    return KwxFFI.wxDataViewCtrl_AssociateModel(obj.ptr, model) != 0
end

function (obj::wxTreebook)
    return KwxFFI.wxDataViewCtrl_GetModel(obj.ptr)
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_AppendTextColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_AppendToggleColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_AppendProgressColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_AppendBitmapColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, col::Ptr{Cvoid})
    return KwxFFI.wxDataViewCtrl_AppendColumn(obj.ptr, col) != 0
end

function (obj::wxTreebook, col::Ptr{Cvoid})
    return KwxFFI.wxDataViewCtrl_PrependColumn(obj.ptr, col) != 0
end

function (obj::wxTreebook, pos::Integer, col::Ptr{Cvoid})
    return KwxFFI.wxDataViewCtrl_InsertColumn(obj.ptr, Cuint(pos), col) != 0
end

function (obj::wxTreebook)
    return KwxFFI.wxDataViewCtrl_GetColumnCount(obj.ptr)
end

function (obj::wxTreebook, pos::Integer)
    return KwxFFI.wxDataViewCtrl_GetColumn(obj.ptr, Cuint(pos))
end

function (obj::wxTreebook, column::Ptr{Cvoid})
    return Int(KwxFFI.wxDataViewCtrl_GetColumnPosition(obj.ptr, column))
end

function (obj::wxTreebook, column::Ptr{Cvoid})
    return KwxFFI.wxDataViewCtrl_DeleteColumn(obj.ptr, column) != 0
end

function (obj::wxTreebook)
    return KwxFFI.wxDataViewCtrl_ClearColumns(obj.ptr) != 0
end

function (obj::wxTreebook, col::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_SetExpanderColumn(obj.ptr, col)
    nothing
end

function (obj::wxTreebook)
    return KwxFFI.wxDataViewCtrl_GetExpanderColumn(obj.ptr)
end

function (obj::wxTreebook)
    return KwxFFI.wxDataViewCtrl_GetSortingColumn(obj.ptr)
end

function (obj::wxTreebook, indent::Integer)
    KwxFFI.wxDataViewCtrl_SetIndent(obj.ptr, Cint(indent))
    nothing
end

function (obj::wxTreebook)
    return Int(KwxFFI.wxDataViewCtrl_GetIndent(obj.ptr))
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_GetCurrentItem(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_SetCurrentItem(obj.ptr, item)
    nothing
end

function (obj::wxTreebook)
    return KwxFFI.wxDataViewCtrl_GetCurrentColumn(obj.ptr)
end

function (obj::wxTreebook)
    return Int(KwxFFI.wxDataViewCtrl_GetSelectedItemsCount(obj.ptr))
end

function (obj::wxTreebook)
    return KwxFFI.wxDataViewCtrl_HasSelection(obj.ptr) != 0
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_GetSelection(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, sel::Ptr{Cvoid})
    return Int(KwxFFI.wxDataViewCtrl_GetSelections(obj.ptr, sel))
end

function (obj::wxTreebook, sel::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_SetSelections(obj.ptr, sel)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_Select(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_Unselect(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    return KwxFFI.wxDataViewCtrl_IsSelected(obj.ptr, item) != 0
end

function (obj::wxTreebook)
    KwxFFI.wxDataViewCtrl_SelectAll(obj.ptr)
    nothing
end

function (obj::wxTreebook)
    KwxFFI.wxDataViewCtrl_UnselectAll(obj.ptr)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_Expand(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_Collapse(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    return KwxFFI.wxDataViewCtrl_IsExpanded(obj.ptr, item) != 0
end

function (obj::wxTreebook, item::Ptr{Cvoid}, column::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_EnsureVisible(obj.ptr, item, column)
    nothing
end

function (obj::wxTreebook, x::Integer, y::Integer, item::Ptr{Cvoid}, col::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_HitTest(obj.ptr, Cint(x), Cint(y), item, col)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid}, column::Ptr{Cvoid}, x::Ptr{Cvoid}, y::Ptr{Cvoid}, width::Ptr{Cvoid}, height::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_GetItemRect(obj.ptr, item, column, x, y, width, height)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid}, column::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_EditItem(obj.ptr, item, column)
    nothing
end

function (obj::wxTreebook)
    return Int(KwxFFI.wxDataViewCtrl_GetCountPerPage(obj.ptr))
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_GetTopItem(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_ExpandChildren(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewCtrl_ExpandAncestors(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, allow::Bool)
    return KwxFFI.wxDataViewCtrl_AllowMultiColumnSort(obj.ptr, Cint(allow)) != 0
end

function (obj::wxTreebook)
    return KwxFFI.wxDataViewCtrl_IsMultiColumnSortAllowed(obj.ptr) != 0
end

function (obj::wxTreebook, column::Integer)
    KwxFFI.wxDataViewCtrl_ToggleSortByColumn(obj.ptr, Cint(column))
    nothing
end

function (obj::wxTreebook, rowHeight::Integer)
    return KwxFFI.wxDataViewCtrl_SetRowHeight(obj.ptr, Cint(rowHeight)) != 0
end

function (obj::wxTreebook, colour::Ptr{Cvoid})
    return KwxFFI.wxDataViewCtrl_SetAlternateRowColour(obj.ptr, colour) != 0
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_AppendIconTextColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_AppendDateColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_PrependTextColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_PrependIconTextColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_PrependToggleColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_PrependProgressColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_PrependDateColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, model_column::Integer, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewCtrl_PrependBitmapColumn(obj.ptr, label_ws.ptr, Cuint(model_column), Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function delete!(obj::wxTreebook, item::Ptr{Cvoid})
    KwxFFI.wxDataViewItem_Delete(obj.ptr, item)
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    return KwxFFI.wxDataViewItem_GetID(obj.ptr, item)
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    return KwxFFI.wxDataViewItem_IsOk(obj.ptr, item) != 0
end

function delete!(obj::wxTreebook, arr::Ptr{Cvoid})
    KwxFFI.wxDataViewItemArray_Delete(obj.ptr, arr)
    nothing
end

function (obj::wxTreebook, arr::Ptr{Cvoid})
    return KwxFFI.wxDataViewItemArray_GetCount(obj.ptr, arr)
end

function (obj::wxTreebook, arr::Ptr{Cvoid}, index::Integer, item::Ptr{Cvoid})
    KwxFFI.wxDataViewItemArray_Item(obj.ptr, arr, Csize_t(index), item)
    nothing
end

function (obj::wxTreebook, arr::Ptr{Cvoid}, item::Ptr{Cvoid})
    KwxFFI.wxDataViewItemArray_Add(obj.ptr, arr, item)
    nothing
end

function (obj::wxTreebook, arr::Ptr{Cvoid})
    KwxFFI.wxDataViewItemArray_Clear(obj.ptr, arr)
    nothing
end

function (obj::wxTreebook)
    return KwxFFI.wxDataViewListCtrl_GetStore(obj.ptr)
end

function (obj::wxTreebook, label::String, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewListCtrl_AppendTextColumn(obj.ptr, label_ws.ptr, Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewListCtrl_AppendToggleColumn(obj.ptr, label_ws.ptr, Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewListCtrl_AppendProgressColumn(obj.ptr, label_ws.ptr, Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, label::String, mode::Integer, width::Integer, align::Integer, flags::Integer)
    label_ws = wxString(label)
    _result = KwxFFI.wxDataViewListCtrl_AppendIconTextColumn(obj.ptr, label_ws.ptr, Cint(mode), Cint(width), Cint(align), Cint(flags))
    delete!(label_ws)
    return _result
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    return Int(KwxFFI.wxDataViewListCtrl_ItemToRow(obj.ptr, item))
end

function (obj::wxTreebook, row::Integer, item::Ptr{Cvoid})
    KwxFFI.wxDataViewListCtrl_RowToItem(obj.ptr, Cint(row), item)
    nothing
end

function (obj::wxTreebook)
    return Int(KwxFFI.wxDataViewListCtrl_GetSelectedRow(obj.ptr))
end

function (obj::wxTreebook, row::Integer)
    KwxFFI.wxDataViewListCtrl_SelectRow(obj.ptr, Cuint(row))
    nothing
end

function (obj::wxTreebook, row::Integer)
    KwxFFI.wxDataViewListCtrl_UnselectRow(obj.ptr, Cuint(row))
    nothing
end

function (obj::wxTreebook, values::Ptr{Cvoid}, data::Integer)
    KwxFFI.wxDataViewListCtrl_AppendItem(obj.ptr, values, Culong(data))
    nothing
end

function (obj::wxTreebook, values::Ptr{Cvoid}, data::Integer)
    KwxFFI.wxDataViewListCtrl_PrependItem(obj.ptr, values, Culong(data))
    nothing
end

function (obj::wxTreebook, row::Integer, values::Ptr{Cvoid}, data::Integer)
    KwxFFI.wxDataViewListCtrl_InsertItem(obj.ptr, Cuint(row), values, Culong(data))
    nothing
end

function (obj::wxTreebook, row::Integer)
    KwxFFI.wxDataViewListCtrl_DeleteItem(obj.ptr, Cuint(row))
    nothing
end

function (obj::wxTreebook)
    KwxFFI.wxDataViewListCtrl_DeleteAllItems(obj.ptr)
    nothing
end

function (obj::wxTreebook, value::Ptr{Cvoid}, row::Integer, col::Integer)
    KwxFFI.wxDataViewListCtrl_SetValue(obj.ptr, value, Cuint(row), Cuint(col))
    nothing
end

function (obj::wxTreebook, value::Ptr{Cvoid}, row::Integer, col::Integer)
    KwxFFI.wxDataViewListCtrl_GetValue(obj.ptr, value, Cuint(row), Cuint(col))
    nothing
end

function (obj::wxTreebook, value::String, row::Integer, col::Integer)
    value_ws = wxString(value)
    KwxFFI.wxDataViewListCtrl_SetTextValue(obj.ptr, value_ws.ptr, Cuint(row), Cuint(col))
    delete!(value_ws)
    nothing
end

function (obj::wxTreebook, row::Integer, col::Integer)
    return KwxFFI.wxDataViewListCtrl_GetTextValue(obj.ptr, Cuint(row), Cuint(col))
end

function (obj::wxTreebook, value::Bool, row::Integer, col::Integer)
    KwxFFI.wxDataViewListCtrl_SetToggleValue(obj.ptr, Cint(value), Cuint(row), Cuint(col))
    nothing
end

function (obj::wxTreebook, row::Integer, col::Integer)
    return KwxFFI.wxDataViewListCtrl_GetToggleValue(obj.ptr, Cuint(row), Cuint(col)) != 0
end

function (obj::wxTreebook, item::Ptr{Cvoid}, data::Integer)
    KwxFFI.wxDataViewListCtrl_SetItemData(obj.ptr, item, Culong(data))
    nothing
end

function (obj::wxTreebook, item::Ptr{Cvoid})
    return KwxFFI.wxDataViewListCtrl_GetItemData(obj.ptr, item)
end

function (obj::wxTreebook)
    return Int(KwxFFI.wxDataViewListCtrl_GetItemCount(obj.ptr))
end

function (obj::wxTreebook, row::Integer)
    return KwxFFI.wxDataViewListCtrl_IsRowSelected(obj.ptr, Cuint(row)) != 0
end

function delete!(obj::wxTreebook, vec::Ptr{Cvoid})
    KwxFFI.wxVariantVector_Delete(obj.ptr, vec)
    nothing
end

function (obj::wxTreebook, vec::Ptr{Cvoid}, value::Ptr{Cvoid})
    KwxFFI.wxVariantVector_Add(obj.ptr, vec, value)
    nothing
end

function (obj::wxTreebook, vec::Ptr{Cvoid}, value::String)
    value_ws = wxString(value)
    KwxFFI.wxVariantVector_AddString(obj.ptr, vec, value_ws.ptr)
    delete!(value_ws)
    nothing
end

function (obj::wxTreebook, vec::Ptr{Cvoid}, value::Integer)
    KwxFFI.wxVariantVector_AddLong(obj.ptr, vec, Clong(value))
    nothing
end

function (obj::wxTreebook, vec::Ptr{Cvoid}, value::Bool)
    KwxFFI.wxVariantVector_AddBool(obj.ptr, vec, Cint(value))
    nothing
end

function (obj::wxTreebook, vec::Ptr{Cvoid})
    return KwxFFI.wxVariantVector_GetCount(obj.ptr, vec)
end

function (obj::wxTreebook, vec::Ptr{Cvoid})
    KwxFFI.wxVariantVector_Clear(obj.ptr, vec)
    nothing
end

function (obj::wxTreebook, dateTime::Ptr{Cvoid})
    KwxFFI.wxDatePickerCtrl_SetValue(obj.ptr, dateTime)
    nothing
end

function (obj::wxTreebook, dateTime::Ptr{Cvoid})
    KwxFFI.wxDatePickerCtrl_GetValue(obj.ptr, dateTime)
    nothing
end

function (obj::wxTreebook, dt1::Ptr{Cvoid}, dt2::Ptr{Cvoid})
    KwxFFI.wxDatePickerCtrl_SetRange(obj.ptr, dt1, dt2)
    nothing
end

function (obj::wxTreebook, dt1::Ptr{Cvoid}, dt2::Ptr{Cvoid})
    return KwxFFI.wxDatePickerCtrl_GetRange(obj.ptr, dt1, dt2) != 0
end

function (obj::wxTreebook)
    return KwxFFI.wxDirPickerCtrl_GetPath(obj.ptr)
end

function (obj::wxTreebook, path::String)
    path_ws = wxString(path)
    KwxFFI.wxDirPickerCtrl_SetPath(obj.ptr, path_ws.ptr)
    delete!(path_ws)
    nothing
end

function (obj::wxTreebook, dir::String)
    dir_ws = wxString(dir)
    KwxFFI.wxDirPickerCtrl_SetInitialDirectory(obj.ptr, dir_ws.ptr)
    delete!(dir_ws)
    nothing
end

function (obj::wxTreebook, dirname::String)
    dirname_ws = wxString(dirname)
    KwxFFI.wxDirPickerCtrl_SetDirName(obj.ptr, dirname_ws.ptr)
    delete!(dirname_ws)
    nothing
end

function (obj::wxTreebook)
    return KwxFFI.wxDirPickerCtrl_GetDirName(obj.ptr)
end

function (obj::wxTreebook)
    return KwxFFI.wxFilePickerCtrl_GetPath(obj.ptr)
end

function (obj::wxTreebook, path::String)
    path_ws = wxString(path)
    KwxFFI.wxFilePickerCtrl_SetPath(obj.ptr, path_ws.ptr)
    delete!(path_ws)
    nothing
end

function (obj::wxTreebook, dir::String)
    dir_ws = wxString(dir)
    KwxFFI.wxFilePickerCtrl_SetInitialDirectory(obj.ptr, dir_ws.ptr)
    delete!(dir_ws)
    nothing
end

function (obj::wxTreebook, filename::String)
    filename_ws = wxString(filename)
    KwxFFI.wxFilePickerCtrl_SetFileName(obj.ptr, filename_ws.ptr)
    delete!(filename_ws)
    nothing
end

function (obj::wxTreebook)
    return KwxFFI.wxFilePickerCtrl_GetFileName(obj.ptr)
end

function (obj::wxTreebook)
    return KwxFFI.wxFontPickerCtrl_GetSelectedFont(obj.ptr)
end

function (obj::wxTreebook, font::Ptr{Cvoid})
    KwxFFI.wxFontPickerCtrl_SetSelectedFont(obj.ptr, font)
    nothing
end

function (obj::wxTreebook)
    return Int(KwxFFI.wxFontPickerCtrl_GetMaxPointSize(obj.ptr))
end

function (obj::wxTreebook, maxSize::Integer)
    KwxFFI.wxFontPickerCtrl_SetMaxPointSize(obj.ptr, Cint(maxSize))
    nothing
end

function (obj::wxTreebook, dateTime::Ptr{Cvoid})
    KwxFFI.wxTimePickerCtrl_SetValue(obj.ptr, dateTime)
    nothing
end

function (obj::wxTreebook, dateTime::Ptr{Cvoid})
    KwxFFI.wxTimePickerCtrl_GetValue(obj.ptr, dateTime)
    nothing
end

function (obj::wxTreebook, hour::Integer, min::Integer, sec::Integer)
    KwxFFI.wxTimePickerCtrl_SetTime(obj.ptr, Cint(hour), Cint(min), Cint(sec))
    nothing
end

function (obj::wxTreebook, hour::Ptr{Cvoid}, min::Ptr{Cvoid}, sec::Ptr{Cvoid})
    return KwxFFI.wxTimePickerCtrl_GetTime(obj.ptr, hour, min, sec) != 0
end

