# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxTreeCompanionWindow <: wxWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxTreeCompanionWindow(parent::Union{wxWindow, Nothing}, id::Integer, x::Integer, y::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    ptr = KwxFFI.wxTreeCompanionWindow_Create(parent_ptr, Cint(id), Cint(x), Cint(y), Cint(width), Cint(height), Cint(style))
    ptr == C_NULL && error("Failed to create wxTreeCompanionWindow")
    obj = wxTreeCompanionWindow(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxTreeCompanionWindow, dc::Ptr{Cvoid}, id::Ptr{Cvoid}, x::Integer, y::Integer, width::Integer, height::Integer)
    KwxFFI.wxTreeCompanionWindow_DrawItem(obj.ptr, dc, id, Cint(x), Cint(y), Cint(width), Cint(height))
    nothing
end

function (obj::wxTreeCompanionWindow)
    return KwxFFI.wxTreeCompanionWindow_GetTreeCtrl(obj.ptr)
end

function (obj::wxTreeCompanionWindow, treeCtrl::Ptr{Cvoid})
    KwxFFI.wxTreeCompanionWindow_SetTreeCtrl(obj.ptr, treeCtrl)
    nothing
end

