# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxValidator <: wxEvtHandler
    ptr::Ptr{Cvoid}
end

function wxValidator()
    ptr = KwxFFI.wxValidator_Create()
    ptr == C_NULL && error("Failed to create wxValidator")
    obj = wxValidator(ptr)
    return obj
end

function delete!(obj::wxValidator)
    KwxFFI.wxValidator_Delete(obj.ptr)
    nothing
end

function (obj::wxValidator)
    return KwxFFI.wxValidator_GetWindow(obj.ptr)
end

function (obj::wxValidator, doIt::Bool)
    KwxFFI.wxValidator_SuppressBellOnError(obj.ptr, Cint(doIt))
    nothing
end

function (obj::wxValidator, win::Ptr{Cvoid})
    KwxFFI.wxValidator_SetWindow(obj.ptr, win)
    nothing
end

function (obj::wxValidator)
    return KwxFFI.wxValidator_TransferFromWindow(obj.ptr) != 0
end

function (obj::wxValidator)
    return KwxFFI.wxValidator_TransferToWindow(obj.ptr) != 0
end

function (obj::wxValidator, parent::Ptr{Cvoid})
    return KwxFFI.wxValidator_Validate(obj.ptr, parent) != 0
end

