# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxWebViewEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxWebViewEvent)
    return KwxFFI.wxWebViewEvent_GetURL(obj.ptr)
end

function (obj::wxWebViewEvent)
    return KwxFFI.wxWebViewEvent_GetTarget(obj.ptr)
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.wxWebViewEvent_GetNavigationAction(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.wxWebViewEvent_GetInt(obj.ptr))
end

function (obj::wxWebViewEvent)
    return KwxFFI.wxWebViewEvent_GetString(obj.ptr)
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_ZOOM_SMALL(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_ZOOM_MEDIUM(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_ZOOM_LARGE(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_ZOOM_LARGEST(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_ZOOM_TYPE_LAYOUT(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_ZOOM_TYPE_TEXT(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_RELOAD_NO_CACHE(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_FIND_ENTIRE_WORD(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_FIND_MATCH_CASE(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_FIND_HIGHLIGHT_RESULT(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_FIND_BACKWARDS(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_FIND_DEFAULT(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_NAV_ERR_CERTIFICATE(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_NAV_ERR_AUTH(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_NAV_ERR_SECURITY(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_NAV_ERR_NOT_FOUND(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_NAV_ERR_REQUEST(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_NAV_ERR_USER_CANCELLED(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_NAV_ERR_OTHER(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_NAV_ACTION_USER(obj.ptr))
end

function (obj::wxWebViewEvent)
    return Int(KwxFFI.expWEBVIEW_NAV_ACTION_OTHER(obj.ptr))
end

