# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxWindowDestroyEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxWindowDestroyEvent)
    return KwxFFI.wxWindowDestroyEvent_GetWindow(obj.ptr)
end

