# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxWizard <: wxTopLevelWindow
    ptr::Ptr{Cvoid}
    children::Vector{Any}
    closures::Vector{Any}
end

function wxWizard(parent::Union{wxWindow, Nothing}, id::Integer, text::String, bitmap::Ptr{Cvoid}, left::Integer, top::Integer, width::Integer, height::Integer, style::Integer)
    parent_ptr = isnothing(parent) ? C_NULL : parent.ptr
    text_ws = wxString(text)
    ptr = KwxFFI.wxWizard_Create(parent_ptr, Cint(id), text_ws.ptr, bitmap, Cint(left), Cint(top), Cint(width), Cint(height), Clong(style))
    delete!(text_ws)
    ptr == C_NULL && error("Failed to create wxWizard")
    obj = wxWizard(ptr, Any[], Any[])
    isnothing(parent) || push!(parent.children, obj)
    return obj
end

function (obj::wxWizard, first::Ptr{Cvoid}, second::Ptr{Cvoid})
    KwxFFI.wxWizard_Chain(obj.ptr, first, second)
    nothing
end

function (obj::wxWizard)
    return KwxFFI.wxWizard_GetCurrentPage(obj.ptr)
end

function (obj::wxWizard)
    return KwxFFI.wxWizard_GetPageSize(obj.ptr)
end

function (obj::wxWizard, firstPage::Ptr{Cvoid})
    return Int(KwxFFI.wxWizard_RunWizard(obj.ptr, firstPage))
end

function (obj::wxWizard, width::Integer, height::Integer)
    KwxFFI.wxWizard_SetPageSize(obj.ptr, Cint(width), Cint(height))
    nothing
end

function (obj::wxWizard)
    return KwxFFI.wxWizard_GetPageAreaSizer(obj.ptr)
end

function (obj::wxWizard, border::Integer)
    KwxFFI.wxWizard_SetBorder(obj.ptr, Cint(border))
    nothing
end

function (obj::wxWizard, firstPage::Ptr{Cvoid})
    KwxFFI.wxWizard_FitToPage(obj.ptr, firstPage)
    nothing
end

function (obj::wxWizard, page::Ptr{Cvoid})
    return KwxFFI.wxWizard_HasNextPage(obj.ptr, page) != 0
end

function (obj::wxWizard, page::Ptr{Cvoid})
    return KwxFFI.wxWizard_HasPrevPage(obj.ptr, page) != 0
end

function (obj::wxWizard, ref::Ptr{Cvoid})
    KwxFFI.wxWizard_GetBitmap(obj.ptr, ref)
    nothing
end

