# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxWindowCreateEvent <: wxObject
    ptr::Ptr{Cvoid}
end

function (obj::wxWindowCreateEvent)
    return KwxFFI.wxWindowCreateEvent_GetWindow(obj.ptr)
end

