# Code generated by kwxgen. DO NOT EDIT.

mutable struct wxWindowDC <: wxObject
    ptr::Ptr{Cvoid}
end

function wxWindowDC(win::Ptr{Cvoid})
    ptr = KwxFFI.wxWindowDC_Create(win)
    ptr == C_NULL && error("Failed to create wxWindowDC")
    obj = wxWindowDC(ptr)
    return obj
end

function delete!(obj::wxWindowDC)
    KwxFFI.wxWindowDC_Delete(obj.ptr)
    nothing
end

